{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.camerax",
    "module": "camera_android_camerax_release",
    "version": "0.25",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        }
      ],
      "files": [
        {
          "name": "camera_android_camerax_release-0.25.aar",
          "url": "camera_android_camerax_release-0.25.aar",
          "size": 266221,
          "sha512": "9af0a5516c2edc27dd35858ebd02c891abf2d850a8cc85be4d23507c3a6b7e3f2742d8724961acfcb5137e32906544fb644759633a842beafd80c2d4cdb31152",
          "sha256": "7c8342a73daf94abcfa1e61df23b7ca3ff6a53e5277ae96d936f58f33e681264",
          "sha1": "bb7b05b1620dd32e4d7199c34e11dc32186b6e96",
          "md5": "b48fafc498f8aa5db42a088ead6fb5a4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.3.4"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.3.4"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.3.4"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-video",
          "version": {
            "requires": "1.3.4"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.3.1-android"
          }
        }
      ],
      "files": [
        {
          "name": "camera_android_camerax_release-0.25.aar",
          "url": "camera_android_camerax_release-0.25.aar",
          "size": 266221,
          "sha512": "9af0a5516c2edc27dd35858ebd02c891abf2d850a8cc85be4d23507c3a6b7e3f2742d8724961acfcb5137e32906544fb644759633a842beafd80c2d4cdb31152",
          "sha256": "7c8342a73daf94abcfa1e61df23b7ca3ff6a53e5277ae96d936f58f33e681264",
          "sha1": "bb7b05b1620dd32e4d7199c34e11dc32186b6e96",
          "md5": "b48fafc498f8aa5db42a088ead6fb5a4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "camera_android_camerax_release-0.25-sources.jar",
          "url": "camera_android_camerax_release-0.25-sources.jar",
          "size": 86316,
          "sha512": "5382ce18bd09440222ebf82115235b669fd9af0e5aa1b7230156e004966fa02af4d6769714e893b0e78dff5e9f64a7111abc9ae654e1ab61bf292113b6ecdfc0",
          "sha256": "79f2b55e1b567c1876f27760b5465af879a2a59f33efec52baeeb486833fa9f7",
          "sha1": "e6e78d7a217d954c995f6146e7d112c64e43e04f",
          "md5": "e33d81ce6a5534f6131cd452966dd58f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "camera_android_camerax_release-0.25-javadoc.jar",
          "url": "camera_android_camerax_release-0.25-javadoc.jar",
          "size": 902163,
          "sha512": "7a2fa19fe5f969621f2c844f51113a3bc0c8e4b0410da26d25e70c918cdb6e2632178a003d8f2e6734971c37c150aab60e5bc4eb5c09b714637a1a1748023b57",
          "sha256": "f73fcb2f1efce7689f23d64977852a04b8438d1b45f9bd8f76251bd52a8d8b42",
          "sha1": "af338ee38cf548e8ed4d2d7f60c121b3219f9e54",
          "md5": "83a4001988b2f6077f16eba19fce3cdc"
        }
      ]
    }
  ]
}
