{
  "formatVersion": "1.1",
  "component": {
    "group": "com.fluttercandies.flutter_image_compress",
    "module": "flutter_image_compress_common_release",
    "version": "0.61",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_image_compress_common_release-0.61.aar",
          "url": "flutter_image_compress_common_release-0.61.aar",
          "size": 30381,
          "sha512": "09784f8ec0de1c50ac3c8d9c6a5bb9761c655ff6283f54d0a823a7047ba6abc33d4fe94650aedac3b3208c9cae476fe385f063a33e7e04037f075d40c4677cd7",
          "sha256": "31f1aa3540fe3d880916b8af20536b9aa8cafdc698bf8b4534e9cfc4fcb8a9cb",
          "sha1": "5f3558b6ea03d72339b00b82650d3ee521333da5",
          "md5": "e7f217bcc03ee9cc1b011fc0cda19fcc"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "androidx.heifwriter",
          "module": "heifwriter",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_image_compress_common_release-0.61.aar",
          "url": "flutter_image_compress_common_release-0.61.aar",
          "size": 30381,
          "sha512": "09784f8ec0de1c50ac3c8d9c6a5bb9761c655ff6283f54d0a823a7047ba6abc33d4fe94650aedac3b3208c9cae476fe385f063a33e7e04037f075d40c4677cd7",
          "sha256": "31f1aa3540fe3d880916b8af20536b9aa8cafdc698bf8b4534e9cfc4fcb8a9cb",
          "sha1": "5f3558b6ea03d72339b00b82650d3ee521333da5",
          "md5": "e7f217bcc03ee9cc1b011fc0cda19fcc"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_image_compress_common_release-0.61-sources.jar",
          "url": "flutter_image_compress_common_release-0.61-sources.jar",
          "size": 13283,
          "sha512": "9d463a80c9f9155d36af415dfbc87fadb7908f534f56929f46ded2280cbd3951f90518b08d83de17af9eab1bb66723f65b386d3d4df8b2a57dc67105fc8cad56",
          "sha256": "93a28e5f9b7fcb467c45057e584caa01f1eb412c0b4a92b23a49dc0100b4af37",
          "sha1": "8f0422fa7a12db6f03202df46f11b2c7ec84061a",
          "md5": "326cceeddeb7bc0e1af417bf6b15811f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_image_compress_common_release-0.61-javadoc.jar",
          "url": "flutter_image_compress_common_release-0.61-javadoc.jar",
          "size": 351481,
          "sha512": "b08b140f930de20694c302628a1549d673108a430c429d1709b02421166be77dd134a2b5c2b02fa14f4455b36f9721cc7209a9ac2a1a630d9fb85bff75b5e8f0",
          "sha256": "8642835f1aaeea8a9e304d5ccda9ad4519d79215700b93b8aa09c847c1b8048f",
          "sha1": "28f4f6b13a56233a5dfcf37ebf272981dfa09649",
          "md5": "7bc0680a5a183ab19702b52139b42538"
        }
      ]
    }
  ]
}
