{
  "formatVersion": "1.1",
  "component": {
    "group": "id.nizwar.screen_capture_event",
    "module": "screen_capture_event_release",
    "version": "0.57",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        }
      ],
      "files": [
        {
          "name": "screen_capture_event_release-0.57.aar",
          "url": "screen_capture_event_release-0.57.aar",
          "size": 12167,
          "sha512": "bed4ba47b48d8a9c4058011a603581757d46f5ffe50edf1e2560c9e62c1e18c70f644df44007a334c6d0a9a5993fa491cc0a53c452068b3944be8382ca53aa60",
          "sha256": "83384fee8e1ca5f96cd25358a98490be601a686707c1126c585852bd7823ae8b",
          "sha1": "fe7aafecdc46feba05b81d9e666ae55e298b80a2",
          "md5": "465488382dc9597137477cb8eae9a3c5"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        }
      ],
      "files": [
        {
          "name": "screen_capture_event_release-0.57.aar",
          "url": "screen_capture_event_release-0.57.aar",
          "size": 12167,
          "sha512": "bed4ba47b48d8a9c4058011a603581757d46f5ffe50edf1e2560c9e62c1e18c70f644df44007a334c6d0a9a5993fa491cc0a53c452068b3944be8382ca53aa60",
          "sha256": "83384fee8e1ca5f96cd25358a98490be601a686707c1126c585852bd7823ae8b",
          "sha1": "fe7aafecdc46feba05b81d9e666ae55e298b80a2",
          "md5": "465488382dc9597137477cb8eae9a3c5"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "screen_capture_event_release-0.57-sources.jar",
          "url": "screen_capture_event_release-0.57-sources.jar",
          "size": 3290,
          "sha512": "2e56fe43d903f199950826f12aa2faa6cb01ed062805911183c9658c4811f15e21f20a766e4ab0ad4a2dbcaed814e326bc94197417d8827edbd0acc396734465",
          "sha256": "d61a767283078b15b3b845e58594d416bad4d1086bbcf42e580f6585c4f9d771",
          "sha1": "04d6fc9ddb95ea131bb593c6aed1378491128798",
          "md5": "8d5e7d5909ee36858b5d9c7667638814"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "screen_capture_event_release-0.57-javadoc.jar",
          "url": "screen_capture_event_release-0.57-javadoc.jar",
          "size": 273267,
          "sha512": "ec2ff76bb1fdcf25cfdb2de1ab0d23a594d527f7b8681b33905e19f3bdd2781be23a97c0831d5c1ce5f297c9f938ce9e097fb3109703cf91c5302a56ea3e31ba",
          "sha256": "24b7c2a27d478d81a951a88de3c53251be7cebd3b697b126dfa6d34c1ecbf837",
          "sha1": "3bfe67f28c705b110395feb06129912b5575cbe2",
          "md5": "3f42742aca35ee31676287e094d6e414"
        }
      ]
    }
  ]
}
