{
  "formatVersion": "1.1",
  "component": {
    "group": "com.cloudwebrtc.webrtc",
    "module": "flutter_webrtc_release",
    "version": "0.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_webrtc_release-0.7.aar",
          "url": "flutter_webrtc_release-0.7.aar",
          "size": 193410,
          "sha512": "43d17351593d2fc42a776c67764fc4f2c846d808ef4cbce08800fbcdb919c902c38998a78c6d75f99578ac6275c72203ca36df24f4d662e6f94457d86657c25f",
          "sha256": "7cf8b7035132cf10a332fd815b4393e413b258bd141b19d4d20b75f3f1e06401",
          "sha1": "8eb95e14bc8290a724fb8e01a5f9ecbabbfe9867",
          "md5": "cf9569f9c4e82e9d7dbee34abeebc504"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        },
        {
          "group": "io.github.webrtc-sdk",
          "module": "android",
          "version": {
            "requires": "125.6422.03"
          }
        },
        {
          "group": "com.github.davidliu",
          "module": "audioswitch",
          "version": {
            "requires": "89582c47c9a04c62f90aa5e57251af4800a62c9a"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_webrtc_release-0.7.aar",
          "url": "flutter_webrtc_release-0.7.aar",
          "size": 193410,
          "sha512": "43d17351593d2fc42a776c67764fc4f2c846d808ef4cbce08800fbcdb919c902c38998a78c6d75f99578ac6275c72203ca36df24f4d662e6f94457d86657c25f",
          "sha256": "7cf8b7035132cf10a332fd815b4393e413b258bd141b19d4d20b75f3f1e06401",
          "sha1": "8eb95e14bc8290a724fb8e01a5f9ecbabbfe9867",
          "md5": "cf9569f9c4e82e9d7dbee34abeebc504"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_webrtc_release-0.7-sources.jar",
          "url": "flutter_webrtc_release-0.7-sources.jar",
          "size": 88566,
          "sha512": "f650a0b74b2eaf4b2dd885894175e35a1f201734c719779b1d203e791816412613ee8d460b477c6f2f0f8bfa40665fef2f5b72ce211ac33915fb03f56286037c",
          "sha256": "299a782649016c4c489d9012ac21cc7c74beedea28819679dcab4624880763d6",
          "sha1": "dcd6fe48a79446555fcdd90a0ac5467228a9afe7",
          "md5": "a627730b77b1017611e86df2dda74384"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_webrtc_release-0.7-javadoc.jar",
          "url": "flutter_webrtc_release-0.7-javadoc.jar",
          "size": 506123,
          "sha512": "334b0529d42deca2362fe1718fd622d9d796687724d9a232eafd0d77cc5cabc6fb581368d119912f13b41e85f8e496650beda2d8ad19fdb32fcc0ac1ac97fd1d",
          "sha256": "84a21aaec6be6519e6a87f865fad8e90a9e61577ec26039624cc3b093b85271b",
          "sha1": "9966e979a8e1802583cbd0d5ef7fff7c996a2f59",
          "md5": "c451b90738d74b89222f696f0955e4bf"
        }
      ]
    }
  ]
}
