{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.yongxin_ring",
    "module": "yongxin_ring_release",
    "version": "0.24",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "yongxin_ring_release-0.24.aar",
          "url": "yongxin_ring_release-0.24.aar",
          "size": 54381,
          "sha512": "40622f7f2a9c32de75012248d14ced181a74f2c99dab234b4a04e06758b06313c8d779dc754d73594fc29ddf846933da3d4bbf7ab432f318309a463e1138863f",
          "sha256": "95c5d9f48e5524e7e66a953d34395422bb1a7d32729cf022d4cd285fa4d37473",
          "sha1": "3cac2eb188e7b2f6d9f0f744b613c8a70340200c",
          "md5": "fbbe22145d6aac2df5bb0c369364b881"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        },
        {
          "group": "com.lm",
          "module": "chipletRing",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.localbroadcastmanager",
          "module": "localbroadcastmanager",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.greenrobot",
          "module": "greendao",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "org.ligboy.retrofit2",
          "module": "converter-fastjson-android",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "24.0.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "com.zhy",
          "module": "okhttputils",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "com.tenmeter.smlibrary",
          "module": "tenmeter",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "yongxin_ring_release-0.24.aar",
          "url": "yongxin_ring_release-0.24.aar",
          "size": 54381,
          "sha512": "40622f7f2a9c32de75012248d14ced181a74f2c99dab234b4a04e06758b06313c8d779dc754d73594fc29ddf846933da3d4bbf7ab432f318309a463e1138863f",
          "sha256": "95c5d9f48e5524e7e66a953d34395422bb1a7d32729cf022d4cd285fa4d37473",
          "sha1": "3cac2eb188e7b2f6d9f0f744b613c8a70340200c",
          "md5": "fbbe22145d6aac2df5bb0c369364b881"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "yongxin_ring_release-0.24-sources.jar",
          "url": "yongxin_ring_release-0.24-sources.jar",
          "size": 15455,
          "sha512": "54f418c7b2c4f741f7afab0117d09c1a9835acb2d766ea58f10edb4ab649ff07aa9d24daf08f88cc074f15d63f76348bee630062beed563748e7033ec0e6103f",
          "sha256": "4a158c67ca34938311298d30c437971b3f24106ba185140be10eec9e47b5c92d",
          "sha1": "c63c174e83e657dc77840a948b427e37515df812",
          "md5": "778d803c3ce84fc13a83a9423f775b35"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "yongxin_ring_release-0.24-javadoc.jar",
          "url": "yongxin_ring_release-0.24-javadoc.jar",
          "size": 301631,
          "sha512": "29e60210bf9341eb63a626cec28175a3f80174a9b90854a2693616bdb2968e12e001e3ecb9bc3a0aa376a764856f5256e73627346411c1a8fdc4988303275871",
          "sha256": "fef9e40450214ffde1b3ee88ed2df8d0b9674b1e25d06d539a50d025bdccc0bb",
          "sha1": "d031bd803efb8d853bcf36de75ba096227d0661d",
          "md5": "f2dcc36038b4b01ab3a5ff6e941d6320"
        }
      ]
    }
  ]
}
