{
  "formatVersion": "1.1",
  "component": {
    "group": "com.aboutyou.dart_packages.sign_in_with_apple",
    "module": "sign_in_with_apple_release",
    "version": "0.18",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        }
      ],
      "files": [
        {
          "name": "sign_in_with_apple_release-0.18.aar",
          "url": "sign_in_with_apple_release-0.18.aar",
          "size": 8197,
          "sha512": "3546297730883300f202c56163affcde6d5d6d23f4f65326b8d7207b25ee3c49149ad6a7aac594eb7b6e508207c16e54f430d3d11fdfc88d253fd144ebcca5da",
          "sha256": "bb8fdbe1cee942ce494643ba451fe136a66e8c933b7051da7a47b284a6b50cff",
          "sha1": "a90c8eb29432c50d134152fbe35464bb93ba6b96",
          "md5": "ae0a0d5a112098d9bc0f019a9cc9cd32"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "sign_in_with_apple_release-0.18.aar",
          "url": "sign_in_with_apple_release-0.18.aar",
          "size": 8197,
          "sha512": "3546297730883300f202c56163affcde6d5d6d23f4f65326b8d7207b25ee3c49149ad6a7aac594eb7b6e508207c16e54f430d3d11fdfc88d253fd144ebcca5da",
          "sha256": "bb8fdbe1cee942ce494643ba451fe136a66e8c933b7051da7a47b284a6b50cff",
          "sha1": "a90c8eb29432c50d134152fbe35464bb93ba6b96",
          "md5": "ae0a0d5a112098d9bc0f019a9cc9cd32"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sign_in_with_apple_release-0.18-sources.jar",
          "url": "sign_in_with_apple_release-0.18-sources.jar",
          "size": 2730,
          "sha512": "232813b66653332be1825dda86c44197be6a6e5c4db974c29b5e382607c23c3453837625416f9ae13f991ba92f998f99dc25155e699a146881cd86e42431b316",
          "sha256": "3f74fc332e872fbcfdc3245f838f6f2e4704e5b0c6a0c865417757fad32ab9b4",
          "sha1": "227ee9e1b8ad1d2663b181163fd2a12db200cd6a",
          "md5": "57be615d4366529cd2aa5385e32ef800"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sign_in_with_apple_release-0.18-javadoc.jar",
          "url": "sign_in_with_apple_release-0.18-javadoc.jar",
          "size": 312438,
          "sha512": "353aa3cdfc60831707476e225be7978589781f6c12e4fabc2d5189c442b91e8972f77d9ba3cf765b8f8aa685837ccb6492d3c16055e327575fcc75beb27b2e60",
          "sha256": "5350da12534f6fdc3d3b0d1fc29dacf75f7c99c66de00bd00e3c01cd432b1497",
          "sha1": "5817b09cdb6f6e87e79fb8d575f73b3bb7ca9f6b",
          "md5": "67f22b21d38ddab10b83395c2b8857a5"
        }
      ]
    }
  ]
}
