{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dexterous.flutterlocalnotifications",
    "module": "flutter_local_notifications_debug",
    "version": "0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_local_notifications_debug-0.1.aar",
          "url": "flutter_local_notifications_debug-0.1.aar",
          "size": 86151,
          "sha512": "3bd099b5b8127e4ef10d0333d6667b22aaa64d03f5a3ccea6449c59433f05a6683703910a15724965bd381d15309ee99bfbb3bc9257c7ea04f3b31b785f0554e",
          "sha256": "5f76643d3eed13cb8c52de4fe39d556f664917713b5549be5b14bceeb65186ff",
          "sha1": "0725b91e57e595f35ac2dba92859dbf745e970fd",
          "md5": "0a39e24e6830c91837580a75533f04b3"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.media",
          "module": "media",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.9"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_local_notifications_debug-0.1.aar",
          "url": "flutter_local_notifications_debug-0.1.aar",
          "size": 86151,
          "sha512": "3bd099b5b8127e4ef10d0333d6667b22aaa64d03f5a3ccea6449c59433f05a6683703910a15724965bd381d15309ee99bfbb3bc9257c7ea04f3b31b785f0554e",
          "sha256": "5f76643d3eed13cb8c52de4fe39d556f664917713b5549be5b14bceeb65186ff",
          "sha1": "0725b91e57e595f35ac2dba92859dbf745e970fd",
          "md5": "0a39e24e6830c91837580a75533f04b3"
        }
      ]
    },
    {
      "name": "debugVariantDebugSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_local_notifications_debug-0.1-sources.jar",
          "url": "flutter_local_notifications_debug-0.1-sources.jar",
          "size": 43596,
          "sha512": "7736acb5954d99f56cb46af46dd8581b373482a317c78c9b99eb6fc6eb8ca140082025906c97406c3b82586029c0e86a3f0d69c96023384abdd8ea46e6bf48d4",
          "sha256": "fc7f32461f268b0581bc3c5c9e2c0d81a79252cb0cf09a351bb0bdffe4993ea6",
          "sha1": "c3fb9f6ef65dc6aff958aa612beca1e2ae4a96c0",
          "md5": "5de3e43acd23922d52c9900575889eda"
        }
      ]
    },
    {
      "name": "debugVariantDebugJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_local_notifications_debug-0.1-javadoc.jar",
          "url": "flutter_local_notifications_debug-0.1-javadoc.jar",
          "size": 417346,
          "sha512": "a2f2862abb717bbfe26fd386a2b034b655785e510642776057450c8e8168a6efc782bf68c24bfafdd2249816becc5f15204a889c150458c472e69cb939954e0c",
          "sha256": "d25dc950e9a91188a19d931702f0332b7ed8798532f26be5e7f806f5a76719c0",
          "sha1": "1930d39eb43decb3b345c92ceff1ca8f949c9f27",
          "md5": "ef5ef5b8b5a10fe611d87c254510abcc"
        }
      ]
    }
  ]
}
