{
  "formatVersion": "1.1",
  "component": {
    "group": "com.benjaminabel.vibration",
    "module": "vibration_release",
    "version": "0.30",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        }
      ],
      "files": [
        {
          "name": "vibration_release-0.30.aar",
          "url": "vibration_release-0.30.aar",
          "size": 5444,
          "sha512": "3cf52fc6e1672f179ba08083e0866bc4583f6c0ff06d99d0e4583556917a1ca0ba36557d9817a9766d0e6b872cf5fc322fd1e1ce1bfa26ebbabec0db7c7776fd",
          "sha256": "3f062eb94cf6ddc6db5ae18c9a67832fcfca4215ed1acf903bf297aa82761e01",
          "sha1": "321b699dac63a21bc623ffa85a28b786a85442b9",
          "md5": "ebbd5f774d4a4660626a6cbc37ef2fd7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        }
      ],
      "files": [
        {
          "name": "vibration_release-0.30.aar",
          "url": "vibration_release-0.30.aar",
          "size": 5444,
          "sha512": "3cf52fc6e1672f179ba08083e0866bc4583f6c0ff06d99d0e4583556917a1ca0ba36557d9817a9766d0e6b872cf5fc322fd1e1ce1bfa26ebbabec0db7c7776fd",
          "sha256": "3f062eb94cf6ddc6db5ae18c9a67832fcfca4215ed1acf903bf297aa82761e01",
          "sha1": "321b699dac63a21bc623ffa85a28b786a85442b9",
          "md5": "ebbd5f774d4a4660626a6cbc37ef2fd7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vibration_release-0.30-sources.jar",
          "url": "vibration_release-0.30-sources.jar",
          "size": 3055,
          "sha512": "384eb290f3959fdee7c259a16e1644ce0676709e1319436f231a1522a548ce0da6c9c7cb04a44b1f3456d50b0488a26d7d80341b6469032740a43a3b226217cc",
          "sha256": "70496470796b88fca44d8fc2ef720ac6bec89b83bbfdefe956dd680a981d8ab6",
          "sha1": "daa83f1f05e9c60ae716519b35e89d79487faf04",
          "md5": "6c40e406630f8b8a8285a64427b965be"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vibration_release-0.30-javadoc.jar",
          "url": "vibration_release-0.30-javadoc.jar",
          "size": 265552,
          "sha512": "53c98836b7098bb9088725ff1c9e4229645a9869b0d37c7e5069f62875e30a36661fcfd995b073c735bacdf8117d4486d7af31d9eac6a6092482bb75bc883a0a",
          "sha256": "c1d43babe0b8935149e69601127da8df00fb2177cac3b8fff1246765782122a0",
          "sha1": "bd4ced374bd24ad0baa796b8ab9898142592db75",
          "md5": "1e97bc8925ebc9b3842fa8faf232b259"
        }
      ]
    }
  ]
}
