{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.yanncabral.open_settings_plus",
    "module": "open_settings_plus_release",
    "version": "0.58",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "open_settings_plus_release-0.58.aar",
          "url": "open_settings_plus_release-0.58.aar",
          "size": 4277,
          "sha512": "153f736838775d00ddfdeb99ccc51d0be0c628301db57ee959793a7e2172371ed96f74c74795536cc4eada24ff4fd870cf9b072ae1edf752034ff8769ca58a18",
          "sha256": "3475fdc44fda57e13c382f92951eb638ffd16636f8ca82dcc1492b710aaa779b",
          "sha1": "a418846586ab0922242faad725c1a695fd483ed3",
          "md5": "fb8cae4e667349289daa5692c5f1a85a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "open_settings_plus_release-0.58.aar",
          "url": "open_settings_plus_release-0.58.aar",
          "size": 4277,
          "sha512": "153f736838775d00ddfdeb99ccc51d0be0c628301db57ee959793a7e2172371ed96f74c74795536cc4eada24ff4fd870cf9b072ae1edf752034ff8769ca58a18",
          "sha256": "3475fdc44fda57e13c382f92951eb638ffd16636f8ca82dcc1492b710aaa779b",
          "sha1": "a418846586ab0922242faad725c1a695fd483ed3",
          "md5": "fb8cae4e667349289daa5692c5f1a85a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "open_settings_plus_release-0.58-sources.jar",
          "url": "open_settings_plus_release-0.58-sources.jar",
          "size": 2127,
          "sha512": "db9d4e79f86c4070737cc098075615485a061c944d20fcd7d7d465966e182776bb8d4494831e08961383872a015cd6164508393c29b8a6be7bfe91cecc9c379d",
          "sha256": "49bbb2bb5b27526e00b39edf6bc3b11dfca6582948d3a6498a6d55cd09f802ed",
          "sha1": "7130ee8ab68a8bc277889bc80d55cdfb048104db",
          "md5": "d4450a7b35aff0e068cd6532e4d6f219"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "open_settings_plus_release-0.58-javadoc.jar",
          "url": "open_settings_plus_release-0.58-javadoc.jar",
          "size": 260999,
          "sha512": "9e233c00db0713eb9cc7264f85173b1174f9deede389883df038d494bdb87824c8f478ff07450cb2c1113617fd96e58f424af48d571552eac445f5da1a75217d",
          "sha256": "773ea969d670bae8d83aebf07b44732e91da0ee6da4e03f0a79dc19a1880ad7c",
          "sha1": "3fb730499b0ee10d7c92a81559481f338ce79df0",
          "md5": "bd10105833d62889b5eaa4883f13e026"
        }
      ]
    }
  ]
}
