{
  "formatVersion": "1.1",
  "component": {
    "group": "com.google_mlkit_commons",
    "module": "google_mlkit_commons_release",
    "version": "0.63",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        }
      ],
      "files": [
        {
          "name": "google_mlkit_commons_release-0.63.aar",
          "url": "google_mlkit_commons_release-0.63.aar",
          "size": 6502,
          "sha512": "8777289bd6f9e5ce8e2504d50e4060532641104118b5224f58bd1640669c313792dfc5aab81288f4591a78729d040343efb6195dd4aa6bb1d3c2365eb9b2a96a",
          "sha256": "4ceb6cc3e5637ff5e31474f37ff5ed48c09cd9bde1877bbecae395364f78ca6a",
          "sha1": "05fe395569b99ee6993d0681ab33b359f91a1abb",
          "md5": "535ce70683f710f7a2d99c3792f5a63c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        },
        {
          "group": "com.google.mlkit",
          "module": "vision-common",
          "version": {
            "requires": "17.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "google_mlkit_commons_release-0.63.aar",
          "url": "google_mlkit_commons_release-0.63.aar",
          "size": 6502,
          "sha512": "8777289bd6f9e5ce8e2504d50e4060532641104118b5224f58bd1640669c313792dfc5aab81288f4591a78729d040343efb6195dd4aa6bb1d3c2365eb9b2a96a",
          "sha256": "4ceb6cc3e5637ff5e31474f37ff5ed48c09cd9bde1877bbecae395364f78ca6a",
          "sha1": "05fe395569b99ee6993d0681ab33b359f91a1abb",
          "md5": "535ce70683f710f7a2d99c3792f5a63c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "google_mlkit_commons_release-0.63-sources.jar",
          "url": "google_mlkit_commons_release-0.63-sources.jar",
          "size": 3161,
          "sha512": "c3482f873b41c01680dda46f780f157f3e306b65e8996a3ce3a839523add8d3682a591baa1ccc0c29d243e1f68c99bc481b759da21c691f5ee47fc4bd06facc2",
          "sha256": "8dc184f7ab29e88d1f80ef14f675650f62d92e3eb1b3b71c3755151bb6b7dd36",
          "sha1": "857842e871494ad5412c86b1243a18e24a461ad7",
          "md5": "05c5d57c78b50eac64010a5e61f7fc80"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "google_mlkit_commons_release-0.63-javadoc.jar",
          "url": "google_mlkit_commons_release-0.63-javadoc.jar",
          "size": 273141,
          "sha512": "15b736d548cf487f431413b40fd963d106e7454fdba0fd8420215ac3c23d3df0287e1391540498066abccfa9a3d4658247c95e3d460c46ccdd46cb76d01a5788",
          "sha256": "b87fb4136faac759e13ff2e37b2732bec3cd6fb60432c3567bcc2dadf41e3673",
          "sha1": "b1bbf16b3c8cd0e35c3e6cf8a13730851b45fdac",
          "md5": "386828731554741c4d2a0e056a85d536"
        }
      ]
    }
  ]
}
