{
  "formatVersion": "1.1",
  "component": {
    "group": "net.wolverinebeach.flutter_timezone",
    "module": "flutter_timezone_release",
    "version": "0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_timezone_release-0.3.aar",
          "url": "flutter_timezone_release-0.3.aar",
          "size": 3149,
          "sha512": "3309e845ee92a2cc8767f85389309be1204c5111453be64626e253efca7d17b05ee6d46d52dc5bbb1edb9b8ea5db93abf8919699f9de70dbc2a04943b421d9c5",
          "sha256": "639e090767ed1e2ffc72438f6d230f61ee208eeb493f32ce12f40eea1448b675",
          "sha1": "f861528d7e10a07ab36d30d672963a204a9fd9f3",
          "md5": "12adccdf2b0aef086ce5e7c174c2227b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_timezone_release-0.3.aar",
          "url": "flutter_timezone_release-0.3.aar",
          "size": 3149,
          "sha512": "3309e845ee92a2cc8767f85389309be1204c5111453be64626e253efca7d17b05ee6d46d52dc5bbb1edb9b8ea5db93abf8919699f9de70dbc2a04943b421d9c5",
          "sha256": "639e090767ed1e2ffc72438f6d230f61ee208eeb493f32ce12f40eea1448b675",
          "sha1": "f861528d7e10a07ab36d30d672963a204a9fd9f3",
          "md5": "12adccdf2b0aef086ce5e7c174c2227b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_timezone_release-0.3-sources.jar",
          "url": "flutter_timezone_release-0.3-sources.jar",
          "size": 1391,
          "sha512": "6b502c6a79c5a500cbc75e27ba9826e824d3531397f55e48644f843cb67f99022926912b04a2dec2823603694ba7d87ac7158fb4c7a19dad399ba8c39a959e15",
          "sha256": "bcd1a3ce8e51473fe5df70506828c2896775bad254f66d3214827d0dc5b69f09",
          "sha1": "95dbfe012e09fbb4605cc781ea5cdbae53414869",
          "md5": "9401f18133d348424988f5ef152a533e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_timezone_release-0.3-javadoc.jar",
          "url": "flutter_timezone_release-0.3-javadoc.jar",
          "size": 262424,
          "sha512": "c80a562185ef275b9a6fdd7634346c923272e3ef4cf99c8fcb202c40eae43736acbc687a79c31a81cd131ee76bf237f5ec4db76ff88f8fbfcc701f7da243c412",
          "sha256": "160e44fbae2c77cb414b5a114bbcdb890d72f3d407f176e20703608efc95e17e",
          "sha1": "542743f8fc5457d2f9c6fc0a43e90235d417ba10",
          "md5": "ac37de6fc8c2ef3be6ba23f6eb1352bb"
        }
      ]
    }
  ]
}
