{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.yongxin_ring",
    "module": "yongxin_ring_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "yongxin_ring_debug-1.0.aar",
          "url": "yongxin_ring_debug-1.0.aar",
          "size": 59279,
          "sha512": "83cdb229f4eee43a38338134fd74a0c71a20a7d88a44c1eff9a8fad4a4aea3b0a599748a139df1248bee0986cd9c47d122617edfe41fd8e8883348232c0688b2",
          "sha256": "4fed1bec937357c0b9c7a7f372656f50d96de8aabbafa6c50c7d337b5d53c760",
          "sha1": "3cf3dbd67fab0b08c1c11b6c1fa55915b3e14819",
          "md5": "a23069b71f88550d4e92e6a4887f9d21"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        },
        {
          "group": "com.lm",
          "module": "chipletRing",
          "version": {
            "requires": "1.0.72"
          }
        },
        {
          "group": "androidx.localbroadcastmanager",
          "module": "localbroadcastmanager",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.greenrobot",
          "module": "greendao",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "org.ligboy.retrofit2",
          "module": "converter-fastjson-android",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "24.0.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "com.zhy",
          "module": "okhttputils",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "yongxin_ring_debug-1.0.aar",
          "url": "yongxin_ring_debug-1.0.aar",
          "size": 59279,
          "sha512": "83cdb229f4eee43a38338134fd74a0c71a20a7d88a44c1eff9a8fad4a4aea3b0a599748a139df1248bee0986cd9c47d122617edfe41fd8e8883348232c0688b2",
          "sha256": "4fed1bec937357c0b9c7a7f372656f50d96de8aabbafa6c50c7d337b5d53c760",
          "sha1": "3cf3dbd67fab0b08c1c11b6c1fa55915b3e14819",
          "md5": "a23069b71f88550d4e92e6a4887f9d21"
        }
      ]
    },
    {
      "name": "debugVariantDebugSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "yongxin_ring_debug-1.0-sources.jar",
          "url": "yongxin_ring_debug-1.0-sources.jar",
          "size": 11716,
          "sha512": "72b960c9e147d6751bf0669f791b55ed0437dab4cd7f94bc36622decba04bf66ed789a390a4e7ce5733f4add47a56fb6fa56068e2a89cb97c943d6a6e2e18c62",
          "sha256": "033e64ff4dd55c4a7525008346496720018969229431433d893721aa72e67963",
          "sha1": "ab6f36f0c28851bee0243bfe4b278bc21bdd4f39",
          "md5": "022da9b50767e388248cef9d55f66bd2"
        }
      ]
    },
    {
      "name": "debugVariantDebugJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "yongxin_ring_debug-1.0-javadoc.jar",
          "url": "yongxin_ring_debug-1.0-javadoc.jar",
          "size": 301293,
          "sha512": "2835cf76ea6a9e59b3a55671d67aa93cfa3fddfd026d4740702b820997aed520476cb5d2e01f26507ea0362f422c8121443b06b63bec335cdb7f4eeb3c114163",
          "sha256": "9fc8828abd412b3053f77bc823abe0c718c0970c15c427685e60148532b7f758",
          "sha1": "ed9b3bccc0ce828393dc566614f7e965e986f22a",
          "md5": "520aa38f36a05f89867ccc62cdcd2f41"
        }
      ]
    }
  ]
}
