{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.videoplayer",
    "module": "video_player_android_release",
    "version": "0.50",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "video_player_android_release-0.50.aar",
          "url": "video_player_android_release-0.50.aar",
          "size": 98056,
          "sha512": "049fb71f62de4dd163db3e412c8b387eaeac982822f6ee0a9a16c11af686c70b01a1e2a48ec2b9da10793743e7b0d3a2729c196f3d0485f70f957282cfd731f9",
          "sha256": "a4df67107ade69986a39280abebdf9ae66c9aed0747a2d03c5bfd632d88aed04",
          "sha1": "1ab3abf9961ea2f6538c554b561ff592a4ced683",
          "md5": "fbf5423689b23911314c8cbd565a1cdb"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.9.2"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-hls",
          "version": {
            "requires": "1.9.2"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-dash",
          "version": {
            "requires": "1.9.2"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-rtsp",
          "version": {
            "requires": "1.9.2"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-smoothstreaming",
          "version": {
            "requires": "1.9.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "video_player_android_release-0.50.aar",
          "url": "video_player_android_release-0.50.aar",
          "size": 98056,
          "sha512": "049fb71f62de4dd163db3e412c8b387eaeac982822f6ee0a9a16c11af686c70b01a1e2a48ec2b9da10793743e7b0d3a2729c196f3d0485f70f957282cfd731f9",
          "sha256": "a4df67107ade69986a39280abebdf9ae66c9aed0747a2d03c5bfd632d88aed04",
          "sha1": "1ab3abf9961ea2f6538c554b561ff592a4ced683",
          "md5": "fbf5423689b23911314c8cbd565a1cdb"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "video_player_android_release-0.50-sources.jar",
          "url": "video_player_android_release-0.50-sources.jar",
          "size": 26931,
          "sha512": "ad5734295e3d2a430d515204017864b81e6c2bd974569e4ce2a12c85b290989af16e745c8b1dda6562dc7cd0cd44a39e34b5b3b36c9b0422a9568fad6332998e",
          "sha256": "e5ca87c8679e3f950902fa2d978806ff357ee80ffcd04416fc7c5a2a21000970",
          "sha1": "ff1a68e54d388b29380c02c515cb3c5779b1c02b",
          "md5": "4fab281c6eccd49db09d5aa9b4d36f4c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "video_player_android_release-0.50-javadoc.jar",
          "url": "video_player_android_release-0.50-javadoc.jar",
          "size": 468918,
          "sha512": "2bd580b8f00a715e8dfd8d40a79e385b2be191752d117660342b56d4341aa112334f7dd27b57c3f3cc2159f1cf12c7e282c755a1509c44a5e3df9da87ef299b3",
          "sha256": "65bbfd7f7cb005c3e3ed320bb2cbe6564f39eaef67fe380fa99bc2b24e262fb1",
          "sha1": "de60d3f82e3c55af2878db1dca1d2add34216ba3",
          "md5": "c4697ab13f7aaf2b8a6f6978713e041e"
        }
      ]
    }
  ]
}
