{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.dart_lang.jni_flutter",
    "module": "jni_flutter_release",
    "version": "0.49",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        }
      ],
      "files": [
        {
          "name": "jni_flutter_release-0.49.aar",
          "url": "jni_flutter_release-0.49.aar",
          "size": 2427,
          "sha512": "97c761376c28718a0a29287f5282dd998641b269f9bc0e8b470ac185ea6b6719a1014b1c66bb2b64e6701f0cc9aa34b208da7fb9040c7b0c6b277aa8b7e94dd8",
          "sha256": "07ffd2a06e1ac0c56d2b9fdd4137e92465e0d36dcefc3a7767fc814363476f13",
          "sha1": "e575ba2cda614864816c20220234a049be2237c0",
          "md5": "d79b0c3fd88408844e211ca64873f26d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        },
        {
          "group": "com.github.dart_lang.jni",
          "module": "jni_release",
          "version": {
            "requires": "0.49"
          }
        }
      ],
      "files": [
        {
          "name": "jni_flutter_release-0.49.aar",
          "url": "jni_flutter_release-0.49.aar",
          "size": 2427,
          "sha512": "97c761376c28718a0a29287f5282dd998641b269f9bc0e8b470ac185ea6b6719a1014b1c66bb2b64e6701f0cc9aa34b208da7fb9040c7b0c6b277aa8b7e94dd8",
          "sha256": "07ffd2a06e1ac0c56d2b9fdd4137e92465e0d36dcefc3a7767fc814363476f13",
          "sha1": "e575ba2cda614864816c20220234a049be2237c0",
          "md5": "d79b0c3fd88408844e211ca64873f26d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "jni_flutter_release-0.49-sources.jar",
          "url": "jni_flutter_release-0.49-sources.jar",
          "size": 1655,
          "sha512": "7a07c72930ea5c442e303f2c17de9b67451b778a59b70d46cadbbfba1a48ec54c6064ed8a8771f3ebac9b4be5a1b590cb73c91f5950db32157c4fbee15a9df72",
          "sha256": "85b049ada44240ce31ffe69985466e9c9fd424e24a293e396576b61f5fefe1b0",
          "sha1": "e3f68df4cf7ea0164890430e8e8a91074584481f",
          "md5": "6ea4b0d8e6f41190c6261b40de37e7b4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "jni_flutter_release-0.49-javadoc.jar",
          "url": "jni_flutter_release-0.49-javadoc.jar",
          "size": 264622,
          "sha512": "819c0fb26e35a3214e34dd8274137c0cf00db547aeb20060db89466e522507bad32670eb5b7c8f0034ef51d9d2678a0a90fb8d61eb55e05b5e00b3083336b516",
          "sha256": "16b4084c41e3d00960fb296accfd0b93413fb5297b4e02e7936e0be9b0783d4e",
          "sha1": "123789da08338cb0b3a8db3af23992d29a174fa8",
          "md5": "78ee8e9761c638c871106707f2ec9cd2"
        }
      ]
    }
  ]
}
