{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.camera",
    "module": "camera_android_debug",
    "version": "1.16",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        }
      ],
      "files": [
        {
          "name": "camera_android_debug-1.16.aar",
          "url": "camera_android_debug-1.16.aar",
          "size": 168513,
          "sha512": "a0d8e40eafeb96792056c335a3f25f573d39443399b01394422b61f9a0015a0ae6b658d09c920e65a9bd2ec6d70310e7f0455406a3d0b8b5ce68821928fecf79",
          "sha256": "42a3f667d5d8a0c726b65918ebc1783c69f46570f103d5b894c202fd622e06df",
          "sha1": "55582f0208e892ed57c4438c319128651c49089e",
          "md5": "19bda8a45f092cb339de13a21e226125"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_debug",
          "version": {
            "requires": "1.16"
          }
        }
      ],
      "files": [
        {
          "name": "camera_android_debug-1.16.aar",
          "url": "camera_android_debug-1.16.aar",
          "size": 168513,
          "sha512": "a0d8e40eafeb96792056c335a3f25f573d39443399b01394422b61f9a0015a0ae6b658d09c920e65a9bd2ec6d70310e7f0455406a3d0b8b5ce68821928fecf79",
          "sha256": "42a3f667d5d8a0c726b65918ebc1783c69f46570f103d5b894c202fd622e06df",
          "sha1": "55582f0208e892ed57c4438c319128651c49089e",
          "md5": "19bda8a45f092cb339de13a21e226125"
        }
      ]
    },
    {
      "name": "debugVariantDebugSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "camera_android_debug-1.16-sources.jar",
          "url": "camera_android_debug-1.16-sources.jar",
          "size": 87770,
          "sha512": "8733a0e5e7d523d2d1391660ca151aaa40df9e5971dd349f74c3a0914b301a96de5bb2f0ca0036453111af4bd793e6a4a80485a925692020d5e8424fcd060e1a",
          "sha256": "11199f940c8ec00530c4b7f72af65b5e760e9afe77a0eec70cbc427bdc892e02",
          "sha1": "ad217bf7a7a1b33d994105f868878a4a5f3ab261",
          "md5": "9806741717a7ed1488e61ce54174ac06"
        }
      ]
    },
    {
      "name": "debugVariantDebugJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "camera_android_debug-1.16-javadoc.jar",
          "url": "camera_android_debug-1.16-javadoc.jar",
          "size": 605670,
          "sha512": "18a182bca2f796e019a67350c03b386c419ac0fbc7c04037c31f2bea55e222f9e0f509491a1c148a5acf3ea27fee45cc67b35a7491dce4ac94575fe7fab6a522",
          "sha256": "33af321dc4400e2530d4793c5072e2364823c76dccd6891820437466e25c6a78",
          "sha1": "9c33564f08c7057de4dc41e4bcd634caec39a5c1",
          "md5": "619e0ac3bd1bb2fbbda1c59ebfa62412"
        }
      ]
    }
  ]
}
