{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.fluttercommunity.plus.device_info",
    "module": "device_info_plus_release",
    "version": "0.58",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        }
      ],
      "files": [
        {
          "name": "device_info_plus_release-0.58.aar",
          "url": "device_info_plus_release-0.58.aar",
          "size": 6932,
          "sha512": "4749f56d78d92dc11eb04d805e655623885a8f6549ed43c58733518105d694890c5251095aff3f31e199c56939a5b8e9329576f0fbc68b7e3d983250b1e07b38",
          "sha256": "6941f2d3701d71d2c6bec48120bc0e1dbc0d8f9b02e081e1c4cb9c60015f4542",
          "sha1": "cc4323b90a02562756d2537851e2731862a918e4",
          "md5": "a0bd92911fc14788066a1dc2e71ec573"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.22"
          }
        }
      ],
      "files": [
        {
          "name": "device_info_plus_release-0.58.aar",
          "url": "device_info_plus_release-0.58.aar",
          "size": 6932,
          "sha512": "4749f56d78d92dc11eb04d805e655623885a8f6549ed43c58733518105d694890c5251095aff3f31e199c56939a5b8e9329576f0fbc68b7e3d983250b1e07b38",
          "sha256": "6941f2d3701d71d2c6bec48120bc0e1dbc0d8f9b02e081e1c4cb9c60015f4542",
          "sha1": "cc4323b90a02562756d2537851e2731862a918e4",
          "md5": "a0bd92911fc14788066a1dc2e71ec573"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "device_info_plus_release-0.58-sources.jar",
          "url": "device_info_plus_release-0.58-sources.jar",
          "size": 2976,
          "sha512": "b0a16c5d099d1a6d3f96d453ca4f34aa2b138d0729fd675fa4dadff9f54e169514b31bd5586b5d4fb388059df0d5e5ff8ceeeec9214322cced8b305c5d67afb3",
          "sha256": "1160189e3c750bbf50affba28a4dbf0fc1216e815a1f01a3d1d9dd17958f37ab",
          "sha1": "b1f985fbb38747f8f626c4988380b4847ff05db6",
          "md5": "7effa257187ed4394bf3919149a7d9e8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "device_info_plus_release-0.58-javadoc.jar",
          "url": "device_info_plus_release-0.58-javadoc.jar",
          "size": 260823,
          "sha512": "5d4f5c90479f64e1ee1403c6873248fe034fbc4bc02466415e07a4cd8143e91c6b97745c01971a7b7e769fa52d785a1797e15290315eef81826f24b4395a866c",
          "sha256": "4253bdb1b376131db25f14b64b1e17eb2b4b5515e0fe092d7ec916df4471c74e",
          "sha1": "f0d7e9beab4dba61396f16b5f9b1309ec1ccdb17",
          "md5": "9d05246a263c282f96b46298fb15a332"
        }
      ]
    }
  ]
}
