{
  "formatVersion": "1.1",
  "component": {
    "group": "com.lib.flutter_blue_plus",
    "module": "flutter_blue_plus_android_release",
    "version": "0.16",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_blue_plus_android_release-0.16.aar",
          "url": "flutter_blue_plus_android_release-0.16.aar",
          "size": 43726,
          "sha512": "f83c0b97fa47d32d50616595ac2e253a29e5764774637368f548c9cd5fa81a7879c9e54616f07cf6f8827ee0abe634f8fdd54854ff259daebac07174e4ffbb9f",
          "sha256": "7b7d3e91f00e81d97acc453a2169cd3d15359b76205acfc1b51226e193b7de23",
          "sha1": "9a9c3ae3f0fe1ce5a98064c009072bddf735d611",
          "md5": "a753e6fff560db83be3be80d4379602e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_blue_plus_android_release-0.16.aar",
          "url": "flutter_blue_plus_android_release-0.16.aar",
          "size": 43726,
          "sha512": "f83c0b97fa47d32d50616595ac2e253a29e5764774637368f548c9cd5fa81a7879c9e54616f07cf6f8827ee0abe634f8fdd54854ff259daebac07174e4ffbb9f",
          "sha256": "7b7d3e91f00e81d97acc453a2169cd3d15359b76205acfc1b51226e193b7de23",
          "sha1": "9a9c3ae3f0fe1ce5a98064c009072bddf735d611",
          "md5": "a753e6fff560db83be3be80d4379602e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_blue_plus_android_release-0.16-sources.jar",
          "url": "flutter_blue_plus_android_release-0.16-sources.jar",
          "size": 24315,
          "sha512": "fce1be94efbed45ac642005b70d573a65c465d5a43ec28ebef8ee5331ca93c664e1ee98bbe7c9d27d73d7c7b85306d0f8a4ec1622fd46c0a3763df237c2eb20e",
          "sha256": "9e2028532ad03708a83ed952f177da22b5376e0cd08ac1548350a0067b363d02",
          "sha1": "0949181f9119f5c1e50d9c0a08456c7ac072bd68",
          "md5": "3303658fda0a6cf48caf12ae9a45b94b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_blue_plus_android_release-0.16-javadoc.jar",
          "url": "flutter_blue_plus_android_release-0.16-javadoc.jar",
          "size": 265357,
          "sha512": "b53bcbaa16e04f4956d5a68f2d57c94f53ad5112f72c880eca3936fcb58cf79aee43a653c00bb90e386bf8bf1e49728f4cd4d8deb48fb2d511aecd2b8b19ee0b",
          "sha256": "f263f4af86e1ad64158fde47995b143e4cf05ceb2451f8222ab8c8b6f3239e01",
          "sha1": "9b056f12a1391bec609d1818ae80035182981a9c",
          "md5": "7236b1107f175eb11c24021ae3036067"
        }
      ]
    }
  ]
}
