{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tekartik.sqflite",
    "module": "sqflite_android_release",
    "version": "0.38",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        }
      ],
      "files": [
        {
          "name": "sqflite_android_release-0.38.aar",
          "url": "sqflite_android_release-0.38.aar",
          "size": 43464,
          "sha512": "7879a5234b45a10d6d14343dd39cc2038f419c9c1f211f2e04b9ddaa5519342b7fbf3b571bb488fc4c04dc07da33ffc708ebda8364532772286f91c08c754e30",
          "sha256": "a2b47e4f53735035112c4d0ecf795b936f49bb4315bea219db776942a98d090b",
          "sha1": "9d71bbae7150e6f0e16a68049adc852a3f5a7575",
          "md5": "90320c1fd75c9407ff1d2397d138f18d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        }
      ],
      "files": [
        {
          "name": "sqflite_android_release-0.38.aar",
          "url": "sqflite_android_release-0.38.aar",
          "size": 43464,
          "sha512": "7879a5234b45a10d6d14343dd39cc2038f419c9c1f211f2e04b9ddaa5519342b7fbf3b571bb488fc4c04dc07da33ffc708ebda8364532772286f91c08c754e30",
          "sha256": "a2b47e4f53735035112c4d0ecf795b936f49bb4315bea219db776942a98d090b",
          "sha1": "9d71bbae7150e6f0e16a68049adc852a3f5a7575",
          "md5": "90320c1fd75c9407ff1d2397d138f18d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sqflite_android_release-0.38-sources.jar",
          "url": "sqflite_android_release-0.38-sources.jar",
          "size": 23906,
          "sha512": "84be2e0f11f6739735214c714fcf25ca7b657afc40b3b54a0f0eff0de0f085cc926571087ab261b90cb6ed1e0be787046b45db4603790b883b119c835c22aa20",
          "sha256": "a127166bbaf1689504c6fc9e5111043a0537dc09ba3ea55a6d743da958ef125a",
          "sha1": "55f721f93f9c468c9d426bc61ff59a393e267750",
          "md5": "3f9cd042a556379914178c3426bed53c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sqflite_android_release-0.38-javadoc.jar",
          "url": "sqflite_android_release-0.38-javadoc.jar",
          "size": 341658,
          "sha512": "3f233ad51d02b29bf54be7d8304ba63bb733b41b65fae3737bfc87c67a5c0c3b8e7a5243719f3deb781b195079f71e942e9c25ef39efdd435effcb557218bc09",
          "sha256": "8f1066ba99abd28b4f7d319435873afde421889481783d3399e85521cf655d48",
          "sha1": "821da9b8b98979a6c2859e26643eb29d421a08e6",
          "md5": "27f72bd958a807fdc1af0f8ffc2361e9"
        }
      ]
    }
  ]
}
