{
  "formatVersion": "1.1",
  "component": {
    "group": "eu.simonbinder.sqlite3_flutter_libs",
    "module": "sqlite3_flutter_libs_release",
    "version": "0.48",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        }
      ],
      "files": [
        {
          "name": "sqlite3_flutter_libs_release-0.48.aar",
          "url": "sqlite3_flutter_libs_release-0.48.aar",
          "size": 2645,
          "sha512": "7b4dbd03128c6f0102b08f4857cb7341516ac1276b3d0b385df1f38aeebdc1bef39b4540d60018decbb744ab64c49aed95d7faae536a0a062b6194a28e3d7a54",
          "sha256": "83d2e060e3458ed1ca74b9fcc737889e0edff46997376e2d35da83403861a473",
          "sha1": "93d31c0338dac780e4b62313cc5714382a7b2df6",
          "md5": "d9bdb8e3831ca54ddb82e9fea2cba741"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        },
        {
          "group": "eu.simonbinder",
          "module": "sqlite3-native-library",
          "version": {
            "requires": "3.50.1"
          }
        }
      ],
      "files": [
        {
          "name": "sqlite3_flutter_libs_release-0.48.aar",
          "url": "sqlite3_flutter_libs_release-0.48.aar",
          "size": 2645,
          "sha512": "7b4dbd03128c6f0102b08f4857cb7341516ac1276b3d0b385df1f38aeebdc1bef39b4540d60018decbb744ab64c49aed95d7faae536a0a062b6194a28e3d7a54",
          "sha256": "83d2e060e3458ed1ca74b9fcc737889e0edff46997376e2d35da83403861a473",
          "sha1": "93d31c0338dac780e4b62313cc5714382a7b2df6",
          "md5": "d9bdb8e3831ca54ddb82e9fea2cba741"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sqlite3_flutter_libs_release-0.48-sources.jar",
          "url": "sqlite3_flutter_libs_release-0.48-sources.jar",
          "size": 1462,
          "sha512": "72a2ddbe506e1d6e2730f00e041dea0f9c617b03138b525c6b88e0ef701b98a66fd1d6b75cd9b22a8ea26fce3e98b7a69945f10593749c1593670c595f78bb9d",
          "sha256": "65510b847d970f272c2935de5b14f0489bd719bee3541f208bc72ba20e42e293",
          "sha1": "cc4891fa470b28d66912771a1d113c24bb411027",
          "md5": "78f2d9b7b35831e0a4e0ebe0e97d4aa4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sqlite3_flutter_libs_release-0.48-javadoc.jar",
          "url": "sqlite3_flutter_libs_release-0.48-javadoc.jar",
          "size": 262085,
          "sha512": "ff8f10fb98b6fb6899f44fdd3d8f60047e632ff2b5f689c5b410af7487b76331aa7c5cf6927c485342c0b220747c5c8a031847def36eb9b2575b888370f27673",
          "sha256": "aa5197f2dbe4c8392a675e13cd44224d1ce99537468938e9a9467b11f3971f45",
          "sha1": "329f01b764307c05d798c35ef8d8f3a15eccafb4",
          "md5": "b3a69b4b63ae26cbffd1a10c8f12195a"
        }
      ]
    }
  ]
}
