{
  "formatVersion": "1.1",
  "component": {
    "group": "com.benjaminabel.vibration",
    "module": "vibration_release",
    "version": "0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        }
      ],
      "files": [
        {
          "name": "vibration_release-0.2.aar",
          "url": "vibration_release-0.2.aar",
          "size": 5440,
          "sha512": "10d872a88b61b26c96994c6968beabcde80b7b9848b6d0b368b3717c4c124abeaef073630c1156afe899b04b3ab508268b82187f8467250c9346ca134d07ff65",
          "sha256": "78ff255c981659585f6c442040ced246ee2e5c8020701e976bd37b57145b50e9",
          "sha1": "72b1c38ff52dc905fe062b03d7c3ec78f7cd189e",
          "md5": "c12b085f35fdcac60d3eec06b44ed6d0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        }
      ],
      "files": [
        {
          "name": "vibration_release-0.2.aar",
          "url": "vibration_release-0.2.aar",
          "size": 5440,
          "sha512": "10d872a88b61b26c96994c6968beabcde80b7b9848b6d0b368b3717c4c124abeaef073630c1156afe899b04b3ab508268b82187f8467250c9346ca134d07ff65",
          "sha256": "78ff255c981659585f6c442040ced246ee2e5c8020701e976bd37b57145b50e9",
          "sha1": "72b1c38ff52dc905fe062b03d7c3ec78f7cd189e",
          "md5": "c12b085f35fdcac60d3eec06b44ed6d0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vibration_release-0.2-sources.jar",
          "url": "vibration_release-0.2-sources.jar",
          "size": 3055,
          "sha512": "384eb290f3959fdee7c259a16e1644ce0676709e1319436f231a1522a548ce0da6c9c7cb04a44b1f3456d50b0488a26d7d80341b6469032740a43a3b226217cc",
          "sha256": "70496470796b88fca44d8fc2ef720ac6bec89b83bbfdefe956dd680a981d8ab6",
          "sha1": "daa83f1f05e9c60ae716519b35e89d79487faf04",
          "md5": "6c40e406630f8b8a8285a64427b965be"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vibration_release-0.2-javadoc.jar",
          "url": "vibration_release-0.2-javadoc.jar",
          "size": 265463,
          "sha512": "a644168bfabe7ef77ed84075b32dd64e1c0fa01f427ee3f4b2a395af643256b27ca103ecf10d9f379e4900c8958a67172b1ccad0f81c3ef7c525e23400307e4c",
          "sha256": "c8ee45d03f22206ec48e66c427e6137ab620341e9fb85c7713380fe6594df8a7",
          "sha1": "6bfcf9e2a02fa090ba83501af074f1df7a9cc09f",
          "md5": "f7b09c94ede4a75059ecff31a57f5e68"
        }
      ]
    }
  ]
}
