{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.camerax",
    "module": "camera_android_camerax_release",
    "version": "0.31",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        }
      ],
      "files": [
        {
          "name": "camera_android_camerax_release-0.31.aar",
          "url": "camera_android_camerax_release-0.31.aar",
          "size": 266221,
          "sha512": "9af0a5516c2edc27dd35858ebd02c891abf2d850a8cc85be4d23507c3a6b7e3f2742d8724961acfcb5137e32906544fb644759633a842beafd80c2d4cdb31152",
          "sha256": "7c8342a73daf94abcfa1e61df23b7ca3ff6a53e5277ae96d936f58f33e681264",
          "sha1": "bb7b05b1620dd32e4d7199c34e11dc32186b6e96",
          "md5": "b48fafc498f8aa5db42a088ead6fb5a4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.3.4"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.3.4"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.3.4"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-video",
          "version": {
            "requires": "1.3.4"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.3.1-android"
          }
        }
      ],
      "files": [
        {
          "name": "camera_android_camerax_release-0.31.aar",
          "url": "camera_android_camerax_release-0.31.aar",
          "size": 266221,
          "sha512": "9af0a5516c2edc27dd35858ebd02c891abf2d850a8cc85be4d23507c3a6b7e3f2742d8724961acfcb5137e32906544fb644759633a842beafd80c2d4cdb31152",
          "sha256": "7c8342a73daf94abcfa1e61df23b7ca3ff6a53e5277ae96d936f58f33e681264",
          "sha1": "bb7b05b1620dd32e4d7199c34e11dc32186b6e96",
          "md5": "b48fafc498f8aa5db42a088ead6fb5a4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "camera_android_camerax_release-0.31-sources.jar",
          "url": "camera_android_camerax_release-0.31-sources.jar",
          "size": 86316,
          "sha512": "5382ce18bd09440222ebf82115235b669fd9af0e5aa1b7230156e004966fa02af4d6769714e893b0e78dff5e9f64a7111abc9ae654e1ab61bf292113b6ecdfc0",
          "sha256": "79f2b55e1b567c1876f27760b5465af879a2a59f33efec52baeeb486833fa9f7",
          "sha1": "e6e78d7a217d954c995f6146e7d112c64e43e04f",
          "md5": "e33d81ce6a5534f6131cd452966dd58f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "camera_android_camerax_release-0.31-javadoc.jar",
          "url": "camera_android_camerax_release-0.31-javadoc.jar",
          "size": 901871,
          "sha512": "d0d566b5abb669149ea6a189936d4cb9e4cc6e20dce0f2a29fc35617c15202830634066d336090f676972ad04bf64754c17614e0aef8f88bd6e8463b5001516c",
          "sha256": "0946bea1b5344aa6bcc860917c1ce9e6d5b579c38fee47a6b4fb7c73ad113b24",
          "sha1": "8883105fd5c29be3f997627104fed3d7c8b4b802",
          "md5": "66996d03d1e28322122d2691dae89412"
        }
      ]
    }
  ]
}
