{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.dart_lang.jni_flutter",
    "module": "jni_flutter_release",
    "version": "0.57",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        }
      ],
      "files": [
        {
          "name": "jni_flutter_release-0.57.aar",
          "url": "jni_flutter_release-0.57.aar",
          "size": 2427,
          "sha512": "97c761376c28718a0a29287f5282dd998641b269f9bc0e8b470ac185ea6b6719a1014b1c66bb2b64e6701f0cc9aa34b208da7fb9040c7b0c6b277aa8b7e94dd8",
          "sha256": "07ffd2a06e1ac0c56d2b9fdd4137e92465e0d36dcefc3a7767fc814363476f13",
          "sha1": "e575ba2cda614864816c20220234a049be2237c0",
          "md5": "d79b0c3fd88408844e211ca64873f26d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        },
        {
          "group": "com.github.dart_lang.jni",
          "module": "jni_release",
          "version": {
            "requires": "0.57"
          }
        }
      ],
      "files": [
        {
          "name": "jni_flutter_release-0.57.aar",
          "url": "jni_flutter_release-0.57.aar",
          "size": 2427,
          "sha512": "97c761376c28718a0a29287f5282dd998641b269f9bc0e8b470ac185ea6b6719a1014b1c66bb2b64e6701f0cc9aa34b208da7fb9040c7b0c6b277aa8b7e94dd8",
          "sha256": "07ffd2a06e1ac0c56d2b9fdd4137e92465e0d36dcefc3a7767fc814363476f13",
          "sha1": "e575ba2cda614864816c20220234a049be2237c0",
          "md5": "d79b0c3fd88408844e211ca64873f26d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "jni_flutter_release-0.57-sources.jar",
          "url": "jni_flutter_release-0.57-sources.jar",
          "size": 1655,
          "sha512": "7a07c72930ea5c442e303f2c17de9b67451b778a59b70d46cadbbfba1a48ec54c6064ed8a8771f3ebac9b4be5a1b590cb73c91f5950db32157c4fbee15a9df72",
          "sha256": "85b049ada44240ce31ffe69985466e9c9fd424e24a293e396576b61f5fefe1b0",
          "sha1": "e3f68df4cf7ea0164890430e8e8a91074584481f",
          "md5": "6ea4b0d8e6f41190c6261b40de37e7b4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "jni_flutter_release-0.57-javadoc.jar",
          "url": "jni_flutter_release-0.57-javadoc.jar",
          "size": 264622,
          "sha512": "90a6b09cedcf92f0d123ae06f431317cfaffd67fb76ed2b9267d66d5f0c42ff0f65fae1c4f7d62051c051eb8e8e7f9fbeba554061a1d36654acf579e7e956a38",
          "sha256": "8766dc2be09fda40a9067c7de9a2550249de2e27643f00b333dc7f787f754235",
          "sha1": "ba942ea7d925e7d27d65bc3678df13cd91c3e392",
          "md5": "1bb23af8573302782dbe4dc67320d9c0"
        }
      ]
    }
  ]
}
