{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.imagepicker",
    "module": "image_picker_android_debug",
    "version": "0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        }
      ],
      "files": [
        {
          "name": "image_picker_android_debug-0.1.aar",
          "url": "image_picker_android_debug-0.1.aar",
          "size": 73723,
          "sha512": "3982b7c437c8c92923199a6f17f2afc77504b5ed943a1f22efe5c4212b16046d7affe06ceb146d6e79eb0eb0a0a00abae1695ccfb5dad5211d162889fd629f20",
          "sha256": "b44b59f0c6532a8b56bd5d9534a93140c6ebba02a2bf5b7373e677d88c4fa2fc",
          "sha1": "1a7eb9fe4b27bc9a90bd6103c5e9d8fbc852708a",
          "md5": "dbf5dc5dd70b9108b24ba51a1532c41f"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.7"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.9.3"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_debug",
          "version": {
            "requires": "0.1"
          }
        }
      ],
      "files": [
        {
          "name": "image_picker_android_debug-0.1.aar",
          "url": "image_picker_android_debug-0.1.aar",
          "size": 73723,
          "sha512": "3982b7c437c8c92923199a6f17f2afc77504b5ed943a1f22efe5c4212b16046d7affe06ceb146d6e79eb0eb0a0a00abae1695ccfb5dad5211d162889fd629f20",
          "sha256": "b44b59f0c6532a8b56bd5d9534a93140c6ebba02a2bf5b7373e677d88c4fa2fc",
          "sha1": "1a7eb9fe4b27bc9a90bd6103c5e9d8fbc852708a",
          "md5": "dbf5dc5dd70b9108b24ba51a1532c41f"
        }
      ]
    },
    {
      "name": "debugVariantDebugSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "image_picker_android_debug-0.1-sources.jar",
          "url": "image_picker_android_debug-0.1-sources.jar",
          "size": 26710,
          "sha512": "372c55c93aa9de3bc39caaa735c8e9f72983fb2a602de7ddd3be0527b8ab1f43bb8f5583d2ec4a8e3b61d6eb874e7e4cf34c0f725649e2d8806f4a45f0225e35",
          "sha256": "3cab7df6aafaac4936a8156024350f81aff0ce6ff88a827513403c895316ab3e",
          "sha1": "50f46bd80d3ea3246d7442d73c95694a4deafe04",
          "md5": "0651b7414a10b08945561bd62b096625"
        }
      ]
    },
    {
      "name": "debugVariantDebugJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "image_picker_android_debug-0.1-javadoc.jar",
          "url": "image_picker_android_debug-0.1-javadoc.jar",
          "size": 382892,
          "sha512": "51ed5ed087c3858b751713d4e39bd747a4ff387f46ded481dbf84dce938e9149a02c5dede91b5920d2cbafd32380bba4496b9e3780cef9900bdee88cf6343edb",
          "sha256": "19f6ba0fcda2e8c0eea8bb8a227576dfdf6935f32523fe8621c95f18074e96d7",
          "sha1": "85555c78454e04f7e48c1fb60c906402c78e983f",
          "md5": "4e3ee4f56e7b730caf1966d82b9d071f"
        }
      ]
    }
  ]
}
