{
  "formatVersion": "1.1",
  "component": {
    "group": "com.cloudwebrtc.webrtc",
    "module": "flutter_webrtc_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_webrtc_debug-1.0.aar",
          "url": "flutter_webrtc_debug-1.0.aar",
          "size": 204037,
          "sha512": "0dcd0b69d93de386f5e8e52408ba1032b75d916b72306fc48f2190bcbf73b360c058a4a73688b1fb50cdc6deaedeec6fef645fc04d8f918f68bc0c840b464a9c",
          "sha256": "25a73293b72c3cc2ccd42752586676ea38177083ab3a0a64bc7987f80e49b5f0",
          "sha1": "bfbac34cef2121c0995669f613f032727253549c",
          "md5": "d1576dcabaa17dafc121f00e52c06eca"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        },
        {
          "group": "io.github.webrtc-sdk",
          "module": "android",
          "version": {
            "requires": "125.6422.03"
          }
        },
        {
          "group": "com.github.davidliu",
          "module": "audioswitch",
          "version": {
            "requires": "89582c47c9a04c62f90aa5e57251af4800a62c9a"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_webrtc_debug-1.0.aar",
          "url": "flutter_webrtc_debug-1.0.aar",
          "size": 204037,
          "sha512": "0dcd0b69d93de386f5e8e52408ba1032b75d916b72306fc48f2190bcbf73b360c058a4a73688b1fb50cdc6deaedeec6fef645fc04d8f918f68bc0c840b464a9c",
          "sha256": "25a73293b72c3cc2ccd42752586676ea38177083ab3a0a64bc7987f80e49b5f0",
          "sha1": "bfbac34cef2121c0995669f613f032727253549c",
          "md5": "d1576dcabaa17dafc121f00e52c06eca"
        }
      ]
    },
    {
      "name": "debugVariantDebugSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_webrtc_debug-1.0-sources.jar",
          "url": "flutter_webrtc_debug-1.0-sources.jar",
          "size": 88566,
          "sha512": "f650a0b74b2eaf4b2dd885894175e35a1f201734c719779b1d203e791816412613ee8d460b477c6f2f0f8bfa40665fef2f5b72ce211ac33915fb03f56286037c",
          "sha256": "299a782649016c4c489d9012ac21cc7c74beedea28819679dcab4624880763d6",
          "sha1": "dcd6fe48a79446555fcdd90a0ac5467228a9afe7",
          "md5": "a627730b77b1017611e86df2dda74384"
        }
      ]
    },
    {
      "name": "debugVariantDebugJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_webrtc_debug-1.0-javadoc.jar",
          "url": "flutter_webrtc_debug-1.0-javadoc.jar",
          "size": 506091,
          "sha512": "29170c4b8a946e125b544dbd1388c1b3c29da4df973b17f0b74e52ef45a6e06b3d1316587b7eedd6041b5857d1dc3660bed72a2d80ffd465209f3dcd61a2caf9",
          "sha256": "7ef59ae368322ba5f52299c6ac57d1945323bf01d86fc1b6f0b94ddfeaead414",
          "sha1": "aa1f2c5056dae761df2f8cf24dfa014d73410a74",
          "md5": "dd9f76b850ab29143d30d7eba76f7758"
        }
      ]
    }
  ]
}
