{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.fluttercommunity.plus.packageinfo",
    "module": "package_info_plus_release",
    "version": "0.56",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        }
      ],
      "files": [
        {
          "name": "package_info_plus_release-0.56.aar",
          "url": "package_info_plus_release-0.56.aar",
          "size": 5912,
          "sha512": "d8f9dbd3cc229f86f2a69eba192b9c266d398cb23cefef0253e05145092087434e45fa71476d458db141f92fb80bfe218e9b3276c9c20d357d7c31977d428504",
          "sha256": "88a724ab3a0f7f3435ff94ec6e2ab516cee597421913b6d0b1839f77286e048f",
          "sha1": "33671c94b7750e62b0b176733fa8e43b4eac5ab6",
          "md5": "70e02aab9fb49ee52e454d1936f3ef66"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.22"
          }
        }
      ],
      "files": [
        {
          "name": "package_info_plus_release-0.56.aar",
          "url": "package_info_plus_release-0.56.aar",
          "size": 5912,
          "sha512": "d8f9dbd3cc229f86f2a69eba192b9c266d398cb23cefef0253e05145092087434e45fa71476d458db141f92fb80bfe218e9b3276c9c20d357d7c31977d428504",
          "sha256": "88a724ab3a0f7f3435ff94ec6e2ab516cee597421913b6d0b1839f77286e048f",
          "sha1": "33671c94b7750e62b0b176733fa8e43b4eac5ab6",
          "md5": "70e02aab9fb49ee52e454d1936f3ef66"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "package_info_plus_release-0.56-sources.jar",
          "url": "package_info_plus_release-0.56-sources.jar",
          "size": 2693,
          "sha512": "baaae2e6245030a7de70f19e43504fb87d6d374ec50af2dd23321d0ab0bf43dbb918967f0b66277e2662ccb4faf2098ffcb870dd1e597bc1dc8ac730e9c7b5fb",
          "sha256": "3f208ebbb8c9b93761dea623949b7ee1a9cd74e818acede7ccc4f562f3839a5d",
          "sha1": "12df81060cfa11fc35581f9c91da8922a5f8e6f0",
          "md5": "f30e01eabb60c79316840a3ed7edecb3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "package_info_plus_release-0.56-javadoc.jar",
          "url": "package_info_plus_release-0.56-javadoc.jar",
          "size": 265026,
          "sha512": "dc576e2f6e36ecceb1fdff6bb38fd99d3e9bf9daf77ffba7ecf289111d32e3f9a633fcf99c91d665496c10aa5a41906169ea91b3b1525bac83fb502a192cc508",
          "sha256": "8b2aab339011331e1196bd7c43787d21298a8f7564ca88e09504244b101d6a47",
          "sha1": "a0b23ef4bd7fc9f39a06f43b20753e9775f4c020",
          "md5": "70dd6818becd31fd864217246f2a6be2"
        }
      ]
    }
  ]
}
