{
  "formatVersion": "1.1",
  "component": {
    "group": "com.ryanheise.just_audio",
    "module": "just_audio_release",
    "version": "0.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        }
      ],
      "files": [
        {
          "name": "just_audio_release-0.10.aar",
          "url": "just_audio_release-0.10.aar",
          "size": 28289,
          "sha512": "184c504db166593522a0acfdbd182c691d74f67ede7c11cab58f4cb1f28f2f18fdf693ef223e313bd3b7b32e7f5676e6bc081b57cd5cc16f17a4a4842f2d7e1b",
          "sha256": "78536165eef803b7bad208bbbcd4135761ab98c3edf3a32471969061a3233576",
          "sha1": "5c55d61cbc5a63024a161cabd0493d2a6482a7d2",
          "md5": "95e027a05bec563ba785a8942577e8c7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-dash",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-hls",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-smoothstreaming",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "com.ryanheise.audio_session",
          "module": "audio_session_release",
          "version": {
            "requires": "0.10"
          }
        }
      ],
      "files": [
        {
          "name": "just_audio_release-0.10.aar",
          "url": "just_audio_release-0.10.aar",
          "size": 28289,
          "sha512": "184c504db166593522a0acfdbd182c691d74f67ede7c11cab58f4cb1f28f2f18fdf693ef223e313bd3b7b32e7f5676e6bc081b57cd5cc16f17a4a4842f2d7e1b",
          "sha256": "78536165eef803b7bad208bbbcd4135761ab98c3edf3a32471969061a3233576",
          "sha1": "5c55d61cbc5a63024a161cabd0493d2a6482a7d2",
          "md5": "95e027a05bec563ba785a8942577e8c7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "just_audio_release-0.10-sources.jar",
          "url": "just_audio_release-0.10-sources.jar",
          "size": 12582,
          "sha512": "4c74666e6cb433b23add7817626b1c45479cdfc21af2a26a4a8ea6e69300e146d22993f411e49cff224b24b9e7e1e067a77f891928dd1ca65021eb9a63e9ff4e",
          "sha256": "f94942b93845504a26f04cfd74c59692e1cbcfadba30d8eb629017c0a4198494",
          "sha1": "aa81c8a6ecfa8f70b620833ef3bf576271acc226",
          "md5": "f292ec584d0d455cc3f8f7572d327f67"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "just_audio_release-0.10-javadoc.jar",
          "url": "just_audio_release-0.10-javadoc.jar",
          "size": 299147,
          "sha512": "5a6555ff16477def5453a7b62f089be196dac7fc33a081662ad0a1c160b902905561546e05b1819e61d91239aa77cf54f18183265a9534b0b22b68c2531dd712",
          "sha256": "261fa86b659303f2bcce3cd037691eeb4a16319c6ba229456fc8c7ad36a6859f",
          "sha1": "f792e58c64fec702590da71e1e17d9fe2a30ab95",
          "md5": "53c7ece3d666eb0825bb30f2ddf0aa2f"
        }
      ]
    }
  ]
}
