{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.steenbakker.mobile_scanner",
    "module": "mobile_scanner_release",
    "version": "0.61",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "mobile_scanner_release-0.61.aar",
          "url": "mobile_scanner_release-0.61.aar",
          "size": 68127,
          "sha512": "261024b0f205a19ad13b01a85075cc11e665bf173039d67e7fdde56ade6a819d6f41ca42d78c7b81e0540f61596fce556580f1dd39e6f4a1cf5e911e7b3e25d4",
          "sha256": "32d87469213d3c0c3b361c98e37eb9627231f660698ec1ff94bab2584015c711",
          "sha1": "b3fea64dc66b3f70b90df15ae16824f67b0a37f8",
          "md5": "2558c7e9981a3ffc339ed2758f91950b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        },
        {
          "group": "com.google.mlkit",
          "module": "barcode-scanning",
          "version": {
            "requires": "17.3.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.3.4"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.3.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "mobile_scanner_release-0.61.aar",
          "url": "mobile_scanner_release-0.61.aar",
          "size": 68127,
          "sha512": "261024b0f205a19ad13b01a85075cc11e665bf173039d67e7fdde56ade6a819d6f41ca42d78c7b81e0540f61596fce556580f1dd39e6f4a1cf5e911e7b3e25d4",
          "sha256": "32d87469213d3c0c3b361c98e37eb9627231f660698ec1ff94bab2584015c711",
          "sha1": "b3fea64dc66b3f70b90df15ae16824f67b0a37f8",
          "md5": "2558c7e9981a3ffc339ed2758f91950b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "mobile_scanner_release-0.61-sources.jar",
          "url": "mobile_scanner_release-0.61-sources.jar",
          "size": 20090,
          "sha512": "d3362bed54acd1325cb709f17d94411437ca5b2f26cbf04bee894c45a1014964f855f9869cfa4d57be601465f6af445a644a3b756f1fe922cb86ea7dd856faed",
          "sha256": "d83d054e3d529b76cfe1b623f586029ca1492f55dd21a3d0a20a33654ac085cd",
          "sha1": "e46370da755c3f10ba18bb11111dfda70707b9d0",
          "md5": "020546aa5e6a0183f636d87d2e226082"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "mobile_scanner_release-0.61-javadoc.jar",
          "url": "mobile_scanner_release-0.61-javadoc.jar",
          "size": 380207,
          "sha512": "6acf44903f0ab55f4997d17ea3d894f45a559efa3f122cf09573ae43b442cbb47e7a6670afaacdd83cc958f0891d1d503e6dab3cc94df55d6e1def0c46dbb645",
          "sha256": "ee26d0d8c129222d7648bac72ceae000eefc595c4a2a3b8ffa651934c8fb3052",
          "sha1": "148a252e5a2a7c0d4cfed953e6fda77e471f7fc4",
          "md5": "39245b7f3ad38a648def1910017df433"
        }
      ]
    }
  ]
}
