{
  "formatVersion": "1.1",
  "component": {
    "group": "com.uxcam.flutteruxcam",
    "module": "flutter_uxcam_release",
    "version": ".39",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_uxcam_release-.39.aar",
          "url": "flutter_uxcam_release-.39.aar",
          "size": 15630,
          "sha512": "d73929120cbb67296aef2ceafa840d0b3e4e816ea03bc35fa0d4f87983c1f6cd598fbb661067e40253a664533edb8314db13a5c81d1ad7caf1dd6939a6e2f4f1",
          "sha256": "be5d3b8d9737ae769dd2f084f6dfcff34953003421e418fd2af75a8a38403385",
          "sha1": "737318f58b543b6fff4bae4dd5645f13d46387ce",
          "md5": "d36cc8a6b15f3da90395a8381c359142"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        },
        {
          "group": "com.uxcam",
          "module": "uxcam",
          "version": {
            "requires": "3.7.3"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.8.1"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_uxcam_release-.39.aar",
          "url": "flutter_uxcam_release-.39.aar",
          "size": 15630,
          "sha512": "d73929120cbb67296aef2ceafa840d0b3e4e816ea03bc35fa0d4f87983c1f6cd598fbb661067e40253a664533edb8314db13a5c81d1ad7caf1dd6939a6e2f4f1",
          "sha256": "be5d3b8d9737ae769dd2f084f6dfcff34953003421e418fd2af75a8a38403385",
          "sha1": "737318f58b543b6fff4bae4dd5645f13d46387ce",
          "md5": "d36cc8a6b15f3da90395a8381c359142"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_uxcam_release-.39-sources.jar",
          "url": "flutter_uxcam_release-.39-sources.jar",
          "size": 6624,
          "sha512": "8c8995128d92a57940fc4ee3e197a0c24043259571da84341c0033ac0c3e14c86692995b1fb3445702f6bf90978e766348da6498e74089f5d2229be78fead2c6",
          "sha256": "38576f89ca9a96e844bc0811bb6268e5a97ca6cebf7ddcf35fb62eafa63f0ff8",
          "sha1": "b5de60a02ecbc73237aac07c073ea8a38b9e3c72",
          "md5": "71e9af78ee02c8408fa779d1ec7bdf5a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_uxcam_release-.39-javadoc.jar",
          "url": "flutter_uxcam_release-.39-javadoc.jar",
          "size": 286923,
          "sha512": "e8af3fe897326f9da7b15a9948131f45265fd972a2557684a5dad7759f35444e8c675435b110f5e10390c299ee14c39d8833eadae6ab574a1741626854eac8f5",
          "sha256": "4ff1a1542b3bba7b986211e8be83d4ff4b5d0ab060400439dc6c4d1fba241cff",
          "sha1": "4269ac9374da3afbde69407a154f50fcc876ea21",
          "md5": "631310bbb44850fa5f382d534ea9e994"
        }
      ]
    }
  ]
}
