{
  "formatVersion": "1.1",
  "component": {
    "group": "com.baseflow.permissionhandler",
    "module": "permission_handler_android_release",
    "version": "0.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        }
      ],
      "files": [
        {
          "name": "permission_handler_android_release-0.10.aar",
          "url": "permission_handler_android_release-0.10.aar",
          "size": 26448,
          "sha512": "885a61c1693e9a63814e13030c0a262dc6c41e1045670b7f5e3851d25f5122be0b00bddb555b74386d3cd79c80b59f312ba44cff460d25c17e3b4384a18c9414",
          "sha256": "ea1ae6e4ca02baf1c3bdb76114435110135e35f1f44055f32f9b1c11dd0339a3",
          "sha1": "9393d7e7522511002b424d27651a24ab36d828a5",
          "md5": "32be0d5d04344864bd83b344d2708707"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        }
      ],
      "files": [
        {
          "name": "permission_handler_android_release-0.10.aar",
          "url": "permission_handler_android_release-0.10.aar",
          "size": 26448,
          "sha512": "885a61c1693e9a63814e13030c0a262dc6c41e1045670b7f5e3851d25f5122be0b00bddb555b74386d3cd79c80b59f312ba44cff460d25c17e3b4384a18c9414",
          "sha256": "ea1ae6e4ca02baf1c3bdb76114435110135e35f1f44055f32f9b1c11dd0339a3",
          "sha1": "9393d7e7522511002b424d27651a24ab36d828a5",
          "md5": "32be0d5d04344864bd83b344d2708707"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "permission_handler_android_release-0.10-sources.jar",
          "url": "permission_handler_android_release-0.10-sources.jar",
          "size": 18178,
          "sha512": "f75ef3dcffb564829cd6a38e38286f4980d44f582e5fe3c185db3c0082da1423393c92de6556956c158928669790cb4220d56c0e2eee1de390df6055fdef5018",
          "sha256": "b1c5b90d8a5e74eb10437a278638751fb12e6d863b14b6225eb7aef1941cb434",
          "sha1": "04e0db92f72a5112e79b561b446c85b4d4e32e2c",
          "md5": "6c3c580a555a61e926892f7155fcdfd2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "permission_handler_android_release-0.10-javadoc.jar",
          "url": "permission_handler_android_release-0.10-javadoc.jar",
          "size": 264648,
          "sha512": "5885bd6bd9bb71b268975aef62dfd1d88fb480df6866628f50309aa729e79f2db2dd5b52b7aa3e374e481d0fcf5184d93d4a8e31ae2eb997342a31a53f30d514",
          "sha256": "52bc81efe8e630abe0736a742b87bcc75e16769933a14ff5eb3f48b5c8ba0473",
          "sha1": "e6e0f6c71e951715c0ac6f9cc0a736f37d89c82d",
          "md5": "ff5b28b596242ec557e9011088d917e0"
        }
      ]
    }
  ]
}
