{
  "formatVersion": "1.1",
  "component": {
    "group": "com.cloudwebrtc.webrtc",
    "module": "flutter_webrtc_release",
    "version": "0.55",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_webrtc_release-0.55.aar",
          "url": "flutter_webrtc_release-0.55.aar",
          "size": 193271,
          "sha512": "38272972962f0c0f8f97f9ff0da107c1f3ff60d63f70e83788f147afa04f38db2fa63af5f05ca93f3d43e37ac9815a66124c5f793e878881628b2f0e3ad68616",
          "sha256": "77cace6bda27eb5ffb11df0efc42206664b3093426ed23158c5bb2f42aee052a",
          "sha1": "82ae42b67c686484d4d92ace8de518606dcb458a",
          "md5": "573c0bdedbdc24de079ca8c7dab4ccd5"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        },
        {
          "group": "io.github.webrtc-sdk",
          "module": "android",
          "version": {
            "requires": "125.6422.03"
          }
        },
        {
          "group": "com.github.davidliu",
          "module": "audioswitch",
          "version": {
            "requires": "89582c47c9a04c62f90aa5e57251af4800a62c9a"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_webrtc_release-0.55.aar",
          "url": "flutter_webrtc_release-0.55.aar",
          "size": 193271,
          "sha512": "38272972962f0c0f8f97f9ff0da107c1f3ff60d63f70e83788f147afa04f38db2fa63af5f05ca93f3d43e37ac9815a66124c5f793e878881628b2f0e3ad68616",
          "sha256": "77cace6bda27eb5ffb11df0efc42206664b3093426ed23158c5bb2f42aee052a",
          "sha1": "82ae42b67c686484d4d92ace8de518606dcb458a",
          "md5": "573c0bdedbdc24de079ca8c7dab4ccd5"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_webrtc_release-0.55-sources.jar",
          "url": "flutter_webrtc_release-0.55-sources.jar",
          "size": 88566,
          "sha512": "f650a0b74b2eaf4b2dd885894175e35a1f201734c719779b1d203e791816412613ee8d460b477c6f2f0f8bfa40665fef2f5b72ce211ac33915fb03f56286037c",
          "sha256": "299a782649016c4c489d9012ac21cc7c74beedea28819679dcab4624880763d6",
          "sha1": "dcd6fe48a79446555fcdd90a0ac5467228a9afe7",
          "md5": "a627730b77b1017611e86df2dda74384"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_webrtc_release-0.55-javadoc.jar",
          "url": "flutter_webrtc_release-0.55-javadoc.jar",
          "size": 506160,
          "sha512": "848de85ef862f21282a40d4d1b6c77b931fd89c338d653b2c9f9d42cbd322a3d94299cf11cca3c7ea5d1bf853443a00e0f1648126133c3fc7302ff2db43add1c",
          "sha256": "e7d61901cc7e68e814786277f6bed9f1bb04b5d9f2d7a43adee509845d548dc8",
          "sha1": "150c078ab083aa61282be06b1833b871fa468fb6",
          "md5": "d9d3b773dd7d481be45a8ce61a038dd2"
        }
      ]
    }
  ]
}
