{
  "formatVersion": "1.1",
  "component": {
    "group": "com.aboutyou.dart_packages.sign_in_with_apple",
    "module": "sign_in_with_apple_release",
    "version": "0.59",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        }
      ],
      "files": [
        {
          "name": "sign_in_with_apple_release-0.59.aar",
          "url": "sign_in_with_apple_release-0.59.aar",
          "size": 8177,
          "sha512": "f116d321fb964c5332220237f4f9cf61d5d6be6ae89f0befc28904dca5d5d961f90d45cf84dad20c9e1119edf4615d7086e221634325a792a3dd5b5830d04843",
          "sha256": "56a5c7a0b97780cc494f803ac383d0e31661ba949ad3394cc3b558cacfcb3c75",
          "sha1": "77855e85afff33761aa0a2c21e32f2330cc9bdbf",
          "md5": "57d791f9b248b96924b9174b51feab12"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "sign_in_with_apple_release-0.59.aar",
          "url": "sign_in_with_apple_release-0.59.aar",
          "size": 8177,
          "sha512": "f116d321fb964c5332220237f4f9cf61d5d6be6ae89f0befc28904dca5d5d961f90d45cf84dad20c9e1119edf4615d7086e221634325a792a3dd5b5830d04843",
          "sha256": "56a5c7a0b97780cc494f803ac383d0e31661ba949ad3394cc3b558cacfcb3c75",
          "sha1": "77855e85afff33761aa0a2c21e32f2330cc9bdbf",
          "md5": "57d791f9b248b96924b9174b51feab12"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sign_in_with_apple_release-0.59-sources.jar",
          "url": "sign_in_with_apple_release-0.59-sources.jar",
          "size": 2730,
          "sha512": "232813b66653332be1825dda86c44197be6a6e5c4db974c29b5e382607c23c3453837625416f9ae13f991ba92f998f99dc25155e699a146881cd86e42431b316",
          "sha256": "3f74fc332e872fbcfdc3245f838f6f2e4704e5b0c6a0c865417757fad32ab9b4",
          "sha1": "227ee9e1b8ad1d2663b181163fd2a12db200cd6a",
          "md5": "57be615d4366529cd2aa5385e32ef800"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sign_in_with_apple_release-0.59-javadoc.jar",
          "url": "sign_in_with_apple_release-0.59-javadoc.jar",
          "size": 311965,
          "sha512": "e5aebc3ca1a54daef65d180c14ab7e5984f8b8f5910cfbc97c16528356c357805419fe40429b9a09c9d9b1e8fe66a24898cd41f704112074cc214f8f31d121f7",
          "sha256": "2c06dfdf47dfa929267c941a1ba0120a168b653f9242e853ee93c78872077c63",
          "sha1": "9df550f9caacdc265af2b2e59112f7b08056b3c3",
          "md5": "9377a649515e37ddace70273abf797ba"
        }
      ]
    }
  ]
}
