{
  "formatVersion": "1.1",
  "component": {
    "group": "com.omnihealth.flutter_ring_module",
    "module": "flutter_release",
    "version": "0.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        },
        {
          "group": "com.ryanheise.audio_session",
          "module": "audio_session_release",
          "version": {
            "requires": "0.12"
          }
        },
        {
          "group": "io.flutter.plugins.camera",
          "module": "camera_android_release",
          "version": {
            "requires": "0.12"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.connectivity",
          "module": "connectivity_plus_release",
          "version": {
            "requires": "0.12"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.device_info",
          "module": "device_info_plus_release",
          "version": {
            "requires": "0.12"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.core",
          "module": "firebase_core_release",
          "version": {
            "requires": "0.12"
          }
        },
        {
          "group": "io.flutter.plugins.firebaseperformance",
          "module": "firebase_performance_release",
          "version": {
            "requires": "0.12"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.firebaseremoteconfig",
          "module": "firebase_remote_config_release",
          "version": {
            "requires": "0.12"
          }
        },
        {
          "group": "com.lib.flutter_blue_plus",
          "module": "flutter_blue_plus_android_release",
          "version": {
            "requires": "0.12"
          }
        },
        {
          "group": "com.crazecoder.flutterbugly",
          "module": "flutter_bugly_release",
          "version": {
            "requires": "0.12"
          }
        },
        {
          "group": "com.fluttercandies.flutter_image_compress",
          "module": "flutter_image_compress_common_release",
          "version": {
            "requires": "0.12"
          }
        },
        {
          "group": "com.pichillilorenzo.flutter_inappwebview_android",
          "module": "flutter_inappwebview_android_release",
          "version": {
            "requires": "0.12"
          }
        },
        {
          "group": "com.dexterous.flutterlocalnotifications",
          "module": "flutter_local_notifications_release",
          "version": {
            "requires": "0.12"
          }
        },
        {
          "group": "ch.simonbraillard.flutter_new_badger",
          "module": "flutter_new_badger_release",
          "version": {
            "requires": "0.12"
          }
        },
        {
          "group": "com.example.flutter_platform_alert",
          "module": "flutter_platform_alert_release",
          "version": {
            "requires": "0.12"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_release",
          "version": {
            "requires": "0.12"
          }
        },
        {
          "group": "net.wolverinebeach.flutter_timezone",
          "module": "flutter_timezone_release",
          "version": {
            "requires": "0.12"
          }
        },
        {
          "group": "com.cloudwebrtc.webrtc",
          "module": "flutter_webrtc_release",
          "version": {
            "requires": "0.12"
          }
        },
        {
          "group": "com.example.FlutterToast",
          "module": "fluttertoast_release",
          "version": {
            "requires": "0.12"
          }
        },
        {
          "group": "io.flutter.plugins.googlesignin",
          "module": "google_sign_in_android_release",
          "version": {
            "requires": "0.12"
          }
        },
        {
          "group": "cachet.plugins.health",
          "module": "health_release",
          "version": {
            "requires": "0.12"
          }
        },
        {
          "group": "io.flutter.plugins.imagepicker",
          "module": "image_picker_android_release",
          "version": {
            "requires": "0.12"
          }
        },
        {
          "group": "io.flutter.plugins.inapppurchase",
          "module": "in_app_purchase_android_release",
          "version": {
            "requires": "0.12"
          }
        },
        {
          "group": "com.ryanheise.just_audio",
          "module": "just_audio_release",
          "version": {
            "requires": "0.12"
          }
        },
        {
          "group": "br.com.yanncabral.open_settings_plus",
          "module": "open_settings_plus_release",
          "version": {
            "requires": "0.12"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.packageinfo",
          "module": "package_info_plus_release",
          "version": {
            "requires": "0.12"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android_release",
          "version": {
            "requires": "0.12"
          }
        },
        {
          "group": "com.baseflow.permissionhandler",
          "module": "permission_handler_android_release",
          "version": {
            "requires": "0.12"
          }
        },
        {
          "group": "com.fluttercandies.photo_manager",
          "module": "photo_manager_release",
          "version": {
            "requires": "0.12"
          }
        },
        {
          "group": "id.nizwar.screen_capture_event",
          "module": "screen_capture_event_release",
          "version": {
            "requires": "0.12"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.sensors",
          "module": "sensors_plus_release",
          "version": {
            "requires": "0.12"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.share",
          "module": "share_plus_release",
          "version": {
            "requires": "0.12"
          }
        },
        {
          "group": "com.aboutyou.dart_packages.sign_in_with_apple",
          "module": "sign_in_with_apple_release",
          "version": {
            "requires": "0.12"
          }
        },
        {
          "group": "com.tekartik.sqflite",
          "module": "sqflite_android_release",
          "version": {
            "requires": "0.12"
          }
        },
        {
          "group": "eu.simonbinder.sqlite3_flutter_libs",
          "module": "sqlite3_flutter_libs_release",
          "version": {
            "requires": "0.12"
          }
        },
        {
          "group": "io.flutter.plugins.urllauncher",
          "module": "url_launcher_android_release",
          "version": {
            "requires": "0.12"
          }
        },
        {
          "group": "com.benjaminabel.vibration",
          "module": "vibration_release",
          "version": {
            "requires": "0.12"
          }
        },
        {
          "group": "io.flutter.plugins.videoplayer",
          "module": "video_player_android_release",
          "version": {
            "requires": "0.12"
          }
        },
        {
          "group": "com.example.yongxin_ring",
          "module": "yongxin_ring_release",
          "version": {
            "requires": "0.12"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-0.12.aar",
          "url": "flutter_release-0.12.aar",
          "size": 40598972,
          "sha512": "1c8c0b2057b8950d295aa9026dd67d616b1d47650256e40de2ec0cb2effd3cfbbe017a7fbfb1d49e40bb8e775b0877242488c3cdb2b832f7ea1151f365c8a8e5",
          "sha256": "07a18f6127bd8370cfde4d40f72d521cb58f2379317c7d2310136db77febf007",
          "sha1": "ef773f64896fd9dc81ff9fcd1b824185f3e30213",
          "md5": "b6f8dfec6dcdb042a69665eeb41b58d0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        },
        {
          "group": "com.ryanheise.audio_session",
          "module": "audio_session_release",
          "version": {
            "requires": "0.12"
          }
        },
        {
          "group": "io.flutter.plugins.camera",
          "module": "camera_android_release",
          "version": {
            "requires": "0.12"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.connectivity",
          "module": "connectivity_plus_release",
          "version": {
            "requires": "0.12"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.device_info",
          "module": "device_info_plus_release",
          "version": {
            "requires": "0.12"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.core",
          "module": "firebase_core_release",
          "version": {
            "requires": "0.12"
          }
        },
        {
          "group": "io.flutter.plugins.firebaseperformance",
          "module": "firebase_performance_release",
          "version": {
            "requires": "0.12"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.firebaseremoteconfig",
          "module": "firebase_remote_config_release",
          "version": {
            "requires": "0.12"
          }
        },
        {
          "group": "com.lib.flutter_blue_plus",
          "module": "flutter_blue_plus_android_release",
          "version": {
            "requires": "0.12"
          }
        },
        {
          "group": "com.crazecoder.flutterbugly",
          "module": "flutter_bugly_release",
          "version": {
            "requires": "0.12"
          }
        },
        {
          "group": "com.fluttercandies.flutter_image_compress",
          "module": "flutter_image_compress_common_release",
          "version": {
            "requires": "0.12"
          }
        },
        {
          "group": "com.pichillilorenzo.flutter_inappwebview_android",
          "module": "flutter_inappwebview_android_release",
          "version": {
            "requires": "0.12"
          }
        },
        {
          "group": "com.dexterous.flutterlocalnotifications",
          "module": "flutter_local_notifications_release",
          "version": {
            "requires": "0.12"
          }
        },
        {
          "group": "ch.simonbraillard.flutter_new_badger",
          "module": "flutter_new_badger_release",
          "version": {
            "requires": "0.12"
          }
        },
        {
          "group": "com.example.flutter_platform_alert",
          "module": "flutter_platform_alert_release",
          "version": {
            "requires": "0.12"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_release",
          "version": {
            "requires": "0.12"
          }
        },
        {
          "group": "net.wolverinebeach.flutter_timezone",
          "module": "flutter_timezone_release",
          "version": {
            "requires": "0.12"
          }
        },
        {
          "group": "com.cloudwebrtc.webrtc",
          "module": "flutter_webrtc_release",
          "version": {
            "requires": "0.12"
          }
        },
        {
          "group": "com.example.FlutterToast",
          "module": "fluttertoast_release",
          "version": {
            "requires": "0.12"
          }
        },
        {
          "group": "io.flutter.plugins.googlesignin",
          "module": "google_sign_in_android_release",
          "version": {
            "requires": "0.12"
          }
        },
        {
          "group": "cachet.plugins.health",
          "module": "health_release",
          "version": {
            "requires": "0.12"
          }
        },
        {
          "group": "io.flutter.plugins.imagepicker",
          "module": "image_picker_android_release",
          "version": {
            "requires": "0.12"
          }
        },
        {
          "group": "io.flutter.plugins.inapppurchase",
          "module": "in_app_purchase_android_release",
          "version": {
            "requires": "0.12"
          }
        },
        {
          "group": "com.ryanheise.just_audio",
          "module": "just_audio_release",
          "version": {
            "requires": "0.12"
          }
        },
        {
          "group": "br.com.yanncabral.open_settings_plus",
          "module": "open_settings_plus_release",
          "version": {
            "requires": "0.12"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.packageinfo",
          "module": "package_info_plus_release",
          "version": {
            "requires": "0.12"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android_release",
          "version": {
            "requires": "0.12"
          }
        },
        {
          "group": "com.baseflow.permissionhandler",
          "module": "permission_handler_android_release",
          "version": {
            "requires": "0.12"
          }
        },
        {
          "group": "com.fluttercandies.photo_manager",
          "module": "photo_manager_release",
          "version": {
            "requires": "0.12"
          }
        },
        {
          "group": "id.nizwar.screen_capture_event",
          "module": "screen_capture_event_release",
          "version": {
            "requires": "0.12"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.sensors",
          "module": "sensors_plus_release",
          "version": {
            "requires": "0.12"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.share",
          "module": "share_plus_release",
          "version": {
            "requires": "0.12"
          }
        },
        {
          "group": "com.aboutyou.dart_packages.sign_in_with_apple",
          "module": "sign_in_with_apple_release",
          "version": {
            "requires": "0.12"
          }
        },
        {
          "group": "com.tekartik.sqflite",
          "module": "sqflite_android_release",
          "version": {
            "requires": "0.12"
          }
        },
        {
          "group": "eu.simonbinder.sqlite3_flutter_libs",
          "module": "sqlite3_flutter_libs_release",
          "version": {
            "requires": "0.12"
          }
        },
        {
          "group": "io.flutter.plugins.urllauncher",
          "module": "url_launcher_android_release",
          "version": {
            "requires": "0.12"
          }
        },
        {
          "group": "com.benjaminabel.vibration",
          "module": "vibration_release",
          "version": {
            "requires": "0.12"
          }
        },
        {
          "group": "io.flutter.plugins.videoplayer",
          "module": "video_player_android_release",
          "version": {
            "requires": "0.12"
          }
        },
        {
          "group": "com.example.yongxin_ring",
          "module": "yongxin_ring_release",
          "version": {
            "requires": "0.12"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-0.12.aar",
          "url": "flutter_release-0.12.aar",
          "size": 40598972,
          "sha512": "1c8c0b2057b8950d295aa9026dd67d616b1d47650256e40de2ec0cb2effd3cfbbe017a7fbfb1d49e40bb8e775b0877242488c3cdb2b832f7ea1151f365c8a8e5",
          "sha256": "07a18f6127bd8370cfde4d40f72d521cb58f2379317c7d2310136db77febf007",
          "sha1": "ef773f64896fd9dc81ff9fcd1b824185f3e30213",
          "md5": "b6f8dfec6dcdb042a69665eeb41b58d0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_release-0.12-sources.jar",
          "url": "flutter_release-0.12-sources.jar",
          "size": 2265,
          "sha512": "2420ea7228ba2e4fd137819de7cb55e5efd63b84db5e0ceb692e9fdb379394e08c93e25c8927f2f9e42db9ed5e140e4d9484d0772c7be0c3d889b037360fd6bc",
          "sha256": "ba44e5371a94a630def3a2c9ac61ec587b904ec7c929524e51256bf36d064bbd",
          "sha1": "2ef94b45cf949604880bec58c420946ae7f8bc15",
          "md5": "5cba290cf5105f13a4b7092aa2b5f4a0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_release-0.12-javadoc.jar",
          "url": "flutter_release-0.12-javadoc.jar",
          "size": 261689,
          "sha512": "4f144d8399d9c526101ab52944e9d9ee04f7736bf78143bdfe3f3bb68308f96d274ff53651b9c37bf657815e46aaaf33cf2b73f98b2dd6ea12ca75bc9650c81c",
          "sha256": "354e1ea6cea1c36cea0f8516af15535b1591d026858f827b32d167c3b88d5f7b",
          "sha1": "4b749899f40aca30bf830c842ce669ade1f9983e",
          "md5": "d1b1bd17725668530e7365c4d444f916"
        }
      ]
    }
  ]
}
