{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.FlutterToast",
    "module": "fluttertoast_release",
    "version": "0.34",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        }
      ],
      "files": [
        {
          "name": "fluttertoast_release-0.34.aar",
          "url": "fluttertoast_release-0.34.aar",
          "size": 8609,
          "sha512": "da482f39ab1e5796b91a3fd52159cf88af8c596dead11d9f627ab528e3b969fd783252cd517323066454b20cbf187164d67f56c6aca6d7dacf98c31f0cfc7c65",
          "sha256": "2a172ed2dbf530740adef5164f9ab707995d4fbc84260936c7b96f9a1ceff08e",
          "sha1": "1b7903da53b0e7db7568cb398c9794f54de8a1da",
          "md5": "171298bcfb9e8479ceaf945d7af1c3d5"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "fluttertoast_release-0.34.aar",
          "url": "fluttertoast_release-0.34.aar",
          "size": 8609,
          "sha512": "da482f39ab1e5796b91a3fd52159cf88af8c596dead11d9f627ab528e3b969fd783252cd517323066454b20cbf187164d67f56c6aca6d7dacf98c31f0cfc7c65",
          "sha256": "2a172ed2dbf530740adef5164f9ab707995d4fbc84260936c7b96f9a1ceff08e",
          "sha1": "1b7903da53b0e7db7568cb398c9794f54de8a1da",
          "md5": "171298bcfb9e8479ceaf945d7af1c3d5"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fluttertoast_release-0.34-sources.jar",
          "url": "fluttertoast_release-0.34-sources.jar",
          "size": 3120,
          "sha512": "d9ebc2d9ee6ac43fe9b5cdc36686129ada7224df1bcc4f2f8f28ae624e9a6e94c44a493482daa6e1bf349432624693b6db5a3005ec9eec1715bbe170f4c4d7b6",
          "sha256": "69e1c82573001740c8ccb654af91736acda45261c9d0bcd2bd2ac8b6b62cdb24",
          "sha1": "9522dbaa5a7420975e525cac223d4b1717db7708",
          "md5": "7898eaf3504977619edc6f80d87654f9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fluttertoast_release-0.34-javadoc.jar",
          "url": "fluttertoast_release-0.34-javadoc.jar",
          "size": 262532,
          "sha512": "f9d33a54ee1a274e00eeccb02efedaf59f86375618e03efcf470af9ec06bca9414ba060d6f3494e6477b94c970f5d4240b65d58b095c1b618d771b9bb38ed999",
          "sha256": "c8d28fc13e6dd5a495e2b2a904ee304189253945c2b43749772bc48d65a251dd",
          "sha1": "f0f47c1af79bff14b8d17c547321d418bff831d1",
          "md5": "523f8647df6de9b9bd322df2147cd7b5"
        }
      ]
    }
  ]
}
