{
  "formatVersion": "1.1",
  "component": {
    "group": "com.omnihealth.flutter_ring_module",
    "module": "flutter_release",
    "version": "0.50",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        },
        {
          "group": "com.ryanheise.audio_session",
          "module": "audio_session_release",
          "version": {
            "requires": "0.50"
          }
        },
        {
          "group": "io.flutter.plugins.camerax",
          "module": "camera_android_camerax_release",
          "version": {
            "requires": "0.50"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.connectivity",
          "module": "connectivity_plus_release",
          "version": {
            "requires": "0.50"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.device_info",
          "module": "device_info_plus_release",
          "version": {
            "requires": "0.50"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.core",
          "module": "firebase_core_release",
          "version": {
            "requires": "0.50"
          }
        },
        {
          "group": "io.flutter.plugins.firebaseperformance",
          "module": "firebase_performance_release",
          "version": {
            "requires": "0.50"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.firebaseremoteconfig",
          "module": "firebase_remote_config_release",
          "version": {
            "requires": "0.50"
          }
        },
        {
          "group": "com.lib.flutter_blue_plus",
          "module": "flutter_blue_plus_android_release",
          "version": {
            "requires": "0.50"
          }
        },
        {
          "group": "com.crazecoder.flutterbugly",
          "module": "flutter_bugly_release",
          "version": {
            "requires": "0.50"
          }
        },
        {
          "group": "com.fluttercandies.flutter_image_compress",
          "module": "flutter_image_compress_common_release",
          "version": {
            "requires": "0.50"
          }
        },
        {
          "group": "com.pichillilorenzo.flutter_inappwebview_android",
          "module": "flutter_inappwebview_android_release",
          "version": {
            "requires": "0.50"
          }
        },
        {
          "group": "com.dexterous.flutterlocalnotifications",
          "module": "flutter_local_notifications_release",
          "version": {
            "requires": "0.50"
          }
        },
        {
          "group": "ch.simonbraillard.flutter_new_badger",
          "module": "flutter_new_badger_release",
          "version": {
            "requires": "0.50"
          }
        },
        {
          "group": "com.example.flutter_platform_alert",
          "module": "flutter_platform_alert_release",
          "version": {
            "requires": "0.50"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_release",
          "version": {
            "requires": "0.50"
          }
        },
        {
          "group": "net.wolverinebeach.flutter_timezone",
          "module": "flutter_timezone_release",
          "version": {
            "requires": "0.50"
          }
        },
        {
          "group": "com.cloudwebrtc.webrtc",
          "module": "flutter_webrtc_release",
          "version": {
            "requires": "0.50"
          }
        },
        {
          "group": "com.example.FlutterToast",
          "module": "fluttertoast_release",
          "version": {
            "requires": "0.50"
          }
        },
        {
          "group": "io.flutter.plugins.googlesignin",
          "module": "google_sign_in_android_release",
          "version": {
            "requires": "0.50"
          }
        },
        {
          "group": "cachet.plugins.health",
          "module": "health_release",
          "version": {
            "requires": "0.50"
          }
        },
        {
          "group": "io.flutter.plugins.imagepicker",
          "module": "image_picker_android_release",
          "version": {
            "requires": "0.50"
          }
        },
        {
          "group": "io.flutter.plugins.inapppurchase",
          "module": "in_app_purchase_android_release",
          "version": {
            "requires": "0.50"
          }
        },
        {
          "group": "com.github.dart_lang.jni",
          "module": "jni_release",
          "version": {
            "requires": "0.50"
          }
        },
        {
          "group": "com.github.dart_lang.jni_flutter",
          "module": "jni_flutter_release",
          "version": {
            "requires": "0.50"
          }
        },
        {
          "group": "com.ryanheise.just_audio",
          "module": "just_audio_release",
          "version": {
            "requires": "0.50"
          }
        },
        {
          "group": "dev.steenbakker.mobile_scanner",
          "module": "mobile_scanner_release",
          "version": {
            "requires": "0.50"
          }
        },
        {
          "group": "br.com.yanncabral.open_settings_plus",
          "module": "open_settings_plus_release",
          "version": {
            "requires": "0.50"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.packageinfo",
          "module": "package_info_plus_release",
          "version": {
            "requires": "0.50"
          }
        },
        {
          "group": "com.baseflow.permissionhandler",
          "module": "permission_handler_android_release",
          "version": {
            "requires": "0.50"
          }
        },
        {
          "group": "id.nizwar.screen_capture_event",
          "module": "screen_capture_event_release",
          "version": {
            "requires": "0.50"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.share",
          "module": "share_plus_release",
          "version": {
            "requires": "0.50"
          }
        },
        {
          "group": "com.aboutyou.dart_packages.sign_in_with_apple",
          "module": "sign_in_with_apple_release",
          "version": {
            "requires": "0.50"
          }
        },
        {
          "group": "com.tekartik.sqflite",
          "module": "sqflite_android_release",
          "version": {
            "requires": "0.50"
          }
        },
        {
          "group": "eu.simonbinder.sqlite3_flutter_libs",
          "module": "sqlite3_flutter_libs_release",
          "version": {
            "requires": "0.50"
          }
        },
        {
          "group": "com.umeng.umeng_common_sdk",
          "module": "umeng_common_sdk_release",
          "version": {
            "requires": "0.50"
          }
        },
        {
          "group": "io.flutter.plugins.urllauncher",
          "module": "url_launcher_android_release",
          "version": {
            "requires": "0.50"
          }
        },
        {
          "group": "com.benjaminabel.vibration",
          "module": "vibration_release",
          "version": {
            "requires": "0.50"
          }
        },
        {
          "group": "io.flutter.plugins.videoplayer",
          "module": "video_player_android_release",
          "version": {
            "requires": "0.50"
          }
        },
        {
          "group": "com.example.yongxin_ring",
          "module": "yongxin_ring_release",
          "version": {
            "requires": "0.50"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-0.50.aar",
          "url": "flutter_release-0.50.aar",
          "size": 89935013,
          "sha512": "c1cdf65242098013a8126e8c2f25a43a7870f713a5d063caca7f5141648c8f58ed42878597b1a87fbbf20cfd37d7940698b213a007a2a787117ee714c60866c9",
          "sha256": "1d1ec4525607a9f761a99986a65205074ae8c4cc0c99e0b86db06c4acec3faeb",
          "sha1": "5bd6db95a4357a5ae862248ffe1e18607145ac4d",
          "md5": "920929284495f39297936736bd471632"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        },
        {
          "group": "com.ryanheise.audio_session",
          "module": "audio_session_release",
          "version": {
            "requires": "0.50"
          }
        },
        {
          "group": "io.flutter.plugins.camerax",
          "module": "camera_android_camerax_release",
          "version": {
            "requires": "0.50"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.connectivity",
          "module": "connectivity_plus_release",
          "version": {
            "requires": "0.50"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.device_info",
          "module": "device_info_plus_release",
          "version": {
            "requires": "0.50"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.core",
          "module": "firebase_core_release",
          "version": {
            "requires": "0.50"
          }
        },
        {
          "group": "io.flutter.plugins.firebaseperformance",
          "module": "firebase_performance_release",
          "version": {
            "requires": "0.50"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.firebaseremoteconfig",
          "module": "firebase_remote_config_release",
          "version": {
            "requires": "0.50"
          }
        },
        {
          "group": "com.lib.flutter_blue_plus",
          "module": "flutter_blue_plus_android_release",
          "version": {
            "requires": "0.50"
          }
        },
        {
          "group": "com.crazecoder.flutterbugly",
          "module": "flutter_bugly_release",
          "version": {
            "requires": "0.50"
          }
        },
        {
          "group": "com.fluttercandies.flutter_image_compress",
          "module": "flutter_image_compress_common_release",
          "version": {
            "requires": "0.50"
          }
        },
        {
          "group": "com.pichillilorenzo.flutter_inappwebview_android",
          "module": "flutter_inappwebview_android_release",
          "version": {
            "requires": "0.50"
          }
        },
        {
          "group": "com.dexterous.flutterlocalnotifications",
          "module": "flutter_local_notifications_release",
          "version": {
            "requires": "0.50"
          }
        },
        {
          "group": "ch.simonbraillard.flutter_new_badger",
          "module": "flutter_new_badger_release",
          "version": {
            "requires": "0.50"
          }
        },
        {
          "group": "com.example.flutter_platform_alert",
          "module": "flutter_platform_alert_release",
          "version": {
            "requires": "0.50"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_release",
          "version": {
            "requires": "0.50"
          }
        },
        {
          "group": "net.wolverinebeach.flutter_timezone",
          "module": "flutter_timezone_release",
          "version": {
            "requires": "0.50"
          }
        },
        {
          "group": "com.cloudwebrtc.webrtc",
          "module": "flutter_webrtc_release",
          "version": {
            "requires": "0.50"
          }
        },
        {
          "group": "com.example.FlutterToast",
          "module": "fluttertoast_release",
          "version": {
            "requires": "0.50"
          }
        },
        {
          "group": "io.flutter.plugins.googlesignin",
          "module": "google_sign_in_android_release",
          "version": {
            "requires": "0.50"
          }
        },
        {
          "group": "cachet.plugins.health",
          "module": "health_release",
          "version": {
            "requires": "0.50"
          }
        },
        {
          "group": "io.flutter.plugins.imagepicker",
          "module": "image_picker_android_release",
          "version": {
            "requires": "0.50"
          }
        },
        {
          "group": "io.flutter.plugins.inapppurchase",
          "module": "in_app_purchase_android_release",
          "version": {
            "requires": "0.50"
          }
        },
        {
          "group": "com.github.dart_lang.jni",
          "module": "jni_release",
          "version": {
            "requires": "0.50"
          }
        },
        {
          "group": "com.github.dart_lang.jni_flutter",
          "module": "jni_flutter_release",
          "version": {
            "requires": "0.50"
          }
        },
        {
          "group": "com.ryanheise.just_audio",
          "module": "just_audio_release",
          "version": {
            "requires": "0.50"
          }
        },
        {
          "group": "dev.steenbakker.mobile_scanner",
          "module": "mobile_scanner_release",
          "version": {
            "requires": "0.50"
          }
        },
        {
          "group": "br.com.yanncabral.open_settings_plus",
          "module": "open_settings_plus_release",
          "version": {
            "requires": "0.50"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.packageinfo",
          "module": "package_info_plus_release",
          "version": {
            "requires": "0.50"
          }
        },
        {
          "group": "com.baseflow.permissionhandler",
          "module": "permission_handler_android_release",
          "version": {
            "requires": "0.50"
          }
        },
        {
          "group": "id.nizwar.screen_capture_event",
          "module": "screen_capture_event_release",
          "version": {
            "requires": "0.50"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.share",
          "module": "share_plus_release",
          "version": {
            "requires": "0.50"
          }
        },
        {
          "group": "com.aboutyou.dart_packages.sign_in_with_apple",
          "module": "sign_in_with_apple_release",
          "version": {
            "requires": "0.50"
          }
        },
        {
          "group": "com.tekartik.sqflite",
          "module": "sqflite_android_release",
          "version": {
            "requires": "0.50"
          }
        },
        {
          "group": "eu.simonbinder.sqlite3_flutter_libs",
          "module": "sqlite3_flutter_libs_release",
          "version": {
            "requires": "0.50"
          }
        },
        {
          "group": "com.umeng.umeng_common_sdk",
          "module": "umeng_common_sdk_release",
          "version": {
            "requires": "0.50"
          }
        },
        {
          "group": "io.flutter.plugins.urllauncher",
          "module": "url_launcher_android_release",
          "version": {
            "requires": "0.50"
          }
        },
        {
          "group": "com.benjaminabel.vibration",
          "module": "vibration_release",
          "version": {
            "requires": "0.50"
          }
        },
        {
          "group": "io.flutter.plugins.videoplayer",
          "module": "video_player_android_release",
          "version": {
            "requires": "0.50"
          }
        },
        {
          "group": "com.example.yongxin_ring",
          "module": "yongxin_ring_release",
          "version": {
            "requires": "0.50"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-0.50.aar",
          "url": "flutter_release-0.50.aar",
          "size": 89935013,
          "sha512": "c1cdf65242098013a8126e8c2f25a43a7870f713a5d063caca7f5141648c8f58ed42878597b1a87fbbf20cfd37d7940698b213a007a2a787117ee714c60866c9",
          "sha256": "1d1ec4525607a9f761a99986a65205074ae8c4cc0c99e0b86db06c4acec3faeb",
          "sha1": "5bd6db95a4357a5ae862248ffe1e18607145ac4d",
          "md5": "920929284495f39297936736bd471632"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_release-0.50-sources.jar",
          "url": "flutter_release-0.50-sources.jar",
          "size": 2306,
          "sha512": "b9fb22647958fe1f06eba817b52aaee596c7569a61a1e3a3ebe10351d3c5938c261ed99dcc9073e3b35ab1da084868bb961c6677f0febd5deb200d5b935be680",
          "sha256": "bc3c84289011ee1ff6771b3a05d1b773f701ee2c9b020c536ba10fd59f4e250e",
          "sha1": "bc1ff5507c7f4d03c599f96dcec0636d246c40b7",
          "md5": "9e5eb20ed5ef3a47fc8a4226f709002c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_release-0.50-javadoc.jar",
          "url": "flutter_release-0.50-javadoc.jar",
          "size": 261619,
          "sha512": "effaef62adacdc85531879d9885a1d0ecdecd60aa4496bc9719af222f1bbf7de20b46f94d2251fbf6e7c2fca0a5799b668c173aa06cec0bec09142f987c23aa4",
          "sha256": "d66c86c646e9606410037ec846b0a4311720c591e77398ab463933e521156857",
          "sha1": "a40df9a0bc4db56c05cfd7bde60963008ed8cf05",
          "md5": "a10a8cf9e0e7a0f409d1076a0f7caae5"
        }
      ]
    }
  ]
}
