{
  "formatVersion": "1.1",
  "component": {
    "group": "com.fluttercandies.photo_manager",
    "module": "photo_manager_debug",
    "version": "0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "photo_manager_debug-0.1.aar",
          "url": "photo_manager_debug-0.1.aar",
          "size": 195367,
          "sha512": "db1896c6520d8bdff1b29762d4be626b2922b1db7b0e0624c21b00306040f57300fed70fbc7475c1abf2e826cd883f3111c12eb56c08bd4a6c1a010d1fed8dff",
          "sha256": "8dcf07fb8270196d8e15cb28448b15db0b3a3ea055dfa14031f16e7502062b2f",
          "sha1": "dfdd3b3ded7d1d341c3607f218f8b80bab2319ec",
          "md5": "5f7875c8c79789c38ac591428074a0b5"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "glide",
          "version": {
            "requires": "4.15.1"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "photo_manager_debug-0.1.aar",
          "url": "photo_manager_debug-0.1.aar",
          "size": 195367,
          "sha512": "db1896c6520d8bdff1b29762d4be626b2922b1db7b0e0624c21b00306040f57300fed70fbc7475c1abf2e826cd883f3111c12eb56c08bd4a6c1a010d1fed8dff",
          "sha256": "8dcf07fb8270196d8e15cb28448b15db0b3a3ea055dfa14031f16e7502062b2f",
          "sha1": "dfdd3b3ded7d1d341c3607f218f8b80bab2319ec",
          "md5": "5f7875c8c79789c38ac591428074a0b5"
        }
      ]
    },
    {
      "name": "debugVariantDebugSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "photo_manager_debug-0.1-sources.jar",
          "url": "photo_manager_debug-0.1-sources.jar",
          "size": 48937,
          "sha512": "a6783be651555e3a89ea6f62b51e4d2d7324c3d4e98b1e7d42f15fac344506ef0691b3e6117abc7939197a529961e5cd51d07eeecfcfbe1ee971b9fc9ad82051",
          "sha256": "7a17149533e8f9b2a858cd11d946b55d5b84c0ebb9f73174ba0c24fb794182e6",
          "sha1": "3321fe6d23305392e3d2ce701bcdb1399e7e94f3",
          "md5": "2faea80851057d113d95cbe62ca59b57"
        }
      ]
    },
    {
      "name": "debugVariantDebugJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "photo_manager_debug-0.1-javadoc.jar",
          "url": "photo_manager_debug-0.1-javadoc.jar",
          "size": 515565,
          "sha512": "b63a9b5f45efde5d3eb0c435ca393231a54ff6adcae4bf07525b721a91411fdea1238d8e6410b1b4e1063ae6edcb646653b805709f0485e47e498bee7299aff8",
          "sha256": "e2266e2809b144ed698985b2bd909097a7c7b58b7194a0b1829d47b9c1c2d8c2",
          "sha1": "8c380a74e71cb224c62293f5b0988e464b780eb6",
          "md5": "0457fca582ad97660391ffb78304d255"
        }
      ]
    }
  ]
}
