{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.firebaseperformance",
    "module": "firebase_performance_release",
    "version": "0.64",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.core",
          "module": "firebase_core_release",
          "version": {
            "requires": "0.64"
          }
        }
      ],
      "files": [
        {
          "name": "firebase_performance_release-0.64.aar",
          "url": "firebase_performance_release-0.64.aar",
          "size": 8698,
          "sha512": "0e26e591695864c1be2ccd3f54c9d4ea079d92dcb3fa62797c1bc0365cf46f3ac04fd908164b57b4934c7c8ed01906d1752f74722e751a7338ac9e77cc9faca5",
          "sha256": "a4f00e555592fe39fccee1089bd8b85a4779f51bfa0132f2ac7792db8b6576a9",
          "sha1": "0eb8f7750cd97b193f1868798d071ab82870dcfc",
          "md5": "3319ae5cd2558367b6ac50ba26e0b971"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-bom",
          "version": {
            "requires": "33.1.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-perf"
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.core",
          "module": "firebase_core_release",
          "version": {
            "requires": "0.64"
          }
        }
      ],
      "files": [
        {
          "name": "firebase_performance_release-0.64.aar",
          "url": "firebase_performance_release-0.64.aar",
          "size": 8698,
          "sha512": "0e26e591695864c1be2ccd3f54c9d4ea079d92dcb3fa62797c1bc0365cf46f3ac04fd908164b57b4934c7c8ed01906d1752f74722e751a7338ac9e77cc9faca5",
          "sha256": "a4f00e555592fe39fccee1089bd8b85a4779f51bfa0132f2ac7792db8b6576a9",
          "sha1": "0eb8f7750cd97b193f1868798d071ab82870dcfc",
          "md5": "3319ae5cd2558367b6ac50ba26e0b971"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "firebase_performance_release-0.64-sources.jar",
          "url": "firebase_performance_release-0.64-sources.jar",
          "size": 4416,
          "sha512": "e05188ba1a224e845647dbd0e51cf2630683c31b7e009c7a2ad5bd7d1554d3c760af682404790b367a2ed5ab85c727c348c610a2364493c9b0dc756c27c56387",
          "sha256": "6a2e6a6b4cc443ba1b22a623738c62e95164ee6525e8595b00f02c2c046b25b3",
          "sha1": "6d0fe455ff284025536fd21e9adf9d5f356e703e",
          "md5": "a4f365cb56dd71144c7246719d32b4bb"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "firebase_performance_release-0.64-javadoc.jar",
          "url": "firebase_performance_release-0.64-javadoc.jar",
          "size": 273487,
          "sha512": "2bc94fbb912fda5b60b562b22411f7c496bc13b31f76f27a8939606d6dc5ca3069998c6549298e530bbf0a99fb176470a7fed9d52d29f52b288ad55e156095b3",
          "sha256": "7551f2de6ed51ca52e9b8526e9056746241d9c363c8953b1aceb38d789c2e169",
          "sha1": "6b23ecf17566e063b1330be2fd186bc814b5b926",
          "md5": "2b8ffd894e51f0cc20e2e365935d34eb"
        }
      ]
    }
  ]
}
