{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.fluttercommunity.plus.device_info",
    "module": "device_info_plus_release",
    "version": "0.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        }
      ],
      "files": [
        {
          "name": "device_info_plus_release-0.8.aar",
          "url": "device_info_plus_release-0.8.aar",
          "size": 7109,
          "sha512": "757a14ab8362f7987e14c8afd7b04a70d256dd593666d877534c3b6efeb31993b215dfe82a08cd61983d17b57d9c1ffa92323576f2dcd160d7335b78a24eb2f0",
          "sha256": "ff8388aff64d4687a3bf1689d49c0065f947b26f7a2e5d4b1c83967d6335e181",
          "sha1": "03ca761898c4604ffa530d46ee44640ce45db6cb",
          "md5": "ccc7e3014dff56b5744a7d3d47a93b4a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.22"
          }
        }
      ],
      "files": [
        {
          "name": "device_info_plus_release-0.8.aar",
          "url": "device_info_plus_release-0.8.aar",
          "size": 7109,
          "sha512": "757a14ab8362f7987e14c8afd7b04a70d256dd593666d877534c3b6efeb31993b215dfe82a08cd61983d17b57d9c1ffa92323576f2dcd160d7335b78a24eb2f0",
          "sha256": "ff8388aff64d4687a3bf1689d49c0065f947b26f7a2e5d4b1c83967d6335e181",
          "sha1": "03ca761898c4604ffa530d46ee44640ce45db6cb",
          "md5": "ccc7e3014dff56b5744a7d3d47a93b4a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "device_info_plus_release-0.8-sources.jar",
          "url": "device_info_plus_release-0.8-sources.jar",
          "size": 2976,
          "sha512": "b0a16c5d099d1a6d3f96d453ca4f34aa2b138d0729fd675fa4dadff9f54e169514b31bd5586b5d4fb388059df0d5e5ff8ceeeec9214322cced8b305c5d67afb3",
          "sha256": "1160189e3c750bbf50affba28a4dbf0fc1216e815a1f01a3d1d9dd17958f37ab",
          "sha1": "b1f985fbb38747f8f626c4988380b4847ff05db6",
          "md5": "7effa257187ed4394bf3919149a7d9e8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "device_info_plus_release-0.8-javadoc.jar",
          "url": "device_info_plus_release-0.8-javadoc.jar",
          "size": 260821,
          "sha512": "42bc32571af10b46a2d2c046f85894f73765ca0e5f0485ce063772a6cf89cc7c0819ae8763c5d2bccf07851a96030b8f419b1d22842ef893a4b280447df6361e",
          "sha256": "99babe14f9a55c096cfe949ee8f2672142a095b5fba790ea86279e08bef397be",
          "sha1": "80561d857b12aa438e5fa457e3be0f5c41cab53b",
          "md5": "4423cbb97382da9b587cfd0a80d1d85d"
        }
      ]
    }
  ]
}
