{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.pathprovider",
    "module": "path_provider_android_release",
    "version": "0.64",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        }
      ],
      "files": [
        {
          "name": "path_provider_android_release-0.64.aar",
          "url": "path_provider_android_release-0.64.aar",
          "size": 10356,
          "sha512": "09d9eb937d577f13d6fb5a865580d4f6e4491e3cca362798490951795e102a698f149c898d5788102889178eda3a13c185a2b717142fee6cb40b296dc6563c5e",
          "sha256": "f51ce58ad0cba4cbb6fd8c5fb039aee32834d849d0ad664c9ab28f658bfa6cfc",
          "sha1": "4f05777baff2a8fb53b5202ce374c4edac5714e4",
          "md5": "b1932ca773b7f149d6369aca9d914b55"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        }
      ],
      "files": [
        {
          "name": "path_provider_android_release-0.64.aar",
          "url": "path_provider_android_release-0.64.aar",
          "size": 10356,
          "sha512": "09d9eb937d577f13d6fb5a865580d4f6e4491e3cca362798490951795e102a698f149c898d5788102889178eda3a13c185a2b717142fee6cb40b296dc6563c5e",
          "sha256": "f51ce58ad0cba4cbb6fd8c5fb039aee32834d849d0ad664c9ab28f658bfa6cfc",
          "sha1": "4f05777baff2a8fb53b5202ce374c4edac5714e4",
          "md5": "b1932ca773b7f149d6369aca9d914b55"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "path_provider_android_release-0.64-sources.jar",
          "url": "path_provider_android_release-0.64-sources.jar",
          "size": 4126,
          "sha512": "fee43fea13d63cc4164f1b1fdc7370c288af088d1200faedd6f439ea2dd38471c4641e8c8897351481f62d6126f19bcb6989c381e44126270db0da6c64b969c6",
          "sha256": "24cad7628f81bb60fd6b9e657667917f55a5d2fa03613f4e6a103db317df7e8e",
          "sha1": "916237e58a6dce2bd1cf8cb404ea2fb6221a8cd1",
          "md5": "2dcb6dc53a694f6e8fa4ebf36877b4fe"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "path_provider_android_release-0.64-javadoc.jar",
          "url": "path_provider_android_release-0.64-javadoc.jar",
          "size": 294223,
          "sha512": "a7585063bb1b20114bcf08f71ba8996dbaa520ff88eaf213b312e5960417d2bfc851b86d1f0bc6d9903a81269d23160756493f33592b9fdd552f7e2283b9c1cc",
          "sha256": "5191bd62d394ded4f44c3f20681ed1d5b89bcf137824d75389e9061fa2460d9a",
          "sha1": "381d9adcd7d1c505a8f21a8ee23ec0c30c63b57d",
          "md5": "8f035ef93bb091ca35172c18e67dcaf6"
        }
      ]
    }
  ]
}
