{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.fluttercommunity.plus.device_info",
    "module": "device_info_plus_release",
    "version": "0.32",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        }
      ],
      "files": [
        {
          "name": "device_info_plus_release-0.32.aar",
          "url": "device_info_plus_release-0.32.aar",
          "size": 6945,
          "sha512": "8598418a70a204b4f6ec104ea541d3066f7713466160a125b82f913027bdd906eab816227a6416b4b76d1a2820915c3810d31921994b6549942f5fcd4d2fd946",
          "sha256": "2b71c14a493ed2d5dcdc0b03af3db168b8a31d5795dcab90a24d355c2d78dc42",
          "sha1": "6db7d849fe908ef67028705c65026bbc9623c8ef",
          "md5": "83f964088c0477c673f44f450ec1b13a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.22"
          }
        }
      ],
      "files": [
        {
          "name": "device_info_plus_release-0.32.aar",
          "url": "device_info_plus_release-0.32.aar",
          "size": 6945,
          "sha512": "8598418a70a204b4f6ec104ea541d3066f7713466160a125b82f913027bdd906eab816227a6416b4b76d1a2820915c3810d31921994b6549942f5fcd4d2fd946",
          "sha256": "2b71c14a493ed2d5dcdc0b03af3db168b8a31d5795dcab90a24d355c2d78dc42",
          "sha1": "6db7d849fe908ef67028705c65026bbc9623c8ef",
          "md5": "83f964088c0477c673f44f450ec1b13a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "device_info_plus_release-0.32-sources.jar",
          "url": "device_info_plus_release-0.32-sources.jar",
          "size": 2976,
          "sha512": "b0a16c5d099d1a6d3f96d453ca4f34aa2b138d0729fd675fa4dadff9f54e169514b31bd5586b5d4fb388059df0d5e5ff8ceeeec9214322cced8b305c5d67afb3",
          "sha256": "1160189e3c750bbf50affba28a4dbf0fc1216e815a1f01a3d1d9dd17958f37ab",
          "sha1": "b1f985fbb38747f8f626c4988380b4847ff05db6",
          "md5": "7effa257187ed4394bf3919149a7d9e8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "device_info_plus_release-0.32-javadoc.jar",
          "url": "device_info_plus_release-0.32-javadoc.jar",
          "size": 260892,
          "sha512": "82e31ce28e70ba9f85da5f3e125756e9b15fb5d63aa81a397f713603156208ebf8f71fae332643d659298603999a842087fec8cbc73c59b59a805df0dd71acb3",
          "sha256": "a1d4c5078486a87c57fe85e32fc5326d71ddf4819756a15e5b0e60b586701f23",
          "sha1": "0696a70c9887e3a1f0ce8b9ce4d705069b950ae7",
          "md5": "d677ddf673f5731745add7da0a0626ee"
        }
      ]
    }
  ]
}
