{
  "formatVersion": "1.1",
  "component": {
    "group": "com.fluttercandies.flutter_image_compress",
    "module": "flutter_image_compress_common_debug",
    "version": "0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_image_compress_common_debug-0.1.aar",
          "url": "flutter_image_compress_common_debug-0.1.aar",
          "size": 31521,
          "sha512": "2ef45b78f733ae6d5e4e15a584c43e4735a01120500687a691fe5bb15b75666f7e4b5f9fd3f0366c6bbe3f1431771f47734c267f5f95a6fc0e96a5f0bb25dd76",
          "sha256": "a4676487bc67ede7646c34d6ea5d27507de9009e7b93141961f557c65c2c1cc1",
          "sha1": "07348c875ec9855c2ee2e6b3c5427ad0c3e0cda2",
          "md5": "423d79178d11fe497a09c9efb20921f8"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "androidx.heifwriter",
          "module": "heifwriter",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_image_compress_common_debug-0.1.aar",
          "url": "flutter_image_compress_common_debug-0.1.aar",
          "size": 31521,
          "sha512": "2ef45b78f733ae6d5e4e15a584c43e4735a01120500687a691fe5bb15b75666f7e4b5f9fd3f0366c6bbe3f1431771f47734c267f5f95a6fc0e96a5f0bb25dd76",
          "sha256": "a4676487bc67ede7646c34d6ea5d27507de9009e7b93141961f557c65c2c1cc1",
          "sha1": "07348c875ec9855c2ee2e6b3c5427ad0c3e0cda2",
          "md5": "423d79178d11fe497a09c9efb20921f8"
        }
      ]
    },
    {
      "name": "debugVariantDebugSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_image_compress_common_debug-0.1-sources.jar",
          "url": "flutter_image_compress_common_debug-0.1-sources.jar",
          "size": 13283,
          "sha512": "9d463a80c9f9155d36af415dfbc87fadb7908f534f56929f46ded2280cbd3951f90518b08d83de17af9eab1bb66723f65b386d3d4df8b2a57dc67105fc8cad56",
          "sha256": "93a28e5f9b7fcb467c45057e584caa01f1eb412c0b4a92b23a49dc0100b4af37",
          "sha1": "8f0422fa7a12db6f03202df46f11b2c7ec84061a",
          "md5": "326cceeddeb7bc0e1af417bf6b15811f"
        }
      ]
    },
    {
      "name": "debugVariantDebugJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_image_compress_common_debug-0.1-javadoc.jar",
          "url": "flutter_image_compress_common_debug-0.1-javadoc.jar",
          "size": 351450,
          "sha512": "c5ece80a35a324fbbeb30cf99675ee488fcda6809e9f080419318d8382fd068da8c1cf0c61e30b898a22f9a03ba54b636c0aff5bb77b27b1efb2114c6ce2b781",
          "sha256": "e981dce82c1e76f2642d7385be6cfc84f3849b1002d7076b9ee30d93ee657250",
          "sha1": "f2bf1978aae0b3a22500afc8ed6a479751fa78b0",
          "md5": "44dd0c3e4e7c5d80dc12ee66f08f23b6"
        }
      ]
    }
  ]
}
