{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.yanncabral.open_settings_plus",
    "module": "open_settings_plus_release",
    "version": "0.61",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "open_settings_plus_release-0.61.aar",
          "url": "open_settings_plus_release-0.61.aar",
          "size": 4277,
          "sha512": "153f736838775d00ddfdeb99ccc51d0be0c628301db57ee959793a7e2172371ed96f74c74795536cc4eada24ff4fd870cf9b072ae1edf752034ff8769ca58a18",
          "sha256": "3475fdc44fda57e13c382f92951eb638ffd16636f8ca82dcc1492b710aaa779b",
          "sha1": "a418846586ab0922242faad725c1a695fd483ed3",
          "md5": "fb8cae4e667349289daa5692c5f1a85a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "open_settings_plus_release-0.61.aar",
          "url": "open_settings_plus_release-0.61.aar",
          "size": 4277,
          "sha512": "153f736838775d00ddfdeb99ccc51d0be0c628301db57ee959793a7e2172371ed96f74c74795536cc4eada24ff4fd870cf9b072ae1edf752034ff8769ca58a18",
          "sha256": "3475fdc44fda57e13c382f92951eb638ffd16636f8ca82dcc1492b710aaa779b",
          "sha1": "a418846586ab0922242faad725c1a695fd483ed3",
          "md5": "fb8cae4e667349289daa5692c5f1a85a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "open_settings_plus_release-0.61-sources.jar",
          "url": "open_settings_plus_release-0.61-sources.jar",
          "size": 2127,
          "sha512": "db9d4e79f86c4070737cc098075615485a061c944d20fcd7d7d465966e182776bb8d4494831e08961383872a015cd6164508393c29b8a6be7bfe91cecc9c379d",
          "sha256": "49bbb2bb5b27526e00b39edf6bc3b11dfca6582948d3a6498a6d55cd09f802ed",
          "sha1": "7130ee8ab68a8bc277889bc80d55cdfb048104db",
          "md5": "d4450a7b35aff0e068cd6532e4d6f219"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "open_settings_plus_release-0.61-javadoc.jar",
          "url": "open_settings_plus_release-0.61-javadoc.jar",
          "size": 261000,
          "sha512": "facd8e631d5960e6557222c66f38e281016f337fc0b8ae8244e8b740f4a8f872ff5cb069b8e144c89ac21695ab78b581557b6a1fff0e2d3229d7c0956789ab3a",
          "sha256": "24fd747108ef21f4cd300026f695b6179419d6a2635870aae6308b035c3feb5c",
          "sha1": "805235a0a4348213bf3ec01bb471a02935850578",
          "md5": "84f3ea5be3a1172ca52bf9f8bbac4350"
        }
      ]
    }
  ]
}
