{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.flutter_platform_alert",
    "module": "flutter_platform_alert_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_platform_alert_debug-1.0.aar",
          "url": "flutter_platform_alert_debug-1.0.aar",
          "size": 9630,
          "sha512": "64adbe2ce660bd371216e1e2d996514041bd96437c189d9b712fe124d1b90ca047ac20ea547cbb153b49265ef035a465c22a5a68c68c46503afe3f5bee90ddfe",
          "sha256": "e7ef823fb1fd467aa0559b58a4bdaaa362f539cef5b1eafdb8ae6bb4392f0f36",
          "sha1": "439426c4a796cd78aa7c798eb1dbbacc483927ff",
          "md5": "58130db01439f20f46b152b946d58b81"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.5.20"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_platform_alert_debug-1.0.aar",
          "url": "flutter_platform_alert_debug-1.0.aar",
          "size": 9630,
          "sha512": "64adbe2ce660bd371216e1e2d996514041bd96437c189d9b712fe124d1b90ca047ac20ea547cbb153b49265ef035a465c22a5a68c68c46503afe3f5bee90ddfe",
          "sha256": "e7ef823fb1fd467aa0559b58a4bdaaa362f539cef5b1eafdb8ae6bb4392f0f36",
          "sha1": "439426c4a796cd78aa7c798eb1dbbacc483927ff",
          "md5": "58130db01439f20f46b152b946d58b81"
        }
      ]
    },
    {
      "name": "debugVariantDebugSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_platform_alert_debug-1.0-sources.jar",
          "url": "flutter_platform_alert_debug-1.0-sources.jar",
          "size": 2419,
          "sha512": "0f2b22bac756a091326a6764355e2ee2c67d54d95ce2c038b9e91741917938070f40268ef2c8938684fb5110558c645f2617a325818b8f9f3fe7a70eec960812",
          "sha256": "0a5a52767371b2959d622148176f784c3054379097ee746859302933d68e85ad",
          "sha1": "5c714b72591bb9a3298241008d3df5fa6c53b609",
          "md5": "67fcd057752c94dc2ab62b41c059f6c0"
        }
      ]
    },
    {
      "name": "debugVariantDebugJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_platform_alert_debug-1.0-javadoc.jar",
          "url": "flutter_platform_alert_debug-1.0-javadoc.jar",
          "size": 262833,
          "sha512": "f21d7946aeef75b5df094ef9e6f3c4c8f7aebb696f3923c31408d425272f662142de5c7b5f77f9e9b3e6d86903a632204a12ec4591d88b875c4e56648c7e7b83",
          "sha256": "cee56bd65e7770368b783750ecce11136c3042d2e5e5ecda5f7110d2447d0540",
          "sha1": "065b0be342060ca9c3cc1ab0cec573cce60aae95",
          "md5": "f9f6b5f0ed0211a82d5ffde21e99348e"
        }
      ]
    }
  ]
}
