{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.yongxin_ring",
    "module": "yongxin_ring_release",
    "version": "0.63",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "yongxin_ring_release-0.63.aar",
          "url": "yongxin_ring_release-0.63.aar",
          "size": 167056,
          "sha512": "70f521c985489df4bec90021a3785c7c315f2579ac4de75f964ba820892165ff4fdb85c3563736e2ddb45ebee586e81c7be1ce7faa24aec0beb058185e2b6940",
          "sha256": "e314b936a8b7a8219b11fb3476da4be52c8fae52a4aa28d1988f212e08c360dc",
          "sha1": "2a57a4a994aedefc2dbdd62830b5df60c93dd0df",
          "md5": "8dc06d3e524ebbba33044cf4a23a5a01"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        },
        {
          "group": "com.lm",
          "module": "chipletRing",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.localbroadcastmanager",
          "module": "localbroadcastmanager",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.greenrobot",
          "module": "greendao",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "org.ligboy.retrofit2",
          "module": "converter-fastjson-android",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "24.0.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "com.zhy",
          "module": "okhttputils",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "com.tenmeter.smlibrary",
          "module": "tenmeter",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "yongxin_ring_release-0.63.aar",
          "url": "yongxin_ring_release-0.63.aar",
          "size": 167056,
          "sha512": "70f521c985489df4bec90021a3785c7c315f2579ac4de75f964ba820892165ff4fdb85c3563736e2ddb45ebee586e81c7be1ce7faa24aec0beb058185e2b6940",
          "sha256": "e314b936a8b7a8219b11fb3476da4be52c8fae52a4aa28d1988f212e08c360dc",
          "sha1": "2a57a4a994aedefc2dbdd62830b5df60c93dd0df",
          "md5": "8dc06d3e524ebbba33044cf4a23a5a01"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "yongxin_ring_release-0.63-sources.jar",
          "url": "yongxin_ring_release-0.63-sources.jar",
          "size": 49677,
          "sha512": "e415bc03c22cb385c3f58b95c59cb19a5dfe4d5fb36a557f3de42a0921509bef0c7add2fa65d56ff2687e20b3f5325afba3106a0a52699b61a202c558316022b",
          "sha256": "7fe508a08d9edd93627b86602de9923c4da74803e2c68885635a4e656e1639bc",
          "sha1": "ed0ac13bfc9a1b88fb19ac84dbeb775391e523b6",
          "md5": "be73b167658dc2a7bcff09c84ded27fc"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "yongxin_ring_release-0.63-javadoc.jar",
          "url": "yongxin_ring_release-0.63-javadoc.jar",
          "size": 301908,
          "sha512": "e6d3734b112eb758b93dc6e6f5b69b371a68811d1fc78de9cadf5c7c0c5a4e27136c685952732f83cbcfcbb7efc1b25406e6a4c9e30de7068ac1e201700fc1e3",
          "sha256": "c17d0be829352c641deaeaa900101e40808fa9fb91b57cad149ff38e96d58591",
          "sha1": "599c9a077c60703de7db52cd9327daf82bb4e96d",
          "md5": "cff93f457601a157d4dae7c783c8c442"
        }
      ]
    }
  ]
}
