{
  "formatVersion": "1.1",
  "component": {
    "group": "com.omnihealth.flutter_ring_module",
    "module": "flutter_release",
    "version": "0.51",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        },
        {
          "group": "com.ryanheise.audio_session",
          "module": "audio_session_release",
          "version": {
            "requires": "0.51"
          }
        },
        {
          "group": "io.flutter.plugins.camerax",
          "module": "camera_android_camerax_release",
          "version": {
            "requires": "0.51"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.connectivity",
          "module": "connectivity_plus_release",
          "version": {
            "requires": "0.51"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.device_info",
          "module": "device_info_plus_release",
          "version": {
            "requires": "0.51"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.core",
          "module": "firebase_core_release",
          "version": {
            "requires": "0.51"
          }
        },
        {
          "group": "io.flutter.plugins.firebaseperformance",
          "module": "firebase_performance_release",
          "version": {
            "requires": "0.51"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.firebaseremoteconfig",
          "module": "firebase_remote_config_release",
          "version": {
            "requires": "0.51"
          }
        },
        {
          "group": "com.lib.flutter_blue_plus",
          "module": "flutter_blue_plus_android_release",
          "version": {
            "requires": "0.51"
          }
        },
        {
          "group": "com.crazecoder.flutterbugly",
          "module": "flutter_bugly_release",
          "version": {
            "requires": "0.51"
          }
        },
        {
          "group": "com.fluttercandies.flutter_image_compress",
          "module": "flutter_image_compress_common_release",
          "version": {
            "requires": "0.51"
          }
        },
        {
          "group": "com.pichillilorenzo.flutter_inappwebview_android",
          "module": "flutter_inappwebview_android_release",
          "version": {
            "requires": "0.51"
          }
        },
        {
          "group": "com.dexterous.flutterlocalnotifications",
          "module": "flutter_local_notifications_release",
          "version": {
            "requires": "0.51"
          }
        },
        {
          "group": "ch.simonbraillard.flutter_new_badger",
          "module": "flutter_new_badger_release",
          "version": {
            "requires": "0.51"
          }
        },
        {
          "group": "com.example.flutter_platform_alert",
          "module": "flutter_platform_alert_release",
          "version": {
            "requires": "0.51"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_release",
          "version": {
            "requires": "0.51"
          }
        },
        {
          "group": "net.wolverinebeach.flutter_timezone",
          "module": "flutter_timezone_release",
          "version": {
            "requires": "0.51"
          }
        },
        {
          "group": "com.cloudwebrtc.webrtc",
          "module": "flutter_webrtc_release",
          "version": {
            "requires": "0.51"
          }
        },
        {
          "group": "com.example.FlutterToast",
          "module": "fluttertoast_release",
          "version": {
            "requires": "0.51"
          }
        },
        {
          "group": "io.flutter.plugins.googlesignin",
          "module": "google_sign_in_android_release",
          "version": {
            "requires": "0.51"
          }
        },
        {
          "group": "cachet.plugins.health",
          "module": "health_release",
          "version": {
            "requires": "0.51"
          }
        },
        {
          "group": "io.flutter.plugins.imagepicker",
          "module": "image_picker_android_release",
          "version": {
            "requires": "0.51"
          }
        },
        {
          "group": "io.flutter.plugins.inapppurchase",
          "module": "in_app_purchase_android_release",
          "version": {
            "requires": "0.51"
          }
        },
        {
          "group": "com.github.dart_lang.jni",
          "module": "jni_release",
          "version": {
            "requires": "0.51"
          }
        },
        {
          "group": "com.github.dart_lang.jni_flutter",
          "module": "jni_flutter_release",
          "version": {
            "requires": "0.51"
          }
        },
        {
          "group": "com.ryanheise.just_audio",
          "module": "just_audio_release",
          "version": {
            "requires": "0.51"
          }
        },
        {
          "group": "dev.steenbakker.mobile_scanner",
          "module": "mobile_scanner_release",
          "version": {
            "requires": "0.51"
          }
        },
        {
          "group": "br.com.yanncabral.open_settings_plus",
          "module": "open_settings_plus_release",
          "version": {
            "requires": "0.51"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.packageinfo",
          "module": "package_info_plus_release",
          "version": {
            "requires": "0.51"
          }
        },
        {
          "group": "com.baseflow.permissionhandler",
          "module": "permission_handler_android_release",
          "version": {
            "requires": "0.51"
          }
        },
        {
          "group": "id.nizwar.screen_capture_event",
          "module": "screen_capture_event_release",
          "version": {
            "requires": "0.51"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.share",
          "module": "share_plus_release",
          "version": {
            "requires": "0.51"
          }
        },
        {
          "group": "com.aboutyou.dart_packages.sign_in_with_apple",
          "module": "sign_in_with_apple_release",
          "version": {
            "requires": "0.51"
          }
        },
        {
          "group": "com.tekartik.sqflite",
          "module": "sqflite_android_release",
          "version": {
            "requires": "0.51"
          }
        },
        {
          "group": "eu.simonbinder.sqlite3_flutter_libs",
          "module": "sqlite3_flutter_libs_release",
          "version": {
            "requires": "0.51"
          }
        },
        {
          "group": "com.umeng.umeng_common_sdk",
          "module": "umeng_common_sdk_release",
          "version": {
            "requires": "0.51"
          }
        },
        {
          "group": "io.flutter.plugins.urllauncher",
          "module": "url_launcher_android_release",
          "version": {
            "requires": "0.51"
          }
        },
        {
          "group": "com.benjaminabel.vibration",
          "module": "vibration_release",
          "version": {
            "requires": "0.51"
          }
        },
        {
          "group": "io.flutter.plugins.videoplayer",
          "module": "video_player_android_release",
          "version": {
            "requires": "0.51"
          }
        },
        {
          "group": "com.example.yongxin_ring",
          "module": "yongxin_ring_release",
          "version": {
            "requires": "0.51"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-0.51.aar",
          "url": "flutter_release-0.51.aar",
          "size": 89929030,
          "sha512": "243d3434b17ffb4e4b0612512e7f8d136ea494cb18392ddff6a17d760f732e45579c5ce894057b67294c2f8c1642ffc4750f4bc9fcc374851222b165a5f0e915",
          "sha256": "e4ffffc34ba2affd4746973792a9a59162ead0c42a009ecd988ca4f8464877de",
          "sha1": "5790973823dc0924ca5b99407a23c007800d6dcb",
          "md5": "1b8d327a10fe3e77db3cbdaee37e60c0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        },
        {
          "group": "com.ryanheise.audio_session",
          "module": "audio_session_release",
          "version": {
            "requires": "0.51"
          }
        },
        {
          "group": "io.flutter.plugins.camerax",
          "module": "camera_android_camerax_release",
          "version": {
            "requires": "0.51"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.connectivity",
          "module": "connectivity_plus_release",
          "version": {
            "requires": "0.51"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.device_info",
          "module": "device_info_plus_release",
          "version": {
            "requires": "0.51"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.core",
          "module": "firebase_core_release",
          "version": {
            "requires": "0.51"
          }
        },
        {
          "group": "io.flutter.plugins.firebaseperformance",
          "module": "firebase_performance_release",
          "version": {
            "requires": "0.51"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.firebaseremoteconfig",
          "module": "firebase_remote_config_release",
          "version": {
            "requires": "0.51"
          }
        },
        {
          "group": "com.lib.flutter_blue_plus",
          "module": "flutter_blue_plus_android_release",
          "version": {
            "requires": "0.51"
          }
        },
        {
          "group": "com.crazecoder.flutterbugly",
          "module": "flutter_bugly_release",
          "version": {
            "requires": "0.51"
          }
        },
        {
          "group": "com.fluttercandies.flutter_image_compress",
          "module": "flutter_image_compress_common_release",
          "version": {
            "requires": "0.51"
          }
        },
        {
          "group": "com.pichillilorenzo.flutter_inappwebview_android",
          "module": "flutter_inappwebview_android_release",
          "version": {
            "requires": "0.51"
          }
        },
        {
          "group": "com.dexterous.flutterlocalnotifications",
          "module": "flutter_local_notifications_release",
          "version": {
            "requires": "0.51"
          }
        },
        {
          "group": "ch.simonbraillard.flutter_new_badger",
          "module": "flutter_new_badger_release",
          "version": {
            "requires": "0.51"
          }
        },
        {
          "group": "com.example.flutter_platform_alert",
          "module": "flutter_platform_alert_release",
          "version": {
            "requires": "0.51"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_release",
          "version": {
            "requires": "0.51"
          }
        },
        {
          "group": "net.wolverinebeach.flutter_timezone",
          "module": "flutter_timezone_release",
          "version": {
            "requires": "0.51"
          }
        },
        {
          "group": "com.cloudwebrtc.webrtc",
          "module": "flutter_webrtc_release",
          "version": {
            "requires": "0.51"
          }
        },
        {
          "group": "com.example.FlutterToast",
          "module": "fluttertoast_release",
          "version": {
            "requires": "0.51"
          }
        },
        {
          "group": "io.flutter.plugins.googlesignin",
          "module": "google_sign_in_android_release",
          "version": {
            "requires": "0.51"
          }
        },
        {
          "group": "cachet.plugins.health",
          "module": "health_release",
          "version": {
            "requires": "0.51"
          }
        },
        {
          "group": "io.flutter.plugins.imagepicker",
          "module": "image_picker_android_release",
          "version": {
            "requires": "0.51"
          }
        },
        {
          "group": "io.flutter.plugins.inapppurchase",
          "module": "in_app_purchase_android_release",
          "version": {
            "requires": "0.51"
          }
        },
        {
          "group": "com.github.dart_lang.jni",
          "module": "jni_release",
          "version": {
            "requires": "0.51"
          }
        },
        {
          "group": "com.github.dart_lang.jni_flutter",
          "module": "jni_flutter_release",
          "version": {
            "requires": "0.51"
          }
        },
        {
          "group": "com.ryanheise.just_audio",
          "module": "just_audio_release",
          "version": {
            "requires": "0.51"
          }
        },
        {
          "group": "dev.steenbakker.mobile_scanner",
          "module": "mobile_scanner_release",
          "version": {
            "requires": "0.51"
          }
        },
        {
          "group": "br.com.yanncabral.open_settings_plus",
          "module": "open_settings_plus_release",
          "version": {
            "requires": "0.51"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.packageinfo",
          "module": "package_info_plus_release",
          "version": {
            "requires": "0.51"
          }
        },
        {
          "group": "com.baseflow.permissionhandler",
          "module": "permission_handler_android_release",
          "version": {
            "requires": "0.51"
          }
        },
        {
          "group": "id.nizwar.screen_capture_event",
          "module": "screen_capture_event_release",
          "version": {
            "requires": "0.51"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.share",
          "module": "share_plus_release",
          "version": {
            "requires": "0.51"
          }
        },
        {
          "group": "com.aboutyou.dart_packages.sign_in_with_apple",
          "module": "sign_in_with_apple_release",
          "version": {
            "requires": "0.51"
          }
        },
        {
          "group": "com.tekartik.sqflite",
          "module": "sqflite_android_release",
          "version": {
            "requires": "0.51"
          }
        },
        {
          "group": "eu.simonbinder.sqlite3_flutter_libs",
          "module": "sqlite3_flutter_libs_release",
          "version": {
            "requires": "0.51"
          }
        },
        {
          "group": "com.umeng.umeng_common_sdk",
          "module": "umeng_common_sdk_release",
          "version": {
            "requires": "0.51"
          }
        },
        {
          "group": "io.flutter.plugins.urllauncher",
          "module": "url_launcher_android_release",
          "version": {
            "requires": "0.51"
          }
        },
        {
          "group": "com.benjaminabel.vibration",
          "module": "vibration_release",
          "version": {
            "requires": "0.51"
          }
        },
        {
          "group": "io.flutter.plugins.videoplayer",
          "module": "video_player_android_release",
          "version": {
            "requires": "0.51"
          }
        },
        {
          "group": "com.example.yongxin_ring",
          "module": "yongxin_ring_release",
          "version": {
            "requires": "0.51"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-0.51.aar",
          "url": "flutter_release-0.51.aar",
          "size": 89929030,
          "sha512": "243d3434b17ffb4e4b0612512e7f8d136ea494cb18392ddff6a17d760f732e45579c5ce894057b67294c2f8c1642ffc4750f4bc9fcc374851222b165a5f0e915",
          "sha256": "e4ffffc34ba2affd4746973792a9a59162ead0c42a009ecd988ca4f8464877de",
          "sha1": "5790973823dc0924ca5b99407a23c007800d6dcb",
          "md5": "1b8d327a10fe3e77db3cbdaee37e60c0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_release-0.51-sources.jar",
          "url": "flutter_release-0.51-sources.jar",
          "size": 2306,
          "sha512": "b9fb22647958fe1f06eba817b52aaee596c7569a61a1e3a3ebe10351d3c5938c261ed99dcc9073e3b35ab1da084868bb961c6677f0febd5deb200d5b935be680",
          "sha256": "bc3c84289011ee1ff6771b3a05d1b773f701ee2c9b020c536ba10fd59f4e250e",
          "sha1": "bc1ff5507c7f4d03c599f96dcec0636d246c40b7",
          "md5": "9e5eb20ed5ef3a47fc8a4226f709002c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_release-0.51-javadoc.jar",
          "url": "flutter_release-0.51-javadoc.jar",
          "size": 261619,
          "sha512": "d553f61dbae3131907b683cae7977d890c9df1571422d8e14d35b0ff3f9c78bcda0e302c5fd4cf362af3d2b8356fe06caa6da3e5ab6e3860246e7fd8d2b8a1ee",
          "sha256": "a3b40d8ac4f1508201cb9847389b943706bc0062020d81fc14f7f4ef8f1b3a92",
          "sha1": "965dd5946a702c6cee278b3679bfd550c3ed6b5b",
          "md5": "0d2e4bffae15a758767aaecb414cb48d"
        }
      ]
    }
  ]
}
