{
  "formatVersion": "1.1",
  "component": {
    "group": "com.fluttercandies.flutter_image_compress",
    "module": "flutter_image_compress_common_release",
    "version": "0.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_image_compress_common_release-0.13.aar",
          "url": "flutter_image_compress_common_release-0.13.aar",
          "size": 30363,
          "sha512": "de2975f069996d9d5816e6de1b3bf19eda41fab8c1f81380ebfa3d37f9d99eb834c3f50a7515748e578492052b289fd80a199f0296fefc155d775a8e5478163e",
          "sha256": "4a34affc052d7531e130b11e94d30f11d81ea9554f2bdbbd8d375c37b3618abb",
          "sha1": "d8e38d08f4b1ad0cb986160dadd168d65a80a883",
          "md5": "5bab0d97e10be665c9d6c16baeab3f65"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "androidx.heifwriter",
          "module": "heifwriter",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_image_compress_common_release-0.13.aar",
          "url": "flutter_image_compress_common_release-0.13.aar",
          "size": 30363,
          "sha512": "de2975f069996d9d5816e6de1b3bf19eda41fab8c1f81380ebfa3d37f9d99eb834c3f50a7515748e578492052b289fd80a199f0296fefc155d775a8e5478163e",
          "sha256": "4a34affc052d7531e130b11e94d30f11d81ea9554f2bdbbd8d375c37b3618abb",
          "sha1": "d8e38d08f4b1ad0cb986160dadd168d65a80a883",
          "md5": "5bab0d97e10be665c9d6c16baeab3f65"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_image_compress_common_release-0.13-sources.jar",
          "url": "flutter_image_compress_common_release-0.13-sources.jar",
          "size": 13283,
          "sha512": "9d463a80c9f9155d36af415dfbc87fadb7908f534f56929f46ded2280cbd3951f90518b08d83de17af9eab1bb66723f65b386d3d4df8b2a57dc67105fc8cad56",
          "sha256": "93a28e5f9b7fcb467c45057e584caa01f1eb412c0b4a92b23a49dc0100b4af37",
          "sha1": "8f0422fa7a12db6f03202df46f11b2c7ec84061a",
          "md5": "326cceeddeb7bc0e1af417bf6b15811f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_image_compress_common_release-0.13-javadoc.jar",
          "url": "flutter_image_compress_common_release-0.13-javadoc.jar",
          "size": 351973,
          "sha512": "3b3bc10d9c1a2d0cfe4304b0275733093469d3f6c8c17abb5558e22d2ddf30faf30bd76d8b0d3ac0f06c9ef316ae56b39c98d097064cb9f985f1278e1cc86cdb",
          "sha256": "bf72736935c71608b0a3a8eb9bff749c368e6afb17badd4e4b9bc8064237235c",
          "sha1": "c609b10fd7917d4ed78ada36626be5aaa6d49d4e",
          "md5": "aacc8a3391cf7c8f72354041ca27a1bf"
        }
      ]
    }
  ]
}
