{
  "formatVersion": "1.1",
  "component": {
    "group": "com.omnihealth.flutter_ring_module",
    "module": "flutter_release",
    "version": "0.58",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        },
        {
          "group": "com.ryanheise.audio_session",
          "module": "audio_session_release",
          "version": {
            "requires": "0.58"
          }
        },
        {
          "group": "io.flutter.plugins.camerax",
          "module": "camera_android_camerax_release",
          "version": {
            "requires": "0.58"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.connectivity",
          "module": "connectivity_plus_release",
          "version": {
            "requires": "0.58"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.device_info",
          "module": "device_info_plus_release",
          "version": {
            "requires": "0.58"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.core",
          "module": "firebase_core_release",
          "version": {
            "requires": "0.58"
          }
        },
        {
          "group": "io.flutter.plugins.firebaseperformance",
          "module": "firebase_performance_release",
          "version": {
            "requires": "0.58"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.firebaseremoteconfig",
          "module": "firebase_remote_config_release",
          "version": {
            "requires": "0.58"
          }
        },
        {
          "group": "com.lib.flutter_blue_plus",
          "module": "flutter_blue_plus_android_release",
          "version": {
            "requires": "0.58"
          }
        },
        {
          "group": "com.fluttercandies.flutter_image_compress",
          "module": "flutter_image_compress_common_release",
          "version": {
            "requires": "0.58"
          }
        },
        {
          "group": "com.pichillilorenzo.flutter_inappwebview_android",
          "module": "flutter_inappwebview_android_release",
          "version": {
            "requires": "0.58"
          }
        },
        {
          "group": "com.dexterous.flutterlocalnotifications",
          "module": "flutter_local_notifications_release",
          "version": {
            "requires": "0.58"
          }
        },
        {
          "group": "ch.simonbraillard.flutter_new_badger",
          "module": "flutter_new_badger_release",
          "version": {
            "requires": "0.58"
          }
        },
        {
          "group": "com.example.flutter_platform_alert",
          "module": "flutter_platform_alert_release",
          "version": {
            "requires": "0.58"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_release",
          "version": {
            "requires": "0.58"
          }
        },
        {
          "group": "net.wolverinebeach.flutter_timezone",
          "module": "flutter_timezone_release",
          "version": {
            "requires": "0.58"
          }
        },
        {
          "group": "com.cloudwebrtc.webrtc",
          "module": "flutter_webrtc_release",
          "version": {
            "requires": "0.58"
          }
        },
        {
          "group": "com.example.FlutterToast",
          "module": "fluttertoast_release",
          "version": {
            "requires": "0.58"
          }
        },
        {
          "group": "io.flutter.plugins.googlesignin",
          "module": "google_sign_in_android_release",
          "version": {
            "requires": "0.58"
          }
        },
        {
          "group": "cachet.plugins.health",
          "module": "health_release",
          "version": {
            "requires": "0.58"
          }
        },
        {
          "group": "io.flutter.plugins.imagepicker",
          "module": "image_picker_android_release",
          "version": {
            "requires": "0.58"
          }
        },
        {
          "group": "io.flutter.plugins.inapppurchase",
          "module": "in_app_purchase_android_release",
          "version": {
            "requires": "0.58"
          }
        },
        {
          "group": "com.github.dart_lang.jni",
          "module": "jni_release",
          "version": {
            "requires": "0.58"
          }
        },
        {
          "group": "com.github.dart_lang.jni_flutter",
          "module": "jni_flutter_release",
          "version": {
            "requires": "0.58"
          }
        },
        {
          "group": "com.ryanheise.just_audio",
          "module": "just_audio_release",
          "version": {
            "requires": "0.58"
          }
        },
        {
          "group": "dev.steenbakker.mobile_scanner",
          "module": "mobile_scanner_release",
          "version": {
            "requires": "0.58"
          }
        },
        {
          "group": "br.com.yanncabral.open_settings_plus",
          "module": "open_settings_plus_release",
          "version": {
            "requires": "0.58"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.packageinfo",
          "module": "package_info_plus_release",
          "version": {
            "requires": "0.58"
          }
        },
        {
          "group": "com.baseflow.permissionhandler",
          "module": "permission_handler_android_release",
          "version": {
            "requires": "0.58"
          }
        },
        {
          "group": "id.nizwar.screen_capture_event",
          "module": "screen_capture_event_release",
          "version": {
            "requires": "0.58"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.share",
          "module": "share_plus_release",
          "version": {
            "requires": "0.58"
          }
        },
        {
          "group": "com.aboutyou.dart_packages.sign_in_with_apple",
          "module": "sign_in_with_apple_release",
          "version": {
            "requires": "0.58"
          }
        },
        {
          "group": "com.tekartik.sqflite",
          "module": "sqflite_android_release",
          "version": {
            "requires": "0.58"
          }
        },
        {
          "group": "eu.simonbinder.sqlite3_flutter_libs",
          "module": "sqlite3_flutter_libs_release",
          "version": {
            "requires": "0.58"
          }
        },
        {
          "group": "com.umeng.umeng_common_sdk",
          "module": "umeng_common_sdk_release",
          "version": {
            "requires": "0.58"
          }
        },
        {
          "group": "io.flutter.plugins.urllauncher",
          "module": "url_launcher_android_release",
          "version": {
            "requires": "0.58"
          }
        },
        {
          "group": "com.benjaminabel.vibration",
          "module": "vibration_release",
          "version": {
            "requires": "0.58"
          }
        },
        {
          "group": "io.flutter.plugins.videoplayer",
          "module": "video_player_android_release",
          "version": {
            "requires": "0.58"
          }
        },
        {
          "group": "com.example.yongxin_ring",
          "module": "yongxin_ring_release",
          "version": {
            "requires": "0.58"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-0.58.aar",
          "url": "flutter_release-0.58.aar",
          "size": 90967237,
          "sha512": "a02214f1fa396a84b164524d9f103c371fa715989a64d9ee351e34b963686ecdd3c46657ded04bf1fda44e31fe2850bc9dd4ad3e7c7177c8d3da68116c05b89a",
          "sha256": "ffbf3e988ab5f057caa8249a0e651f121d77ba2e8aa9ed7454d5d7188141b8c9",
          "sha1": "c0acea9dd5083922d62ce498ad150307a4b70fbb",
          "md5": "a559bd59a3d29da539f94afeb43a1d9d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        },
        {
          "group": "com.ryanheise.audio_session",
          "module": "audio_session_release",
          "version": {
            "requires": "0.58"
          }
        },
        {
          "group": "io.flutter.plugins.camerax",
          "module": "camera_android_camerax_release",
          "version": {
            "requires": "0.58"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.connectivity",
          "module": "connectivity_plus_release",
          "version": {
            "requires": "0.58"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.device_info",
          "module": "device_info_plus_release",
          "version": {
            "requires": "0.58"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.core",
          "module": "firebase_core_release",
          "version": {
            "requires": "0.58"
          }
        },
        {
          "group": "io.flutter.plugins.firebaseperformance",
          "module": "firebase_performance_release",
          "version": {
            "requires": "0.58"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.firebaseremoteconfig",
          "module": "firebase_remote_config_release",
          "version": {
            "requires": "0.58"
          }
        },
        {
          "group": "com.lib.flutter_blue_plus",
          "module": "flutter_blue_plus_android_release",
          "version": {
            "requires": "0.58"
          }
        },
        {
          "group": "com.fluttercandies.flutter_image_compress",
          "module": "flutter_image_compress_common_release",
          "version": {
            "requires": "0.58"
          }
        },
        {
          "group": "com.pichillilorenzo.flutter_inappwebview_android",
          "module": "flutter_inappwebview_android_release",
          "version": {
            "requires": "0.58"
          }
        },
        {
          "group": "com.dexterous.flutterlocalnotifications",
          "module": "flutter_local_notifications_release",
          "version": {
            "requires": "0.58"
          }
        },
        {
          "group": "ch.simonbraillard.flutter_new_badger",
          "module": "flutter_new_badger_release",
          "version": {
            "requires": "0.58"
          }
        },
        {
          "group": "com.example.flutter_platform_alert",
          "module": "flutter_platform_alert_release",
          "version": {
            "requires": "0.58"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_release",
          "version": {
            "requires": "0.58"
          }
        },
        {
          "group": "net.wolverinebeach.flutter_timezone",
          "module": "flutter_timezone_release",
          "version": {
            "requires": "0.58"
          }
        },
        {
          "group": "com.cloudwebrtc.webrtc",
          "module": "flutter_webrtc_release",
          "version": {
            "requires": "0.58"
          }
        },
        {
          "group": "com.example.FlutterToast",
          "module": "fluttertoast_release",
          "version": {
            "requires": "0.58"
          }
        },
        {
          "group": "io.flutter.plugins.googlesignin",
          "module": "google_sign_in_android_release",
          "version": {
            "requires": "0.58"
          }
        },
        {
          "group": "cachet.plugins.health",
          "module": "health_release",
          "version": {
            "requires": "0.58"
          }
        },
        {
          "group": "io.flutter.plugins.imagepicker",
          "module": "image_picker_android_release",
          "version": {
            "requires": "0.58"
          }
        },
        {
          "group": "io.flutter.plugins.inapppurchase",
          "module": "in_app_purchase_android_release",
          "version": {
            "requires": "0.58"
          }
        },
        {
          "group": "com.github.dart_lang.jni",
          "module": "jni_release",
          "version": {
            "requires": "0.58"
          }
        },
        {
          "group": "com.github.dart_lang.jni_flutter",
          "module": "jni_flutter_release",
          "version": {
            "requires": "0.58"
          }
        },
        {
          "group": "com.ryanheise.just_audio",
          "module": "just_audio_release",
          "version": {
            "requires": "0.58"
          }
        },
        {
          "group": "dev.steenbakker.mobile_scanner",
          "module": "mobile_scanner_release",
          "version": {
            "requires": "0.58"
          }
        },
        {
          "group": "br.com.yanncabral.open_settings_plus",
          "module": "open_settings_plus_release",
          "version": {
            "requires": "0.58"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.packageinfo",
          "module": "package_info_plus_release",
          "version": {
            "requires": "0.58"
          }
        },
        {
          "group": "com.baseflow.permissionhandler",
          "module": "permission_handler_android_release",
          "version": {
            "requires": "0.58"
          }
        },
        {
          "group": "id.nizwar.screen_capture_event",
          "module": "screen_capture_event_release",
          "version": {
            "requires": "0.58"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.share",
          "module": "share_plus_release",
          "version": {
            "requires": "0.58"
          }
        },
        {
          "group": "com.aboutyou.dart_packages.sign_in_with_apple",
          "module": "sign_in_with_apple_release",
          "version": {
            "requires": "0.58"
          }
        },
        {
          "group": "com.tekartik.sqflite",
          "module": "sqflite_android_release",
          "version": {
            "requires": "0.58"
          }
        },
        {
          "group": "eu.simonbinder.sqlite3_flutter_libs",
          "module": "sqlite3_flutter_libs_release",
          "version": {
            "requires": "0.58"
          }
        },
        {
          "group": "com.umeng.umeng_common_sdk",
          "module": "umeng_common_sdk_release",
          "version": {
            "requires": "0.58"
          }
        },
        {
          "group": "io.flutter.plugins.urllauncher",
          "module": "url_launcher_android_release",
          "version": {
            "requires": "0.58"
          }
        },
        {
          "group": "com.benjaminabel.vibration",
          "module": "vibration_release",
          "version": {
            "requires": "0.58"
          }
        },
        {
          "group": "io.flutter.plugins.videoplayer",
          "module": "video_player_android_release",
          "version": {
            "requires": "0.58"
          }
        },
        {
          "group": "com.example.yongxin_ring",
          "module": "yongxin_ring_release",
          "version": {
            "requires": "0.58"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-0.58.aar",
          "url": "flutter_release-0.58.aar",
          "size": 90967237,
          "sha512": "a02214f1fa396a84b164524d9f103c371fa715989a64d9ee351e34b963686ecdd3c46657ded04bf1fda44e31fe2850bc9dd4ad3e7c7177c8d3da68116c05b89a",
          "sha256": "ffbf3e988ab5f057caa8249a0e651f121d77ba2e8aa9ed7454d5d7188141b8c9",
          "sha1": "c0acea9dd5083922d62ce498ad150307a4b70fbb",
          "md5": "a559bd59a3d29da539f94afeb43a1d9d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_release-0.58-sources.jar",
          "url": "flutter_release-0.58-sources.jar",
          "size": 2282,
          "sha512": "d04131485b4867d395920b04c3af6eb853d7267784aea68e4a75edb6ae266960bc50abef74616c9f9dad6dbe7076e065c842340eeaba409d3bb0b8298ea7f966",
          "sha256": "0514f50a49685e256040c5c9519b83373c3a42404f3bbebd5fe453078d31d89e",
          "sha1": "6bfd4de7895dd0fa160df1681b13d1f0b703ad41",
          "md5": "6351fd52e1a7688cfea1300d077fd91c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_release-0.58-javadoc.jar",
          "url": "flutter_release-0.58-javadoc.jar",
          "size": 261619,
          "sha512": "9a78d13c03986aa81a17f04c6b983bbb58aca64beaa37dadd3a7eeaea1262a94330e9c95dd4b9d3457d4806db4b5670495ae595ac608f757f47b3a37c713c387",
          "sha256": "5fcdb8c1f36bb1a42ff139b53855ac20b1df998773276fb3fb4076da865259e9",
          "sha1": "9eb1355de26ab0329b566c30648f8748cfc8375b",
          "md5": "60f3abccaad7534304f99763b77b7d58"
        }
      ]
    }
  ]
}
