{
  "formatVersion": "1.1",
  "component": {
    "group": "ch.simonbraillard.flutter_new_badger",
    "module": "flutter_new_badger_release",
    "version": "0.15",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_new_badger_release-0.15.aar",
          "url": "flutter_new_badger_release-0.15.aar",
          "size": 4061,
          "sha512": "7024e7bdd2665a86d9d3e67191e785afdaf6a03b238158d6fdbb36188209e9e51353e9e0294014ed99ddea06628215917f3a82af7763592661318cfde22c97c9",
          "sha256": "5f09844ee38b839a48b1fc6de6ea862dd7063e67ed956336262f8afeb48604bb",
          "sha1": "46246764ea503e2f94f970bf9531af946255f74d",
          "md5": "df8191d16185d3a1bab0d7ef51a8c251"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        },
        {
          "group": "me.leolin",
          "module": "ShortcutBadger",
          "version": {
            "requires": "1.1.22"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "ShortcutBadger",
              "type": "aar",
              "extension": "aar"
            }
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_new_badger_release-0.15.aar",
          "url": "flutter_new_badger_release-0.15.aar",
          "size": 4061,
          "sha512": "7024e7bdd2665a86d9d3e67191e785afdaf6a03b238158d6fdbb36188209e9e51353e9e0294014ed99ddea06628215917f3a82af7763592661318cfde22c97c9",
          "sha256": "5f09844ee38b839a48b1fc6de6ea862dd7063e67ed956336262f8afeb48604bb",
          "sha1": "46246764ea503e2f94f970bf9531af946255f74d",
          "md5": "df8191d16185d3a1bab0d7ef51a8c251"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_new_badger_release-0.15-sources.jar",
          "url": "flutter_new_badger_release-0.15-sources.jar",
          "size": 1776,
          "sha512": "c3d1ee04902cd70b0d5dad70cf8a33d467503a4187a2533a44f393362c35ed7346ace3326668222d4dffd17d1172b1df25dadad9ce27d30ace3e5c9c02c9c648",
          "sha256": "a29d615e4a0c05e28a1a76b0cd89cfc61b4f6648092aa31666d2c30e86c13a41",
          "sha1": "00948fe19d0d77a813d3083387c846f71a2237f1",
          "md5": "66078d106b1cb86ef6e66ffaa3a37a47"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_new_badger_release-0.15-javadoc.jar",
          "url": "flutter_new_badger_release-0.15-javadoc.jar",
          "size": 262521,
          "sha512": "885857d9b5f8fe9101b58ba2e43d612da8228b6a45267287c6c496aaca166d9f7b91139d72229c3fb9ee72ae1290111c5567ca4bcaf5374ed132e6c0df574e5b",
          "sha256": "77207310c79b01f1fc2743057082a1841ffedf1acabbacb60c21ef4a56428226",
          "sha1": "2fda9ce711636fa9edd736bf5784ae1fee7178f2",
          "md5": "79984db083d4f345acc9ce36573e38ba"
        }
      ]
    }
  ]
}
