{
  "formatVersion": "1.1",
  "component": {
    "group": "com.baseflow.permissionhandler",
    "module": "permission_handler_android_release",
    "version": "0.24",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        }
      ],
      "files": [
        {
          "name": "permission_handler_android_release-0.24.aar",
          "url": "permission_handler_android_release-0.24.aar",
          "size": 26574,
          "sha512": "7797947e8f92e95e7520a0f262758f78113da4ff3ca5eb52a29efff0b8fd27c187b7189dc6c911c8e3d8b6577d4d5719b45593bee628e6f9af4413334058a9ee",
          "sha256": "93b573335b77eacffc289f0b6e6954bdc5dda63932f6fa415272d80e3927063c",
          "sha1": "468f33ea2536ac122173cdd5cdc8ab5c3a21ec39",
          "md5": "608bf4bd03ac8f29e3f2affcc135eb51"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        }
      ],
      "files": [
        {
          "name": "permission_handler_android_release-0.24.aar",
          "url": "permission_handler_android_release-0.24.aar",
          "size": 26574,
          "sha512": "7797947e8f92e95e7520a0f262758f78113da4ff3ca5eb52a29efff0b8fd27c187b7189dc6c911c8e3d8b6577d4d5719b45593bee628e6f9af4413334058a9ee",
          "sha256": "93b573335b77eacffc289f0b6e6954bdc5dda63932f6fa415272d80e3927063c",
          "sha1": "468f33ea2536ac122173cdd5cdc8ab5c3a21ec39",
          "md5": "608bf4bd03ac8f29e3f2affcc135eb51"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "permission_handler_android_release-0.24-sources.jar",
          "url": "permission_handler_android_release-0.24-sources.jar",
          "size": 18177,
          "sha512": "673bc0d22579ac8c7f7a50b04d3f47d4cdb85dbc8aa15bfcb371b64223d3ee8f535385b2e67dfa1230c825ecddb11e45e1a0b74410e608691074c11623d4f06e",
          "sha256": "3301b75b44b9f004580d559b28ab51dd9205289cc88ccc668ce8179f5bf24c67",
          "sha1": "7a9e4cb073bdd84100ad45b7d2c21b036815543f",
          "md5": "6347cb73f0ecc4fc5e825d6de82fca4e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "permission_handler_android_release-0.24-javadoc.jar",
          "url": "permission_handler_android_release-0.24-javadoc.jar",
          "size": 264649,
          "sha512": "9cd1812a0fab605ddb35b2f68cefd7da93ee8519a6824a9397c458389f2c14412e5a423571078e3ed2b49ef46b84e7b043d9412e89d066143ad5baa22442ef1c",
          "sha256": "1592d202e1922299c5ed1622cc54706b8652a9d39340752de007183b1d7d6afc",
          "sha1": "037c401c86f2b425ce4907c10111c407e48d6a89",
          "md5": "85313d83f8f7d2249f1db74c76842414"
        }
      ]
    }
  ]
}
