{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.yongxin_ring",
    "module": "yongxin_ring_release",
    "version": "0.39",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "yongxin_ring_release-0.39.aar",
          "url": "yongxin_ring_release-0.39.aar",
          "size": 55008,
          "sha512": "d3379f7c0ede311ffe8c5309854fe10d8e9903042df9b73d7361898a6c0329558f7eedd9b66230e770ef58a9e780b63affe6217134e477da29b35a6126ed091c",
          "sha256": "c11bfa109544f6442d048a1e173d2fc82644b02cbea6152f83601ca3d4c79a45",
          "sha1": "ac06e9bf01962b090924ae6f79907e0f7407ea0d",
          "md5": "d3a460e98d510fdd714984b4f14816b3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        },
        {
          "group": "com.lm",
          "module": "chipletRing",
          "version": {
            "requires": "1.1.14"
          }
        },
        {
          "group": "androidx.localbroadcastmanager",
          "module": "localbroadcastmanager",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.greenrobot",
          "module": "greendao",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "org.ligboy.retrofit2",
          "module": "converter-fastjson-android",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "24.0.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "com.zhy",
          "module": "okhttputils",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "com.tenmeter.smlibrary",
          "module": "tenmeter",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "yongxin_ring_release-0.39.aar",
          "url": "yongxin_ring_release-0.39.aar",
          "size": 55008,
          "sha512": "d3379f7c0ede311ffe8c5309854fe10d8e9903042df9b73d7361898a6c0329558f7eedd9b66230e770ef58a9e780b63affe6217134e477da29b35a6126ed091c",
          "sha256": "c11bfa109544f6442d048a1e173d2fc82644b02cbea6152f83601ca3d4c79a45",
          "sha1": "ac06e9bf01962b090924ae6f79907e0f7407ea0d",
          "md5": "d3a460e98d510fdd714984b4f14816b3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "yongxin_ring_release-0.39-sources.jar",
          "url": "yongxin_ring_release-0.39-sources.jar",
          "size": 15952,
          "sha512": "111b0d3326a094f8450c32869eaa17464329c84765fd5b12350fe07bad0045c57ed73a71d24b9302eda390af3d308d36eb6c76a761948b4e3206dfa4ecbb1290",
          "sha256": "895677424e2363f5e6d6c2ebaade1b192b4f1a2b9c4b004466db4d781774cecf",
          "sha1": "23dedf962c1a24b261d39cdc2c75909ad6ac911e",
          "md5": "903721ca856d530a7a1068e4aa4f1ad8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "yongxin_ring_release-0.39-javadoc.jar",
          "url": "yongxin_ring_release-0.39-javadoc.jar",
          "size": 301409,
          "sha512": "aed91e5aca6a91a9db3dfc2e3d2d7d90f6cde3eba52be90ee8c89d2303d04c10243cda578bf7798413b99f46ea57de264b4eadfd85fc06bab9191e39ec3843de",
          "sha256": "0dfd40a92da015bfb02688cc7f863ba8ea70466beb38dffeaaf219052abb248c",
          "sha1": "847c149de4e3343385e9ab9822b3baed165b940f",
          "md5": "32b153ab0279820a8fc539773c3d471b"
        }
      ]
    }
  ]
}
