{
  "formatVersion": "1.1",
  "component": {
    "group": "com.ryanheise.just_audio",
    "module": "just_audio_release",
    "version": "0.56",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        }
      ],
      "files": [
        {
          "name": "just_audio_release-0.56.aar",
          "url": "just_audio_release-0.56.aar",
          "size": 28482,
          "sha512": "43fb036df9eee45abee15a17f29c276eb82b6a273fd1363effb176f8b15e69e199d35ab6cbfef537d1e439db339cf51cf4ecced1437f6485917397d4a49c0892",
          "sha256": "32f70ebafd4441da3dc884ae41d574fff07249ab0cd28465245ba258a5cf61c2",
          "sha1": "d821f699bf6597f5612ec38a7cb376d7257fa62d",
          "md5": "01f45aa6819d4393b8c0c1597e834fc8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-dash",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-hls",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-smoothstreaming",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "com.ryanheise.audio_session",
          "module": "audio_session_release",
          "version": {
            "requires": "0.56"
          }
        }
      ],
      "files": [
        {
          "name": "just_audio_release-0.56.aar",
          "url": "just_audio_release-0.56.aar",
          "size": 28482,
          "sha512": "43fb036df9eee45abee15a17f29c276eb82b6a273fd1363effb176f8b15e69e199d35ab6cbfef537d1e439db339cf51cf4ecced1437f6485917397d4a49c0892",
          "sha256": "32f70ebafd4441da3dc884ae41d574fff07249ab0cd28465245ba258a5cf61c2",
          "sha1": "d821f699bf6597f5612ec38a7cb376d7257fa62d",
          "md5": "01f45aa6819d4393b8c0c1597e834fc8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "just_audio_release-0.56-sources.jar",
          "url": "just_audio_release-0.56-sources.jar",
          "size": 12367,
          "sha512": "2eba84c4eaf56d746d92b9c441394d778f95430542c70651f53da2952bac03723ef9faa4a6fe0092e26552caa5c7ddfe39519196a362aad35816415e44fa74a5",
          "sha256": "cd77c71ce6d19744b96dececbdbd80a8a7b4885024a49f9ab338977af3d2d0d0",
          "sha1": "710a1b4889a1c3b4bbd706a40003c05e0193a9bc",
          "md5": "848ba57b390dfb54191e690b40ec57ed"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "just_audio_release-0.56-javadoc.jar",
          "url": "just_audio_release-0.56-javadoc.jar",
          "size": 298934,
          "sha512": "f26a587397b7f1480bd48c8540d91d59bc522697cec479f52bf84540e32999333c7b1afc4772586a1601858cbd88fc12b9f373217ec8ed345c2d5f67cfaaca7d",
          "sha256": "162c576a8b3869f10d8ac80136d3d1428e9162269914153dab2755feb1c4cb64",
          "sha1": "4aa8cb2405d3140848c1b3771fce293167f9df72",
          "md5": "bb0622534532fadeec93b55df368524a"
        }
      ]
    }
  ]
}
