{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.camerax",
    "module": "camera_android_camerax_release",
    "version": "0.47",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        }
      ],
      "files": [
        {
          "name": "camera_android_camerax_release-0.47.aar",
          "url": "camera_android_camerax_release-0.47.aar",
          "size": 266218,
          "sha512": "544362c5ff1f3dfd670bdd3b139a956eac39301eaa4567deb2bbd70ebf7fdb10d4b2db3279dc8d8d98120bea20447cc1be08e6d6be19d719be9b68c7e3025c9b",
          "sha256": "818b9d45bac3888e15c2e5e908c6e89136d4b2e1b116e14e897eff19fb2591f5",
          "sha1": "ae55d2037022e6ba7311a33962718a865d919ef3",
          "md5": "e115344ccf08c22c2c20497ee49725da"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.3.4"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.3.4"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.3.4"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-video",
          "version": {
            "requires": "1.3.4"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.3.1-android"
          }
        }
      ],
      "files": [
        {
          "name": "camera_android_camerax_release-0.47.aar",
          "url": "camera_android_camerax_release-0.47.aar",
          "size": 266218,
          "sha512": "544362c5ff1f3dfd670bdd3b139a956eac39301eaa4567deb2bbd70ebf7fdb10d4b2db3279dc8d8d98120bea20447cc1be08e6d6be19d719be9b68c7e3025c9b",
          "sha256": "818b9d45bac3888e15c2e5e908c6e89136d4b2e1b116e14e897eff19fb2591f5",
          "sha1": "ae55d2037022e6ba7311a33962718a865d919ef3",
          "md5": "e115344ccf08c22c2c20497ee49725da"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "camera_android_camerax_release-0.47-sources.jar",
          "url": "camera_android_camerax_release-0.47-sources.jar",
          "size": 86316,
          "sha512": "5382ce18bd09440222ebf82115235b669fd9af0e5aa1b7230156e004966fa02af4d6769714e893b0e78dff5e9f64a7111abc9ae654e1ab61bf292113b6ecdfc0",
          "sha256": "79f2b55e1b567c1876f27760b5465af879a2a59f33efec52baeeb486833fa9f7",
          "sha1": "e6e78d7a217d954c995f6146e7d112c64e43e04f",
          "md5": "e33d81ce6a5534f6131cd452966dd58f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "camera_android_camerax_release-0.47-javadoc.jar",
          "url": "camera_android_camerax_release-0.47-javadoc.jar",
          "size": 900059,
          "sha512": "9a3c110bec97c7af3a0a7de1931b04cbe786b97803162b23e8f5f0f47231cec84c6114ebb649c94b4c6c34f52d59df4674d92af241810dda31e3c49f919347a9",
          "sha256": "d3c1256286aff83f7fd44134a1d5d44b03f8e1d7ddd7c8ffdf3c7aee64e08073",
          "sha1": "271ac8973f785cd7fa48d3afd3ad4c098998a9d8",
          "md5": "5b8b4c5ce34807dd221a102ef1db534a"
        }
      ]
    }
  ]
}
