{
  "formatVersion": "1.1",
  "component": {
    "group": "net.wolverinebeach.flutter_timezone",
    "module": "flutter_timezone_release",
    "version": "0.47",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_timezone_release-0.47.aar",
          "url": "flutter_timezone_release-0.47.aar",
          "size": 3139,
          "sha512": "ed784c35ffba67c5140d33782e639a8bbec149a0a7bd2fd4f012a7133ae8dcfa25bf4bbd3ade60296f91841e855f72ac9906ba77831e2344dc1c877bef50c245",
          "sha256": "068c1de289c2fe7bded4a89406ba99e7a714a7185e675c555ee788d8d4077dbf",
          "sha1": "77b0eec34498847e3db08de8250d262d55e5305b",
          "md5": "663828c0ed77cba7908f32a29fdd3e5c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_timezone_release-0.47.aar",
          "url": "flutter_timezone_release-0.47.aar",
          "size": 3139,
          "sha512": "ed784c35ffba67c5140d33782e639a8bbec149a0a7bd2fd4f012a7133ae8dcfa25bf4bbd3ade60296f91841e855f72ac9906ba77831e2344dc1c877bef50c245",
          "sha256": "068c1de289c2fe7bded4a89406ba99e7a714a7185e675c555ee788d8d4077dbf",
          "sha1": "77b0eec34498847e3db08de8250d262d55e5305b",
          "md5": "663828c0ed77cba7908f32a29fdd3e5c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_timezone_release-0.47-sources.jar",
          "url": "flutter_timezone_release-0.47-sources.jar",
          "size": 1391,
          "sha512": "6b502c6a79c5a500cbc75e27ba9826e824d3531397f55e48644f843cb67f99022926912b04a2dec2823603694ba7d87ac7158fb4c7a19dad399ba8c39a959e15",
          "sha256": "bcd1a3ce8e51473fe5df70506828c2896775bad254f66d3214827d0dc5b69f09",
          "sha1": "95dbfe012e09fbb4605cc781ea5cdbae53414869",
          "md5": "9401f18133d348424988f5ef152a533e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_timezone_release-0.47-javadoc.jar",
          "url": "flutter_timezone_release-0.47-javadoc.jar",
          "size": 262427,
          "sha512": "bb9b5140500dfd7de7d982cb95f8b23087c246109d471372ee3d667fd92304efc4db56a9ae246edf8d10b9ad450a0523347d72105752f77a2d76ed9e1b84f7ad",
          "sha256": "438ccd5d61bdf60826e91a16165bc93789ac157d839ac77ac0f296d2e155da8b",
          "sha1": "5ec7707b36082eadfacc8e6209e45669ed06aa17",
          "md5": "153ba068152a6c1fb6029251aea7778e"
        }
      ]
    }
  ]
}
