{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tekartik.sqflite",
    "module": "sqflite_android_release",
    "version": "0.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        }
      ],
      "files": [
        {
          "name": "sqflite_android_release-0.11.aar",
          "url": "sqflite_android_release-0.11.aar",
          "size": 43468,
          "sha512": "bdf2f00eeb27c614972aafa29bfc09af9c76b7132f5d38fe7000a82df52ff272394aa3b846ce4c452f968af81f7c46ce317e7bbe4e80baf12b2e7da29b735ee4",
          "sha256": "c18824bca0d106cfb5c2e4a22fd13eb7bc8a8b4b6ae584571422e2ffdb0ccef6",
          "sha1": "492ac55c4970e1fb772c56e7fe95e743962897f8",
          "md5": "876d43595c452d77691e1b32fb117efb"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        }
      ],
      "files": [
        {
          "name": "sqflite_android_release-0.11.aar",
          "url": "sqflite_android_release-0.11.aar",
          "size": 43468,
          "sha512": "bdf2f00eeb27c614972aafa29bfc09af9c76b7132f5d38fe7000a82df52ff272394aa3b846ce4c452f968af81f7c46ce317e7bbe4e80baf12b2e7da29b735ee4",
          "sha256": "c18824bca0d106cfb5c2e4a22fd13eb7bc8a8b4b6ae584571422e2ffdb0ccef6",
          "sha1": "492ac55c4970e1fb772c56e7fe95e743962897f8",
          "md5": "876d43595c452d77691e1b32fb117efb"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sqflite_android_release-0.11-sources.jar",
          "url": "sqflite_android_release-0.11-sources.jar",
          "size": 23906,
          "sha512": "84be2e0f11f6739735214c714fcf25ca7b657afc40b3b54a0f0eff0de0f085cc926571087ab261b90cb6ed1e0be787046b45db4603790b883b119c835c22aa20",
          "sha256": "a127166bbaf1689504c6fc9e5111043a0537dc09ba3ea55a6d743da958ef125a",
          "sha1": "55f721f93f9c468c9d426bc61ff59a393e267750",
          "md5": "3f9cd042a556379914178c3426bed53c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sqflite_android_release-0.11-javadoc.jar",
          "url": "sqflite_android_release-0.11-javadoc.jar",
          "size": 342107,
          "sha512": "3d8975121bdd6267643bae096432b879df108525bf67bbd2f8794967a442fe286745ef7257c48d97bf31dfb7d256fa4cb198ca202dfe739de1c6ae5c8033739c",
          "sha256": "856597dc2d231c77b6ecc91aaaec4fdf69b91e3fc08f8d88206e306433d3bf6e",
          "sha1": "4559ea68e3dadaa0205c8ee00317b8de0c111007",
          "md5": "30ebc24f9edf99d80a16a1831323f944"
        }
      ]
    }
  ]
}
