{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tekartik.sqflite",
    "module": "sqflite_android_release",
    "version": "0.59",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        }
      ],
      "files": [
        {
          "name": "sqflite_android_release-0.59.aar",
          "url": "sqflite_android_release-0.59.aar",
          "size": 43464,
          "sha512": "7879a5234b45a10d6d14343dd39cc2038f419c9c1f211f2e04b9ddaa5519342b7fbf3b571bb488fc4c04dc07da33ffc708ebda8364532772286f91c08c754e30",
          "sha256": "a2b47e4f53735035112c4d0ecf795b936f49bb4315bea219db776942a98d090b",
          "sha1": "9d71bbae7150e6f0e16a68049adc852a3f5a7575",
          "md5": "90320c1fd75c9407ff1d2397d138f18d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        }
      ],
      "files": [
        {
          "name": "sqflite_android_release-0.59.aar",
          "url": "sqflite_android_release-0.59.aar",
          "size": 43464,
          "sha512": "7879a5234b45a10d6d14343dd39cc2038f419c9c1f211f2e04b9ddaa5519342b7fbf3b571bb488fc4c04dc07da33ffc708ebda8364532772286f91c08c754e30",
          "sha256": "a2b47e4f53735035112c4d0ecf795b936f49bb4315bea219db776942a98d090b",
          "sha1": "9d71bbae7150e6f0e16a68049adc852a3f5a7575",
          "md5": "90320c1fd75c9407ff1d2397d138f18d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sqflite_android_release-0.59-sources.jar",
          "url": "sqflite_android_release-0.59-sources.jar",
          "size": 23906,
          "sha512": "84be2e0f11f6739735214c714fcf25ca7b657afc40b3b54a0f0eff0de0f085cc926571087ab261b90cb6ed1e0be787046b45db4603790b883b119c835c22aa20",
          "sha256": "a127166bbaf1689504c6fc9e5111043a0537dc09ba3ea55a6d743da958ef125a",
          "sha1": "55f721f93f9c468c9d426bc61ff59a393e267750",
          "md5": "3f9cd042a556379914178c3426bed53c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sqflite_android_release-0.59-javadoc.jar",
          "url": "sqflite_android_release-0.59-javadoc.jar",
          "size": 341669,
          "sha512": "036a23a178ceee3d92793a893bff8f276331bfca173559245fc4f56cdb86d37f8894fea64c3945590db1c6f7185113a6957c86cbb64244fbe5afdaae6342c327",
          "sha256": "6b520b0d23153a42637e3b917537d13edd16929112e87baa1d7d3453407e10b4",
          "sha1": "91ae1d80e91114d5f9a6fc2b650ce24a3a124754",
          "md5": "f402045aaaf246764ad4dbec17b97a7d"
        }
      ]
    }
  ]
}
