{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.yongxin_ring",
    "module": "yongxin_ring_release",
    "version": "0.46",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "yongxin_ring_release-0.46.aar",
          "url": "yongxin_ring_release-0.46.aar",
          "size": 67188,
          "sha512": "4ade0a32943bceea916cee208d84a75d2d43e558a85347d4790359c56807e5871045c8df832727b736c0001f4e4650e54fe39ea466b240eefffc5ab177830cff",
          "sha256": "5828da8ec454c46c4e88b8603d84b850cabf2ebc470aee278d57c1aee9579444",
          "sha1": "a858089ae586d1ea8065019d545273e94f9c2b23",
          "md5": "9720cbbcdbc7f8737cfcd000b1638add"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        },
        {
          "group": "androidx.localbroadcastmanager",
          "module": "localbroadcastmanager",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.greenrobot",
          "module": "greendao",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "org.ligboy.retrofit2",
          "module": "converter-fastjson-android",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "24.0.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "com.zhy",
          "module": "okhttputils",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "com.tenmeter.smlibrary",
          "module": "tenmeter",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "yongxin_ring_release-0.46.aar",
          "url": "yongxin_ring_release-0.46.aar",
          "size": 67188,
          "sha512": "4ade0a32943bceea916cee208d84a75d2d43e558a85347d4790359c56807e5871045c8df832727b736c0001f4e4650e54fe39ea466b240eefffc5ab177830cff",
          "sha256": "5828da8ec454c46c4e88b8603d84b850cabf2ebc470aee278d57c1aee9579444",
          "sha1": "a858089ae586d1ea8065019d545273e94f9c2b23",
          "md5": "9720cbbcdbc7f8737cfcd000b1638add"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "yongxin_ring_release-0.46-sources.jar",
          "url": "yongxin_ring_release-0.46-sources.jar",
          "size": 19772,
          "sha512": "66b1da1fa8b1a59076c867bfe13952aacf14cce89cc5bc566c18989c041434237f16e1f51dc6d441605cb27d8ee57db251235aa26e2f970494080a45852f9499",
          "sha256": "aae4f92a76ab840fbd795124fb7ff605f047812129b7cd848529416591f0fd57",
          "sha1": "ae8a5241220f8885a361d55e2d0c9da9fbfb6d17",
          "md5": "631cda6e75f4537fb481183f8c6eb899"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "yongxin_ring_release-0.46-javadoc.jar",
          "url": "yongxin_ring_release-0.46-javadoc.jar",
          "size": 301443,
          "sha512": "099791ce65f799d03dd9539bedd71318cf984225e1aa1bb3c2f10008d017621d7efa09dbcb458443f6641e9cad88a264aa7c547220518d25facd70f281384d73",
          "sha256": "aba6971530ab2c5701e6b6b35680c27fed1e921a2f68281300734cb5c03ea687",
          "sha1": "b1c41bfea1cfc8eb0220bcf8dc95a10611af7066",
          "md5": "63619a3ecf7ac66e11371f14a526c353"
        }
      ]
    }
  ]
}
