{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.flutter_platform_alert",
    "module": "flutter_platform_alert_release",
    "version": "0.31",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_platform_alert_release-0.31.aar",
          "url": "flutter_platform_alert_release-0.31.aar",
          "size": 9179,
          "sha512": "bad7c4a8191fa519b3bb6457cd0204c53495101ecbed5e538c5aa1931df4dd7957a96f1c73c7696cfab1fef0210ae8d666900ba3fc188aea363b04a80caafb08",
          "sha256": "01e1888ef153eafb5a2b674cd05ee15fc2134b51964d4bbbb88ecdada208929d",
          "sha1": "49be972bb11cbfae15874fa7651a8bb0cbdfefe1",
          "md5": "2bc8722ee75445f7666fabf6e6e275ad"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.5.20"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_platform_alert_release-0.31.aar",
          "url": "flutter_platform_alert_release-0.31.aar",
          "size": 9179,
          "sha512": "bad7c4a8191fa519b3bb6457cd0204c53495101ecbed5e538c5aa1931df4dd7957a96f1c73c7696cfab1fef0210ae8d666900ba3fc188aea363b04a80caafb08",
          "sha256": "01e1888ef153eafb5a2b674cd05ee15fc2134b51964d4bbbb88ecdada208929d",
          "sha1": "49be972bb11cbfae15874fa7651a8bb0cbdfefe1",
          "md5": "2bc8722ee75445f7666fabf6e6e275ad"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_platform_alert_release-0.31-sources.jar",
          "url": "flutter_platform_alert_release-0.31-sources.jar",
          "size": 2419,
          "sha512": "0f2b22bac756a091326a6764355e2ee2c67d54d95ce2c038b9e91741917938070f40268ef2c8938684fb5110558c645f2617a325818b8f9f3fe7a70eec960812",
          "sha256": "0a5a52767371b2959d622148176f784c3054379097ee746859302933d68e85ad",
          "sha1": "5c714b72591bb9a3298241008d3df5fa6c53b609",
          "md5": "67fcd057752c94dc2ab62b41c059f6c0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_platform_alert_release-0.31-javadoc.jar",
          "url": "flutter_platform_alert_release-0.31-javadoc.jar",
          "size": 262874,
          "sha512": "afaed3058dc98ae6f108c4dbedb95d86861ce68b313bd7e11223f21695d48bb059782145195f0781d786849ddc866b9ce3f2208bd675c8f38f101814758ef00c",
          "sha256": "069c4e9d37fb175b7faaddcff4f7f9012014e3bd8495835f4929c7ace94d48f0",
          "sha1": "5ec4e220d23729000c8b048352838a6953e24af3",
          "md5": "9f2c21e92aad1d14dd6576e249f9764b"
        }
      ]
    }
  ]
}
