{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.firebase.firebaseremoteconfig",
    "module": "firebase_remote_config_release",
    "version": "0.27",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.core",
          "module": "firebase_core_release",
          "version": {
            "requires": "0.27"
          }
        }
      ],
      "files": [
        {
          "name": "firebase_remote_config_release-0.27.aar",
          "url": "firebase_remote_config_release-0.27.aar",
          "size": 10654,
          "sha512": "18b6840271418efd9a30eb92b0fec6ac27783cd7d5d0e62f5e96e662726e83172b8105aa89f2c962f13fa10f9fe39c3e6b9f5965cffa744029d1ffe10d7a41b3",
          "sha256": "9089d54e09e71a9bf64eb50d4e9a9c3d8d7c4f592be74aadeba9a1ea04298425",
          "sha1": "4be783baa16c599c9893d15f3db8def578f59315",
          "md5": "d9e920eaa16d14ef1224e72d062943ea"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-bom",
          "version": {
            "requires": "33.11.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-config"
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.core",
          "module": "firebase_core_release",
          "version": {
            "requires": "0.27"
          }
        }
      ],
      "files": [
        {
          "name": "firebase_remote_config_release-0.27.aar",
          "url": "firebase_remote_config_release-0.27.aar",
          "size": 10654,
          "sha512": "18b6840271418efd9a30eb92b0fec6ac27783cd7d5d0e62f5e96e662726e83172b8105aa89f2c962f13fa10f9fe39c3e6b9f5965cffa744029d1ffe10d7a41b3",
          "sha256": "9089d54e09e71a9bf64eb50d4e9a9c3d8d7c4f592be74aadeba9a1ea04298425",
          "sha1": "4be783baa16c599c9893d15f3db8def578f59315",
          "md5": "d9e920eaa16d14ef1224e72d062943ea"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "firebase_remote_config_release-0.27-sources.jar",
          "url": "firebase_remote_config_release-0.27-sources.jar",
          "size": 5293,
          "sha512": "101f051f9b8d8792612b26e61328dae1aaa93b234776ab1e12599e624e30a9606c0d3028658011342adc14bb4302bfb1ee40076094270e42f4f374c5db85e2bd",
          "sha256": "045ba4ec1f4c5d909e665f96786d729bb53b16f879b68b3977b79faed5f2c7c8",
          "sha1": "099573723c677b461b1502e2cf2ff7ab709ba529",
          "md5": "5f86a2e7dc66da959059dc0da259c46c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "firebase_remote_config_release-0.27-javadoc.jar",
          "url": "firebase_remote_config_release-0.27-javadoc.jar",
          "size": 273917,
          "sha512": "c42d1f780da92bf2ead69590430ffb0905af40e8775f5fb58015efc9bf81afefbd4eb94e3e158f267e4d46ef6a4b5e395998bd71e4554815ec397b6fbb116535",
          "sha256": "38ea15107fe29ea070f90be42735d8962b0bfbd36691806e0b21b38a35a10ede",
          "sha1": "0c623c84756d522713effaccd40a36d220a1d9eb",
          "md5": "d6502a400b068fe4464a86071be6d909"
        }
      ]
    }
  ]
}
