{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.yongxin_ring",
    "module": "yongxin_ring_release",
    "version": "0.66",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "yongxin_ring_release-0.66.aar",
          "url": "yongxin_ring_release-0.66.aar",
          "size": 200853,
          "sha512": "575ee7a70e2520a59587fe8bf38900412bb7a9015ccdcbd6d5c3755dfca71a5b9a70b9beae60ce3789b2f1ca806a17511308ebf0de99440e756f8b2463d16842",
          "sha256": "99595dda93439bfc1a8e655a1cd773f485e66fb52a07038faf60889ffd3ad6c1",
          "sha1": "4fd012f6a222ac99190e5e98eb089d7e0f797ed9",
          "md5": "8ada2c18902f91ade90d913059786d79"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        },
        {
          "group": "com.lm",
          "module": "chipletRing",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.localbroadcastmanager",
          "module": "localbroadcastmanager",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.greenrobot",
          "module": "greendao",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "org.ligboy.retrofit2",
          "module": "converter-fastjson-android",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "24.0.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "com.zhy",
          "module": "okhttputils",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "com.tenmeter.smlibrary",
          "module": "tenmeter",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "yongxin_ring_release-0.66.aar",
          "url": "yongxin_ring_release-0.66.aar",
          "size": 200853,
          "sha512": "575ee7a70e2520a59587fe8bf38900412bb7a9015ccdcbd6d5c3755dfca71a5b9a70b9beae60ce3789b2f1ca806a17511308ebf0de99440e756f8b2463d16842",
          "sha256": "99595dda93439bfc1a8e655a1cd773f485e66fb52a07038faf60889ffd3ad6c1",
          "sha1": "4fd012f6a222ac99190e5e98eb089d7e0f797ed9",
          "md5": "8ada2c18902f91ade90d913059786d79"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "yongxin_ring_release-0.66-sources.jar",
          "url": "yongxin_ring_release-0.66-sources.jar",
          "size": 59275,
          "sha512": "da2f6129fe0b86cfc2655f786009ac32d623e97b8a1356a98fcbf41659ad2a7ad72b648a1c7a75155b17f34f5db2a9eb33bf66d74809b5e051dc29551304f510",
          "sha256": "9ba285c46a78c1b4b8922df6f33f527fd3b43085ca9b4a4795c886018e6a9209",
          "sha1": "ddcb8d2323f141b2d05f66a1eaf4a96459b89f31",
          "md5": "1759c56992aef55bc32376f425dafc69"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "yongxin_ring_release-0.66-javadoc.jar",
          "url": "yongxin_ring_release-0.66-javadoc.jar",
          "size": 285141,
          "sha512": "940da2bb3a127262c44d957af4d19f8f40b7a2de63502df766f9b60043b60df44e7f1f050f405e516badda2208766bab14f9498fd49efc572e92d8c7d5e0eaa4",
          "sha256": "c717f2e2daf70b262c479d57812925b02a6b5b2aeab8b7804cca39e685b16994",
          "sha1": "8c8545a2b14f299ed1cb2b57498f9b136aecb468",
          "md5": "d58691d14c8b88b23b45f429ab47286e"
        }
      ]
    }
  ]
}
