{
  "formatVersion": "1.1",
  "component": {
    "group": "com.fluttercandies.flutter_image_compress",
    "module": "flutter_image_compress_common_release",
    "version": "0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_image_compress_common_release-0.2.aar",
          "url": "flutter_image_compress_common_release-0.2.aar",
          "size": 30456,
          "sha512": "1cef88b3d7e6eaea0c3aa30c64d67d58436242ad972812c241d4812df73b5efd8072be2ce22353d3039a9fa46732e697ac47df6a00b74cd1ea433b3b28d9bc13",
          "sha256": "1498b45475564bc8f0b6b31c982380e743ad767c0e132b6107b8ff26ccda6d3a",
          "sha1": "e9e9561dc2be55fc28830e77d9ed2d32c34b32a8",
          "md5": "ededa47d4da6304fe7e65990cd4584d7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "androidx.heifwriter",
          "module": "heifwriter",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_image_compress_common_release-0.2.aar",
          "url": "flutter_image_compress_common_release-0.2.aar",
          "size": 30456,
          "sha512": "1cef88b3d7e6eaea0c3aa30c64d67d58436242ad972812c241d4812df73b5efd8072be2ce22353d3039a9fa46732e697ac47df6a00b74cd1ea433b3b28d9bc13",
          "sha256": "1498b45475564bc8f0b6b31c982380e743ad767c0e132b6107b8ff26ccda6d3a",
          "sha1": "e9e9561dc2be55fc28830e77d9ed2d32c34b32a8",
          "md5": "ededa47d4da6304fe7e65990cd4584d7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_image_compress_common_release-0.2-sources.jar",
          "url": "flutter_image_compress_common_release-0.2-sources.jar",
          "size": 13283,
          "sha512": "9d463a80c9f9155d36af415dfbc87fadb7908f534f56929f46ded2280cbd3951f90518b08d83de17af9eab1bb66723f65b386d3d4df8b2a57dc67105fc8cad56",
          "sha256": "93a28e5f9b7fcb467c45057e584caa01f1eb412c0b4a92b23a49dc0100b4af37",
          "sha1": "8f0422fa7a12db6f03202df46f11b2c7ec84061a",
          "md5": "326cceeddeb7bc0e1af417bf6b15811f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_image_compress_common_release-0.2-javadoc.jar",
          "url": "flutter_image_compress_common_release-0.2-javadoc.jar",
          "size": 351453,
          "sha512": "1884815f821dc67fd5acf7702256355ce5791c1b36e8045e075503596ca9724982dfa97d01cfcdd846d99c5a0a48e28c26dbb837fbaea83faaddd5d5acef5446",
          "sha256": "418e60a2b583ee96e26569e121d15b6a76a223eef243a66c19fb9538e42ce54f",
          "sha1": "c12c64d739fa1a54f62ac07a6c57a5bf2119c256",
          "md5": "097761a8329855eeeb7045727dd19c69"
        }
      ]
    }
  ]
}
