{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.flutter_platform_alert",
    "module": "flutter_platform_alert_release",
    "version": "0.44",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_platform_alert_release-0.44.aar",
          "url": "flutter_platform_alert_release-0.44.aar",
          "size": 9177,
          "sha512": "c2eeffedf2e6830275db0891d6372f1d6bcdd851c99cc7a683e5d3a6c9bdb60c57292f0be93607e13319cfb585913ed1807b52c103d346cac86e6a2123fd4005",
          "sha256": "b6d2312257cd8895f1c4272a923aebec3d12affb4ca0fc48779210691564b60d",
          "sha1": "6693d5fd3fd0948464f3c8055fd96deb497ae974",
          "md5": "7435386bf56f8f7bc0f951fcaac09c29"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.5.20"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_platform_alert_release-0.44.aar",
          "url": "flutter_platform_alert_release-0.44.aar",
          "size": 9177,
          "sha512": "c2eeffedf2e6830275db0891d6372f1d6bcdd851c99cc7a683e5d3a6c9bdb60c57292f0be93607e13319cfb585913ed1807b52c103d346cac86e6a2123fd4005",
          "sha256": "b6d2312257cd8895f1c4272a923aebec3d12affb4ca0fc48779210691564b60d",
          "sha1": "6693d5fd3fd0948464f3c8055fd96deb497ae974",
          "md5": "7435386bf56f8f7bc0f951fcaac09c29"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_platform_alert_release-0.44-sources.jar",
          "url": "flutter_platform_alert_release-0.44-sources.jar",
          "size": 2419,
          "sha512": "0f2b22bac756a091326a6764355e2ee2c67d54d95ce2c038b9e91741917938070f40268ef2c8938684fb5110558c645f2617a325818b8f9f3fe7a70eec960812",
          "sha256": "0a5a52767371b2959d622148176f784c3054379097ee746859302933d68e85ad",
          "sha1": "5c714b72591bb9a3298241008d3df5fa6c53b609",
          "md5": "67fcd057752c94dc2ab62b41c059f6c0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_platform_alert_release-0.44-javadoc.jar",
          "url": "flutter_platform_alert_release-0.44-javadoc.jar",
          "size": 262836,
          "sha512": "2a682a586504e76e3752217c2ef2dbd478332c109f5e2481bff987c4db3808958689ab1d9ceaaa6b0dadd87d5f1089077be72963a1d681b15ba5a89ee7dea13a",
          "sha256": "b627bc13d3312dfa3d8aaed83ce57a7da1d0d9e99b191f47efc3ee275750f5e3",
          "sha1": "1ad6b347367034f2e7675e1cc25160072798ee06",
          "md5": "e7cb48e5e11ee0c885bc8c1303ff411a"
        }
      ]
    }
  ]
}
