{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.FlutterToast",
    "module": "fluttertoast_debug",
    "version": "0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        }
      ],
      "files": [
        {
          "name": "fluttertoast_debug-0.1.aar",
          "url": "fluttertoast_debug-0.1.aar",
          "size": 8938,
          "sha512": "f8eef99b48c710729d2745024c76a9e7cc9e4624320d86d20941d3d26f8715016b4de522ff0d25ad74eabb26c3277cd9467c80297d84f22e6b11f7d0b6fc5efd",
          "sha256": "1a037c9b7d5d82604bb823f9ade605d22dc00f470a77760addf8d89a17d38493",
          "sha1": "2ccfaaa102c3b2f171151d40f2e7e44c66976c39",
          "md5": "ef47b7e7c338f13c200d61299ee95066"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "fluttertoast_debug-0.1.aar",
          "url": "fluttertoast_debug-0.1.aar",
          "size": 8938,
          "sha512": "f8eef99b48c710729d2745024c76a9e7cc9e4624320d86d20941d3d26f8715016b4de522ff0d25ad74eabb26c3277cd9467c80297d84f22e6b11f7d0b6fc5efd",
          "sha256": "1a037c9b7d5d82604bb823f9ade605d22dc00f470a77760addf8d89a17d38493",
          "sha1": "2ccfaaa102c3b2f171151d40f2e7e44c66976c39",
          "md5": "ef47b7e7c338f13c200d61299ee95066"
        }
      ]
    },
    {
      "name": "debugVariantDebugSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fluttertoast_debug-0.1-sources.jar",
          "url": "fluttertoast_debug-0.1-sources.jar",
          "size": 3120,
          "sha512": "d9ebc2d9ee6ac43fe9b5cdc36686129ada7224df1bcc4f2f8f28ae624e9a6e94c44a493482daa6e1bf349432624693b6db5a3005ec9eec1715bbe170f4c4d7b6",
          "sha256": "69e1c82573001740c8ccb654af91736acda45261c9d0bcd2bd2ac8b6b62cdb24",
          "sha1": "9522dbaa5a7420975e525cac223d4b1717db7708",
          "md5": "7898eaf3504977619edc6f80d87654f9"
        }
      ]
    },
    {
      "name": "debugVariantDebugJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fluttertoast_debug-0.1-javadoc.jar",
          "url": "fluttertoast_debug-0.1-javadoc.jar",
          "size": 262528,
          "sha512": "fcdb77079f1dfda00e15e2d53c3c104ee91d690ced0b717c92942dd6e5b85ef692263d155806d05bf4e842cf03d809f3c03ee5da14e669567a62714ba5b118de",
          "sha256": "3b2f8652e35f5cb6b1ae2ea4f5cd6b700de2c2810b88d1ca2aff7bd75a2e974d",
          "sha1": "7ba223a553009e1d27140a46e409e2dc8dc96f0b",
          "md5": "0548cca140345ebe57898b77881ab17f"
        }
      ]
    }
  ]
}
