{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.fluttercommunity.plus.device_info",
    "module": "device_info_plus_release",
    "version": "0.17",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        }
      ],
      "files": [
        {
          "name": "device_info_plus_release-0.17.aar",
          "url": "device_info_plus_release-0.17.aar",
          "size": 6945,
          "sha512": "8598418a70a204b4f6ec104ea541d3066f7713466160a125b82f913027bdd906eab816227a6416b4b76d1a2820915c3810d31921994b6549942f5fcd4d2fd946",
          "sha256": "2b71c14a493ed2d5dcdc0b03af3db168b8a31d5795dcab90a24d355c2d78dc42",
          "sha1": "6db7d849fe908ef67028705c65026bbc9623c8ef",
          "md5": "83f964088c0477c673f44f450ec1b13a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.22"
          }
        }
      ],
      "files": [
        {
          "name": "device_info_plus_release-0.17.aar",
          "url": "device_info_plus_release-0.17.aar",
          "size": 6945,
          "sha512": "8598418a70a204b4f6ec104ea541d3066f7713466160a125b82f913027bdd906eab816227a6416b4b76d1a2820915c3810d31921994b6549942f5fcd4d2fd946",
          "sha256": "2b71c14a493ed2d5dcdc0b03af3db168b8a31d5795dcab90a24d355c2d78dc42",
          "sha1": "6db7d849fe908ef67028705c65026bbc9623c8ef",
          "md5": "83f964088c0477c673f44f450ec1b13a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "device_info_plus_release-0.17-sources.jar",
          "url": "device_info_plus_release-0.17-sources.jar",
          "size": 2976,
          "sha512": "b0a16c5d099d1a6d3f96d453ca4f34aa2b138d0729fd675fa4dadff9f54e169514b31bd5586b5d4fb388059df0d5e5ff8ceeeec9214322cced8b305c5d67afb3",
          "sha256": "1160189e3c750bbf50affba28a4dbf0fc1216e815a1f01a3d1d9dd17958f37ab",
          "sha1": "b1f985fbb38747f8f626c4988380b4847ff05db6",
          "md5": "7effa257187ed4394bf3919149a7d9e8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "device_info_plus_release-0.17-javadoc.jar",
          "url": "device_info_plus_release-0.17-javadoc.jar",
          "size": 260895,
          "sha512": "9e33856350c53ffad4515e60ee9878f9df9d131236c0fef8cfcb55cd2dae02aea02486ba30d4ac8980ab4ec6fc7480f084c540e8a91e4e7071e18fcbd5919e17",
          "sha256": "baa5a76bbd26d8a0d5fa0f7db6571de24e8ae733fc9af42741787852e7e1a1fb",
          "sha1": "92f66d9a6fb5fb7312ec22884d2b63b5bf9d1901",
          "md5": "ef295009389d1a0061fd5dcd699a8996"
        }
      ]
    }
  ]
}
