{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.yongxin_ring",
    "module": "yongxin_ring_release",
    "version": "0.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "yongxin_ring_release-0.13.aar",
          "url": "yongxin_ring_release-0.13.aar",
          "size": 52098,
          "sha512": "cb00a9f6d04b5b911f6e07fe4eb12ec8ceb65a33845a00acb2032c0ab8d4ef6f1cc4afc5cf014cd0e543f78b3e7543064e607af6a60c0371ded2e8f2af818c62",
          "sha256": "37da48cceb6406146ed3cbd67deaf3c2835f1b8993fe9148df1176c9a4dfe2d6",
          "sha1": "85fc699950772f4e35d9486b2c953dbf716607fe",
          "md5": "3067e990f93264580a5d77f95cf98f18"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        },
        {
          "group": "com.lm",
          "module": "chipletRing",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.localbroadcastmanager",
          "module": "localbroadcastmanager",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.greenrobot",
          "module": "greendao",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "org.ligboy.retrofit2",
          "module": "converter-fastjson-android",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "24.0.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "com.zhy",
          "module": "okhttputils",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "com.tenmeter.smlibrary",
          "module": "tenmeter",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "yongxin_ring_release-0.13.aar",
          "url": "yongxin_ring_release-0.13.aar",
          "size": 52098,
          "sha512": "cb00a9f6d04b5b911f6e07fe4eb12ec8ceb65a33845a00acb2032c0ab8d4ef6f1cc4afc5cf014cd0e543f78b3e7543064e607af6a60c0371ded2e8f2af818c62",
          "sha256": "37da48cceb6406146ed3cbd67deaf3c2835f1b8993fe9148df1176c9a4dfe2d6",
          "sha1": "85fc699950772f4e35d9486b2c953dbf716607fe",
          "md5": "3067e990f93264580a5d77f95cf98f18"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "yongxin_ring_release-0.13-sources.jar",
          "url": "yongxin_ring_release-0.13-sources.jar",
          "size": 14876,
          "sha512": "cb9cb8a2e734a1e7ad3c400eb29f72bb8a3df8b2a2f24a06539e0a6a7638d013a9b06fc0f3fdb4640bab28db797fdd5c40fbd679ec46c14610ca5a0c05f17fd2",
          "sha256": "3504c9e45a2e9169fa14d9943192c09f5f73207da6ea592b6d2d5c9c3b4ae5d3",
          "sha1": "e46dfd3b621e9439cb0a7b9d75f49151ce92aa99",
          "md5": "c61bf7351d3f56ea84ac74f6c6e370ec"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "yongxin_ring_release-0.13-javadoc.jar",
          "url": "yongxin_ring_release-0.13-javadoc.jar",
          "size": 301627,
          "sha512": "68335e190735f204709748bda07266be4ed7ec2355b2d02e774d67391ad5087bc1d6def0435b75edea6a4a5d94a3d0c4cd8cb2326c5a43770d5e85789b14763c",
          "sha256": "34fe38adf08cfb6c19fe2fdfc97ab427d892303642496f2079d15ab7ec56c8c5",
          "sha1": "3847d364a42e7c6c04d873984377bc4903c345bc",
          "md5": "bc7335cc512aac110a3fb32ff581f31a"
        }
      ]
    }
  ]
}
