{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.fluttercommunity.plus.packageinfo",
    "module": "package_info_plus_release",
    "version": "0.64",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        }
      ],
      "files": [
        {
          "name": "package_info_plus_release-0.64.aar",
          "url": "package_info_plus_release-0.64.aar",
          "size": 5912,
          "sha512": "12952471061dcc1dce31b4d3a749e685819f7024aa86fab60189b5b0598b2af2334730663b78839aaaae20a4bacfc1b694276022be39cd970a13f6e843c1f877",
          "sha256": "74d813b268e2caafd12878053297be94bfe7c1af4b696922081820e6668662b6",
          "sha1": "7f4d545eace18925875da63cae963d1055812da1",
          "md5": "06f7d5d754603a9090614e4367d42d32"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.22"
          }
        }
      ],
      "files": [
        {
          "name": "package_info_plus_release-0.64.aar",
          "url": "package_info_plus_release-0.64.aar",
          "size": 5912,
          "sha512": "12952471061dcc1dce31b4d3a749e685819f7024aa86fab60189b5b0598b2af2334730663b78839aaaae20a4bacfc1b694276022be39cd970a13f6e843c1f877",
          "sha256": "74d813b268e2caafd12878053297be94bfe7c1af4b696922081820e6668662b6",
          "sha1": "7f4d545eace18925875da63cae963d1055812da1",
          "md5": "06f7d5d754603a9090614e4367d42d32"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "package_info_plus_release-0.64-sources.jar",
          "url": "package_info_plus_release-0.64-sources.jar",
          "size": 2693,
          "sha512": "baaae2e6245030a7de70f19e43504fb87d6d374ec50af2dd23321d0ab0bf43dbb918967f0b66277e2662ccb4faf2098ffcb870dd1e597bc1dc8ac730e9c7b5fb",
          "sha256": "3f208ebbb8c9b93761dea623949b7ee1a9cd74e818acede7ccc4f562f3839a5d",
          "sha1": "12df81060cfa11fc35581f9c91da8922a5f8e6f0",
          "md5": "f30e01eabb60c79316840a3ed7edecb3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "package_info_plus_release-0.64-javadoc.jar",
          "url": "package_info_plus_release-0.64-javadoc.jar",
          "size": 265026,
          "sha512": "dd95694407f4258bc8fa28577b12f406dee9460b23acb5e28a1592371651beb0c3053678e48c7211e97878761ce5a0aaf77dfaeea985320ed237cb905bc59cb4",
          "sha256": "af2a67add2ab8f1eed9b6e4e14b8b3826be6e9e84bab575a33c60fa842a42c3d",
          "sha1": "848e14af2c04912ed15143c6b0af13c36af64f58",
          "md5": "c4f55095033d014dcfd0190ff4bed5d9"
        }
      ]
    }
  ]
}
