{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.yongxin_ring",
    "module": "yongxin_ring_release",
    "version": "0.27",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "yongxin_ring_release-0.27.aar",
          "url": "yongxin_ring_release-0.27.aar",
          "size": 54859,
          "sha512": "e50719d1644015d1b367229db33d619fb2e20aba6f287f34d5b494119b30a0b96a25fe1de7ba3905296a21439809c963f048e02225038094e61f33ebf4e6011a",
          "sha256": "f102eb5d90d8eb9ff9abf0c53ae4ac5e3d23fac3314d18b0ed4dfdadc6f7e986",
          "sha1": "e676ac1340b5382f445d62cbf49c9cb01f94dd9c",
          "md5": "348fef946f9905de4f166b6568053bfd"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        },
        {
          "group": "com.lm",
          "module": "chipletRing",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.localbroadcastmanager",
          "module": "localbroadcastmanager",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.greenrobot",
          "module": "greendao",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "org.ligboy.retrofit2",
          "module": "converter-fastjson-android",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "24.0.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "com.zhy",
          "module": "okhttputils",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "com.tenmeter.smlibrary",
          "module": "tenmeter",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "yongxin_ring_release-0.27.aar",
          "url": "yongxin_ring_release-0.27.aar",
          "size": 54859,
          "sha512": "e50719d1644015d1b367229db33d619fb2e20aba6f287f34d5b494119b30a0b96a25fe1de7ba3905296a21439809c963f048e02225038094e61f33ebf4e6011a",
          "sha256": "f102eb5d90d8eb9ff9abf0c53ae4ac5e3d23fac3314d18b0ed4dfdadc6f7e986",
          "sha1": "e676ac1340b5382f445d62cbf49c9cb01f94dd9c",
          "md5": "348fef946f9905de4f166b6568053bfd"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "yongxin_ring_release-0.27-sources.jar",
          "url": "yongxin_ring_release-0.27-sources.jar",
          "size": 15552,
          "sha512": "4ed7f1f235c7e958843a143b50662106cdbeb9b9252f0bfabeb4d20566dce7ea8a3408cc8f5e0d3309d31a4365e76151d089ce9cc271645a794ebf67a6b5f5c0",
          "sha256": "3efa0d688381f9f9c477a2852a910b9a6e9a52ce3e4a33f416b28c7de9cdee72",
          "sha1": "2dcdb31602edfbc85c179ff787024d6b466c16b7",
          "md5": "32c3f3566e014617fa2c163ddda59dd8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "yongxin_ring_release-0.27-javadoc.jar",
          "url": "yongxin_ring_release-0.27-javadoc.jar",
          "size": 301633,
          "sha512": "8a35fb823038976fceda68db6292df9ea8b70db43e2cd64dbc4d8734a6a054e4ecd1ccf048d31e7795b6918bff77509c959ce129aeb60cd5f02147e63cc526e9",
          "sha256": "b7c5fd50a1bb9f4b8d5b47b0bf89f00c7c65064efa8db36b77c32be2b178f82e",
          "sha1": "0d74d14d19304311e050c225a7daa6d29dcc24a3",
          "md5": "58585148d499dece63b3301d70e01881"
        }
      ]
    }
  ]
}
