{
  "formatVersion": "1.1",
  "component": {
    "group": "com.ryanheise.just_audio",
    "module": "just_audio_release",
    "version": "0.54",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        }
      ],
      "files": [
        {
          "name": "just_audio_release-0.54.aar",
          "url": "just_audio_release-0.54.aar",
          "size": 28482,
          "sha512": "43fb036df9eee45abee15a17f29c276eb82b6a273fd1363effb176f8b15e69e199d35ab6cbfef537d1e439db339cf51cf4ecced1437f6485917397d4a49c0892",
          "sha256": "32f70ebafd4441da3dc884ae41d574fff07249ab0cd28465245ba258a5cf61c2",
          "sha1": "d821f699bf6597f5612ec38a7cb376d7257fa62d",
          "md5": "01f45aa6819d4393b8c0c1597e834fc8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-dash",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-hls",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-smoothstreaming",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "com.ryanheise.audio_session",
          "module": "audio_session_release",
          "version": {
            "requires": "0.54"
          }
        }
      ],
      "files": [
        {
          "name": "just_audio_release-0.54.aar",
          "url": "just_audio_release-0.54.aar",
          "size": 28482,
          "sha512": "43fb036df9eee45abee15a17f29c276eb82b6a273fd1363effb176f8b15e69e199d35ab6cbfef537d1e439db339cf51cf4ecced1437f6485917397d4a49c0892",
          "sha256": "32f70ebafd4441da3dc884ae41d574fff07249ab0cd28465245ba258a5cf61c2",
          "sha1": "d821f699bf6597f5612ec38a7cb376d7257fa62d",
          "md5": "01f45aa6819d4393b8c0c1597e834fc8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "just_audio_release-0.54-sources.jar",
          "url": "just_audio_release-0.54-sources.jar",
          "size": 12367,
          "sha512": "2eba84c4eaf56d746d92b9c441394d778f95430542c70651f53da2952bac03723ef9faa4a6fe0092e26552caa5c7ddfe39519196a362aad35816415e44fa74a5",
          "sha256": "cd77c71ce6d19744b96dececbdbd80a8a7b4885024a49f9ab338977af3d2d0d0",
          "sha1": "710a1b4889a1c3b4bbd706a40003c05e0193a9bc",
          "md5": "848ba57b390dfb54191e690b40ec57ed"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "just_audio_release-0.54-javadoc.jar",
          "url": "just_audio_release-0.54-javadoc.jar",
          "size": 298932,
          "sha512": "35c42b5a9316356fcf2acb35e082ad9a7af32f504d724a64be46b8aa1e3ea99b5e81f003067ad456155d321e5f7936f58fb66844562d0ffc9d29a96547c45ca1",
          "sha256": "bf44ffd803d4adea06d66208309cd26266e26f6ec091d7a56b86d3b0e0bb9f80",
          "sha1": "10ecbbb10e287b828c69a721c812e3309303d03d",
          "md5": "d49688897fbff42254205a9dabd4883e"
        }
      ]
    }
  ]
}
