{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.firebaseperformance",
    "module": "firebase_performance_release",
    "version": "0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.core",
          "module": "firebase_core_release",
          "version": {
            "requires": "0.3"
          }
        }
      ],
      "files": [
        {
          "name": "firebase_performance_release-0.3.aar",
          "url": "firebase_performance_release-0.3.aar",
          "size": 8724,
          "sha512": "127d79e86d90cb8bca4c5f359cb3b7a46c2629d648b7214ecc9174488cdfd8fa06aca4ee2df20e6150360aa71c247badf755826b7955c307029d5d6646c864e9",
          "sha256": "cdbbb94919cca22abd28362c05d074407fbe3ceee7edf7a6c85da6ab42ae5b92",
          "sha1": "fa4202a09134baf0e1f0ded85cd17f2d1f1ae6ac",
          "md5": "c6eb8f4229ff42e54d26fd7396dcfad5"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-bom",
          "version": {
            "requires": "33.11.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-perf"
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.core",
          "module": "firebase_core_release",
          "version": {
            "requires": "0.3"
          }
        }
      ],
      "files": [
        {
          "name": "firebase_performance_release-0.3.aar",
          "url": "firebase_performance_release-0.3.aar",
          "size": 8724,
          "sha512": "127d79e86d90cb8bca4c5f359cb3b7a46c2629d648b7214ecc9174488cdfd8fa06aca4ee2df20e6150360aa71c247badf755826b7955c307029d5d6646c864e9",
          "sha256": "cdbbb94919cca22abd28362c05d074407fbe3ceee7edf7a6c85da6ab42ae5b92",
          "sha1": "fa4202a09134baf0e1f0ded85cd17f2d1f1ae6ac",
          "md5": "c6eb8f4229ff42e54d26fd7396dcfad5"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "firebase_performance_release-0.3-sources.jar",
          "url": "firebase_performance_release-0.3-sources.jar",
          "size": 4416,
          "sha512": "fba5daa26f6d62a7a8ff7046e7884ae6226be7412ef275e7a35dca78c1b504caa21d3b92e5a7bf471f51e9fb7a6be9a71365eba8b8dff9b33e9eedf40bb2d8eb",
          "sha256": "71dfa838fec053e41f73a2efdea999fab1e372cd1ff8d6d5d58643fa2e9ebb52",
          "sha1": "f34f6b23b162908566c21ecfcccbf69fa9e2c14c",
          "md5": "ac96771d4a0151e4a8c0d4170deb5fd7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "firebase_performance_release-0.3-javadoc.jar",
          "url": "firebase_performance_release-0.3-javadoc.jar",
          "size": 273480,
          "sha512": "7c6cca184589051f4dc15bc7463cd086392d0c960bded12d700ca95cbec3341708ee72f824b229ced93dfb9a49bdfb5be58e563aee608066b3065749bf75d806",
          "sha256": "a7e2b6f126a6a6cab0e6121e89a31f692c701bf4bd6d28d7d84cd0f90a63d96a",
          "sha1": "30a39c4fb128333e0389d9e58d6bc96aee081cd3",
          "md5": "fad4c011c219198c4479a9950fa16ed4"
        }
      ]
    }
  ]
}
