{
  "formatVersion": "1.1",
  "component": {
    "group": "com.uxcam.flutteruxcam",
    "module": "flutter_uxcam_release",
    "version": "0.30",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_uxcam_release-0.30.aar",
          "url": "flutter_uxcam_release-0.30.aar",
          "size": 15635,
          "sha512": "19335b9f1d6c203870553ad741a432b7d91953d80919881823d749c6357ec1217d6ecf1191340bc87ad3695cf74570479b0240ada789d63d53d6621e2d1a78e8",
          "sha256": "8b2eb5ccba653f6b9d01587bf247e5c12b4f2b0ff559e10e58086e65885b55e9",
          "sha1": "a85a19167f2b34e28e5767926d7ca6c9296950da",
          "md5": "ee733c7a06f0d35e2b9dddea324ab151"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        },
        {
          "group": "com.uxcam",
          "module": "uxcam",
          "version": {
            "requires": "3.7.3"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.8.1"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_uxcam_release-0.30.aar",
          "url": "flutter_uxcam_release-0.30.aar",
          "size": 15635,
          "sha512": "19335b9f1d6c203870553ad741a432b7d91953d80919881823d749c6357ec1217d6ecf1191340bc87ad3695cf74570479b0240ada789d63d53d6621e2d1a78e8",
          "sha256": "8b2eb5ccba653f6b9d01587bf247e5c12b4f2b0ff559e10e58086e65885b55e9",
          "sha1": "a85a19167f2b34e28e5767926d7ca6c9296950da",
          "md5": "ee733c7a06f0d35e2b9dddea324ab151"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_uxcam_release-0.30-sources.jar",
          "url": "flutter_uxcam_release-0.30-sources.jar",
          "size": 6624,
          "sha512": "8c8995128d92a57940fc4ee3e197a0c24043259571da84341c0033ac0c3e14c86692995b1fb3445702f6bf90978e766348da6498e74089f5d2229be78fead2c6",
          "sha256": "38576f89ca9a96e844bc0811bb6268e5a97ca6cebf7ddcf35fb62eafa63f0ff8",
          "sha1": "b5de60a02ecbc73237aac07c073ea8a38b9e3c72",
          "md5": "71e9af78ee02c8408fa779d1ec7bdf5a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_uxcam_release-0.30-javadoc.jar",
          "url": "flutter_uxcam_release-0.30-javadoc.jar",
          "size": 287112,
          "sha512": "9d0a422e928a7601ce95ecbafef7bf4b32ea5f5456c379fb379fe198bdf733846eac4a4dee50e3ceb64193e1142ecccfcfc69e5216c4ee1381beac1b1885ac2c",
          "sha256": "7dde01158283c705e1cb06ea2ebe16d6eb5dac26d147af4fb92e813c4433bd9a",
          "sha1": "5ad22c3d5e8f37b484ee075698fb14219aa7a5a0",
          "md5": "0c38b131060b976f661eddb384d661f8"
        }
      ]
    }
  ]
}
