{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.steenbakker.mobile_scanner",
    "module": "mobile_scanner_release",
    "version": "0.59",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "mobile_scanner_release-0.59.aar",
          "url": "mobile_scanner_release-0.59.aar",
          "size": 80052,
          "sha512": "e8906be5b9bd883074988babe185837dad3924066401da9907b44fdac95bde40db1de4fbd36da2ff2a100b55adf67e4acefbe641dabe488a591b603b69a73450",
          "sha256": "b974f14f48dc266f92bbe2969f1f23d84087eb8c259db1468c4f7af1d8fd0439",
          "sha1": "97d63ab9e3ada1c60e4d070d6cddbb6a40579c21",
          "md5": "691b6ad477dda55c4ec6c5245d4effd7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        },
        {
          "group": "com.google.mlkit",
          "module": "barcode-scanning",
          "version": {
            "requires": "17.3.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "mobile_scanner_release-0.59.aar",
          "url": "mobile_scanner_release-0.59.aar",
          "size": 80052,
          "sha512": "e8906be5b9bd883074988babe185837dad3924066401da9907b44fdac95bde40db1de4fbd36da2ff2a100b55adf67e4acefbe641dabe488a591b603b69a73450",
          "sha256": "b974f14f48dc266f92bbe2969f1f23d84087eb8c259db1468c4f7af1d8fd0439",
          "sha1": "97d63ab9e3ada1c60e4d070d6cddbb6a40579c21",
          "md5": "691b6ad477dda55c4ec6c5245d4effd7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "mobile_scanner_release-0.59-sources.jar",
          "url": "mobile_scanner_release-0.59-sources.jar",
          "size": 24609,
          "sha512": "27f89198c4cab12886a5e9125b01909563d71ddd4f011f8e61d5ab93c4804a84c6cdb0f2c8ec6b8a80b0ff023818e75e0cfeda8d84baa8bd076bd9d1d1884e8c",
          "sha256": "c441928c04d6a1239519fc37216168b1a9fa71a78d204038e6743a717956cd39",
          "sha1": "7f26d772affa7468d29e632995715b80b06636ee",
          "md5": "119c437ddc3b190ce9e78fc1a2ae97ed"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "mobile_scanner_release-0.59-javadoc.jar",
          "url": "mobile_scanner_release-0.59-javadoc.jar",
          "size": 392293,
          "sha512": "5715780b8e8cbec73200b0c3c5d2c33eadde0fdd6e29aff97c1f6367d2cb0f4802f933bd9852b8aa709d7b63d845c0f21fd3ba605c66f9ae0810bcd347612d7c",
          "sha256": "a1fa584ebc886916434e590a14c97c40a05e03fe10a95ae3179633017a51064e",
          "sha1": "b2efba983ff40bdfabd0a19a30541460354de261",
          "md5": "7ea3ccd64b9dd798d558618fcaae76cb"
        }
      ]
    }
  ]
}
