{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tekartik.sqflite",
    "module": "sqflite_android_release",
    "version": "0.60",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        }
      ],
      "files": [
        {
          "name": "sqflite_android_release-0.60.aar",
          "url": "sqflite_android_release-0.60.aar",
          "size": 43464,
          "sha512": "7879a5234b45a10d6d14343dd39cc2038f419c9c1f211f2e04b9ddaa5519342b7fbf3b571bb488fc4c04dc07da33ffc708ebda8364532772286f91c08c754e30",
          "sha256": "a2b47e4f53735035112c4d0ecf795b936f49bb4315bea219db776942a98d090b",
          "sha1": "9d71bbae7150e6f0e16a68049adc852a3f5a7575",
          "md5": "90320c1fd75c9407ff1d2397d138f18d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        }
      ],
      "files": [
        {
          "name": "sqflite_android_release-0.60.aar",
          "url": "sqflite_android_release-0.60.aar",
          "size": 43464,
          "sha512": "7879a5234b45a10d6d14343dd39cc2038f419c9c1f211f2e04b9ddaa5519342b7fbf3b571bb488fc4c04dc07da33ffc708ebda8364532772286f91c08c754e30",
          "sha256": "a2b47e4f53735035112c4d0ecf795b936f49bb4315bea219db776942a98d090b",
          "sha1": "9d71bbae7150e6f0e16a68049adc852a3f5a7575",
          "md5": "90320c1fd75c9407ff1d2397d138f18d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sqflite_android_release-0.60-sources.jar",
          "url": "sqflite_android_release-0.60-sources.jar",
          "size": 23906,
          "sha512": "84be2e0f11f6739735214c714fcf25ca7b657afc40b3b54a0f0eff0de0f085cc926571087ab261b90cb6ed1e0be787046b45db4603790b883b119c835c22aa20",
          "sha256": "a127166bbaf1689504c6fc9e5111043a0537dc09ba3ea55a6d743da958ef125a",
          "sha1": "55f721f93f9c468c9d426bc61ff59a393e267750",
          "md5": "3f9cd042a556379914178c3426bed53c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sqflite_android_release-0.60-javadoc.jar",
          "url": "sqflite_android_release-0.60-javadoc.jar",
          "size": 341664,
          "sha512": "7c17adf6cd7e43f483afefba45b00ddc03d0f674c7ea52d7a748a4c857c51e6361367515bd69a23aaed746c655bba5d53ba34af96ce3033a47767ce208de317d",
          "sha256": "3d0c2915f697b27883734b954382f80145c4ea08304b69627fd7a7feddfbbac2",
          "sha1": "f12060fd7f57b2d1b9a08fa4fd5934440e3d2afe",
          "md5": "d2994cf59794a42fe089120cee7efd68"
        }
      ]
    }
  ]
}
