{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
    "module": "flutter_plugin_android_lifecycle_release",
    "version": "0.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_plugin_android_lifecycle_release-0.13.aar",
          "url": "flutter_plugin_android_lifecycle_release-0.13.aar",
          "size": 2503,
          "sha512": "c47015d3684b3b1a0cef077b1929cbe61ffaa4f3d8ec078ed4279cb7aa1ada9dc8e0f337ea5b9159a936cc75e63540eb8e70c1088a32642ceff62862fe1374f9",
          "sha256": "9fb4cf8d054e60d0bf6d639cfacc66db8aab776059fd0e9b67ace8c60d169d65",
          "sha1": "e526db6513439eebf917c63e27fa7b9d969a4d2d",
          "md5": "89a4374677faa54c80076e99a9da11a4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_plugin_android_lifecycle_release-0.13.aar",
          "url": "flutter_plugin_android_lifecycle_release-0.13.aar",
          "size": 2503,
          "sha512": "c47015d3684b3b1a0cef077b1929cbe61ffaa4f3d8ec078ed4279cb7aa1ada9dc8e0f337ea5b9159a936cc75e63540eb8e70c1088a32642ceff62862fe1374f9",
          "sha256": "9fb4cf8d054e60d0bf6d639cfacc66db8aab776059fd0e9b67ace8c60d169d65",
          "sha1": "e526db6513439eebf917c63e27fa7b9d969a4d2d",
          "md5": "89a4374677faa54c80076e99a9da11a4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_plugin_android_lifecycle_release-0.13-sources.jar",
          "url": "flutter_plugin_android_lifecycle_release-0.13-sources.jar",
          "size": 2683,
          "sha512": "a3f7fee602ae01e1fe53ad82c914db15159744a75a0e4f439cdbe5e530abf6d3b431e26802ccd3cf08245278758e1aef335a9e00aec7ded1b1c89a60a53d7915",
          "sha256": "ea22384264efbced6ae1be61be8aadee870b81c3a1e0b6accc0ef62396aaeae0",
          "sha1": "1ddcac6e1149d882ff8719e00a4eebfeb282eb36",
          "md5": "351ed496e751473b57d20e3a693b432d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_plugin_android_lifecycle_release-0.13-javadoc.jar",
          "url": "flutter_plugin_android_lifecycle_release-0.13-javadoc.jar",
          "size": 269939,
          "sha512": "c11bd23eafb7e1af2f30b2c2aa2c99d1c0c4eb1193e50db08768ea2f806ef75ca771559771f03084ff8e39c7e82e04f109fe460a78d823960da90535c592e6f1",
          "sha256": "ed4cdad406f2e2e0ae68a676a304902178a37742d37745a06f18a96c2e541dfe",
          "sha1": "1f91e60c25771e674556774957cc31e576550704",
          "md5": "a1d1e5735271fb9d8c409b8e26c6948f"
        }
      ]
    }
  ]
}
