{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.camera",
    "module": "camera_android_release",
    "version": "0.20",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        }
      ],
      "files": [
        {
          "name": "camera_android_release-0.20.aar",
          "url": "camera_android_release-0.20.aar",
          "size": 160855,
          "sha512": "06798cc7c9b1e65caa0be5a0cf196feb5b0b7ec5c06e9ed917a921adb7a6d9bf67a284593e78a947280ca5beb4e81e5c7c6525a7be14aa16693f90be5fd7729e",
          "sha256": "3b5a909f96a3d48f4d30e52a4d097ec4c3e66d1bc2660247db37161dc5aa6117",
          "sha1": "23b2da27a571640af5600c54202479797bdbef85",
          "md5": "be6000683e9cf8879ad728b27e34a474"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_release",
          "version": {
            "requires": "0.20"
          }
        }
      ],
      "files": [
        {
          "name": "camera_android_release-0.20.aar",
          "url": "camera_android_release-0.20.aar",
          "size": 160855,
          "sha512": "06798cc7c9b1e65caa0be5a0cf196feb5b0b7ec5c06e9ed917a921adb7a6d9bf67a284593e78a947280ca5beb4e81e5c7c6525a7be14aa16693f90be5fd7729e",
          "sha256": "3b5a909f96a3d48f4d30e52a4d097ec4c3e66d1bc2660247db37161dc5aa6117",
          "sha1": "23b2da27a571640af5600c54202479797bdbef85",
          "md5": "be6000683e9cf8879ad728b27e34a474"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "camera_android_release-0.20-sources.jar",
          "url": "camera_android_release-0.20-sources.jar",
          "size": 88327,
          "sha512": "4495e9efa9193aa2dc723beb5a09cdd6ce754fbc890cee9aa2c170644d99d5c7e2d15e8678e1dbff69b040ed068d931605812dca76ca2a6cb847a1b485f3f43b",
          "sha256": "fe50a797bb52ef81ce67840287ec2d60ba851288ce3713b923ba6a2427fb54f0",
          "sha1": "200754a2e631ba8f6d4cc3a4325ca97205b96422",
          "md5": "27092203793db372f3df052b4d900525"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "camera_android_release-0.20-javadoc.jar",
          "url": "camera_android_release-0.20-javadoc.jar",
          "size": 605717,
          "sha512": "ba2297302a5903d954b3566be135ab1117e9b442bb730f969272ed9a27afa0f2b3f461c4b3da8672fa39d32b58f6747eedadea1790c98227649ad54930beb51a",
          "sha256": "92188b81075f6e6f0c2200b5c6a1d4011ee9f6e3d0a2fc96a8f2508dc057bfdf",
          "sha1": "6c928764a58f498ccbffb4b78678b260b55b9e0e",
          "md5": "12f359793751802715a1d9359cb5c937"
        }
      ]
    }
  ]
}
