{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tekartik.sqflite",
    "module": "sqflite_android_release",
    "version": "0.23",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        }
      ],
      "files": [
        {
          "name": "sqflite_android_release-0.23.aar",
          "url": "sqflite_android_release-0.23.aar",
          "size": 43468,
          "sha512": "bdf2f00eeb27c614972aafa29bfc09af9c76b7132f5d38fe7000a82df52ff272394aa3b846ce4c452f968af81f7c46ce317e7bbe4e80baf12b2e7da29b735ee4",
          "sha256": "c18824bca0d106cfb5c2e4a22fd13eb7bc8a8b4b6ae584571422e2ffdb0ccef6",
          "sha1": "492ac55c4970e1fb772c56e7fe95e743962897f8",
          "md5": "876d43595c452d77691e1b32fb117efb"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        }
      ],
      "files": [
        {
          "name": "sqflite_android_release-0.23.aar",
          "url": "sqflite_android_release-0.23.aar",
          "size": 43468,
          "sha512": "bdf2f00eeb27c614972aafa29bfc09af9c76b7132f5d38fe7000a82df52ff272394aa3b846ce4c452f968af81f7c46ce317e7bbe4e80baf12b2e7da29b735ee4",
          "sha256": "c18824bca0d106cfb5c2e4a22fd13eb7bc8a8b4b6ae584571422e2ffdb0ccef6",
          "sha1": "492ac55c4970e1fb772c56e7fe95e743962897f8",
          "md5": "876d43595c452d77691e1b32fb117efb"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sqflite_android_release-0.23-sources.jar",
          "url": "sqflite_android_release-0.23-sources.jar",
          "size": 23906,
          "sha512": "84be2e0f11f6739735214c714fcf25ca7b657afc40b3b54a0f0eff0de0f085cc926571087ab261b90cb6ed1e0be787046b45db4603790b883b119c835c22aa20",
          "sha256": "a127166bbaf1689504c6fc9e5111043a0537dc09ba3ea55a6d743da958ef125a",
          "sha1": "55f721f93f9c468c9d426bc61ff59a393e267750",
          "md5": "3f9cd042a556379914178c3426bed53c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sqflite_android_release-0.23-javadoc.jar",
          "url": "sqflite_android_release-0.23-javadoc.jar",
          "size": 342105,
          "sha512": "c0813f791c8d7806593ee0a17b8bc951e08c4ebca47ec78d278e5759c0dd37cc1c7613b5a422ebb41443bb80d58826446372bd5652a0dbd87c1324b52ff1db14",
          "sha256": "2f7476f6bf3f96d6566152991ffd7d538d39a406ab977b0ec392fa7d4ef08b79",
          "sha1": "987269102b1791cf52f19b96176180493e257552",
          "md5": "c6e55b7a6f6c6097172f7d24edecb07b"
        }
      ]
    }
  ]
}
