{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tekartik.sqflite",
    "module": "sqflite_android_release",
    "version": "0.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        }
      ],
      "files": [
        {
          "name": "sqflite_android_release-0.14.aar",
          "url": "sqflite_android_release-0.14.aar",
          "size": 43468,
          "sha512": "bdf2f00eeb27c614972aafa29bfc09af9c76b7132f5d38fe7000a82df52ff272394aa3b846ce4c452f968af81f7c46ce317e7bbe4e80baf12b2e7da29b735ee4",
          "sha256": "c18824bca0d106cfb5c2e4a22fd13eb7bc8a8b4b6ae584571422e2ffdb0ccef6",
          "sha1": "492ac55c4970e1fb772c56e7fe95e743962897f8",
          "md5": "876d43595c452d77691e1b32fb117efb"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        }
      ],
      "files": [
        {
          "name": "sqflite_android_release-0.14.aar",
          "url": "sqflite_android_release-0.14.aar",
          "size": 43468,
          "sha512": "bdf2f00eeb27c614972aafa29bfc09af9c76b7132f5d38fe7000a82df52ff272394aa3b846ce4c452f968af81f7c46ce317e7bbe4e80baf12b2e7da29b735ee4",
          "sha256": "c18824bca0d106cfb5c2e4a22fd13eb7bc8a8b4b6ae584571422e2ffdb0ccef6",
          "sha1": "492ac55c4970e1fb772c56e7fe95e743962897f8",
          "md5": "876d43595c452d77691e1b32fb117efb"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sqflite_android_release-0.14-sources.jar",
          "url": "sqflite_android_release-0.14-sources.jar",
          "size": 23906,
          "sha512": "84be2e0f11f6739735214c714fcf25ca7b657afc40b3b54a0f0eff0de0f085cc926571087ab261b90cb6ed1e0be787046b45db4603790b883b119c835c22aa20",
          "sha256": "a127166bbaf1689504c6fc9e5111043a0537dc09ba3ea55a6d743da958ef125a",
          "sha1": "55f721f93f9c468c9d426bc61ff59a393e267750",
          "md5": "3f9cd042a556379914178c3426bed53c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sqflite_android_release-0.14-javadoc.jar",
          "url": "sqflite_android_release-0.14-javadoc.jar",
          "size": 342114,
          "sha512": "fb602320e0da7c5ead3fb7c721731af89bbaf31691212c50507c5fbdee21f57a68d291745a43ededeb9acdebd96365333a0e9e4697720078295fdcacdfb23dbe",
          "sha256": "bcb6dc3f7effb478826cc0b6755bbb293a8a90fb824c2cca4171b263eefc9e97",
          "sha1": "c5b0b9be655beac8bdff73d5a83b2b979a3ac52c",
          "md5": "e067424827d7ea8adb861be8f61add5d"
        }
      ]
    }
  ]
}
