{
  "formatVersion": "1.1",
  "component": {
    "group": "com.benjaminabel.vibration",
    "module": "vibration_release",
    "version": "0.24",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        }
      ],
      "files": [
        {
          "name": "vibration_release-0.24.aar",
          "url": "vibration_release-0.24.aar",
          "size": 5444,
          "sha512": "3cf52fc6e1672f179ba08083e0866bc4583f6c0ff06d99d0e4583556917a1ca0ba36557d9817a9766d0e6b872cf5fc322fd1e1ce1bfa26ebbabec0db7c7776fd",
          "sha256": "3f062eb94cf6ddc6db5ae18c9a67832fcfca4215ed1acf903bf297aa82761e01",
          "sha1": "321b699dac63a21bc623ffa85a28b786a85442b9",
          "md5": "ebbd5f774d4a4660626a6cbc37ef2fd7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        }
      ],
      "files": [
        {
          "name": "vibration_release-0.24.aar",
          "url": "vibration_release-0.24.aar",
          "size": 5444,
          "sha512": "3cf52fc6e1672f179ba08083e0866bc4583f6c0ff06d99d0e4583556917a1ca0ba36557d9817a9766d0e6b872cf5fc322fd1e1ce1bfa26ebbabec0db7c7776fd",
          "sha256": "3f062eb94cf6ddc6db5ae18c9a67832fcfca4215ed1acf903bf297aa82761e01",
          "sha1": "321b699dac63a21bc623ffa85a28b786a85442b9",
          "md5": "ebbd5f774d4a4660626a6cbc37ef2fd7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vibration_release-0.24-sources.jar",
          "url": "vibration_release-0.24-sources.jar",
          "size": 3055,
          "sha512": "384eb290f3959fdee7c259a16e1644ce0676709e1319436f231a1522a548ce0da6c9c7cb04a44b1f3456d50b0488a26d7d80341b6469032740a43a3b226217cc",
          "sha256": "70496470796b88fca44d8fc2ef720ac6bec89b83bbfdefe956dd680a981d8ab6",
          "sha1": "daa83f1f05e9c60ae716519b35e89d79487faf04",
          "md5": "6c40e406630f8b8a8285a64427b965be"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vibration_release-0.24-javadoc.jar",
          "url": "vibration_release-0.24-javadoc.jar",
          "size": 265554,
          "sha512": "e21f92fef949048631012f4f5c48f4e9d1789f6634713d12afb4449abe5bf580aa7cd72061f288505f3105a30310b6b31ae4a8e1fa937c4fc2999ce7dfc8f676",
          "sha256": "7dfa9512777284e2c07912dc323c51ad957da17bf01b1d708a5da216ee8d2292",
          "sha1": "2eae9d85be7600cf0f71f5ae92eeecf5f2501cdf",
          "md5": "b785de2ac9c00350a0ebd46aa57b1af6"
        }
      ]
    }
  ]
}
