{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.flutter_platform_alert",
    "module": "flutter_platform_alert_release",
    "version": "0.52",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_platform_alert_release-0.52.aar",
          "url": "flutter_platform_alert_release-0.52.aar",
          "size": 9160,
          "sha512": "39338f3f70951e3e7e67c9a5d270a284a6bcf6900f8f69ee4d7e3fd41dd34a9afa6a234c01a657bb185bba5450cd9c02992efb3d0966edcaffb7f876ccbd0b8b",
          "sha256": "c2eba9d7748bd0bc6459d65a286597355aeea298c747f6001f50804c1fb28435",
          "sha1": "c52d000cdb606ea9dee3641d355fcaabf54a26a7",
          "md5": "7430fb632c1ed9826a681f91efadf923"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.5.20"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_platform_alert_release-0.52.aar",
          "url": "flutter_platform_alert_release-0.52.aar",
          "size": 9160,
          "sha512": "39338f3f70951e3e7e67c9a5d270a284a6bcf6900f8f69ee4d7e3fd41dd34a9afa6a234c01a657bb185bba5450cd9c02992efb3d0966edcaffb7f876ccbd0b8b",
          "sha256": "c2eba9d7748bd0bc6459d65a286597355aeea298c747f6001f50804c1fb28435",
          "sha1": "c52d000cdb606ea9dee3641d355fcaabf54a26a7",
          "md5": "7430fb632c1ed9826a681f91efadf923"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_platform_alert_release-0.52-sources.jar",
          "url": "flutter_platform_alert_release-0.52-sources.jar",
          "size": 2419,
          "sha512": "0f2b22bac756a091326a6764355e2ee2c67d54d95ce2c038b9e91741917938070f40268ef2c8938684fb5110558c645f2617a325818b8f9f3fe7a70eec960812",
          "sha256": "0a5a52767371b2959d622148176f784c3054379097ee746859302933d68e85ad",
          "sha1": "5c714b72591bb9a3298241008d3df5fa6c53b609",
          "md5": "67fcd057752c94dc2ab62b41c059f6c0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_platform_alert_release-0.52-javadoc.jar",
          "url": "flutter_platform_alert_release-0.52-javadoc.jar",
          "size": 262835,
          "sha512": "de1b099745aa07e204c237b29f4069c53bcdc57ee8884f0d6049c82c3247da1cb042a89f0603e93603e821b1560113df8c1070eec2a9c3ff3744a745fa90c047",
          "sha256": "96a0f0d6481920073aa2f6bbd5179887a81717af25e0972938fc80b9ddc8e1fe",
          "sha1": "c42c871962fa95de610d782f3558b805ac940a67",
          "md5": "f55d190abaadad82a153ab6c3156491a"
        }
      ]
    }
  ]
}
