{
  "formatVersion": "1.1",
  "component": {
    "group": "com.fluttercandies.flutter_image_compress",
    "module": "flutter_image_compress_common_release",
    "version": "0.47",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_image_compress_common_release-0.47.aar",
          "url": "flutter_image_compress_common_release-0.47.aar",
          "size": 30359,
          "sha512": "b6b43e3253259d5caa1b3c369b4602f25f70718e15be1553a44a7e940f33e214349044f1afa9a66ed0e3b03dd4294dc423bf9876bb8c745d5c9a5bf5cc4436aa",
          "sha256": "98a0aa6a4d757ea34f53ecaf23da2a2dde174768ebfe319dd7984ad2122c5718",
          "sha1": "00f2e0e2d10553a6d3da56f7bcab00ade8726029",
          "md5": "6b229d6e16be3d16127b31a7b4b63d66"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "androidx.heifwriter",
          "module": "heifwriter",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_image_compress_common_release-0.47.aar",
          "url": "flutter_image_compress_common_release-0.47.aar",
          "size": 30359,
          "sha512": "b6b43e3253259d5caa1b3c369b4602f25f70718e15be1553a44a7e940f33e214349044f1afa9a66ed0e3b03dd4294dc423bf9876bb8c745d5c9a5bf5cc4436aa",
          "sha256": "98a0aa6a4d757ea34f53ecaf23da2a2dde174768ebfe319dd7984ad2122c5718",
          "sha1": "00f2e0e2d10553a6d3da56f7bcab00ade8726029",
          "md5": "6b229d6e16be3d16127b31a7b4b63d66"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_image_compress_common_release-0.47-sources.jar",
          "url": "flutter_image_compress_common_release-0.47-sources.jar",
          "size": 13283,
          "sha512": "9d463a80c9f9155d36af415dfbc87fadb7908f534f56929f46ded2280cbd3951f90518b08d83de17af9eab1bb66723f65b386d3d4df8b2a57dc67105fc8cad56",
          "sha256": "93a28e5f9b7fcb467c45057e584caa01f1eb412c0b4a92b23a49dc0100b4af37",
          "sha1": "8f0422fa7a12db6f03202df46f11b2c7ec84061a",
          "md5": "326cceeddeb7bc0e1af417bf6b15811f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_image_compress_common_release-0.47-javadoc.jar",
          "url": "flutter_image_compress_common_release-0.47-javadoc.jar",
          "size": 351488,
          "sha512": "c3002e5a9b36a7a32da950a9d2964f915f04646fc32c507a0a4479216638ebda3c485e4a03be583dc1be6a9b545d8dd5fb635b93ee1687f39d0d51657058cfa2",
          "sha256": "8cea6c4006c43f81b06599e64be6c60d463d8b531d20eaac3e16a861230f26e4",
          "sha1": "5587d57f1ec2b4da4ebf8633ef4fba9f3047f1b4",
          "md5": "af587ee7c771d61b6eacddb9f2a100f4"
        }
      ]
    }
  ]
}
