{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.FlutterToast",
    "module": "fluttertoast_release",
    "version": "0.31",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        }
      ],
      "files": [
        {
          "name": "fluttertoast_release-0.31.aar",
          "url": "fluttertoast_release-0.31.aar",
          "size": 8612,
          "sha512": "5379e9f553f0fe31bd108a2f6e4e712df819d44b4fd38fcc4f18be8d273cc347022e08d4bdc1cf66b118c410b9d8824c38d77cf7aacec8c51952506dee252d8d",
          "sha256": "1cf5a8977e72973896d686622085422175797c5168f567362940c6b5c251ce29",
          "sha1": "ac9c3a411a5d0a3bbbfa65b8ed639fc96ed367a8",
          "md5": "b464478e32d86befc70195c021fe5069"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "fluttertoast_release-0.31.aar",
          "url": "fluttertoast_release-0.31.aar",
          "size": 8612,
          "sha512": "5379e9f553f0fe31bd108a2f6e4e712df819d44b4fd38fcc4f18be8d273cc347022e08d4bdc1cf66b118c410b9d8824c38d77cf7aacec8c51952506dee252d8d",
          "sha256": "1cf5a8977e72973896d686622085422175797c5168f567362940c6b5c251ce29",
          "sha1": "ac9c3a411a5d0a3bbbfa65b8ed639fc96ed367a8",
          "md5": "b464478e32d86befc70195c021fe5069"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fluttertoast_release-0.31-sources.jar",
          "url": "fluttertoast_release-0.31-sources.jar",
          "size": 3120,
          "sha512": "d9ebc2d9ee6ac43fe9b5cdc36686129ada7224df1bcc4f2f8f28ae624e9a6e94c44a493482daa6e1bf349432624693b6db5a3005ec9eec1715bbe170f4c4d7b6",
          "sha256": "69e1c82573001740c8ccb654af91736acda45261c9d0bcd2bd2ac8b6b62cdb24",
          "sha1": "9522dbaa5a7420975e525cac223d4b1717db7708",
          "md5": "7898eaf3504977619edc6f80d87654f9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fluttertoast_release-0.31-javadoc.jar",
          "url": "fluttertoast_release-0.31-javadoc.jar",
          "size": 262611,
          "sha512": "0f7d7640aa7ebf33bbcf165370c8a1c4189beac5fab9d63ae0428c375a4fda870a2d9c51b0c9a70d806c4ff5da37684b0c7ffd450b070ecd177784c66bb8dc01",
          "sha256": "a8977964c80b61ef5dbb618acaf8c0159fc3d9a3a2c461c6877e3e89b6c817e3",
          "sha1": "46f19dcbb24a40a7cb3887d19de6b3ab5bddaf09",
          "md5": "51660a6209763bd982bd450ec317cf9f"
        }
      ]
    }
  ]
}
