{
  "formatVersion": "1.1",
  "component": {
    "group": "com.lib.flutter_blue_plus",
    "module": "flutter_blue_plus_android_release",
    "version": "0.33",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_blue_plus_android_release-0.33.aar",
          "url": "flutter_blue_plus_android_release-0.33.aar",
          "size": 43723,
          "sha512": "53a9a8394bf8a6e3122bb926201662eca1f83274ffb1bd42f824a6cfa92f523211cd395792a99a3014cd8c4e3dd3b830806ca3761a5c6f0dcd5c2a51fd9fbb4a",
          "sha256": "e75dbceff0e533266f46df89e5f4a26238ee2db0cbeb6e07390789f07aeebde2",
          "sha1": "b9db27bc67a0cfe030fba5250a3c9e8baf493d36",
          "md5": "1007eb817d49cae3395c92195cccdfc8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_blue_plus_android_release-0.33.aar",
          "url": "flutter_blue_plus_android_release-0.33.aar",
          "size": 43723,
          "sha512": "53a9a8394bf8a6e3122bb926201662eca1f83274ffb1bd42f824a6cfa92f523211cd395792a99a3014cd8c4e3dd3b830806ca3761a5c6f0dcd5c2a51fd9fbb4a",
          "sha256": "e75dbceff0e533266f46df89e5f4a26238ee2db0cbeb6e07390789f07aeebde2",
          "sha1": "b9db27bc67a0cfe030fba5250a3c9e8baf493d36",
          "md5": "1007eb817d49cae3395c92195cccdfc8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_blue_plus_android_release-0.33-sources.jar",
          "url": "flutter_blue_plus_android_release-0.33-sources.jar",
          "size": 24315,
          "sha512": "fce1be94efbed45ac642005b70d573a65c465d5a43ec28ebef8ee5331ca93c664e1ee98bbe7c9d27d73d7c7b85306d0f8a4ec1622fd46c0a3763df237c2eb20e",
          "sha256": "9e2028532ad03708a83ed952f177da22b5376e0cd08ac1548350a0067b363d02",
          "sha1": "0949181f9119f5c1e50d9c0a08456c7ac072bd68",
          "md5": "3303658fda0a6cf48caf12ae9a45b94b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_blue_plus_android_release-0.33-javadoc.jar",
          "url": "flutter_blue_plus_android_release-0.33-javadoc.jar",
          "size": 265496,
          "sha512": "1447dd66069dc38075c6ea70c00adf1b5026cdc0dd99ef89d216b1e886ed7c00e6186c07f37dd7b093e3ca044facc8583d53dc579d8ce74e784d3e3d6892c429",
          "sha256": "8018b0b2c2699728f6ca2f4dce47617573ceed919b17f9c244ef9c5f5d3cc4f4",
          "sha1": "4b90731989b1e29713e1ad7c668e88ceab687f90",
          "md5": "7601df2f966f23ffd1bd62e027dd1f5e"
        }
      ]
    }
  ]
}
