{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.yongxin_ring",
    "module": "yongxin_ring_release",
    "version": "0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "yongxin_ring_release-0.2.aar",
          "url": "yongxin_ring_release-0.2.aar",
          "size": 56756,
          "sha512": "bca02e3d66111f6886000b27ef49ac78611e3beb82732c05f957ebf0719837c15b7b55fd24a751a9fe0f2392fb106ca164c92aa6e97ca16b33b0fe22d53052c2",
          "sha256": "21e7a6abac594f7cdf568574e8c6d5df1d3bfb653b7a26febdf68876027facef",
          "sha1": "b79d72fb958c233c2eff422fbd524c16a4edaa95",
          "md5": "270d5208c23156c4bd359abaea7b7fdf"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        },
        {
          "group": "com.lm",
          "module": "chipletRing",
          "version": {
            "requires": "1.0.72"
          }
        },
        {
          "group": "androidx.localbroadcastmanager",
          "module": "localbroadcastmanager",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.greenrobot",
          "module": "greendao",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "org.ligboy.retrofit2",
          "module": "converter-fastjson-android",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "24.0.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "com.zhy",
          "module": "okhttputils",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "yongxin_ring_release-0.2.aar",
          "url": "yongxin_ring_release-0.2.aar",
          "size": 56756,
          "sha512": "bca02e3d66111f6886000b27ef49ac78611e3beb82732c05f957ebf0719837c15b7b55fd24a751a9fe0f2392fb106ca164c92aa6e97ca16b33b0fe22d53052c2",
          "sha256": "21e7a6abac594f7cdf568574e8c6d5df1d3bfb653b7a26febdf68876027facef",
          "sha1": "b79d72fb958c233c2eff422fbd524c16a4edaa95",
          "md5": "270d5208c23156c4bd359abaea7b7fdf"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "yongxin_ring_release-0.2-sources.jar",
          "url": "yongxin_ring_release-0.2-sources.jar",
          "size": 11716,
          "sha512": "72b960c9e147d6751bf0669f791b55ed0437dab4cd7f94bc36622decba04bf66ed789a390a4e7ce5733f4add47a56fb6fa56068e2a89cb97c943d6a6e2e18c62",
          "sha256": "033e64ff4dd55c4a7525008346496720018969229431433d893721aa72e67963",
          "sha1": "ab6f36f0c28851bee0243bfe4b278bc21bdd4f39",
          "md5": "022da9b50767e388248cef9d55f66bd2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "yongxin_ring_release-0.2-javadoc.jar",
          "url": "yongxin_ring_release-0.2-javadoc.jar",
          "size": 301292,
          "sha512": "26adde75843abf6d82a4575de22fd4d790eadf0f938c6837bcfa70d7e976b5a988edf37f7ed35a92d6e990a724f4ee67c2eea68187f7ab6afc095ffdd8547683",
          "sha256": "2574d95d3e71d05353a10508acb963c2a4419f538d7e6c5803b49d2adfc3eabe",
          "sha1": "fbb71a0916db8708150fed548366ad9d29213564",
          "md5": "a3559f1018e20373e594c6dadfaf1b67"
        }
      ]
    }
  ]
}
