{
  "formatVersion": "1.1",
  "component": {
    "group": "com.baseflow.permissionhandler",
    "module": "permission_handler_android_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        }
      ],
      "files": [
        {
          "name": "permission_handler_android_debug-1.0.aar",
          "url": "permission_handler_android_debug-1.0.aar",
          "size": 27669,
          "sha512": "2e430a82dcb97eb0fb8b0345ee2ef3802d712be12cde18fa49716c4a31675e018a7527e863044bb5578b8af4eff8ac9a34b2ac32ebe05ece0a98cf9c61beb2a6",
          "sha256": "c2ab115add0ada2bef33a1eec1e8747ed0ca985f6794835480b04602c97d8f3a",
          "sha1": "cdf02b1b53a98292c3572948a2e22b03e73684c4",
          "md5": "6672c2a644e6a016be8be09296f8c70e"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        }
      ],
      "files": [
        {
          "name": "permission_handler_android_debug-1.0.aar",
          "url": "permission_handler_android_debug-1.0.aar",
          "size": 27669,
          "sha512": "2e430a82dcb97eb0fb8b0345ee2ef3802d712be12cde18fa49716c4a31675e018a7527e863044bb5578b8af4eff8ac9a34b2ac32ebe05ece0a98cf9c61beb2a6",
          "sha256": "c2ab115add0ada2bef33a1eec1e8747ed0ca985f6794835480b04602c97d8f3a",
          "sha1": "cdf02b1b53a98292c3572948a2e22b03e73684c4",
          "md5": "6672c2a644e6a016be8be09296f8c70e"
        }
      ]
    },
    {
      "name": "debugVariantDebugSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "permission_handler_android_debug-1.0-sources.jar",
          "url": "permission_handler_android_debug-1.0-sources.jar",
          "size": 18178,
          "sha512": "f75ef3dcffb564829cd6a38e38286f4980d44f582e5fe3c185db3c0082da1423393c92de6556956c158928669790cb4220d56c0e2eee1de390df6055fdef5018",
          "sha256": "b1c5b90d8a5e74eb10437a278638751fb12e6d863b14b6225eb7aef1941cb434",
          "sha1": "04e0db92f72a5112e79b561b446c85b4d4e32e2c",
          "md5": "6c3c580a555a61e926892f7155fcdfd2"
        }
      ]
    },
    {
      "name": "debugVariantDebugJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "permission_handler_android_debug-1.0-javadoc.jar",
          "url": "permission_handler_android_debug-1.0-javadoc.jar",
          "size": 264570,
          "sha512": "3be6887e1c3eb6f4f5cc3c29d78d6fc7e76aa119efbe66eddc845188e75d33b44b42e61299641a6859221c9d35855a1e2f60318a79a1717fc60fedcf3e4aca06",
          "sha256": "93e2c4a268e21e2976e08cb0730b11145ae6c5ed6cd62d38110b22c722a3440c",
          "sha1": "25381a46620546bf71b0cbc8dee1933cc4558d5a",
          "md5": "53a8a2bb6bbaa57d24380ae1dd3da35c"
        }
      ]
    }
  ]
}
