{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.inapppurchase",
    "module": "in_app_purchase_android_release",
    "version": "0.30",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        }
      ],
      "files": [
        {
          "name": "in_app_purchase_android_release-0.30.aar",
          "url": "in_app_purchase_android_release-0.30.aar",
          "size": 110436,
          "sha512": "b5a113fccb69fb585e16d6aef7a4f5e508e147fdf5cb8c8d9710165a7ebb1ffd7b2e59044509c3472189de6f3ad18e4d7aa3dc325f822a1b6314e661b61cfab1",
          "sha256": "afc9bf1d9bc07d1a99f4e2ab90ddc52e7137029fc02a14dcbd40e47dc818c880",
          "sha1": "480ae1d547b4f6318296f5f590f86dac25f83155",
          "md5": "d47762a71b052bac49b099a00112683d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "com.android.billingclient",
          "module": "billing",
          "version": {
            "requires": "7.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "in_app_purchase_android_release-0.30.aar",
          "url": "in_app_purchase_android_release-0.30.aar",
          "size": 110436,
          "sha512": "b5a113fccb69fb585e16d6aef7a4f5e508e147fdf5cb8c8d9710165a7ebb1ffd7b2e59044509c3472189de6f3ad18e4d7aa3dc325f822a1b6314e661b61cfab1",
          "sha256": "afc9bf1d9bc07d1a99f4e2ab90ddc52e7137029fc02a14dcbd40e47dc818c880",
          "sha1": "480ae1d547b4f6318296f5f590f86dac25f83155",
          "md5": "d47762a71b052bac49b099a00112683d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "in_app_purchase_android_release-0.30-sources.jar",
          "url": "in_app_purchase_android_release-0.30-sources.jar",
          "size": 25611,
          "sha512": "224e14deb1e3b31bfd89bb1c67d5174994e7da999ae61413d0717c7771e544be861d562d8eebeb59bcfbaced4f03c50d0dd602115c628812982934b06ba9ebcb",
          "sha256": "9acfd5214ac71ecd1d693ab9d2e6cfc40208bfa096cb8fd75b2c286862d279b4",
          "sha1": "951a82e3bf3c01239beacb1c2e2230b7d46b3497",
          "md5": "bb6c7516e99f919afffe135a754ed2d1"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "in_app_purchase_android_release-0.30-javadoc.jar",
          "url": "in_app_purchase_android_release-0.30-javadoc.jar",
          "size": 498345,
          "sha512": "f91808feeaee8b30a31f4a4485cdd52b176d8978aa08e5a6344e39c068900aaf6a359b7e815ca220ae2789dd26f4dcb229193b07627be82ba3d93f8b26faba78",
          "sha256": "601081af0d334ec64f15cdba0a4c475429a75f6f42a30d1522b55e899399df75",
          "sha1": "a6d447839bf7cebe019f126e8d6f26d4df2d693f",
          "md5": "6d079185974b924476d9802d2c35025b"
        }
      ]
    }
  ]
}
