{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.firebaseperformance",
    "module": "firebase_performance_release",
    "version": "0.43",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.core",
          "module": "firebase_core_release",
          "version": {
            "requires": "0.43"
          }
        }
      ],
      "files": [
        {
          "name": "firebase_performance_release-0.43.aar",
          "url": "firebase_performance_release-0.43.aar",
          "size": 8724,
          "sha512": "127d79e86d90cb8bca4c5f359cb3b7a46c2629d648b7214ecc9174488cdfd8fa06aca4ee2df20e6150360aa71c247badf755826b7955c307029d5d6646c864e9",
          "sha256": "cdbbb94919cca22abd28362c05d074407fbe3ceee7edf7a6c85da6ab42ae5b92",
          "sha1": "fa4202a09134baf0e1f0ded85cd17f2d1f1ae6ac",
          "md5": "c6eb8f4229ff42e54d26fd7396dcfad5"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-bom",
          "version": {
            "requires": "33.11.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-perf"
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.core",
          "module": "firebase_core_release",
          "version": {
            "requires": "0.43"
          }
        }
      ],
      "files": [
        {
          "name": "firebase_performance_release-0.43.aar",
          "url": "firebase_performance_release-0.43.aar",
          "size": 8724,
          "sha512": "127d79e86d90cb8bca4c5f359cb3b7a46c2629d648b7214ecc9174488cdfd8fa06aca4ee2df20e6150360aa71c247badf755826b7955c307029d5d6646c864e9",
          "sha256": "cdbbb94919cca22abd28362c05d074407fbe3ceee7edf7a6c85da6ab42ae5b92",
          "sha1": "fa4202a09134baf0e1f0ded85cd17f2d1f1ae6ac",
          "md5": "c6eb8f4229ff42e54d26fd7396dcfad5"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "firebase_performance_release-0.43-sources.jar",
          "url": "firebase_performance_release-0.43-sources.jar",
          "size": 4416,
          "sha512": "fba5daa26f6d62a7a8ff7046e7884ae6226be7412ef275e7a35dca78c1b504caa21d3b92e5a7bf471f51e9fb7a6be9a71365eba8b8dff9b33e9eedf40bb2d8eb",
          "sha256": "71dfa838fec053e41f73a2efdea999fab1e372cd1ff8d6d5d58643fa2e9ebb52",
          "sha1": "f34f6b23b162908566c21ecfcccbf69fa9e2c14c",
          "md5": "ac96771d4a0151e4a8c0d4170deb5fd7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "firebase_performance_release-0.43-javadoc.jar",
          "url": "firebase_performance_release-0.43-javadoc.jar",
          "size": 273484,
          "sha512": "a17b8bd6a2532246b3b0fd217b9bae9914218824164ce1ee2f52f5703b2a199e53ddb51248ed49ade1d33ec6e3e06d1fafbe55b5f595cc17c754aff388a26d65",
          "sha256": "afe9fcfb60132fb93b59af7d8a61e367b91ed630d700c64983f70d7f4c0bef07",
          "sha1": "811770e791da460f9e40932523801472ecec443a",
          "md5": "acbc5e704a1bbb1c81be90e4eb56bd92"
        }
      ]
    }
  ]
}
