{
  "formatVersion": "1.1",
  "component": {
    "group": "com.lib.flutter_blue_plus",
    "module": "flutter_blue_plus_android_release",
    "version": "0.47",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_blue_plus_android_release-0.47.aar",
          "url": "flutter_blue_plus_android_release-0.47.aar",
          "size": 43723,
          "sha512": "53a9a8394bf8a6e3122bb926201662eca1f83274ffb1bd42f824a6cfa92f523211cd395792a99a3014cd8c4e3dd3b830806ca3761a5c6f0dcd5c2a51fd9fbb4a",
          "sha256": "e75dbceff0e533266f46df89e5f4a26238ee2db0cbeb6e07390789f07aeebde2",
          "sha1": "b9db27bc67a0cfe030fba5250a3c9e8baf493d36",
          "md5": "1007eb817d49cae3395c92195cccdfc8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_blue_plus_android_release-0.47.aar",
          "url": "flutter_blue_plus_android_release-0.47.aar",
          "size": 43723,
          "sha512": "53a9a8394bf8a6e3122bb926201662eca1f83274ffb1bd42f824a6cfa92f523211cd395792a99a3014cd8c4e3dd3b830806ca3761a5c6f0dcd5c2a51fd9fbb4a",
          "sha256": "e75dbceff0e533266f46df89e5f4a26238ee2db0cbeb6e07390789f07aeebde2",
          "sha1": "b9db27bc67a0cfe030fba5250a3c9e8baf493d36",
          "md5": "1007eb817d49cae3395c92195cccdfc8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_blue_plus_android_release-0.47-sources.jar",
          "url": "flutter_blue_plus_android_release-0.47-sources.jar",
          "size": 24315,
          "sha512": "fce1be94efbed45ac642005b70d573a65c465d5a43ec28ebef8ee5331ca93c664e1ee98bbe7c9d27d73d7c7b85306d0f8a4ec1622fd46c0a3763df237c2eb20e",
          "sha256": "9e2028532ad03708a83ed952f177da22b5376e0cd08ac1548350a0067b363d02",
          "sha1": "0949181f9119f5c1e50d9c0a08456c7ac072bd68",
          "md5": "3303658fda0a6cf48caf12ae9a45b94b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_blue_plus_android_release-0.47-javadoc.jar",
          "url": "flutter_blue_plus_android_release-0.47-javadoc.jar",
          "size": 265498,
          "sha512": "cb97611bf63952d04299cf8d6358d52976325eb5581bc08461181a45d0337f8902b2402c73356449c499c9ec2a466e1ba8c34a865a51651f73e761dc27d30ff1",
          "sha256": "378f22e743fbcda0789ddb4f4b795819be333e87a845c7546a710e39af2d0f83",
          "sha1": "9c418e9bf4ed6b9998be468bff22e188055b51f2",
          "md5": "48bf7e40d41b706ad0dab1c806e2cb28"
        }
      ]
    }
  ]
}
