{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.fluttercommunity.plus.device_info",
    "module": "device_info_plus_release",
    "version": "0.61",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        }
      ],
      "files": [
        {
          "name": "device_info_plus_release-0.61.aar",
          "url": "device_info_plus_release-0.61.aar",
          "size": 6932,
          "sha512": "4749f56d78d92dc11eb04d805e655623885a8f6549ed43c58733518105d694890c5251095aff3f31e199c56939a5b8e9329576f0fbc68b7e3d983250b1e07b38",
          "sha256": "6941f2d3701d71d2c6bec48120bc0e1dbc0d8f9b02e081e1c4cb9c60015f4542",
          "sha1": "cc4323b90a02562756d2537851e2731862a918e4",
          "md5": "a0bd92911fc14788066a1dc2e71ec573"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.22"
          }
        }
      ],
      "files": [
        {
          "name": "device_info_plus_release-0.61.aar",
          "url": "device_info_plus_release-0.61.aar",
          "size": 6932,
          "sha512": "4749f56d78d92dc11eb04d805e655623885a8f6549ed43c58733518105d694890c5251095aff3f31e199c56939a5b8e9329576f0fbc68b7e3d983250b1e07b38",
          "sha256": "6941f2d3701d71d2c6bec48120bc0e1dbc0d8f9b02e081e1c4cb9c60015f4542",
          "sha1": "cc4323b90a02562756d2537851e2731862a918e4",
          "md5": "a0bd92911fc14788066a1dc2e71ec573"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "device_info_plus_release-0.61-sources.jar",
          "url": "device_info_plus_release-0.61-sources.jar",
          "size": 2976,
          "sha512": "b0a16c5d099d1a6d3f96d453ca4f34aa2b138d0729fd675fa4dadff9f54e169514b31bd5586b5d4fb388059df0d5e5ff8ceeeec9214322cced8b305c5d67afb3",
          "sha256": "1160189e3c750bbf50affba28a4dbf0fc1216e815a1f01a3d1d9dd17958f37ab",
          "sha1": "b1f985fbb38747f8f626c4988380b4847ff05db6",
          "md5": "7effa257187ed4394bf3919149a7d9e8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "device_info_plus_release-0.61-javadoc.jar",
          "url": "device_info_plus_release-0.61-javadoc.jar",
          "size": 260825,
          "sha512": "a581d16442d9a3b421f1328255d081b8a0ca401ad8734eaf0903166298229194e504288cb912ebd8e7acaa6af0ee7d5b05cc82d3a07e1aa1e52dbb84fd81fd9c",
          "sha256": "41825f7c6cd40d19876146a9d8ed9f2f6d0f1fd3c1f36a79561b6f1764fe03ab",
          "sha1": "558e5714f463a95f3ef3f075b3503fae12fd9be4",
          "md5": "e66987ee26924bb5e9af777b4b75bd03"
        }
      ]
    }
  ]
}
