{
  "formatVersion": "1.1",
  "component": {
    "group": "eu.simonbinder.sqlite3_flutter_libs",
    "module": "sqlite3_flutter_libs_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        }
      ],
      "files": [
        {
          "name": "sqlite3_flutter_libs_debug-1.0.aar",
          "url": "sqlite3_flutter_libs_debug-1.0.aar",
          "size": 2708,
          "sha512": "0ce9d58627fdbc71c32d3566c9c18d6d5e28b98b44b2f836d50f7c07672f0867b928593d8c2e8b4a900b616aeadb2dece3250e198ad2ec407b724aa40fe1ed84",
          "sha256": "69524398551d07beaaabc732932cae68e760d3279b686e98f20d11fcd8714881",
          "sha1": "a86a4c7a599a98a22d9bd27da8c6dfd6ca347896",
          "md5": "36978d0bd1303d1348cef78d86a682de"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        },
        {
          "group": "eu.simonbinder",
          "module": "sqlite3-native-library",
          "version": {
            "requires": "3.50.1"
          }
        }
      ],
      "files": [
        {
          "name": "sqlite3_flutter_libs_debug-1.0.aar",
          "url": "sqlite3_flutter_libs_debug-1.0.aar",
          "size": 2708,
          "sha512": "0ce9d58627fdbc71c32d3566c9c18d6d5e28b98b44b2f836d50f7c07672f0867b928593d8c2e8b4a900b616aeadb2dece3250e198ad2ec407b724aa40fe1ed84",
          "sha256": "69524398551d07beaaabc732932cae68e760d3279b686e98f20d11fcd8714881",
          "sha1": "a86a4c7a599a98a22d9bd27da8c6dfd6ca347896",
          "md5": "36978d0bd1303d1348cef78d86a682de"
        }
      ]
    },
    {
      "name": "debugVariantDebugSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sqlite3_flutter_libs_debug-1.0-sources.jar",
          "url": "sqlite3_flutter_libs_debug-1.0-sources.jar",
          "size": 1462,
          "sha512": "72a2ddbe506e1d6e2730f00e041dea0f9c617b03138b525c6b88e0ef701b98a66fd1d6b75cd9b22a8ea26fce3e98b7a69945f10593749c1593670c595f78bb9d",
          "sha256": "65510b847d970f272c2935de5b14f0489bd719bee3541f208bc72ba20e42e293",
          "sha1": "cc4891fa470b28d66912771a1d113c24bb411027",
          "md5": "78f2d9b7b35831e0a4e0ebe0e97d4aa4"
        }
      ]
    },
    {
      "name": "debugVariantDebugJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sqlite3_flutter_libs_debug-1.0-javadoc.jar",
          "url": "sqlite3_flutter_libs_debug-1.0-javadoc.jar",
          "size": 262083,
          "sha512": "203ee3752cf2d33eae5292be3cc7a76ea036eae7c4bae7c66c87aaacd161a3265d97dedebff7f247dd2226dd861f7181e9cdf5bed87d3797f4e682b568965249",
          "sha256": "8d6df2bf7928cbcae15f0afc4b91aec921c01605de7c7467b12f27ac7f2479c8",
          "sha1": "7c8d7b0246dbe1bbd9e047451893b589d0507022",
          "md5": "c42c317186f3c59a334f2e81be983b02"
        }
      ]
    }
  ]
}
