{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.imagepicker",
    "module": "image_picker_android_release",
    "version": "0.22",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        }
      ],
      "files": [
        {
          "name": "image_picker_android_release-0.22.aar",
          "url": "image_picker_android_release-0.22.aar",
          "size": 70174,
          "sha512": "e661e3d95510f5a01304a86bddc0b2a0deae8adf35ea52c8b755f8c229583f0ef25280ebd23582d7c7497c07071470d706f6b5c76dbd7cb82e2370b34ad3d92b",
          "sha256": "4363388520a4bd46490e4d55f443dd86af2db28f4f0c8ad898e4fc22dd71b48a",
          "sha1": "af4e3bb1c7fba6bfca55908e4a5cdef2934f1cfe",
          "md5": "a291a73e1243c19995b5c5a7ed970138"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.7"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_release",
          "version": {
            "requires": "0.22"
          }
        }
      ],
      "files": [
        {
          "name": "image_picker_android_release-0.22.aar",
          "url": "image_picker_android_release-0.22.aar",
          "size": 70174,
          "sha512": "e661e3d95510f5a01304a86bddc0b2a0deae8adf35ea52c8b755f8c229583f0ef25280ebd23582d7c7497c07071470d706f6b5c76dbd7cb82e2370b34ad3d92b",
          "sha256": "4363388520a4bd46490e4d55f443dd86af2db28f4f0c8ad898e4fc22dd71b48a",
          "sha1": "af4e3bb1c7fba6bfca55908e4a5cdef2934f1cfe",
          "md5": "a291a73e1243c19995b5c5a7ed970138"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "image_picker_android_release-0.22-sources.jar",
          "url": "image_picker_android_release-0.22-sources.jar",
          "size": 26801,
          "sha512": "c75dec79aa43394ef7c9e350d56066bbd21d36a46b717f6379bdf096f79c40faa20470702479ec8d0832930ede6d201aee0984784b5598a7ffe8d3f4944281e9",
          "sha256": "e1cb1632d99d19497525667666244470ff11af62a911cdcd912f1f392efab9c0",
          "sha1": "818529d659856ccd5698584039f48cc46a38b6dc",
          "md5": "700b44a0d333feea78b3447fb2daf558"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "image_picker_android_release-0.22-javadoc.jar",
          "url": "image_picker_android_release-0.22-javadoc.jar",
          "size": 383599,
          "sha512": "1a637894679b84053436f1e87df5a533130520a802db893209eed1cd0bcd1c6e9f6ebc3023aeb94ebb461122b362b003f12eb6cec1531acad64867b022e3e83c",
          "sha256": "5a2907311a6b6339d272f29cbf6807aa4671417f0fc27ce7dd38fa0ebf51c032",
          "sha1": "6a62dadc7c5aba26fdc1a87e1a95002a3dbea0e9",
          "md5": "47dc56528b3513889d54908e8f152cba"
        }
      ]
    }
  ]
}
