{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.fluttercommunity.plus.share",
    "module": "share_plus_release",
    "version": "0.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        }
      ],
      "files": [
        {
          "name": "share_plus_release-0.21.aar",
          "url": "share_plus_release-0.21.aar",
          "size": 18489,
          "sha512": "d92d30a4699abc871550fe0281a12146ac3531e09621da504866d9d30f38ea7f9bf7835ed624258e459eb047b8051b5dddb2f20f2a91212745d60b7b39d98938",
          "sha256": "c4f4b9eddf70e99443ae5799f7a0c2357e16620198ffacf33b9cdf80c56b5631",
          "sha1": "5120431a3c2ccdc07022f88aaf6cd8ae2e2209d5",
          "md5": "09b0c8dceba778116907892d3ea510cd"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.22"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.2"
          }
        }
      ],
      "files": [
        {
          "name": "share_plus_release-0.21.aar",
          "url": "share_plus_release-0.21.aar",
          "size": 18489,
          "sha512": "d92d30a4699abc871550fe0281a12146ac3531e09621da504866d9d30f38ea7f9bf7835ed624258e459eb047b8051b5dddb2f20f2a91212745d60b7b39d98938",
          "sha256": "c4f4b9eddf70e99443ae5799f7a0c2357e16620198ffacf33b9cdf80c56b5631",
          "sha1": "5120431a3c2ccdc07022f88aaf6cd8ae2e2209d5",
          "md5": "09b0c8dceba778116907892d3ea510cd"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "share_plus_release-0.21-sources.jar",
          "url": "share_plus_release-0.21-sources.jar",
          "size": 7549,
          "sha512": "1a5b96be106d4c0b6b444f86b82bba55d669c339a90ba0f900d68ea65d921fa7a13717eda480ae1bfc80ac5770de5b08ae156f78ac24cb2940d803150c509048",
          "sha256": "00a661206911b35ef1eb9da74874f6bd4a344ab73594284512d33d70d009ac9e",
          "sha1": "d2b61c8108b4c3fbc286ac3313656ab3fd693559",
          "md5": "aaef7fecc35bf97193158fde6d1c85e8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "share_plus_release-0.21-javadoc.jar",
          "url": "share_plus_release-0.21-javadoc.jar",
          "size": 283915,
          "sha512": "aa38d2fdd892e82233a8ed38615a8661d44b7a672a25db509f1de6558cf4e6233fb972e0490eb4fd275bb0798e4db19507c37751771e0d090715dee88aae9267",
          "sha256": "b49f892f6b88c1de6a7a563feede5cc22bf860a93a51e86638b84fc2908baf39",
          "sha1": "09d021c604e6a517f463a49f720ee181835fbe2e",
          "md5": "af7609522269e43288641e9db0bfa3c2"
        }
      ]
    }
  ]
}
