{
  "formatVersion": "1.1",
  "component": {
    "group": "com.aboutyou.dart_packages.sign_in_with_apple",
    "module": "sign_in_with_apple_release",
    "version": "0.64",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        }
      ],
      "files": [
        {
          "name": "sign_in_with_apple_release-0.64.aar",
          "url": "sign_in_with_apple_release-0.64.aar",
          "size": 8194,
          "sha512": "d8ef25bf12a5af32557beba219afcde7856084240b1e3223541192d98666b23dd94688cc15bf953a6b0234d671f8af5c42b64a3077a0b40134bbf5dde268b1aa",
          "sha256": "8c169b3b032f679340a8a7e128db4be66c79a53314b423359dbf113d59c6ba87",
          "sha1": "31c60e58356281b233c2218f365e219bf511e874",
          "md5": "dfd7bc364693529c7af6651393175155"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "sign_in_with_apple_release-0.64.aar",
          "url": "sign_in_with_apple_release-0.64.aar",
          "size": 8194,
          "sha512": "d8ef25bf12a5af32557beba219afcde7856084240b1e3223541192d98666b23dd94688cc15bf953a6b0234d671f8af5c42b64a3077a0b40134bbf5dde268b1aa",
          "sha256": "8c169b3b032f679340a8a7e128db4be66c79a53314b423359dbf113d59c6ba87",
          "sha1": "31c60e58356281b233c2218f365e219bf511e874",
          "md5": "dfd7bc364693529c7af6651393175155"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sign_in_with_apple_release-0.64-sources.jar",
          "url": "sign_in_with_apple_release-0.64-sources.jar",
          "size": 2730,
          "sha512": "232813b66653332be1825dda86c44197be6a6e5c4db974c29b5e382607c23c3453837625416f9ae13f991ba92f998f99dc25155e699a146881cd86e42431b316",
          "sha256": "3f74fc332e872fbcfdc3245f838f6f2e4704e5b0c6a0c865417757fad32ab9b4",
          "sha1": "227ee9e1b8ad1d2663b181163fd2a12db200cd6a",
          "md5": "57be615d4366529cd2aa5385e32ef800"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sign_in_with_apple_release-0.64-javadoc.jar",
          "url": "sign_in_with_apple_release-0.64-javadoc.jar",
          "size": 311964,
          "sha512": "81ad4341daceceace9523bc93cd85b5a40752bab22a661b669c481b844ddec9810b7c847b328aacd28e6be07ee61496587d9fc5db8463637c7a46972f454cc79",
          "sha256": "1d8b319815102b07b94b7c163922d4d91b33ea223a6cc6ebf5f55050fab75eb8",
          "sha1": "b656b73caf0b0ea8cc434d63044de571b837699a",
          "md5": "ef7a5d2e42fc238f16600a44aa1cda59"
        }
      ]
    }
  ]
}
