{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.yongxin_ring",
    "module": "yongxin_ring_release",
    "version": "0.36",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "yongxin_ring_release-0.36.aar",
          "url": "yongxin_ring_release-0.36.aar",
          "size": 54896,
          "sha512": "e828936636671edeb48e5167695b3fd2009745de63059dfd130639226975683c4fce6babd1bf8e475d70f7883a0b576ec1b3a6e0130a34b6605cd447b964efea",
          "sha256": "f2f24b406c5e0f9104bdfa70fcc1c2316003ef177b64e9e0472522e97abcb187",
          "sha1": "614f921c89ba3ba3b72b05159f9d7bd377a15dbd",
          "md5": "54fdd16fbbf8ed62072f163a874293e1"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        },
        {
          "group": "com.lm",
          "module": "chipletRing",
          "version": {
            "requires": "1.1.14"
          }
        },
        {
          "group": "androidx.localbroadcastmanager",
          "module": "localbroadcastmanager",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.greenrobot",
          "module": "greendao",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "org.ligboy.retrofit2",
          "module": "converter-fastjson-android",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "24.0.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "com.zhy",
          "module": "okhttputils",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "com.tenmeter.smlibrary",
          "module": "tenmeter",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "yongxin_ring_release-0.36.aar",
          "url": "yongxin_ring_release-0.36.aar",
          "size": 54896,
          "sha512": "e828936636671edeb48e5167695b3fd2009745de63059dfd130639226975683c4fce6babd1bf8e475d70f7883a0b576ec1b3a6e0130a34b6605cd447b964efea",
          "sha256": "f2f24b406c5e0f9104bdfa70fcc1c2316003ef177b64e9e0472522e97abcb187",
          "sha1": "614f921c89ba3ba3b72b05159f9d7bd377a15dbd",
          "md5": "54fdd16fbbf8ed62072f163a874293e1"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "yongxin_ring_release-0.36-sources.jar",
          "url": "yongxin_ring_release-0.36-sources.jar",
          "size": 15572,
          "sha512": "12f4b00d56da1398124535107f42c4e5b5a67694e40f36b673fce36fbf02fcfde617d63cd0f30a746f71236aa857a721cd08d8745944699257b35451b3620d15",
          "sha256": "07b67529dae2d0fdc87321a866af01b8e9332c9b6150555f21d434b6e9742cf6",
          "sha1": "e2bb7c12bf10a2dc6f84205a2ef765d8228dec2b",
          "md5": "7361e4c0f3c83f2b79376c9d66a67aad"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "yongxin_ring_release-0.36-javadoc.jar",
          "url": "yongxin_ring_release-0.36-javadoc.jar",
          "size": 301409,
          "sha512": "d0c07da8467af65ad8067781dd727c62f75bcb8b3d2f603523792e7384a2abab87f89b0482d02962fcf7ee016482ecadca6f3fb867000318eb6112bb8529e6ba",
          "sha256": "7d4cc4b82f3eb68b12a7afcb756dc3a9a9f91d8d1d61b4ce6725e616a824fc29",
          "sha1": "dcf5bc85e85e637e61a7becf9dddc9b4a12eb2c8",
          "md5": "74f47730d2dcd66b98a5276b41f2029f"
        }
      ]
    }
  ]
}
