{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.urllauncher",
    "module": "url_launcher_android_release",
    "version": "0.16",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        }
      ],
      "files": [
        {
          "name": "url_launcher_android_release-0.16.aar",
          "url": "url_launcher_android_release-0.16.aar",
          "size": 22203,
          "sha512": "a87a0ba546a24738e8a8908141c27fa7f84ef88e819801ef147419cd544fc59f924677385cbbacc4429829ab6308f03d0a21a568d983e4835142f1d759b1821e",
          "sha256": "386e45d1097e6dd5ca92f416a7af564d03c6e1f59a937f43f06d332037ab3903",
          "sha1": "e267ef296c8591f5954f777fc8d57f4ceb13a93c",
          "md5": "f5aef924ffde406c3027581bbff91c19"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "url_launcher_android_release-0.16.aar",
          "url": "url_launcher_android_release-0.16.aar",
          "size": 22203,
          "sha512": "a87a0ba546a24738e8a8908141c27fa7f84ef88e819801ef147419cd544fc59f924677385cbbacc4429829ab6308f03d0a21a568d983e4835142f1d759b1821e",
          "sha256": "386e45d1097e6dd5ca92f416a7af564d03c6e1f59a937f43f06d332037ab3903",
          "sha1": "e267ef296c8591f5954f777fc8d57f4ceb13a93c",
          "md5": "f5aef924ffde406c3027581bbff91c19"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "url_launcher_android_release-0.16-sources.jar",
          "url": "url_launcher_android_release-0.16-sources.jar",
          "size": 9298,
          "sha512": "0262c8612c2cf645d08303916c89d49e1a667d186c0826f46f0eff0d61045226c814a65487016a126b5f773f03f7c28f6e25abb52e9251b959efc2623ae35bb7",
          "sha256": "d335bd3d73a99eedfbffabc15e6ec40b541c3ed458ad8098399e5e8fb48856c4",
          "sha1": "752f364f32d032ede33f3a9148ffa8a94633685c",
          "md5": "85f195d617dd46caec31c43d0b357f1d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "url_launcher_android_release-0.16-javadoc.jar",
          "url": "url_launcher_android_release-0.16-javadoc.jar",
          "size": 331569,
          "sha512": "2953fb7f7bfb8c24d4bb07220b858cb1eacd5c6fedc0ecd74c44144dcef5fd2a9346a868866b8f7f498c0194f3a8254eb0ac7444fc472ba9f7ef162192fb5ceb",
          "sha256": "9a6512f4130da5531bf4ca4b0db9a4cf134d9b4f3370f3fd184ca62a79fdb005",
          "sha1": "0914c5e6a37ef11bb6356782c649f84e55b50b52",
          "md5": "1893dcd449a6c228a4d7f6ffa11195f9"
        }
      ]
    }
  ]
}
