{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.fluttercommunity.plus.device_info",
    "module": "device_info_plus_release",
    "version": "0.59",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        }
      ],
      "files": [
        {
          "name": "device_info_plus_release-0.59.aar",
          "url": "device_info_plus_release-0.59.aar",
          "size": 6932,
          "sha512": "4749f56d78d92dc11eb04d805e655623885a8f6549ed43c58733518105d694890c5251095aff3f31e199c56939a5b8e9329576f0fbc68b7e3d983250b1e07b38",
          "sha256": "6941f2d3701d71d2c6bec48120bc0e1dbc0d8f9b02e081e1c4cb9c60015f4542",
          "sha1": "cc4323b90a02562756d2537851e2731862a918e4",
          "md5": "a0bd92911fc14788066a1dc2e71ec573"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.22"
          }
        }
      ],
      "files": [
        {
          "name": "device_info_plus_release-0.59.aar",
          "url": "device_info_plus_release-0.59.aar",
          "size": 6932,
          "sha512": "4749f56d78d92dc11eb04d805e655623885a8f6549ed43c58733518105d694890c5251095aff3f31e199c56939a5b8e9329576f0fbc68b7e3d983250b1e07b38",
          "sha256": "6941f2d3701d71d2c6bec48120bc0e1dbc0d8f9b02e081e1c4cb9c60015f4542",
          "sha1": "cc4323b90a02562756d2537851e2731862a918e4",
          "md5": "a0bd92911fc14788066a1dc2e71ec573"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "device_info_plus_release-0.59-sources.jar",
          "url": "device_info_plus_release-0.59-sources.jar",
          "size": 2976,
          "sha512": "b0a16c5d099d1a6d3f96d453ca4f34aa2b138d0729fd675fa4dadff9f54e169514b31bd5586b5d4fb388059df0d5e5ff8ceeeec9214322cced8b305c5d67afb3",
          "sha256": "1160189e3c750bbf50affba28a4dbf0fc1216e815a1f01a3d1d9dd17958f37ab",
          "sha1": "b1f985fbb38747f8f626c4988380b4847ff05db6",
          "md5": "7effa257187ed4394bf3919149a7d9e8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "device_info_plus_release-0.59-javadoc.jar",
          "url": "device_info_plus_release-0.59-javadoc.jar",
          "size": 260825,
          "sha512": "60b840af52511a45b27d5a94ae50233c8610d7797dab2c8f11928ad8a031ccf684268210ff55f335c541765e4ab9eb631e0245aa24d08c1b7804b0e33145be9e",
          "sha256": "d65c6f652a9b144e92d88c723faf91e2a8133ef9f0ba97c4ba80aa5364aa0703",
          "sha1": "dd6c5b90dc74957142e71b1561eb95bdb5c05652",
          "md5": "790193dbfb88def6b07aa447d28f2494"
        }
      ]
    }
  ]
}
