{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.flutter_platform_alert",
    "module": "flutter_platform_alert_release",
    "version": "0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_platform_alert_release-0.4.aar",
          "url": "flutter_platform_alert_release-0.4.aar",
          "size": 9300,
          "sha512": "890a002297e1656d660f2de9922004e5c15f31a4255bbe40eec18ba66d45195dca743efee62e2b7950b091192026c70d796e307c44efcccf74a1e8e219199de3",
          "sha256": "f4874058c3fea42b558b9e910a514ac068b4a2ec9bc438a0c7bb0c90a68fb3ea",
          "sha1": "d74c31fa82b4de13ded1debad674f4b9fe5e5745",
          "md5": "671aed9ed10be5c4bfed4a27ff14e6f6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.5.20"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_platform_alert_release-0.4.aar",
          "url": "flutter_platform_alert_release-0.4.aar",
          "size": 9300,
          "sha512": "890a002297e1656d660f2de9922004e5c15f31a4255bbe40eec18ba66d45195dca743efee62e2b7950b091192026c70d796e307c44efcccf74a1e8e219199de3",
          "sha256": "f4874058c3fea42b558b9e910a514ac068b4a2ec9bc438a0c7bb0c90a68fb3ea",
          "sha1": "d74c31fa82b4de13ded1debad674f4b9fe5e5745",
          "md5": "671aed9ed10be5c4bfed4a27ff14e6f6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_platform_alert_release-0.4-sources.jar",
          "url": "flutter_platform_alert_release-0.4-sources.jar",
          "size": 2419,
          "sha512": "0f2b22bac756a091326a6764355e2ee2c67d54d95ce2c038b9e91741917938070f40268ef2c8938684fb5110558c645f2617a325818b8f9f3fe7a70eec960812",
          "sha256": "0a5a52767371b2959d622148176f784c3054379097ee746859302933d68e85ad",
          "sha1": "5c714b72591bb9a3298241008d3df5fa6c53b609",
          "md5": "67fcd057752c94dc2ab62b41c059f6c0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_platform_alert_release-0.4-javadoc.jar",
          "url": "flutter_platform_alert_release-0.4-javadoc.jar",
          "size": 262834,
          "sha512": "0a19e1c06da226469f234ffdcedcc7ff42194428df5a2943b56b6886a2471493bbf6458debd48bf1df753407c6849e9076ebe22c2af4802d4e996d3b55045c0d",
          "sha256": "23508f091be9feedb9a5af89a786826e44a356b94231c685652757f26b522380",
          "sha1": "29bc5a517a388fdce09867d19de2be1cbd29e953",
          "md5": "0de118f985a7da43c176879d4bc2e79f"
        }
      ]
    }
  ]
}
