{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.camerax",
    "module": "camera_android_camerax_release",
    "version": "0.39",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        }
      ],
      "files": [
        {
          "name": "camera_android_camerax_release-0.39.aar",
          "url": "camera_android_camerax_release-0.39.aar",
          "size": 266218,
          "sha512": "544362c5ff1f3dfd670bdd3b139a956eac39301eaa4567deb2bbd70ebf7fdb10d4b2db3279dc8d8d98120bea20447cc1be08e6d6be19d719be9b68c7e3025c9b",
          "sha256": "818b9d45bac3888e15c2e5e908c6e89136d4b2e1b116e14e897eff19fb2591f5",
          "sha1": "ae55d2037022e6ba7311a33962718a865d919ef3",
          "md5": "e115344ccf08c22c2c20497ee49725da"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.3.4"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.3.4"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.3.4"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-video",
          "version": {
            "requires": "1.3.4"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.3.1-android"
          }
        }
      ],
      "files": [
        {
          "name": "camera_android_camerax_release-0.39.aar",
          "url": "camera_android_camerax_release-0.39.aar",
          "size": 266218,
          "sha512": "544362c5ff1f3dfd670bdd3b139a956eac39301eaa4567deb2bbd70ebf7fdb10d4b2db3279dc8d8d98120bea20447cc1be08e6d6be19d719be9b68c7e3025c9b",
          "sha256": "818b9d45bac3888e15c2e5e908c6e89136d4b2e1b116e14e897eff19fb2591f5",
          "sha1": "ae55d2037022e6ba7311a33962718a865d919ef3",
          "md5": "e115344ccf08c22c2c20497ee49725da"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "camera_android_camerax_release-0.39-sources.jar",
          "url": "camera_android_camerax_release-0.39-sources.jar",
          "size": 86316,
          "sha512": "5382ce18bd09440222ebf82115235b669fd9af0e5aa1b7230156e004966fa02af4d6769714e893b0e78dff5e9f64a7111abc9ae654e1ab61bf292113b6ecdfc0",
          "sha256": "79f2b55e1b567c1876f27760b5465af879a2a59f33efec52baeeb486833fa9f7",
          "sha1": "e6e78d7a217d954c995f6146e7d112c64e43e04f",
          "md5": "e33d81ce6a5534f6131cd452966dd58f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "camera_android_camerax_release-0.39-javadoc.jar",
          "url": "camera_android_camerax_release-0.39-javadoc.jar",
          "size": 899995,
          "sha512": "f490f06fbfabe701546315ede849428677928627490b15ea15db6086c7f108db3be116772f7b6ad15e879d71a5af3b35c57b11034f259890353850ceec9c4bb3",
          "sha256": "d5725e2a2267aa06c61525a8ff97676d5288cf5d0dc3cc78a9fee43d748c9d47",
          "sha1": "da944761801c09af68489b026a20cfd2d854dcb8",
          "md5": "a4db3b6fbf1f7ec17eb53218bd61b053"
        }
      ]
    }
  ]
}
