{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.firebase.firebaseremoteconfig",
    "module": "firebase_remote_config_release",
    "version": "0.23",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.core",
          "module": "firebase_core_release",
          "version": {
            "requires": "0.23"
          }
        }
      ],
      "files": [
        {
          "name": "firebase_remote_config_release-0.23.aar",
          "url": "firebase_remote_config_release-0.23.aar",
          "size": 10654,
          "sha512": "18b6840271418efd9a30eb92b0fec6ac27783cd7d5d0e62f5e96e662726e83172b8105aa89f2c962f13fa10f9fe39c3e6b9f5965cffa744029d1ffe10d7a41b3",
          "sha256": "9089d54e09e71a9bf64eb50d4e9a9c3d8d7c4f592be74aadeba9a1ea04298425",
          "sha1": "4be783baa16c599c9893d15f3db8def578f59315",
          "md5": "d9e920eaa16d14ef1224e72d062943ea"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-bom",
          "version": {
            "requires": "33.11.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-config"
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.core",
          "module": "firebase_core_release",
          "version": {
            "requires": "0.23"
          }
        }
      ],
      "files": [
        {
          "name": "firebase_remote_config_release-0.23.aar",
          "url": "firebase_remote_config_release-0.23.aar",
          "size": 10654,
          "sha512": "18b6840271418efd9a30eb92b0fec6ac27783cd7d5d0e62f5e96e662726e83172b8105aa89f2c962f13fa10f9fe39c3e6b9f5965cffa744029d1ffe10d7a41b3",
          "sha256": "9089d54e09e71a9bf64eb50d4e9a9c3d8d7c4f592be74aadeba9a1ea04298425",
          "sha1": "4be783baa16c599c9893d15f3db8def578f59315",
          "md5": "d9e920eaa16d14ef1224e72d062943ea"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "firebase_remote_config_release-0.23-sources.jar",
          "url": "firebase_remote_config_release-0.23-sources.jar",
          "size": 5293,
          "sha512": "101f051f9b8d8792612b26e61328dae1aaa93b234776ab1e12599e624e30a9606c0d3028658011342adc14bb4302bfb1ee40076094270e42f4f374c5db85e2bd",
          "sha256": "045ba4ec1f4c5d909e665f96786d729bb53b16f879b68b3977b79faed5f2c7c8",
          "sha1": "099573723c677b461b1502e2cf2ff7ab709ba529",
          "md5": "5f86a2e7dc66da959059dc0da259c46c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "firebase_remote_config_release-0.23-javadoc.jar",
          "url": "firebase_remote_config_release-0.23-javadoc.jar",
          "size": 273913,
          "sha512": "9274fba21bbfee0c1830cc952dbdf1e4a37c4f10f65c25e9edc0316630c2f65fb0f868ecefab37019a2cefd8325ad745b899a0d8c1e587c785c423651915f9bd",
          "sha256": "047c99ba92a85916fe549cbc28ea6c4c70e8b52691301d3da6e8c9f6ed9ab203",
          "sha1": "68e2e446e0f2498519b8627f778ea0357f62216e",
          "md5": "ad2fa5f1c70921f3c05d76307f3c875c"
        }
      ]
    }
  ]
}
