{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tekartik.sqflite",
    "module": "sqflite_android_debug",
    "version": "1.16",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        }
      ],
      "files": [
        {
          "name": "sqflite_android_debug-1.16.aar",
          "url": "sqflite_android_debug-1.16.aar",
          "size": 45459,
          "sha512": "57d6c665c629d68f9e4e94c458e9603a48c281113ef0883ca54889d191a9b8ff52b8e1f1f28cdc79d0fb7c08bada74719c91e2a0ff028549c0e88f25d69d98ff",
          "sha256": "003b02e275c7987dea4000bc39aa47bc8bd7674541b69d8b4c2306a680a52a04",
          "sha1": "078cb5ea9edbb34619002fcee5ab98a14d35c8c9",
          "md5": "1224fb7a5a317cc68f9f691842b0c75c"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        }
      ],
      "files": [
        {
          "name": "sqflite_android_debug-1.16.aar",
          "url": "sqflite_android_debug-1.16.aar",
          "size": 45459,
          "sha512": "57d6c665c629d68f9e4e94c458e9603a48c281113ef0883ca54889d191a9b8ff52b8e1f1f28cdc79d0fb7c08bada74719c91e2a0ff028549c0e88f25d69d98ff",
          "sha256": "003b02e275c7987dea4000bc39aa47bc8bd7674541b69d8b4c2306a680a52a04",
          "sha1": "078cb5ea9edbb34619002fcee5ab98a14d35c8c9",
          "md5": "1224fb7a5a317cc68f9f691842b0c75c"
        }
      ]
    },
    {
      "name": "debugVariantDebugSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sqflite_android_debug-1.16-sources.jar",
          "url": "sqflite_android_debug-1.16-sources.jar",
          "size": 23906,
          "sha512": "84be2e0f11f6739735214c714fcf25ca7b657afc40b3b54a0f0eff0de0f085cc926571087ab261b90cb6ed1e0be787046b45db4603790b883b119c835c22aa20",
          "sha256": "a127166bbaf1689504c6fc9e5111043a0537dc09ba3ea55a6d743da958ef125a",
          "sha1": "55f721f93f9c468c9d426bc61ff59a393e267750",
          "md5": "3f9cd042a556379914178c3426bed53c"
        }
      ]
    },
    {
      "name": "debugVariantDebugJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sqflite_android_debug-1.16-javadoc.jar",
          "url": "sqflite_android_debug-1.16-javadoc.jar",
          "size": 342118,
          "sha512": "dd075b4ce860b7b3b729eeeb3c254dfff79d4e2bbda127f3006484d915aaf6914307fb1a712f96b61ce6634f8ba52ee1e5679921e4fbaa67ebf9009598c967f0",
          "sha256": "0c31091f8673e269a998fe1d64be92c2a623acaba633180b3075a079f5bb2b6e",
          "sha1": "9ebcbc10612091d222f226fca01d7c5bd28da357",
          "md5": "3abad068c99ca39ed2420ff52a3a6ba4"
        }
      ]
    }
  ]
}
