{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
    "module": "flutter_plugin_android_lifecycle_release",
    "version": "0.32",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_plugin_android_lifecycle_release-0.32.aar",
          "url": "flutter_plugin_android_lifecycle_release-0.32.aar",
          "size": 2503,
          "sha512": "c47015d3684b3b1a0cef077b1929cbe61ffaa4f3d8ec078ed4279cb7aa1ada9dc8e0f337ea5b9159a936cc75e63540eb8e70c1088a32642ceff62862fe1374f9",
          "sha256": "9fb4cf8d054e60d0bf6d639cfacc66db8aab776059fd0e9b67ace8c60d169d65",
          "sha1": "e526db6513439eebf917c63e27fa7b9d969a4d2d",
          "md5": "89a4374677faa54c80076e99a9da11a4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_plugin_android_lifecycle_release-0.32.aar",
          "url": "flutter_plugin_android_lifecycle_release-0.32.aar",
          "size": 2503,
          "sha512": "c47015d3684b3b1a0cef077b1929cbe61ffaa4f3d8ec078ed4279cb7aa1ada9dc8e0f337ea5b9159a936cc75e63540eb8e70c1088a32642ceff62862fe1374f9",
          "sha256": "9fb4cf8d054e60d0bf6d639cfacc66db8aab776059fd0e9b67ace8c60d169d65",
          "sha1": "e526db6513439eebf917c63e27fa7b9d969a4d2d",
          "md5": "89a4374677faa54c80076e99a9da11a4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_plugin_android_lifecycle_release-0.32-sources.jar",
          "url": "flutter_plugin_android_lifecycle_release-0.32-sources.jar",
          "size": 2683,
          "sha512": "a3f7fee602ae01e1fe53ad82c914db15159744a75a0e4f439cdbe5e530abf6d3b431e26802ccd3cf08245278758e1aef335a9e00aec7ded1b1c89a60a53d7915",
          "sha256": "ea22384264efbced6ae1be61be8aadee870b81c3a1e0b6accc0ef62396aaeae0",
          "sha1": "1ddcac6e1149d882ff8719e00a4eebfeb282eb36",
          "md5": "351ed496e751473b57d20e3a693b432d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_plugin_android_lifecycle_release-0.32-javadoc.jar",
          "url": "flutter_plugin_android_lifecycle_release-0.32-javadoc.jar",
          "size": 269832,
          "sha512": "173f6bc030532a46b37bc556a16eb5daffc86278077ab96165a4d54c8417f6d6f725d56aa65af611ff35d536a3404f265cefb6569595bd5630fbd667a609f44d",
          "sha256": "57af8d653d895a4ba8f74297850ccf4d81219ff75f7e9b042a8935c4ffddfe79",
          "sha1": "247b81043a7602da8eaea7a3eb014dc2fc5f0d5e",
          "md5": "55e4d2ffee097f47ab73cf72d16a96cf"
        }
      ]
    }
  ]
}
