{
  "formatVersion": "1.1",
  "component": {
    "group": "com.fluttercandies.flutter_image_compress",
    "module": "flutter_image_compress_common_release",
    "version": "0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_image_compress_common_release-0.3.aar",
          "url": "flutter_image_compress_common_release-0.3.aar",
          "size": 30456,
          "sha512": "1cef88b3d7e6eaea0c3aa30c64d67d58436242ad972812c241d4812df73b5efd8072be2ce22353d3039a9fa46732e697ac47df6a00b74cd1ea433b3b28d9bc13",
          "sha256": "1498b45475564bc8f0b6b31c982380e743ad767c0e132b6107b8ff26ccda6d3a",
          "sha1": "e9e9561dc2be55fc28830e77d9ed2d32c34b32a8",
          "md5": "ededa47d4da6304fe7e65990cd4584d7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "androidx.heifwriter",
          "module": "heifwriter",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_image_compress_common_release-0.3.aar",
          "url": "flutter_image_compress_common_release-0.3.aar",
          "size": 30456,
          "sha512": "1cef88b3d7e6eaea0c3aa30c64d67d58436242ad972812c241d4812df73b5efd8072be2ce22353d3039a9fa46732e697ac47df6a00b74cd1ea433b3b28d9bc13",
          "sha256": "1498b45475564bc8f0b6b31c982380e743ad767c0e132b6107b8ff26ccda6d3a",
          "sha1": "e9e9561dc2be55fc28830e77d9ed2d32c34b32a8",
          "md5": "ededa47d4da6304fe7e65990cd4584d7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_image_compress_common_release-0.3-sources.jar",
          "url": "flutter_image_compress_common_release-0.3-sources.jar",
          "size": 13283,
          "sha512": "9d463a80c9f9155d36af415dfbc87fadb7908f534f56929f46ded2280cbd3951f90518b08d83de17af9eab1bb66723f65b386d3d4df8b2a57dc67105fc8cad56",
          "sha256": "93a28e5f9b7fcb467c45057e584caa01f1eb412c0b4a92b23a49dc0100b4af37",
          "sha1": "8f0422fa7a12db6f03202df46f11b2c7ec84061a",
          "md5": "326cceeddeb7bc0e1af417bf6b15811f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_image_compress_common_release-0.3-javadoc.jar",
          "url": "flutter_image_compress_common_release-0.3-javadoc.jar",
          "size": 351453,
          "sha512": "ec5fc7ea54328052dc54b7a2ffac4ba352410a784e9b26b840d3bf0e6e0cd01beadadf4e08198ded81eaed4d59bef705e84d5b5c7cb1abcef731807a6cce6a5c",
          "sha256": "581f392a0f00e8c969d85f08d93b1944d658f3fd559e94e50fec83485f8e4c28",
          "sha1": "61665b81f3a1d087d0d6e0383d263a1cd4cad2a0",
          "md5": "5d8bad9af279c31acef6cf6875176c2e"
        }
      ]
    }
  ]
}
