{
  "formatVersion": "1.1",
  "component": {
    "group": "ch.simonbraillard.flutter_new_badger",
    "module": "flutter_new_badger_release",
    "version": "0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_new_badger_release-0.5.aar",
          "url": "flutter_new_badger_release-0.5.aar",
          "size": 4089,
          "sha512": "3b8d020cc09f8dfea02c5cdbbfe8e6b4fc52d2065bd6bd4292255ce84fe7a32a233e0906a9329b03855a01e4e95c3bf414cef0867683c4102514c947552bbc2c",
          "sha256": "a2d5986cfc2aff3f884933b335ee06609866fdb2a8086d57a117a546248dd638",
          "sha1": "f1a93da1fcc94072e47675c39e3f0bd40b5eef7d",
          "md5": "49267deb86f4d5f21849cc85fbe07fe9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        },
        {
          "group": "me.leolin",
          "module": "ShortcutBadger",
          "version": {
            "requires": "1.1.22"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "ShortcutBadger",
              "type": "aar",
              "extension": "aar"
            }
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_new_badger_release-0.5.aar",
          "url": "flutter_new_badger_release-0.5.aar",
          "size": 4089,
          "sha512": "3b8d020cc09f8dfea02c5cdbbfe8e6b4fc52d2065bd6bd4292255ce84fe7a32a233e0906a9329b03855a01e4e95c3bf414cef0867683c4102514c947552bbc2c",
          "sha256": "a2d5986cfc2aff3f884933b335ee06609866fdb2a8086d57a117a546248dd638",
          "sha1": "f1a93da1fcc94072e47675c39e3f0bd40b5eef7d",
          "md5": "49267deb86f4d5f21849cc85fbe07fe9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_new_badger_release-0.5-sources.jar",
          "url": "flutter_new_badger_release-0.5-sources.jar",
          "size": 1776,
          "sha512": "c3d1ee04902cd70b0d5dad70cf8a33d467503a4187a2533a44f393362c35ed7346ace3326668222d4dffd17d1172b1df25dadad9ce27d30ace3e5c9c02c9c648",
          "sha256": "a29d615e4a0c05e28a1a76b0cd89cfc61b4f6648092aa31666d2c30e86c13a41",
          "sha1": "00948fe19d0d77a813d3083387c846f71a2237f1",
          "md5": "66078d106b1cb86ef6e66ffaa3a37a47"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_new_badger_release-0.5-javadoc.jar",
          "url": "flutter_new_badger_release-0.5-javadoc.jar",
          "size": 262486,
          "sha512": "9284205f5051233c26fb37bfb93f9cb999d1d50dd5df236eca89acd5b0c6092debf37d8ce01d37cee105b1112b90c0d30432e9101f34a34d79f7a6ee1c17dce5",
          "sha256": "8d6b9af477e7ceece412f318ad67127d217f79d71037bcfdf8558c340f547340",
          "sha1": "4e05d00371c8b6b2c81ec5339f012cface6ed10b",
          "md5": "2c4b93d5950a48b32303a0eaa664912b"
        }
      ]
    }
  ]
}
