{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tekartik.sqflite",
    "module": "sqflite_android_release",
    "version": "0.47",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        }
      ],
      "files": [
        {
          "name": "sqflite_android_release-0.47.aar",
          "url": "sqflite_android_release-0.47.aar",
          "size": 43464,
          "sha512": "7879a5234b45a10d6d14343dd39cc2038f419c9c1f211f2e04b9ddaa5519342b7fbf3b571bb488fc4c04dc07da33ffc708ebda8364532772286f91c08c754e30",
          "sha256": "a2b47e4f53735035112c4d0ecf795b936f49bb4315bea219db776942a98d090b",
          "sha1": "9d71bbae7150e6f0e16a68049adc852a3f5a7575",
          "md5": "90320c1fd75c9407ff1d2397d138f18d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        }
      ],
      "files": [
        {
          "name": "sqflite_android_release-0.47.aar",
          "url": "sqflite_android_release-0.47.aar",
          "size": 43464,
          "sha512": "7879a5234b45a10d6d14343dd39cc2038f419c9c1f211f2e04b9ddaa5519342b7fbf3b571bb488fc4c04dc07da33ffc708ebda8364532772286f91c08c754e30",
          "sha256": "a2b47e4f53735035112c4d0ecf795b936f49bb4315bea219db776942a98d090b",
          "sha1": "9d71bbae7150e6f0e16a68049adc852a3f5a7575",
          "md5": "90320c1fd75c9407ff1d2397d138f18d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sqflite_android_release-0.47-sources.jar",
          "url": "sqflite_android_release-0.47-sources.jar",
          "size": 23906,
          "sha512": "84be2e0f11f6739735214c714fcf25ca7b657afc40b3b54a0f0eff0de0f085cc926571087ab261b90cb6ed1e0be787046b45db4603790b883b119c835c22aa20",
          "sha256": "a127166bbaf1689504c6fc9e5111043a0537dc09ba3ea55a6d743da958ef125a",
          "sha1": "55f721f93f9c468c9d426bc61ff59a393e267750",
          "md5": "3f9cd042a556379914178c3426bed53c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sqflite_android_release-0.47-javadoc.jar",
          "url": "sqflite_android_release-0.47-javadoc.jar",
          "size": 341671,
          "sha512": "312539e3a61f89419c86b1b27c9d84a393a0da6328b663d8222082eaf7b2912fa0efab137600160f9b1c1f7da622392380013a44b27decb841492f2edb706b2e",
          "sha256": "7e368a3f4cc626ffa14eceac1ae184371094966101868cc4b2822e3a05601849",
          "sha1": "c9e4a3b3fc3008a4c7364bd1852b17e1ce820b2b",
          "md5": "b52b6e846c98e189710e1de1ff4e9351"
        }
      ]
    }
  ]
}
