{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.fluttercommunity.plus.device_info",
    "module": "device_info_plus_debug",
    "version": "0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        }
      ],
      "files": [
        {
          "name": "device_info_plus_debug-0.1.aar",
          "url": "device_info_plus_debug-0.1.aar",
          "size": 7348,
          "sha512": "c50bf18203fcb3ed09fb767a1038aafe6fdca39bbd6ada68290995e149a2f61370587d5fffc35bfeca110792fbe774eeaab98bdb7089c7a53c89e2d62098f215",
          "sha256": "22751c70e182b11a06ac3488a713bb5805eed2bdb8e528cab83032c9085c6920",
          "sha1": "6c28f02a2a3b901abd5990c6f4922471045aea77",
          "md5": "3b6c8427b1a1be92c3bf01753ebe3cb1"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.22"
          }
        }
      ],
      "files": [
        {
          "name": "device_info_plus_debug-0.1.aar",
          "url": "device_info_plus_debug-0.1.aar",
          "size": 7348,
          "sha512": "c50bf18203fcb3ed09fb767a1038aafe6fdca39bbd6ada68290995e149a2f61370587d5fffc35bfeca110792fbe774eeaab98bdb7089c7a53c89e2d62098f215",
          "sha256": "22751c70e182b11a06ac3488a713bb5805eed2bdb8e528cab83032c9085c6920",
          "sha1": "6c28f02a2a3b901abd5990c6f4922471045aea77",
          "md5": "3b6c8427b1a1be92c3bf01753ebe3cb1"
        }
      ]
    },
    {
      "name": "debugVariantDebugSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "device_info_plus_debug-0.1-sources.jar",
          "url": "device_info_plus_debug-0.1-sources.jar",
          "size": 2976,
          "sha512": "b0a16c5d099d1a6d3f96d453ca4f34aa2b138d0729fd675fa4dadff9f54e169514b31bd5586b5d4fb388059df0d5e5ff8ceeeec9214322cced8b305c5d67afb3",
          "sha256": "1160189e3c750bbf50affba28a4dbf0fc1216e815a1f01a3d1d9dd17958f37ab",
          "sha1": "b1f985fbb38747f8f626c4988380b4847ff05db6",
          "md5": "7effa257187ed4394bf3919149a7d9e8"
        }
      ]
    },
    {
      "name": "debugVariantDebugJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "device_info_plus_debug-0.1-javadoc.jar",
          "url": "device_info_plus_debug-0.1-javadoc.jar",
          "size": 260821,
          "sha512": "3fa0bb03343d46ff4d2238445f4cf46efa0009c04a86755eefabc2d49bd89982ecc63ab28fbc11ec3513fbc66dc743abb3d7dba5f91a8d722b8bbdee06a95ab0",
          "sha256": "2c8345951d5c7c1ea7d1557db2657e2c49012322d3e73e983eb7fdba7ff5e5fe",
          "sha1": "3573f6da30783c39f84a0b400b9b09fba540fc7f",
          "md5": "a1e47fbaa9c3b8eb255359acb6f153e5"
        }
      ]
    }
  ]
}
