{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.fluttercommunity.plus.packageinfo",
    "module": "package_info_plus_release",
    "version": "0.31",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        }
      ],
      "files": [
        {
          "name": "package_info_plus_release-0.31.aar",
          "url": "package_info_plus_release-0.31.aar",
          "size": 5915,
          "sha512": "39fddec667221329f3f1233762f432e08c47979f626eb243e9d1ddef4a004a8fb3ce72a6bff5707b6d577b4808835afd0fe10958b891a104754ecb14a4771e15",
          "sha256": "ff2033b7afb476b1aca6ab2f8c2579910aef48ffb84aa82b3d9284f1489272ab",
          "sha1": "1110925d06b92f7797406fd790f2abbb0448aee5",
          "md5": "8d057ad108d3506c7c0a1d4770075f45"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.22"
          }
        }
      ],
      "files": [
        {
          "name": "package_info_plus_release-0.31.aar",
          "url": "package_info_plus_release-0.31.aar",
          "size": 5915,
          "sha512": "39fddec667221329f3f1233762f432e08c47979f626eb243e9d1ddef4a004a8fb3ce72a6bff5707b6d577b4808835afd0fe10958b891a104754ecb14a4771e15",
          "sha256": "ff2033b7afb476b1aca6ab2f8c2579910aef48ffb84aa82b3d9284f1489272ab",
          "sha1": "1110925d06b92f7797406fd790f2abbb0448aee5",
          "md5": "8d057ad108d3506c7c0a1d4770075f45"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "package_info_plus_release-0.31-sources.jar",
          "url": "package_info_plus_release-0.31-sources.jar",
          "size": 2693,
          "sha512": "baaae2e6245030a7de70f19e43504fb87d6d374ec50af2dd23321d0ab0bf43dbb918967f0b66277e2662ccb4faf2098ffcb870dd1e597bc1dc8ac730e9c7b5fb",
          "sha256": "3f208ebbb8c9b93761dea623949b7ee1a9cd74e818acede7ccc4f562f3839a5d",
          "sha1": "12df81060cfa11fc35581f9c91da8922a5f8e6f0",
          "md5": "f30e01eabb60c79316840a3ed7edecb3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "package_info_plus_release-0.31-javadoc.jar",
          "url": "package_info_plus_release-0.31-javadoc.jar",
          "size": 265109,
          "sha512": "45ed1a5ef4fde6678fb1015c9e25686f1800a4375dfff5f0aa3ee49cb363a0ee7a7c80c2eaedbcd05c5a36b91383f90bdc0a59df414120beff55da5aca8653ba",
          "sha256": "0796be4a1cf754cdf9d8e6093f9c5d43b56161edfe1396d82fa5d00280b3d20a",
          "sha1": "0bfe95eccea660d85ac417dff236d39c52663218",
          "md5": "3f45564d4fc0b6e4d882008a1336bef7"
        }
      ]
    }
  ]
}
