{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dexterous.flutterlocalnotifications",
    "module": "flutter_local_notifications_release",
    "version": "0.30",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_local_notifications_release-0.30.aar",
          "url": "flutter_local_notifications_release-0.30.aar",
          "size": 81399,
          "sha512": "9fcbc64ea730f13fb1533be23db0a12f873006e639dfb33c8f41583c0ecd291bd1440e9166d982c6821e73e80b51255487de5d7a1348aaeb3b2fde1380344175",
          "sha256": "910fe7884a81957367186ed054a953699c18d9cbac904acb437e207f4ebc01b8",
          "sha1": "850711a5952417b4b65346943ad725d3c9f08922",
          "md5": "a560ca83a23736f44a26a497a1fd90d2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.media",
          "module": "media",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.9"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_local_notifications_release-0.30.aar",
          "url": "flutter_local_notifications_release-0.30.aar",
          "size": 81399,
          "sha512": "9fcbc64ea730f13fb1533be23db0a12f873006e639dfb33c8f41583c0ecd291bd1440e9166d982c6821e73e80b51255487de5d7a1348aaeb3b2fde1380344175",
          "sha256": "910fe7884a81957367186ed054a953699c18d9cbac904acb437e207f4ebc01b8",
          "sha1": "850711a5952417b4b65346943ad725d3c9f08922",
          "md5": "a560ca83a23736f44a26a497a1fd90d2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_local_notifications_release-0.30-sources.jar",
          "url": "flutter_local_notifications_release-0.30-sources.jar",
          "size": 43596,
          "sha512": "7736acb5954d99f56cb46af46dd8581b373482a317c78c9b99eb6fc6eb8ca140082025906c97406c3b82586029c0e86a3f0d69c96023384abdd8ea46e6bf48d4",
          "sha256": "fc7f32461f268b0581bc3c5c9e2c0d81a79252cb0cf09a351bb0bdffe4993ea6",
          "sha1": "c3fb9f6ef65dc6aff958aa612beca1e2ae4a96c0",
          "md5": "5de3e43acd23922d52c9900575889eda"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_local_notifications_release-0.30-javadoc.jar",
          "url": "flutter_local_notifications_release-0.30-javadoc.jar",
          "size": 417868,
          "sha512": "ffa7f5eba6c53fe42d593117ce525acdd3ac8690ebc4081bac6bc7264c9af382e9020843791b7e488354d814166322c66591d0c80712eb175f9ad498b2c9d5ba",
          "sha256": "c9f17b09f206ac84607a9c1ee9d53a93835203401ac20724ffa98f7ee54a35d5",
          "sha1": "a16fd88fb2f0192483d7f82927cf3029717133ed",
          "md5": "7a16513cac8bbd1ba438970d393ae082"
        }
      ]
    }
  ]
}
