{
  "formatVersion": "1.1",
  "component": {
    "group": "eu.simonbinder.sqlite3_flutter_libs",
    "module": "sqlite3_flutter_libs_debug",
    "version": "1.16",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        }
      ],
      "files": [
        {
          "name": "sqlite3_flutter_libs_debug-1.16.aar",
          "url": "sqlite3_flutter_libs_debug-1.16.aar",
          "size": 2711,
          "sha512": "91cf23dfcbfb674da4822432cbfa9af26bf1fbb759c1bf7e47f7c7afa7f482d42bae670ca7a47f910ca7c2860d6ba6964006f00ac68e339cdee86c9a25f58b12",
          "sha256": "a19f85ab9c7882ddb8aa2e117705583ec40a7be3277e28e98a2560f7a2d7d0df",
          "sha1": "00d7fe41e05a38ffdad764398664a13e12df113e",
          "md5": "5417e7c5d72609c00b886a0c71ce56f6"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        },
        {
          "group": "eu.simonbinder",
          "module": "sqlite3-native-library",
          "version": {
            "requires": "3.50.1"
          }
        }
      ],
      "files": [
        {
          "name": "sqlite3_flutter_libs_debug-1.16.aar",
          "url": "sqlite3_flutter_libs_debug-1.16.aar",
          "size": 2711,
          "sha512": "91cf23dfcbfb674da4822432cbfa9af26bf1fbb759c1bf7e47f7c7afa7f482d42bae670ca7a47f910ca7c2860d6ba6964006f00ac68e339cdee86c9a25f58b12",
          "sha256": "a19f85ab9c7882ddb8aa2e117705583ec40a7be3277e28e98a2560f7a2d7d0df",
          "sha1": "00d7fe41e05a38ffdad764398664a13e12df113e",
          "md5": "5417e7c5d72609c00b886a0c71ce56f6"
        }
      ]
    },
    {
      "name": "debugVariantDebugSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sqlite3_flutter_libs_debug-1.16-sources.jar",
          "url": "sqlite3_flutter_libs_debug-1.16-sources.jar",
          "size": 1462,
          "sha512": "72a2ddbe506e1d6e2730f00e041dea0f9c617b03138b525c6b88e0ef701b98a66fd1d6b75cd9b22a8ea26fce3e98b7a69945f10593749c1593670c595f78bb9d",
          "sha256": "65510b847d970f272c2935de5b14f0489bd719bee3541f208bc72ba20e42e293",
          "sha1": "cc4891fa470b28d66912771a1d113c24bb411027",
          "md5": "78f2d9b7b35831e0a4e0ebe0e97d4aa4"
        }
      ]
    },
    {
      "name": "debugVariantDebugJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sqlite3_flutter_libs_debug-1.16-javadoc.jar",
          "url": "sqlite3_flutter_libs_debug-1.16-javadoc.jar",
          "size": 262153,
          "sha512": "ab9a46bf27d4f648f0a2cf05818067a30af27e70702b692a2cf9862f45efc3818206046e53e759c7072bcd8876751622e276b844f2427b3839d083251833cdb2",
          "sha256": "8757b74ad5261f6cb9866c0d02015fa9827d74bf3cacbfbe77e27277a9879447",
          "sha1": "a5d1db1431631add4a82465b6694435d14a1d198",
          "md5": "efcfd7e167195e00beb8a519cfce2e48"
        }
      ]
    }
  ]
}
