{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.firebase.firebaseremoteconfig",
    "module": "firebase_remote_config_release",
    "version": "0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.core",
          "module": "firebase_core_release",
          "version": {
            "requires": "0.5"
          }
        }
      ],
      "files": [
        {
          "name": "firebase_remote_config_release-0.5.aar",
          "url": "firebase_remote_config_release-0.5.aar",
          "size": 10650,
          "sha512": "1e2a62801386be4b287d63d09e169d1b17926662410f80fc81a04736e7c4265533c3bc10387ba3bce8e474a39c70157e3d8e14d0cb65a5c7fdfe4591a40375f3",
          "sha256": "a1666cc9636600310dba5a2f5ea20ec24c297a74794bbeb5913bb19822240dd8",
          "sha1": "ea5d377550cac2247d3493ddfa9bb896eaa0a23f",
          "md5": "f0fad2b2f383d38911d230b83edf96aa"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-bom",
          "version": {
            "requires": "33.11.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-config"
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.core",
          "module": "firebase_core_release",
          "version": {
            "requires": "0.5"
          }
        }
      ],
      "files": [
        {
          "name": "firebase_remote_config_release-0.5.aar",
          "url": "firebase_remote_config_release-0.5.aar",
          "size": 10650,
          "sha512": "1e2a62801386be4b287d63d09e169d1b17926662410f80fc81a04736e7c4265533c3bc10387ba3bce8e474a39c70157e3d8e14d0cb65a5c7fdfe4591a40375f3",
          "sha256": "a1666cc9636600310dba5a2f5ea20ec24c297a74794bbeb5913bb19822240dd8",
          "sha1": "ea5d377550cac2247d3493ddfa9bb896eaa0a23f",
          "md5": "f0fad2b2f383d38911d230b83edf96aa"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "firebase_remote_config_release-0.5-sources.jar",
          "url": "firebase_remote_config_release-0.5-sources.jar",
          "size": 5293,
          "sha512": "101f051f9b8d8792612b26e61328dae1aaa93b234776ab1e12599e624e30a9606c0d3028658011342adc14bb4302bfb1ee40076094270e42f4f374c5db85e2bd",
          "sha256": "045ba4ec1f4c5d909e665f96786d729bb53b16f879b68b3977b79faed5f2c7c8",
          "sha1": "099573723c677b461b1502e2cf2ff7ab709ba529",
          "md5": "5f86a2e7dc66da959059dc0da259c46c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "firebase_remote_config_release-0.5-javadoc.jar",
          "url": "firebase_remote_config_release-0.5-javadoc.jar",
          "size": 273792,
          "sha512": "99d000b19a2ca6159eac10f09a2dfdd2471ba4b4e89a57d1460dc327d574e0f47439ba2b69f89e3b6e1e4869db133ccee0fb4585633562a109ef84ca50de4692",
          "sha256": "3e41255b39013fb66e7d3940fab17f0e15a51a023e1abe604ba770229c4e9b8a",
          "sha1": "9d902485071950bcdf41fe3459153102ee7a1fbd",
          "md5": "94de415f63415333e8913eb00aa22bd7"
        }
      ]
    }
  ]
}
