{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.firebase.firebaseremoteconfig",
    "module": "firebase_remote_config_release",
    "version": "0.15",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.core",
          "module": "firebase_core_release",
          "version": {
            "requires": "0.15"
          }
        }
      ],
      "files": [
        {
          "name": "firebase_remote_config_release-0.15.aar",
          "url": "firebase_remote_config_release-0.15.aar",
          "size": 10654,
          "sha512": "18b6840271418efd9a30eb92b0fec6ac27783cd7d5d0e62f5e96e662726e83172b8105aa89f2c962f13fa10f9fe39c3e6b9f5965cffa744029d1ffe10d7a41b3",
          "sha256": "9089d54e09e71a9bf64eb50d4e9a9c3d8d7c4f592be74aadeba9a1ea04298425",
          "sha1": "4be783baa16c599c9893d15f3db8def578f59315",
          "md5": "d9e920eaa16d14ef1224e72d062943ea"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-bom",
          "version": {
            "requires": "33.11.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-config"
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.core",
          "module": "firebase_core_release",
          "version": {
            "requires": "0.15"
          }
        }
      ],
      "files": [
        {
          "name": "firebase_remote_config_release-0.15.aar",
          "url": "firebase_remote_config_release-0.15.aar",
          "size": 10654,
          "sha512": "18b6840271418efd9a30eb92b0fec6ac27783cd7d5d0e62f5e96e662726e83172b8105aa89f2c962f13fa10f9fe39c3e6b9f5965cffa744029d1ffe10d7a41b3",
          "sha256": "9089d54e09e71a9bf64eb50d4e9a9c3d8d7c4f592be74aadeba9a1ea04298425",
          "sha1": "4be783baa16c599c9893d15f3db8def578f59315",
          "md5": "d9e920eaa16d14ef1224e72d062943ea"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "firebase_remote_config_release-0.15-sources.jar",
          "url": "firebase_remote_config_release-0.15-sources.jar",
          "size": 5293,
          "sha512": "101f051f9b8d8792612b26e61328dae1aaa93b234776ab1e12599e624e30a9606c0d3028658011342adc14bb4302bfb1ee40076094270e42f4f374c5db85e2bd",
          "sha256": "045ba4ec1f4c5d909e665f96786d729bb53b16f879b68b3977b79faed5f2c7c8",
          "sha1": "099573723c677b461b1502e2cf2ff7ab709ba529",
          "md5": "5f86a2e7dc66da959059dc0da259c46c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "firebase_remote_config_release-0.15-javadoc.jar",
          "url": "firebase_remote_config_release-0.15-javadoc.jar",
          "size": 273875,
          "sha512": "b923bebe2cbd3055bcd9d57252e4aee1ac70a24105fa92dcc70e3fd7d2adb98002167ce80ce7eb94432256f3cc7242aee3cd21333032577fae97ae0126fbfbbc",
          "sha256": "f8cc1cb3ab33895f38418a1cdd9452288cf19c7bd07e2c0f6beb21e8113b003e",
          "sha1": "b8ab046fdc731e4aa360a5f392e23211af374c0e",
          "md5": "54bd5e4d5eaed8ab1ee0c4b16cd13f6c"
        }
      ]
    }
  ]
}
