{
  "formatVersion": "1.1",
  "component": {
    "group": "com.pichillilorenzo.flutter_inappwebview_android",
    "module": "flutter_inappwebview_android_debug",
    "version": "1.16",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_inappwebview_android_debug-1.16.aar",
          "url": "flutter_inappwebview_android_debug-1.16.aar",
          "size": 539467,
          "sha512": "a1e3018519a015e146165a2433e6525abaa7a02753e4d2bc90fb074595ed4f6a433afdd7a8a3b2afacf430cf21f339f4ea0452d3caa35d2ec80199c128b930f2",
          "sha256": "a873a603e8398eeb6f18889f266c61763edfca91ce12628a1da8629000e75c7d",
          "sha1": "aaf75832bb07b91faa0b96dbad44831d0202a4c7",
          "md5": "b7ee4d191804b35099d1b48a02327cf4"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.swiperefreshlayout",
          "module": "swiperefreshlayout",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_inappwebview_android_debug-1.16.aar",
          "url": "flutter_inappwebview_android_debug-1.16.aar",
          "size": 539467,
          "sha512": "a1e3018519a015e146165a2433e6525abaa7a02753e4d2bc90fb074595ed4f6a433afdd7a8a3b2afacf430cf21f339f4ea0452d3caa35d2ec80199c128b930f2",
          "sha256": "a873a603e8398eeb6f18889f266c61763edfca91ce12628a1da8629000e75c7d",
          "sha1": "aaf75832bb07b91faa0b96dbad44831d0202a4c7",
          "md5": "b7ee4d191804b35099d1b48a02327cf4"
        }
      ]
    },
    {
      "name": "debugVariantDebugSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_inappwebview_android_debug-1.16-sources.jar",
          "url": "flutter_inappwebview_android_debug-1.16-sources.jar",
          "size": 231367,
          "sha512": "39e7bab5ae4e86a0f762af35f4a3b428c7bed967108a81dd6b731a225daacec4ee60976a9c6f374b169dc545a84eac0a9ef97acb5833c964b81f7a6b9250ee3f",
          "sha256": "48bd11608d04ea6b5f2f91795ddc66f364fdb0b591680cb989cf2462be853553",
          "sha1": "4d5670c4fcb1bc6e4abc987cb1d470f60cb333a0",
          "md5": "2370669b7ebb349e7e5198f2e0e32601"
        }
      ]
    },
    {
      "name": "debugVariantDebugJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_inappwebview_android_debug-1.16-javadoc.jar",
          "url": "flutter_inappwebview_android_debug-1.16-javadoc.jar",
          "size": 1171062,
          "sha512": "243be7e6ef8d7815c59530ce5e26e63fe788bb3cd8b050095f310d7cab04524615d0200118f05a188b39548c6565f0f6bfab92b0a70dc9881e50dad4466ec7e6",
          "sha256": "670555f000cb4ff40601b4ecd2261a9979d616b26e4970b864c2e58db942e469",
          "sha1": "0345233aefff35175c77c14d05d3533d440cd966",
          "md5": "1f0a3ba304878811399d201bcb4753e6"
        }
      ]
    }
  ]
}
