{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.firebase.firebaseremoteconfig",
    "module": "firebase_remote_config_release",
    "version": "0.30",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.core",
          "module": "firebase_core_release",
          "version": {
            "requires": "0.30"
          }
        }
      ],
      "files": [
        {
          "name": "firebase_remote_config_release-0.30.aar",
          "url": "firebase_remote_config_release-0.30.aar",
          "size": 10654,
          "sha512": "18b6840271418efd9a30eb92b0fec6ac27783cd7d5d0e62f5e96e662726e83172b8105aa89f2c962f13fa10f9fe39c3e6b9f5965cffa744029d1ffe10d7a41b3",
          "sha256": "9089d54e09e71a9bf64eb50d4e9a9c3d8d7c4f592be74aadeba9a1ea04298425",
          "sha1": "4be783baa16c599c9893d15f3db8def578f59315",
          "md5": "d9e920eaa16d14ef1224e72d062943ea"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-bom",
          "version": {
            "requires": "33.11.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-config"
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.core",
          "module": "firebase_core_release",
          "version": {
            "requires": "0.30"
          }
        }
      ],
      "files": [
        {
          "name": "firebase_remote_config_release-0.30.aar",
          "url": "firebase_remote_config_release-0.30.aar",
          "size": 10654,
          "sha512": "18b6840271418efd9a30eb92b0fec6ac27783cd7d5d0e62f5e96e662726e83172b8105aa89f2c962f13fa10f9fe39c3e6b9f5965cffa744029d1ffe10d7a41b3",
          "sha256": "9089d54e09e71a9bf64eb50d4e9a9c3d8d7c4f592be74aadeba9a1ea04298425",
          "sha1": "4be783baa16c599c9893d15f3db8def578f59315",
          "md5": "d9e920eaa16d14ef1224e72d062943ea"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "firebase_remote_config_release-0.30-sources.jar",
          "url": "firebase_remote_config_release-0.30-sources.jar",
          "size": 5293,
          "sha512": "101f051f9b8d8792612b26e61328dae1aaa93b234776ab1e12599e624e30a9606c0d3028658011342adc14bb4302bfb1ee40076094270e42f4f374c5db85e2bd",
          "sha256": "045ba4ec1f4c5d909e665f96786d729bb53b16f879b68b3977b79faed5f2c7c8",
          "sha1": "099573723c677b461b1502e2cf2ff7ab709ba529",
          "md5": "5f86a2e7dc66da959059dc0da259c46c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "firebase_remote_config_release-0.30-javadoc.jar",
          "url": "firebase_remote_config_release-0.30-javadoc.jar",
          "size": 273914,
          "sha512": "f6ea5d2b7c1465429d5c4c943f915394aab3df8e56bd1f00f8b71e55a29fb626c082979288b1d3de3d0e3868aac72a8a26f4f80bbb422805cfaf43ecb527eebe",
          "sha256": "4ba1d6a0e5be00e2871c1c7cdacaa0c33cf10446928f3b889fe104db0b56273c",
          "sha1": "291637726c0c0e2f1d08ed22b522cdad1ae809e9",
          "md5": "5dbc88b968c8e3bd961de6c859e456ae"
        }
      ]
    }
  ]
}
