{
  "formatVersion": "1.1",
  "component": {
    "group": "com.ryanheise.just_audio",
    "module": "just_audio_release",
    "version": "0.66",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        }
      ],
      "files": [
        {
          "name": "just_audio_release-0.66.aar",
          "url": "just_audio_release-0.66.aar",
          "size": 28482,
          "sha512": "43fb036df9eee45abee15a17f29c276eb82b6a273fd1363effb176f8b15e69e199d35ab6cbfef537d1e439db339cf51cf4ecced1437f6485917397d4a49c0892",
          "sha256": "32f70ebafd4441da3dc884ae41d574fff07249ab0cd28465245ba258a5cf61c2",
          "sha1": "d821f699bf6597f5612ec38a7cb376d7257fa62d",
          "md5": "01f45aa6819d4393b8c0c1597e834fc8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-dash",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-hls",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-smoothstreaming",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "com.ryanheise.audio_session",
          "module": "audio_session_release",
          "version": {
            "requires": "0.66"
          }
        }
      ],
      "files": [
        {
          "name": "just_audio_release-0.66.aar",
          "url": "just_audio_release-0.66.aar",
          "size": 28482,
          "sha512": "43fb036df9eee45abee15a17f29c276eb82b6a273fd1363effb176f8b15e69e199d35ab6cbfef537d1e439db339cf51cf4ecced1437f6485917397d4a49c0892",
          "sha256": "32f70ebafd4441da3dc884ae41d574fff07249ab0cd28465245ba258a5cf61c2",
          "sha1": "d821f699bf6597f5612ec38a7cb376d7257fa62d",
          "md5": "01f45aa6819d4393b8c0c1597e834fc8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "just_audio_release-0.66-sources.jar",
          "url": "just_audio_release-0.66-sources.jar",
          "size": 12367,
          "sha512": "2eba84c4eaf56d746d92b9c441394d778f95430542c70651f53da2952bac03723ef9faa4a6fe0092e26552caa5c7ddfe39519196a362aad35816415e44fa74a5",
          "sha256": "cd77c71ce6d19744b96dececbdbd80a8a7b4885024a49f9ab338977af3d2d0d0",
          "sha1": "710a1b4889a1c3b4bbd706a40003c05e0193a9bc",
          "md5": "848ba57b390dfb54191e690b40ec57ed"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "just_audio_release-0.66-javadoc.jar",
          "url": "just_audio_release-0.66-javadoc.jar",
          "size": 298934,
          "sha512": "22bf735575a37f70b05a4c918daa198366a0fcbbdeb08842af5c73ae649ebaf783e56f74319bd99a12159971d56ba89994d20872043bbdd7fe3f39a64592a2fe",
          "sha256": "4c4f7df35c3b0a3fd84496c6f2e2e1cf6c0afba395d7eb143d80d10bdecb7aa0",
          "sha1": "176828d726bd0f9d3fcfb3883ce39bf9dce2c4d9",
          "md5": "63ed20f383f5247ebaacb3ab4150da35"
        }
      ]
    }
  ]
}
