{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.flutter_platform_alert",
    "module": "flutter_platform_alert_release",
    "version": "0.56",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_platform_alert_release-0.56.aar",
          "url": "flutter_platform_alert_release-0.56.aar",
          "size": 9160,
          "sha512": "39338f3f70951e3e7e67c9a5d270a284a6bcf6900f8f69ee4d7e3fd41dd34a9afa6a234c01a657bb185bba5450cd9c02992efb3d0966edcaffb7f876ccbd0b8b",
          "sha256": "c2eba9d7748bd0bc6459d65a286597355aeea298c747f6001f50804c1fb28435",
          "sha1": "c52d000cdb606ea9dee3641d355fcaabf54a26a7",
          "md5": "7430fb632c1ed9826a681f91efadf923"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.5.20"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_platform_alert_release-0.56.aar",
          "url": "flutter_platform_alert_release-0.56.aar",
          "size": 9160,
          "sha512": "39338f3f70951e3e7e67c9a5d270a284a6bcf6900f8f69ee4d7e3fd41dd34a9afa6a234c01a657bb185bba5450cd9c02992efb3d0966edcaffb7f876ccbd0b8b",
          "sha256": "c2eba9d7748bd0bc6459d65a286597355aeea298c747f6001f50804c1fb28435",
          "sha1": "c52d000cdb606ea9dee3641d355fcaabf54a26a7",
          "md5": "7430fb632c1ed9826a681f91efadf923"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_platform_alert_release-0.56-sources.jar",
          "url": "flutter_platform_alert_release-0.56-sources.jar",
          "size": 2419,
          "sha512": "0f2b22bac756a091326a6764355e2ee2c67d54d95ce2c038b9e91741917938070f40268ef2c8938684fb5110558c645f2617a325818b8f9f3fe7a70eec960812",
          "sha256": "0a5a52767371b2959d622148176f784c3054379097ee746859302933d68e85ad",
          "sha1": "5c714b72591bb9a3298241008d3df5fa6c53b609",
          "md5": "67fcd057752c94dc2ab62b41c059f6c0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_platform_alert_release-0.56-javadoc.jar",
          "url": "flutter_platform_alert_release-0.56-javadoc.jar",
          "size": 262836,
          "sha512": "ea56cb3b8249dfc98016011717c23b26ceeb929dc190b4647441f67bf5f9e27eba6293ef3e50e8459911272412f0f9c41a2e1555ef55db77c881b606f0f72aa4",
          "sha256": "815aae102b8a7e911735ef0990cff665d218344c1417bdaa55d478433271de3e",
          "sha1": "63b1570aeb3bf5c299fdbb8163f25c1951d1712a",
          "md5": "7b776b13da4060d51e0e1d1b004e604f"
        }
      ]
    }
  ]
}
