{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.fluttercommunity.plus.device_info",
    "module": "device_info_plus_release",
    "version": "0.65",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        }
      ],
      "files": [
        {
          "name": "device_info_plus_release-0.65.aar",
          "url": "device_info_plus_release-0.65.aar",
          "size": 6941,
          "sha512": "fea211d3ad74ae4b515c2707941973f24a2f4bfdef280327512dea982161c684997a5fd618950aa4bacf5f8c27cf608684067b6c56f823fcc3d7d6afdff8ee71",
          "sha256": "7d29bc694fff6d0bf36d82e5d39b3a902d471937efe4fe642dcba9282df6c595",
          "sha1": "1c8cf3d5d4270d9455ac184cade193f2a6a023da",
          "md5": "de6237d8eb8ccc921185153704dea100"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.22"
          }
        }
      ],
      "files": [
        {
          "name": "device_info_plus_release-0.65.aar",
          "url": "device_info_plus_release-0.65.aar",
          "size": 6941,
          "sha512": "fea211d3ad74ae4b515c2707941973f24a2f4bfdef280327512dea982161c684997a5fd618950aa4bacf5f8c27cf608684067b6c56f823fcc3d7d6afdff8ee71",
          "sha256": "7d29bc694fff6d0bf36d82e5d39b3a902d471937efe4fe642dcba9282df6c595",
          "sha1": "1c8cf3d5d4270d9455ac184cade193f2a6a023da",
          "md5": "de6237d8eb8ccc921185153704dea100"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "device_info_plus_release-0.65-sources.jar",
          "url": "device_info_plus_release-0.65-sources.jar",
          "size": 2976,
          "sha512": "b0a16c5d099d1a6d3f96d453ca4f34aa2b138d0729fd675fa4dadff9f54e169514b31bd5586b5d4fb388059df0d5e5ff8ceeeec9214322cced8b305c5d67afb3",
          "sha256": "1160189e3c750bbf50affba28a4dbf0fc1216e815a1f01a3d1d9dd17958f37ab",
          "sha1": "b1f985fbb38747f8f626c4988380b4847ff05db6",
          "md5": "7effa257187ed4394bf3919149a7d9e8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "device_info_plus_release-0.65-javadoc.jar",
          "url": "device_info_plus_release-0.65-javadoc.jar",
          "size": 260825,
          "sha512": "3120711bd67c799febbe4818bf0c75a3b1a3fdea216b8ccae27b457ef187495bbf06a610e9c8f752deecc46c18fcba4c667658d850fab1f5f13530bba5c0fa76",
          "sha256": "25958f74df0d9884b8af1b187e74845d86c46825aab94d96db40684639c03795",
          "sha1": "5ff56b3d8c9ff617e92a287a69c49bc5984c6a2d",
          "md5": "f9560c8229fb7e661f39bfd1a50d9e4c"
        }
      ]
    }
  ]
}
