{
  "formatVersion": "1.1",
  "component": {
    "group": "com.aboutyou.dart_packages.sign_in_with_apple",
    "module": "sign_in_with_apple_release",
    "version": "0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        }
      ],
      "files": [
        {
          "name": "sign_in_with_apple_release-0.3.aar",
          "url": "sign_in_with_apple_release-0.3.aar",
          "size": 9259,
          "sha512": "b88c9329301678e6c9b93650a6148902511f89b2f53b050a9fcfb015edd223a28c0e8eb24859d75fa82f3b211fdae85f54e9ed71818d4a38322d1a3c0e3977c7",
          "sha256": "b0dc4856e95b872b9373068340eb190e74c59cbb045588f4f874017bd631ba83",
          "sha1": "310100d78bc580d1edbfb95a712551eea7ba38e5",
          "md5": "2ddc4a40079941f83a112a08a3f936ce"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "sign_in_with_apple_release-0.3.aar",
          "url": "sign_in_with_apple_release-0.3.aar",
          "size": 9259,
          "sha512": "b88c9329301678e6c9b93650a6148902511f89b2f53b050a9fcfb015edd223a28c0e8eb24859d75fa82f3b211fdae85f54e9ed71818d4a38322d1a3c0e3977c7",
          "sha256": "b0dc4856e95b872b9373068340eb190e74c59cbb045588f4f874017bd631ba83",
          "sha1": "310100d78bc580d1edbfb95a712551eea7ba38e5",
          "md5": "2ddc4a40079941f83a112a08a3f936ce"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sign_in_with_apple_release-0.3-sources.jar",
          "url": "sign_in_with_apple_release-0.3-sources.jar",
          "size": 2730,
          "sha512": "232813b66653332be1825dda86c44197be6a6e5c4db974c29b5e382607c23c3453837625416f9ae13f991ba92f998f99dc25155e699a146881cd86e42431b316",
          "sha256": "3f74fc332e872fbcfdc3245f838f6f2e4704e5b0c6a0c865417757fad32ab9b4",
          "sha1": "227ee9e1b8ad1d2663b181163fd2a12db200cd6a",
          "md5": "57be615d4366529cd2aa5385e32ef800"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sign_in_with_apple_release-0.3-javadoc.jar",
          "url": "sign_in_with_apple_release-0.3-javadoc.jar",
          "size": 311956,
          "sha512": "ab48485b2226af45d2305a7246653fbda614ff72142d20bb228b15bd3e72ea12deb16db2b20eb981394d85f00d6bbf4376cfa487a2e16ffffdad8ea8da73dd8c",
          "sha256": "d9b267c2c77f639d44b57cbb312f3c9ad5fdbce19add6eedb3cfdcb0e5f827c9",
          "sha1": "9006e952132b25c52b219154ce8d44ddeccbd899",
          "md5": "01c035a0b17d002cb3e24fefab01c528"
        }
      ]
    }
  ]
}
