{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.fluttercommunity.plus.device_info",
    "module": "device_info_plus_release",
    "version": "0.43",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        }
      ],
      "files": [
        {
          "name": "device_info_plus_release-0.43.aar",
          "url": "device_info_plus_release-0.43.aar",
          "size": 6941,
          "sha512": "fea211d3ad74ae4b515c2707941973f24a2f4bfdef280327512dea982161c684997a5fd618950aa4bacf5f8c27cf608684067b6c56f823fcc3d7d6afdff8ee71",
          "sha256": "7d29bc694fff6d0bf36d82e5d39b3a902d471937efe4fe642dcba9282df6c595",
          "sha1": "1c8cf3d5d4270d9455ac184cade193f2a6a023da",
          "md5": "de6237d8eb8ccc921185153704dea100"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.22"
          }
        }
      ],
      "files": [
        {
          "name": "device_info_plus_release-0.43.aar",
          "url": "device_info_plus_release-0.43.aar",
          "size": 6941,
          "sha512": "fea211d3ad74ae4b515c2707941973f24a2f4bfdef280327512dea982161c684997a5fd618950aa4bacf5f8c27cf608684067b6c56f823fcc3d7d6afdff8ee71",
          "sha256": "7d29bc694fff6d0bf36d82e5d39b3a902d471937efe4fe642dcba9282df6c595",
          "sha1": "1c8cf3d5d4270d9455ac184cade193f2a6a023da",
          "md5": "de6237d8eb8ccc921185153704dea100"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "device_info_plus_release-0.43-sources.jar",
          "url": "device_info_plus_release-0.43-sources.jar",
          "size": 2976,
          "sha512": "b0a16c5d099d1a6d3f96d453ca4f34aa2b138d0729fd675fa4dadff9f54e169514b31bd5586b5d4fb388059df0d5e5ff8ceeeec9214322cced8b305c5d67afb3",
          "sha256": "1160189e3c750bbf50affba28a4dbf0fc1216e815a1f01a3d1d9dd17958f37ab",
          "sha1": "b1f985fbb38747f8f626c4988380b4847ff05db6",
          "md5": "7effa257187ed4394bf3919149a7d9e8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "device_info_plus_release-0.43-javadoc.jar",
          "url": "device_info_plus_release-0.43-javadoc.jar",
          "size": 260825,
          "sha512": "b49e1478e2b6b164df51da963f47cc4abed31ea15bd2840151ddbd4060d862874afa47a4b5a900f8ca63b147f34c6fda28c9086f4023be727cff32eee082a76b",
          "sha256": "17f25ce56cde66798b36a51523f91d428642b049b02d8223fe163c0edb333714",
          "sha1": "379a09adda5f50da26bad09306b8d781afc54d5b",
          "md5": "f4870540af376db3d00b84815ddfd8e9"
        }
      ]
    }
  ]
}
