{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.flutter_platform_alert",
    "module": "flutter_platform_alert_release",
    "version": "0.17",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_platform_alert_release-0.17.aar",
          "url": "flutter_platform_alert_release-0.17.aar",
          "size": 9179,
          "sha512": "bad7c4a8191fa519b3bb6457cd0204c53495101ecbed5e538c5aa1931df4dd7957a96f1c73c7696cfab1fef0210ae8d666900ba3fc188aea363b04a80caafb08",
          "sha256": "01e1888ef153eafb5a2b674cd05ee15fc2134b51964d4bbbb88ecdada208929d",
          "sha1": "49be972bb11cbfae15874fa7651a8bb0cbdfefe1",
          "md5": "2bc8722ee75445f7666fabf6e6e275ad"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.5.20"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_platform_alert_release-0.17.aar",
          "url": "flutter_platform_alert_release-0.17.aar",
          "size": 9179,
          "sha512": "bad7c4a8191fa519b3bb6457cd0204c53495101ecbed5e538c5aa1931df4dd7957a96f1c73c7696cfab1fef0210ae8d666900ba3fc188aea363b04a80caafb08",
          "sha256": "01e1888ef153eafb5a2b674cd05ee15fc2134b51964d4bbbb88ecdada208929d",
          "sha1": "49be972bb11cbfae15874fa7651a8bb0cbdfefe1",
          "md5": "2bc8722ee75445f7666fabf6e6e275ad"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_platform_alert_release-0.17-sources.jar",
          "url": "flutter_platform_alert_release-0.17-sources.jar",
          "size": 2419,
          "sha512": "0f2b22bac756a091326a6764355e2ee2c67d54d95ce2c038b9e91741917938070f40268ef2c8938684fb5110558c645f2617a325818b8f9f3fe7a70eec960812",
          "sha256": "0a5a52767371b2959d622148176f784c3054379097ee746859302933d68e85ad",
          "sha1": "5c714b72591bb9a3298241008d3df5fa6c53b609",
          "md5": "67fcd057752c94dc2ab62b41c059f6c0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_platform_alert_release-0.17-javadoc.jar",
          "url": "flutter_platform_alert_release-0.17-javadoc.jar",
          "size": 262915,
          "sha512": "a91b8d3691e8679d493c5764ef40093eb2336b6027028742edd970f1f77fce4e3d5fd559596cb3ef96e55d38ec4cb5cedb1529f6f0bb04e18d91727b8156ff47",
          "sha256": "1a18970bac72e79c554f10231dc60af9c85d57976c3325615362f477fc2b8734",
          "sha1": "b6f592ab96d15e771089b3a1cfb58021bcf88e27",
          "md5": "2ce8a4a3d8bb3d422c8a561405529fbe"
        }
      ]
    }
  ]
}
