{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.firebaseperformance",
    "module": "firebase_performance_release",
    "version": "0.66",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.core",
          "module": "firebase_core_release",
          "version": {
            "requires": "0.66"
          }
        }
      ],
      "files": [
        {
          "name": "firebase_performance_release-0.66.aar",
          "url": "firebase_performance_release-0.66.aar",
          "size": 8698,
          "sha512": "0e26e591695864c1be2ccd3f54c9d4ea079d92dcb3fa62797c1bc0365cf46f3ac04fd908164b57b4934c7c8ed01906d1752f74722e751a7338ac9e77cc9faca5",
          "sha256": "a4f00e555592fe39fccee1089bd8b85a4779f51bfa0132f2ac7792db8b6576a9",
          "sha1": "0eb8f7750cd97b193f1868798d071ab82870dcfc",
          "md5": "3319ae5cd2558367b6ac50ba26e0b971"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-bom",
          "version": {
            "requires": "33.1.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-perf"
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.core",
          "module": "firebase_core_release",
          "version": {
            "requires": "0.66"
          }
        }
      ],
      "files": [
        {
          "name": "firebase_performance_release-0.66.aar",
          "url": "firebase_performance_release-0.66.aar",
          "size": 8698,
          "sha512": "0e26e591695864c1be2ccd3f54c9d4ea079d92dcb3fa62797c1bc0365cf46f3ac04fd908164b57b4934c7c8ed01906d1752f74722e751a7338ac9e77cc9faca5",
          "sha256": "a4f00e555592fe39fccee1089bd8b85a4779f51bfa0132f2ac7792db8b6576a9",
          "sha1": "0eb8f7750cd97b193f1868798d071ab82870dcfc",
          "md5": "3319ae5cd2558367b6ac50ba26e0b971"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "firebase_performance_release-0.66-sources.jar",
          "url": "firebase_performance_release-0.66-sources.jar",
          "size": 4416,
          "sha512": "e05188ba1a224e845647dbd0e51cf2630683c31b7e009c7a2ad5bd7d1554d3c760af682404790b367a2ed5ab85c727c348c610a2364493c9b0dc756c27c56387",
          "sha256": "6a2e6a6b4cc443ba1b22a623738c62e95164ee6525e8595b00f02c2c046b25b3",
          "sha1": "6d0fe455ff284025536fd21e9adf9d5f356e703e",
          "md5": "a4f365cb56dd71144c7246719d32b4bb"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "firebase_performance_release-0.66-javadoc.jar",
          "url": "firebase_performance_release-0.66-javadoc.jar",
          "size": 273486,
          "sha512": "697879fe7c656ee73f3cd61e26ab99fe79cd5c1c3d48e2e1d6f7880359e8f0a7b284d79cd8564aefdd581a77e5eca97fc2c06b5e8a1c29e1f1a1d6e096df5a5e",
          "sha256": "7f9919e4084dca3664690d0a94ea298340641ff445039977d83f5a5156f77f27",
          "sha1": "706db30390d824ee10a48bc01646755fbff6b47a",
          "md5": "50f551d2784c06c093179f17cab5a8bf"
        }
      ]
    }
  ]
}
