{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.fluttercommunity.plus.device_info",
    "module": "device_info_plus_release",
    "version": "0.30",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        }
      ],
      "files": [
        {
          "name": "device_info_plus_release-0.30.aar",
          "url": "device_info_plus_release-0.30.aar",
          "size": 6945,
          "sha512": "8598418a70a204b4f6ec104ea541d3066f7713466160a125b82f913027bdd906eab816227a6416b4b76d1a2820915c3810d31921994b6549942f5fcd4d2fd946",
          "sha256": "2b71c14a493ed2d5dcdc0b03af3db168b8a31d5795dcab90a24d355c2d78dc42",
          "sha1": "6db7d849fe908ef67028705c65026bbc9623c8ef",
          "md5": "83f964088c0477c673f44f450ec1b13a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.22"
          }
        }
      ],
      "files": [
        {
          "name": "device_info_plus_release-0.30.aar",
          "url": "device_info_plus_release-0.30.aar",
          "size": 6945,
          "sha512": "8598418a70a204b4f6ec104ea541d3066f7713466160a125b82f913027bdd906eab816227a6416b4b76d1a2820915c3810d31921994b6549942f5fcd4d2fd946",
          "sha256": "2b71c14a493ed2d5dcdc0b03af3db168b8a31d5795dcab90a24d355c2d78dc42",
          "sha1": "6db7d849fe908ef67028705c65026bbc9623c8ef",
          "md5": "83f964088c0477c673f44f450ec1b13a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "device_info_plus_release-0.30-sources.jar",
          "url": "device_info_plus_release-0.30-sources.jar",
          "size": 2976,
          "sha512": "b0a16c5d099d1a6d3f96d453ca4f34aa2b138d0729fd675fa4dadff9f54e169514b31bd5586b5d4fb388059df0d5e5ff8ceeeec9214322cced8b305c5d67afb3",
          "sha256": "1160189e3c750bbf50affba28a4dbf0fc1216e815a1f01a3d1d9dd17958f37ab",
          "sha1": "b1f985fbb38747f8f626c4988380b4847ff05db6",
          "md5": "7effa257187ed4394bf3919149a7d9e8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "device_info_plus_release-0.30-javadoc.jar",
          "url": "device_info_plus_release-0.30-javadoc.jar",
          "size": 260893,
          "sha512": "eca891e0262c1419559fb391d5e5a2562d8660c56c2ac4240fa04b99bcfd3be4313eb95471a5dafac86085b1a1ffcd585253966fd187be4ffc80cc6b299b3dd0",
          "sha256": "f2b8da87f72a7640c6c432510e3d506c1a8546f3be5e20b2c3fa28026852d3f8",
          "sha1": "d5d043cabedfeeb1af0a9be3e8933bbe4a1fface",
          "md5": "2e1e15df1537daae9738c0249a0d7f7d"
        }
      ]
    }
  ]
}
