{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.fluttercommunity.plus.device_info",
    "module": "device_info_plus_release",
    "version": "0.26",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        }
      ],
      "files": [
        {
          "name": "device_info_plus_release-0.26.aar",
          "url": "device_info_plus_release-0.26.aar",
          "size": 6945,
          "sha512": "8598418a70a204b4f6ec104ea541d3066f7713466160a125b82f913027bdd906eab816227a6416b4b76d1a2820915c3810d31921994b6549942f5fcd4d2fd946",
          "sha256": "2b71c14a493ed2d5dcdc0b03af3db168b8a31d5795dcab90a24d355c2d78dc42",
          "sha1": "6db7d849fe908ef67028705c65026bbc9623c8ef",
          "md5": "83f964088c0477c673f44f450ec1b13a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.22"
          }
        }
      ],
      "files": [
        {
          "name": "device_info_plus_release-0.26.aar",
          "url": "device_info_plus_release-0.26.aar",
          "size": 6945,
          "sha512": "8598418a70a204b4f6ec104ea541d3066f7713466160a125b82f913027bdd906eab816227a6416b4b76d1a2820915c3810d31921994b6549942f5fcd4d2fd946",
          "sha256": "2b71c14a493ed2d5dcdc0b03af3db168b8a31d5795dcab90a24d355c2d78dc42",
          "sha1": "6db7d849fe908ef67028705c65026bbc9623c8ef",
          "md5": "83f964088c0477c673f44f450ec1b13a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "device_info_plus_release-0.26-sources.jar",
          "url": "device_info_plus_release-0.26-sources.jar",
          "size": 2976,
          "sha512": "b0a16c5d099d1a6d3f96d453ca4f34aa2b138d0729fd675fa4dadff9f54e169514b31bd5586b5d4fb388059df0d5e5ff8ceeeec9214322cced8b305c5d67afb3",
          "sha256": "1160189e3c750bbf50affba28a4dbf0fc1216e815a1f01a3d1d9dd17958f37ab",
          "sha1": "b1f985fbb38747f8f626c4988380b4847ff05db6",
          "md5": "7effa257187ed4394bf3919149a7d9e8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "device_info_plus_release-0.26-javadoc.jar",
          "url": "device_info_plus_release-0.26-javadoc.jar",
          "size": 260894,
          "sha512": "a9697f4b5a738eb70add5c171e1fc07488d670fe22634cfcf8ba5c5e30ec558ca618445fecb7519e1b07199b25d6902b491f4a19d2e56584e59faf1a723f24b2",
          "sha256": "a4cf5150f3d79a1767cbc66d96b82bcb5f2b90b2cd81ce0f3c75f466ff05bef3",
          "sha1": "d5fa7c8c8ef82a152252b8fb6392b32a80ab1238",
          "md5": "10fd36ca0587cb87d7cd7faeb614d79e"
        }
      ]
    }
  ]
}
