{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.fluttercommunity.plus.device_info",
    "module": "device_info_plus_release",
    "version": "0.45",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        }
      ],
      "files": [
        {
          "name": "device_info_plus_release-0.45.aar",
          "url": "device_info_plus_release-0.45.aar",
          "size": 6941,
          "sha512": "fea211d3ad74ae4b515c2707941973f24a2f4bfdef280327512dea982161c684997a5fd618950aa4bacf5f8c27cf608684067b6c56f823fcc3d7d6afdff8ee71",
          "sha256": "7d29bc694fff6d0bf36d82e5d39b3a902d471937efe4fe642dcba9282df6c595",
          "sha1": "1c8cf3d5d4270d9455ac184cade193f2a6a023da",
          "md5": "de6237d8eb8ccc921185153704dea100"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.22"
          }
        }
      ],
      "files": [
        {
          "name": "device_info_plus_release-0.45.aar",
          "url": "device_info_plus_release-0.45.aar",
          "size": 6941,
          "sha512": "fea211d3ad74ae4b515c2707941973f24a2f4bfdef280327512dea982161c684997a5fd618950aa4bacf5f8c27cf608684067b6c56f823fcc3d7d6afdff8ee71",
          "sha256": "7d29bc694fff6d0bf36d82e5d39b3a902d471937efe4fe642dcba9282df6c595",
          "sha1": "1c8cf3d5d4270d9455ac184cade193f2a6a023da",
          "md5": "de6237d8eb8ccc921185153704dea100"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "device_info_plus_release-0.45-sources.jar",
          "url": "device_info_plus_release-0.45-sources.jar",
          "size": 2976,
          "sha512": "b0a16c5d099d1a6d3f96d453ca4f34aa2b138d0729fd675fa4dadff9f54e169514b31bd5586b5d4fb388059df0d5e5ff8ceeeec9214322cced8b305c5d67afb3",
          "sha256": "1160189e3c750bbf50affba28a4dbf0fc1216e815a1f01a3d1d9dd17958f37ab",
          "sha1": "b1f985fbb38747f8f626c4988380b4847ff05db6",
          "md5": "7effa257187ed4394bf3919149a7d9e8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "device_info_plus_release-0.45-javadoc.jar",
          "url": "device_info_plus_release-0.45-javadoc.jar",
          "size": 260825,
          "sha512": "1b127392b5bca1f9ddf7aadf427cc0ae385fcd4247200138d07052f46a13bfd0438853c6f4acefb562876b4b7e2d4ac236e757a094e767b6438b9ea56f36b947",
          "sha256": "052a9570ca42298a77bb6b3ecda305f4473dfe6ceefa9681e44ad307aaca9b46",
          "sha1": "bd26469ac3123b4efb11865462176be5512e4d14",
          "md5": "481dca1f3d87c9c1a2cb383c272fc98e"
        }
      ]
    }
  ]
}
