{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.imagepicker",
    "module": "image_picker_android_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        }
      ],
      "files": [
        {
          "name": "image_picker_android_debug-1.0.aar",
          "url": "image_picker_android_debug-1.0.aar",
          "size": 73728,
          "sha512": "f6ad1f771c2a812ff3d760d7fa4c43a32a8b288678503841c436b817ca975e248c8893a0b54b832286ef63b7a304eecd468620bdf151df6723c2ea24c44b0ba9",
          "sha256": "8cb05d3769680a29511f291d485e4ab2d5dfdf5ca807452a2a06bb33357aef23",
          "sha1": "1ed97f4097641b58c142fc9f76a11f2d7aa36ff6",
          "md5": "0abc363d7c90081a67834275662ae517"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.7"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.9.3"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_debug",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "image_picker_android_debug-1.0.aar",
          "url": "image_picker_android_debug-1.0.aar",
          "size": 73728,
          "sha512": "f6ad1f771c2a812ff3d760d7fa4c43a32a8b288678503841c436b817ca975e248c8893a0b54b832286ef63b7a304eecd468620bdf151df6723c2ea24c44b0ba9",
          "sha256": "8cb05d3769680a29511f291d485e4ab2d5dfdf5ca807452a2a06bb33357aef23",
          "sha1": "1ed97f4097641b58c142fc9f76a11f2d7aa36ff6",
          "md5": "0abc363d7c90081a67834275662ae517"
        }
      ]
    },
    {
      "name": "debugVariantDebugSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "image_picker_android_debug-1.0-sources.jar",
          "url": "image_picker_android_debug-1.0-sources.jar",
          "size": 26710,
          "sha512": "372c55c93aa9de3bc39caaa735c8e9f72983fb2a602de7ddd3be0527b8ab1f43bb8f5583d2ec4a8e3b61d6eb874e7e4cf34c0f725649e2d8806f4a45f0225e35",
          "sha256": "3cab7df6aafaac4936a8156024350f81aff0ce6ff88a827513403c895316ab3e",
          "sha1": "50f46bd80d3ea3246d7442d73c95694a4deafe04",
          "md5": "0651b7414a10b08945561bd62b096625"
        }
      ]
    },
    {
      "name": "debugVariantDebugJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "image_picker_android_debug-1.0-javadoc.jar",
          "url": "image_picker_android_debug-1.0-javadoc.jar",
          "size": 383482,
          "sha512": "938a99829fdab10121e52ef4687b41a863a4258524d778705b95c03174b1a8b2dd527e77d6fceca6f713630025d9e611cb27f031140133c2ae56cfe56405eadb",
          "sha256": "154b315930e4f27a333c7e5c9f8a956e344899267572e2e910843c05e213d811",
          "sha1": "510e9e74109c1bc3acc72476d399aa7432a0c5ca",
          "md5": "5e31df544502eead83bcb8eb1fad24a7"
        }
      ]
    }
  ]
}
