{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dexterous.flutterlocalnotifications",
    "module": "flutter_local_notifications_release",
    "version": "0.47",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_local_notifications_release-0.47.aar",
          "url": "flutter_local_notifications_release-0.47.aar",
          "size": 81397,
          "sha512": "badae51c21a557fdd0f0537a0297a394c1216a0600a71576ece95fe97c56438ae36e09341f3720dfffc70e2464d0564171eee341526449ffcfd3ed85a4555caf",
          "sha256": "8eba8e1028ea9776c2681ab6d9ade65f5226ea0c2a3d935858e0d4b684da258c",
          "sha1": "3ed1756f9da09eec41408c768dec774a55b55112",
          "md5": "8b5d80d59711f4175f3afe2cb44cf26c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.media",
          "module": "media",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.9"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_local_notifications_release-0.47.aar",
          "url": "flutter_local_notifications_release-0.47.aar",
          "size": 81397,
          "sha512": "badae51c21a557fdd0f0537a0297a394c1216a0600a71576ece95fe97c56438ae36e09341f3720dfffc70e2464d0564171eee341526449ffcfd3ed85a4555caf",
          "sha256": "8eba8e1028ea9776c2681ab6d9ade65f5226ea0c2a3d935858e0d4b684da258c",
          "sha1": "3ed1756f9da09eec41408c768dec774a55b55112",
          "md5": "8b5d80d59711f4175f3afe2cb44cf26c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_local_notifications_release-0.47-sources.jar",
          "url": "flutter_local_notifications_release-0.47-sources.jar",
          "size": 43596,
          "sha512": "7736acb5954d99f56cb46af46dd8581b373482a317c78c9b99eb6fc6eb8ca140082025906c97406c3b82586029c0e86a3f0d69c96023384abdd8ea46e6bf48d4",
          "sha256": "fc7f32461f268b0581bc3c5c9e2c0d81a79252cb0cf09a351bb0bdffe4993ea6",
          "sha1": "c3fb9f6ef65dc6aff958aa612beca1e2ae4a96c0",
          "md5": "5de3e43acd23922d52c9900575889eda"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_local_notifications_release-0.47-javadoc.jar",
          "url": "flutter_local_notifications_release-0.47-javadoc.jar",
          "size": 417415,
          "sha512": "96265d37338a017c4519bd293916d5d2cdf58faba785ce5315630cc3eec186cc5f935577fb7469c24021c259f3763b4a92267bd263afccc47f2e592217d02c0c",
          "sha256": "e4ecf1d2993fa875b8a4e7e72057373a82c8928a021199d2faf0a475cf487438",
          "sha1": "8663222af2a2083e40ee02182ff992b6eac4db04",
          "md5": "5aec1b34e9d9e1a701dc878ab0752c14"
        }
      ]
    }
  ]
}
