{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
    "module": "flutter_plugin_android_lifecycle_release",
    "version": "0.20",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_plugin_android_lifecycle_release-0.20.aar",
          "url": "flutter_plugin_android_lifecycle_release-0.20.aar",
          "size": 2503,
          "sha512": "c47015d3684b3b1a0cef077b1929cbe61ffaa4f3d8ec078ed4279cb7aa1ada9dc8e0f337ea5b9159a936cc75e63540eb8e70c1088a32642ceff62862fe1374f9",
          "sha256": "9fb4cf8d054e60d0bf6d639cfacc66db8aab776059fd0e9b67ace8c60d169d65",
          "sha1": "e526db6513439eebf917c63e27fa7b9d969a4d2d",
          "md5": "89a4374677faa54c80076e99a9da11a4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_plugin_android_lifecycle_release-0.20.aar",
          "url": "flutter_plugin_android_lifecycle_release-0.20.aar",
          "size": 2503,
          "sha512": "c47015d3684b3b1a0cef077b1929cbe61ffaa4f3d8ec078ed4279cb7aa1ada9dc8e0f337ea5b9159a936cc75e63540eb8e70c1088a32642ceff62862fe1374f9",
          "sha256": "9fb4cf8d054e60d0bf6d639cfacc66db8aab776059fd0e9b67ace8c60d169d65",
          "sha1": "e526db6513439eebf917c63e27fa7b9d969a4d2d",
          "md5": "89a4374677faa54c80076e99a9da11a4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_plugin_android_lifecycle_release-0.20-sources.jar",
          "url": "flutter_plugin_android_lifecycle_release-0.20-sources.jar",
          "size": 2683,
          "sha512": "a3f7fee602ae01e1fe53ad82c914db15159744a75a0e4f439cdbe5e530abf6d3b431e26802ccd3cf08245278758e1aef335a9e00aec7ded1b1c89a60a53d7915",
          "sha256": "ea22384264efbced6ae1be61be8aadee870b81c3a1e0b6accc0ef62396aaeae0",
          "sha1": "1ddcac6e1149d882ff8719e00a4eebfeb282eb36",
          "md5": "351ed496e751473b57d20e3a693b432d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_plugin_android_lifecycle_release-0.20-javadoc.jar",
          "url": "flutter_plugin_android_lifecycle_release-0.20-javadoc.jar",
          "size": 269939,
          "sha512": "946a9ead247a3ea40eb6d231cd2de9d106645c1a83f700093e139584c7b795417895154523c879eb20ca2785dec993dc176eb73cff963d4477701adf1b3124c6",
          "sha256": "53c6c5f42fa8972171f487fc6d17c5700a4bba96db80eccaff424cdf744949dc",
          "sha1": "ee45f4091b248613ceb13e92f275e1ff735de068",
          "md5": "d877856fe14e0dbf429ab7ec797c49bf"
        }
      ]
    }
  ]
}
