{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.googlesignin",
    "module": "google_sign_in_android_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        }
      ],
      "files": [
        {
          "name": "google_sign_in_android_debug-1.0.aar",
          "url": "google_sign_in_android_debug-1.0.aar",
          "size": 34264,
          "sha512": "b8436c736d6780a64db0ca639ae792a8aab8fbfe54a8fc3cbf384674394ea5e2bd0bbc734381bee388da2d1013edb4dc51928513910711c9f06c7cca254125f5",
          "sha256": "470222889e0d07905fd8755c71e988aab19fb4ee7be16c25f9ae55cc39840c78",
          "sha1": "1967a97ecc5cd75ce1f3e9ad9999c13322f77814",
          "md5": "b0b1a7c0c3d625c8ccdfb952a8ebc9b0"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-auth",
          "version": {
            "requires": "21.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "google_sign_in_android_debug-1.0.aar",
          "url": "google_sign_in_android_debug-1.0.aar",
          "size": 34264,
          "sha512": "b8436c736d6780a64db0ca639ae792a8aab8fbfe54a8fc3cbf384674394ea5e2bd0bbc734381bee388da2d1013edb4dc51928513910711c9f06c7cca254125f5",
          "sha256": "470222889e0d07905fd8755c71e988aab19fb4ee7be16c25f9ae55cc39840c78",
          "sha1": "1967a97ecc5cd75ce1f3e9ad9999c13322f77814",
          "md5": "b0b1a7c0c3d625c8ccdfb952a8ebc9b0"
        }
      ]
    },
    {
      "name": "debugVariantDebugSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "google_sign_in_android_debug-1.0-sources.jar",
          "url": "google_sign_in_android_debug-1.0-sources.jar",
          "size": 11750,
          "sha512": "a076a3ab2783e9605712cd675db915170332f1c10199520e8ed282e612a187bdbf9cf5246f89dab12bee5aff0ae0af14b198eb1941d0bd944f3516b83e29ffcf",
          "sha256": "ffbebf33efe5de1e2686c7927d0c094af8b35912b055a4d423dd80713b1b8f14",
          "sha1": "561a2032af2f873ddae6450d0cad46aa82a5a2cb",
          "md5": "7655baa785bb4b603c84ef864a8625ab"
        }
      ]
    },
    {
      "name": "debugVariantDebugJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "google_sign_in_android_debug-1.0-javadoc.jar",
          "url": "google_sign_in_android_debug-1.0-javadoc.jar",
          "size": 334873,
          "sha512": "2b787fc4c8960163490e2316db383d857ce59ec5a1f02be883db32dda54b4fdae29ee75f9582ab6c41670c000b2bab9a96b1b0c034f7e5a73218cc312a725fe7",
          "sha256": "fc4dc38097ad7b05f3189bbe7ad7935dd02522ec521025198d57f42435b67b48",
          "sha1": "010f0be1268e6bd3f62a9a73cbb45a4ae64b667a",
          "md5": "b51390b4b3c1c65ac2f0d934d10e2970"
        }
      ]
    }
  ]
}
