{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.imagepicker",
    "module": "image_picker_android_release",
    "version": "0.49",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        }
      ],
      "files": [
        {
          "name": "image_picker_android_release-0.49.aar",
          "url": "image_picker_android_release-0.49.aar",
          "size": 69969,
          "sha512": "0f6c819d7b2a55201017c93deb6963fee7fb5d9072d2fb3658d14c5a16f61653b02d38b719715da377bfe37fbc87c2506095f7a922e3c1794df7957ae4109191",
          "sha256": "cc2613df28e9c1543645d013b580c09cc68c8014726fb7b5b0532404b06a9e07",
          "sha1": "8fd47c92b3b365e3dc064d0bf591c604e2c98f24",
          "md5": "e677c6d8d2b88479e6f77248b37f28b8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.7"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.9.3"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_release",
          "version": {
            "requires": "0.49"
          }
        }
      ],
      "files": [
        {
          "name": "image_picker_android_release-0.49.aar",
          "url": "image_picker_android_release-0.49.aar",
          "size": 69969,
          "sha512": "0f6c819d7b2a55201017c93deb6963fee7fb5d9072d2fb3658d14c5a16f61653b02d38b719715da377bfe37fbc87c2506095f7a922e3c1794df7957ae4109191",
          "sha256": "cc2613df28e9c1543645d013b580c09cc68c8014726fb7b5b0532404b06a9e07",
          "sha1": "8fd47c92b3b365e3dc064d0bf591c604e2c98f24",
          "md5": "e677c6d8d2b88479e6f77248b37f28b8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "image_picker_android_release-0.49-sources.jar",
          "url": "image_picker_android_release-0.49-sources.jar",
          "size": 26710,
          "sha512": "372c55c93aa9de3bc39caaa735c8e9f72983fb2a602de7ddd3be0527b8ab1f43bb8f5583d2ec4a8e3b61d6eb874e7e4cf34c0f725649e2d8806f4a45f0225e35",
          "sha256": "3cab7df6aafaac4936a8156024350f81aff0ce6ff88a827513403c895316ab3e",
          "sha1": "50f46bd80d3ea3246d7442d73c95694a4deafe04",
          "md5": "0651b7414a10b08945561bd62b096625"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "image_picker_android_release-0.49-javadoc.jar",
          "url": "image_picker_android_release-0.49-javadoc.jar",
          "size": 382951,
          "sha512": "dbf78642d99e9d0b561d9816bb5a6d1ed1d9977e3c5ed5a2e5ce7b3930607503cfabe7f139ad2c5ce2fc5896a39171b09e7acd0e3e32f08be664589194682c59",
          "sha256": "56fb672679383c2bb6130bb045b7871e37bcfb3cbb9f314cb171edd29f6fab55",
          "sha1": "8f13a96f1fa676b97a39cb66cd96e9502b5f29dc",
          "md5": "70b852afc9306863662ff4725c96c563"
        }
      ]
    }
  ]
}
