{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.fluttercommunity.plus.sensors",
    "module": "sensors_plus_release",
    "version": "0.15",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        }
      ],
      "files": [
        {
          "name": "sensors_plus_release-0.15.aar",
          "url": "sensors_plus_release-0.15.aar",
          "size": 9113,
          "sha512": "d55cb7f95ac827fff80c5d3e89418b18fcd6549e6913c47970aff5c3c48a482cff9ceef905208fffc0412274249f24e073dc5b530185fd462de057b1972b3b81",
          "sha256": "4f57145ecd872831400d12658da98ab1bd04af6587f8550f3de4edc241b739e6",
          "sha1": "0d417d560269f4d408c3f60ebc2a20905e1d04e8",
          "md5": "54eb0861a5278c6fd17aa5b06e8ac348"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.22"
          }
        }
      ],
      "files": [
        {
          "name": "sensors_plus_release-0.15.aar",
          "url": "sensors_plus_release-0.15.aar",
          "size": 9113,
          "sha512": "d55cb7f95ac827fff80c5d3e89418b18fcd6549e6913c47970aff5c3c48a482cff9ceef905208fffc0412274249f24e073dc5b530185fd462de057b1972b3b81",
          "sha256": "4f57145ecd872831400d12658da98ab1bd04af6587f8550f3de4edc241b739e6",
          "sha1": "0d417d560269f4d408c3f60ebc2a20905e1d04e8",
          "md5": "54eb0861a5278c6fd17aa5b06e8ac348"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sensors_plus_release-0.15-sources.jar",
          "url": "sensors_plus_release-0.15-sources.jar",
          "size": 3078,
          "sha512": "ff8c14ac129b7e7d57ba1c1d48a7bd51656b3a77eccd557666bdf8a3b0172ecca0df5ba81b9ebbe8d029f941c22d8f18a241481915f11253f61492bda395d5e3",
          "sha256": "bc48e760fb87da67a364f00faddba3a1e477beac55f4ede297734f50cf1cd795",
          "sha1": "6b5cb27f9ac4f036dc8728014deb48440cb4dfba",
          "md5": "19db92f4ba177bdc11b351b78aa144de"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sensors_plus_release-0.15-javadoc.jar",
          "url": "sensors_plus_release-0.15-javadoc.jar",
          "size": 264783,
          "sha512": "fcfed5c8de11248baf09f5c6324d0dae5fffaeeaf08e0bcaa46a7b00b751026315a72342f5fdaabfe47874f5f405b0604ee7085d05dff313d645fc2d512b381c",
          "sha256": "d2a999578f9de88d71f11dc1452c043be85091fee835ac6bd415fd555e6ac525",
          "sha1": "ca026cb78ac92bfac1936ca24975d512e7a5e35e",
          "md5": "65b9b88edcb1a97c7665ee9cf871a85d"
        }
      ]
    }
  ]
}
