{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.steenbakker.mobile_scanner",
    "module": "mobile_scanner_release",
    "version": "0.56",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "mobile_scanner_release-0.56.aar",
          "url": "mobile_scanner_release-0.56.aar",
          "size": 68127,
          "sha512": "261024b0f205a19ad13b01a85075cc11e665bf173039d67e7fdde56ade6a819d6f41ca42d78c7b81e0540f61596fce556580f1dd39e6f4a1cf5e911e7b3e25d4",
          "sha256": "32d87469213d3c0c3b361c98e37eb9627231f660698ec1ff94bab2584015c711",
          "sha1": "b3fea64dc66b3f70b90df15ae16824f67b0a37f8",
          "md5": "2558c7e9981a3ffc339ed2758f91950b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        },
        {
          "group": "com.google.mlkit",
          "module": "barcode-scanning",
          "version": {
            "requires": "17.3.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.3.4"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.3.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "mobile_scanner_release-0.56.aar",
          "url": "mobile_scanner_release-0.56.aar",
          "size": 68127,
          "sha512": "261024b0f205a19ad13b01a85075cc11e665bf173039d67e7fdde56ade6a819d6f41ca42d78c7b81e0540f61596fce556580f1dd39e6f4a1cf5e911e7b3e25d4",
          "sha256": "32d87469213d3c0c3b361c98e37eb9627231f660698ec1ff94bab2584015c711",
          "sha1": "b3fea64dc66b3f70b90df15ae16824f67b0a37f8",
          "md5": "2558c7e9981a3ffc339ed2758f91950b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "mobile_scanner_release-0.56-sources.jar",
          "url": "mobile_scanner_release-0.56-sources.jar",
          "size": 20090,
          "sha512": "d3362bed54acd1325cb709f17d94411437ca5b2f26cbf04bee894c45a1014964f855f9869cfa4d57be601465f6af445a644a3b756f1fe922cb86ea7dd856faed",
          "sha256": "d83d054e3d529b76cfe1b623f586029ca1492f55dd21a3d0a20a33654ac085cd",
          "sha1": "e46370da755c3f10ba18bb11111dfda70707b9d0",
          "md5": "020546aa5e6a0183f636d87d2e226082"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "mobile_scanner_release-0.56-javadoc.jar",
          "url": "mobile_scanner_release-0.56-javadoc.jar",
          "size": 380217,
          "sha512": "b6d2d59f26568783353648837e9f63ace30073cd321dde9e1a9808738549d23e65e3fef428390a6fa753084cf381013ecaecc6df4be9b212663302dcdfc192a3",
          "sha256": "51040f22e4cc2b951ac0733abe8c160cd074862b7c7040bd7391c749ad2e44b9",
          "sha1": "5854ac22749b9668b26ef3b0ad52e11349c696af",
          "md5": "50d77801ac124a99671700c6a8688e50"
        }
      ]
    }
  ]
}
