{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.fluttercommunity.plus.share",
    "module": "share_plus_release",
    "version": "0.64",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        }
      ],
      "files": [
        {
          "name": "share_plus_release-0.64.aar",
          "url": "share_plus_release-0.64.aar",
          "size": 18506,
          "sha512": "d01ce2353d0dab5fafb9e9ed267db72428cd8615f0f368876cd4e3c5ff650bf0ea2c4602495fc5c0d6070865a9a57ecbf7df24923b7390d17291511acb19686d",
          "sha256": "bce0fec0e21e1573f50e5079b5535b122f08bbf734deb1ffc394215f4fe02d9a",
          "sha1": "ec04d4135d526ded74e7f408db3a824350078dd2",
          "md5": "ee6f35ece1c677e30daedc54f3682fa0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.22"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.2"
          }
        }
      ],
      "files": [
        {
          "name": "share_plus_release-0.64.aar",
          "url": "share_plus_release-0.64.aar",
          "size": 18506,
          "sha512": "d01ce2353d0dab5fafb9e9ed267db72428cd8615f0f368876cd4e3c5ff650bf0ea2c4602495fc5c0d6070865a9a57ecbf7df24923b7390d17291511acb19686d",
          "sha256": "bce0fec0e21e1573f50e5079b5535b122f08bbf734deb1ffc394215f4fe02d9a",
          "sha1": "ec04d4135d526ded74e7f408db3a824350078dd2",
          "md5": "ee6f35ece1c677e30daedc54f3682fa0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "share_plus_release-0.64-sources.jar",
          "url": "share_plus_release-0.64-sources.jar",
          "size": 7549,
          "sha512": "1a5b96be106d4c0b6b444f86b82bba55d669c339a90ba0f900d68ea65d921fa7a13717eda480ae1bfc80ac5770de5b08ae156f78ac24cb2940d803150c509048",
          "sha256": "00a661206911b35ef1eb9da74874f6bd4a344ab73594284512d33d70d009ac9e",
          "sha1": "d2b61c8108b4c3fbc286ac3313656ab3fd693559",
          "md5": "aaef7fecc35bf97193158fde6d1c85e8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "share_plus_release-0.64-javadoc.jar",
          "url": "share_plus_release-0.64-javadoc.jar",
          "size": 283815,
          "sha512": "e2ecdc07831577c56e0a6fa25d5e5eb01b2ad350c08f5e6b7af2bfaf8053199cbd65f0299610e33987df8c7bb9f33512421ab0b00aea79ec4f4239739835e022",
          "sha256": "ce59f8b69150d74c516f1ed26d8b15485830f3cc779ca9ec0ca3fe118cdf44d3",
          "sha1": "970b1fd43f982069fcb3d8fd853219a7740155d2",
          "md5": "044e4a44cbb26b534c7410bedb14eebe"
        }
      ]
    }
  ]
}
