{
  "formatVersion": "1.1",
  "component": {
    "group": "com.baseflow.permissionhandler",
    "module": "permission_handler_android_release",
    "version": "0.48",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        }
      ],
      "files": [
        {
          "name": "permission_handler_android_release-0.48.aar",
          "url": "permission_handler_android_release-0.48.aar",
          "size": 26569,
          "sha512": "a19c8358f85369ebffff5ed3232d52a054dafef7413138f166164aba01007c9bf943d91ff641482dcea626999ca407291f3badad86d256ed1a3a8c89063eee47",
          "sha256": "d726785e1a7ab9fa4b9fba0d00dca6e7239602e7c7588a2f75f253ff73c5149c",
          "sha1": "7f8066b3ad1d63119e5700553805d065a7c319c1",
          "md5": "68fe138c9bac48487c0b91c6a9b084ec"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        }
      ],
      "files": [
        {
          "name": "permission_handler_android_release-0.48.aar",
          "url": "permission_handler_android_release-0.48.aar",
          "size": 26569,
          "sha512": "a19c8358f85369ebffff5ed3232d52a054dafef7413138f166164aba01007c9bf943d91ff641482dcea626999ca407291f3badad86d256ed1a3a8c89063eee47",
          "sha256": "d726785e1a7ab9fa4b9fba0d00dca6e7239602e7c7588a2f75f253ff73c5149c",
          "sha1": "7f8066b3ad1d63119e5700553805d065a7c319c1",
          "md5": "68fe138c9bac48487c0b91c6a9b084ec"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "permission_handler_android_release-0.48-sources.jar",
          "url": "permission_handler_android_release-0.48-sources.jar",
          "size": 18177,
          "sha512": "673bc0d22579ac8c7f7a50b04d3f47d4cdb85dbc8aa15bfcb371b64223d3ee8f535385b2e67dfa1230c825ecddb11e45e1a0b74410e608691074c11623d4f06e",
          "sha256": "3301b75b44b9f004580d559b28ab51dd9205289cc88ccc668ce8179f5bf24c67",
          "sha1": "7a9e4cb073bdd84100ad45b7d2c21b036815543f",
          "md5": "6347cb73f0ecc4fc5e825d6de82fca4e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "permission_handler_android_release-0.48-javadoc.jar",
          "url": "permission_handler_android_release-0.48-javadoc.jar",
          "size": 264574,
          "sha512": "c044656d75b2c7be6aa54930fa8dc606427a539fcb4cf77300b0dc1246462d824711a0f6e3b449b1a0c63aee8fd7948c396c62447a84122195cad35394e89738",
          "sha256": "b6333d51c4da6f91a2fe5dfbae32c7e05fada1cafc3b36fdbc3175d0d593bec5",
          "sha1": "c1efdc135cc913fe4ab030ffefcc49e3b2920d89",
          "md5": "408f8ef26e108befc954c99ef4554d8c"
        }
      ]
    }
  ]
}
