{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.fluttercommunity.plus.packageinfo",
    "module": "package_info_plus_release",
    "version": ".39",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        }
      ],
      "files": [
        {
          "name": "package_info_plus_release-.39.aar",
          "url": "package_info_plus_release-.39.aar",
          "size": 5912,
          "sha512": "12952471061dcc1dce31b4d3a749e685819f7024aa86fab60189b5b0598b2af2334730663b78839aaaae20a4bacfc1b694276022be39cd970a13f6e843c1f877",
          "sha256": "74d813b268e2caafd12878053297be94bfe7c1af4b696922081820e6668662b6",
          "sha1": "7f4d545eace18925875da63cae963d1055812da1",
          "md5": "06f7d5d754603a9090614e4367d42d32"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.22"
          }
        }
      ],
      "files": [
        {
          "name": "package_info_plus_release-.39.aar",
          "url": "package_info_plus_release-.39.aar",
          "size": 5912,
          "sha512": "12952471061dcc1dce31b4d3a749e685819f7024aa86fab60189b5b0598b2af2334730663b78839aaaae20a4bacfc1b694276022be39cd970a13f6e843c1f877",
          "sha256": "74d813b268e2caafd12878053297be94bfe7c1af4b696922081820e6668662b6",
          "sha1": "7f4d545eace18925875da63cae963d1055812da1",
          "md5": "06f7d5d754603a9090614e4367d42d32"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "package_info_plus_release-.39-sources.jar",
          "url": "package_info_plus_release-.39-sources.jar",
          "size": 2693,
          "sha512": "baaae2e6245030a7de70f19e43504fb87d6d374ec50af2dd23321d0ab0bf43dbb918967f0b66277e2662ccb4faf2098ffcb870dd1e597bc1dc8ac730e9c7b5fb",
          "sha256": "3f208ebbb8c9b93761dea623949b7ee1a9cd74e818acede7ccc4f562f3839a5d",
          "sha1": "12df81060cfa11fc35581f9c91da8922a5f8e6f0",
          "md5": "f30e01eabb60c79316840a3ed7edecb3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "package_info_plus_release-.39-javadoc.jar",
          "url": "package_info_plus_release-.39-javadoc.jar",
          "size": 265021,
          "sha512": "27180468c78aa1ef94d123a344add23e75d9e3b7a86c0c7e60695a5e574c8bb5a4ef4df5eb79b3b56cc48faaf5835d57074d13d51f8034e4c06401875d46ffd2",
          "sha256": "2bebd391690a862fd2193795c25e16607313c3a666ad2d79bf37e94349d1f270",
          "sha1": "0aae1e23ae1f3cda501e0a93c8cfc950cf882f9b",
          "md5": "5d627b6d3db98aed7348d235ec9ed9ff"
        }
      ]
    }
  ]
}
