{
  "formatVersion": "1.1",
  "component": {
    "group": "com.benjaminabel.vibration",
    "module": "vibration_release",
    "version": "0.49",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        }
      ],
      "files": [
        {
          "name": "vibration_release-0.49.aar",
          "url": "vibration_release-0.49.aar",
          "size": 5670,
          "sha512": "438671eeae568fb44f97b35fb6dd53ec5b65d27dc136268cb1b760a941b41961f1010d3ae4a0900ee554bbfb71b2d3ad4cf79b59afb8f07adf2a54a1b9b8c45b",
          "sha256": "fd889b0c8e36d19c0cf7a71860721375d70ee929baea932d01d048a6f67d987c",
          "sha1": "8c8bc6200b71ac7b4e52ebd39e7880ce61b23285",
          "md5": "82318fee623adfeca93e43e66ab16ac4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        }
      ],
      "files": [
        {
          "name": "vibration_release-0.49.aar",
          "url": "vibration_release-0.49.aar",
          "size": 5670,
          "sha512": "438671eeae568fb44f97b35fb6dd53ec5b65d27dc136268cb1b760a941b41961f1010d3ae4a0900ee554bbfb71b2d3ad4cf79b59afb8f07adf2a54a1b9b8c45b",
          "sha256": "fd889b0c8e36d19c0cf7a71860721375d70ee929baea932d01d048a6f67d987c",
          "sha1": "8c8bc6200b71ac7b4e52ebd39e7880ce61b23285",
          "md5": "82318fee623adfeca93e43e66ab16ac4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vibration_release-0.49-sources.jar",
          "url": "vibration_release-0.49-sources.jar",
          "size": 3212,
          "sha512": "d5968737c6b71ee7b4cb2294798caa5ffcf06bad0dd878445306ce94d132e9f5ff482aa27ef53047940383b71edc6b41fb90e2571256fd4cb4ba2f80703a3df1",
          "sha256": "9ba7f8c690080fa9025eb06a74fdae61feaaefdbcda9f88e01f7344479c831c5",
          "sha1": "f366f2e24cf9806f2a34d2651525e7344789eaab",
          "md5": "28ab8d7e2ed74e9a55bdf7586ad556c0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vibration_release-0.49-javadoc.jar",
          "url": "vibration_release-0.49-javadoc.jar",
          "size": 265470,
          "sha512": "6fcf285b347d7a4c1b41132cc593574afedb165b920574045a49064b75174d7a59239ece2226d5e3dfb814f128c188a12cde915a0099d7ddc82135b5a3bba5e5",
          "sha256": "8887f6d65511e8d15184a1cb07e05e50eae913d468ed1b0383869c6dff0a4978",
          "sha1": "0e8e91c6bf8b1bc57537a507c08ad7dbe070d8f1",
          "md5": "7dbdea92ee3811db3113e850d2acd9eb"
        }
      ]
    }
  ]
}
