{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
    "module": "flutter_plugin_android_lifecycle_release",
    "version": "0.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_plugin_android_lifecycle_release-0.21.aar",
          "url": "flutter_plugin_android_lifecycle_release-0.21.aar",
          "size": 2503,
          "sha512": "c47015d3684b3b1a0cef077b1929cbe61ffaa4f3d8ec078ed4279cb7aa1ada9dc8e0f337ea5b9159a936cc75e63540eb8e70c1088a32642ceff62862fe1374f9",
          "sha256": "9fb4cf8d054e60d0bf6d639cfacc66db8aab776059fd0e9b67ace8c60d169d65",
          "sha1": "e526db6513439eebf917c63e27fa7b9d969a4d2d",
          "md5": "89a4374677faa54c80076e99a9da11a4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_plugin_android_lifecycle_release-0.21.aar",
          "url": "flutter_plugin_android_lifecycle_release-0.21.aar",
          "size": 2503,
          "sha512": "c47015d3684b3b1a0cef077b1929cbe61ffaa4f3d8ec078ed4279cb7aa1ada9dc8e0f337ea5b9159a936cc75e63540eb8e70c1088a32642ceff62862fe1374f9",
          "sha256": "9fb4cf8d054e60d0bf6d639cfacc66db8aab776059fd0e9b67ace8c60d169d65",
          "sha1": "e526db6513439eebf917c63e27fa7b9d969a4d2d",
          "md5": "89a4374677faa54c80076e99a9da11a4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_plugin_android_lifecycle_release-0.21-sources.jar",
          "url": "flutter_plugin_android_lifecycle_release-0.21-sources.jar",
          "size": 2683,
          "sha512": "a3f7fee602ae01e1fe53ad82c914db15159744a75a0e4f439cdbe5e530abf6d3b431e26802ccd3cf08245278758e1aef335a9e00aec7ded1b1c89a60a53d7915",
          "sha256": "ea22384264efbced6ae1be61be8aadee870b81c3a1e0b6accc0ef62396aaeae0",
          "sha1": "1ddcac6e1149d882ff8719e00a4eebfeb282eb36",
          "md5": "351ed496e751473b57d20e3a693b432d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_plugin_android_lifecycle_release-0.21-javadoc.jar",
          "url": "flutter_plugin_android_lifecycle_release-0.21-javadoc.jar",
          "size": 269939,
          "sha512": "5a86ee6c74202d576604b62330d76dd8d0b8eb4977ec415f0120c86c57cbf69347ca0bc7dfb0fe50ea5dc6cb30202e819d0c13558ac3949dcfb6f451e102110e",
          "sha256": "c8192e8af2332ed6752a36e2d7ee3ca0dcf5ae82abe217812053e7df69d24137",
          "sha1": "969393d68f6468f57a0b0e4b889c17ad570e1840",
          "md5": "af4b3d6d06ff23c39e39aa782d319273"
        }
      ]
    }
  ]
}
