{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dexterous.flutterlocalnotifications",
    "module": "flutter_local_notifications_debug",
    "version": "1.16",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_local_notifications_debug-1.16.aar",
          "url": "flutter_local_notifications_debug-1.16.aar",
          "size": 86153,
          "sha512": "ce66b6449f14d04fb4968936165702c159729747831d42bdae9330faedf8e49d578599a6add0d46c02e65bc0ea91d6dc6ddce4f85dfbc302635843b60669b550",
          "sha256": "a88bab2fbf424b071109ee7ca8ff71eaa87c199a61515f0460fb0e82271d9ff3",
          "sha1": "88fc03a106fdc4822f17fc98506bc7c7ebe6894c",
          "md5": "2e7928ec6d93dbcbe540410fc90376a2"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.media",
          "module": "media",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.9"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_local_notifications_debug-1.16.aar",
          "url": "flutter_local_notifications_debug-1.16.aar",
          "size": 86153,
          "sha512": "ce66b6449f14d04fb4968936165702c159729747831d42bdae9330faedf8e49d578599a6add0d46c02e65bc0ea91d6dc6ddce4f85dfbc302635843b60669b550",
          "sha256": "a88bab2fbf424b071109ee7ca8ff71eaa87c199a61515f0460fb0e82271d9ff3",
          "sha1": "88fc03a106fdc4822f17fc98506bc7c7ebe6894c",
          "md5": "2e7928ec6d93dbcbe540410fc90376a2"
        }
      ]
    },
    {
      "name": "debugVariantDebugSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_local_notifications_debug-1.16-sources.jar",
          "url": "flutter_local_notifications_debug-1.16-sources.jar",
          "size": 43596,
          "sha512": "7736acb5954d99f56cb46af46dd8581b373482a317c78c9b99eb6fc6eb8ca140082025906c97406c3b82586029c0e86a3f0d69c96023384abdd8ea46e6bf48d4",
          "sha256": "fc7f32461f268b0581bc3c5c9e2c0d81a79252cb0cf09a351bb0bdffe4993ea6",
          "sha1": "c3fb9f6ef65dc6aff958aa612beca1e2ae4a96c0",
          "md5": "5de3e43acd23922d52c9900575889eda"
        }
      ]
    },
    {
      "name": "debugVariantDebugJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_local_notifications_debug-1.16-javadoc.jar",
          "url": "flutter_local_notifications_debug-1.16-javadoc.jar",
          "size": 417881,
          "sha512": "1d11e1155bdce0b471ccceaf6203acdbb88bfff1fcebafc5a292ae2fc74eac867eaf9488fec3139ada06d6d38d9375c3301d0a58b4f1134d45127602f9b0f504",
          "sha256": "2adbe82c8fd5d0aadb2ce1067c5dbd3a80cbef185062712786d7c6ede80ca053",
          "sha1": "1d7007fd28a858c2d186964ac740047956e08ec4",
          "md5": "9ef631ad05db10ba0f51f7758cccc334"
        }
      ]
    }
  ]
}
