{
  "formatVersion": "1.1",
  "component": {
    "group": "com.baseflow.permissionhandler",
    "module": "permission_handler_android_release",
    "version": "0.18",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        }
      ],
      "files": [
        {
          "name": "permission_handler_android_release-0.18.aar",
          "url": "permission_handler_android_release-0.18.aar",
          "size": 26448,
          "sha512": "885a61c1693e9a63814e13030c0a262dc6c41e1045670b7f5e3851d25f5122be0b00bddb555b74386d3cd79c80b59f312ba44cff460d25c17e3b4384a18c9414",
          "sha256": "ea1ae6e4ca02baf1c3bdb76114435110135e35f1f44055f32f9b1c11dd0339a3",
          "sha1": "9393d7e7522511002b424d27651a24ab36d828a5",
          "md5": "32be0d5d04344864bd83b344d2708707"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        }
      ],
      "files": [
        {
          "name": "permission_handler_android_release-0.18.aar",
          "url": "permission_handler_android_release-0.18.aar",
          "size": 26448,
          "sha512": "885a61c1693e9a63814e13030c0a262dc6c41e1045670b7f5e3851d25f5122be0b00bddb555b74386d3cd79c80b59f312ba44cff460d25c17e3b4384a18c9414",
          "sha256": "ea1ae6e4ca02baf1c3bdb76114435110135e35f1f44055f32f9b1c11dd0339a3",
          "sha1": "9393d7e7522511002b424d27651a24ab36d828a5",
          "md5": "32be0d5d04344864bd83b344d2708707"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "permission_handler_android_release-0.18-sources.jar",
          "url": "permission_handler_android_release-0.18-sources.jar",
          "size": 18178,
          "sha512": "f75ef3dcffb564829cd6a38e38286f4980d44f582e5fe3c185db3c0082da1423393c92de6556956c158928669790cb4220d56c0e2eee1de390df6055fdef5018",
          "sha256": "b1c5b90d8a5e74eb10437a278638751fb12e6d863b14b6225eb7aef1941cb434",
          "sha1": "04e0db92f72a5112e79b561b446c85b4d4e32e2c",
          "md5": "6c3c580a555a61e926892f7155fcdfd2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "permission_handler_android_release-0.18-javadoc.jar",
          "url": "permission_handler_android_release-0.18-javadoc.jar",
          "size": 264648,
          "sha512": "c2821f2cf77020aa38b8235d6d04b7b07f4b1f73f7fe82b7861b095e206143e4ec53bce40275d64f584c29a911f20dc398f4712e7e5b00691c1a22a1f44c8426",
          "sha256": "f24c1b465bedfa483c32b8060bba00fb57733ba40c50326ca9862de1b8b1a2db",
          "sha1": "a5768dd2ea2ccae1fb0c45e4a825b93bada71853",
          "md5": "61e8e09f23bfa415b86102953e070fe3"
        }
      ]
    }
  ]
}
