{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.steenbakker.mobile_scanner",
    "module": "mobile_scanner_release",
    "version": "0.66",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "mobile_scanner_release-0.66.aar",
          "url": "mobile_scanner_release-0.66.aar",
          "size": 68166,
          "sha512": "8795dadcf4dc4c382bb25a2c6be0ba8780ba6f2f385236eb41aa57e0a54f15445e642e2ea78b48781b21ad9f30e0949a3d5352af8be5da40abc1f8a7301f551f",
          "sha256": "358638c77c6721de28447f65cd3deb71c9a2f252f8fbcdb8e138c694280f111f",
          "sha1": "41cae8d9ab2fce2746028f2046fe329218630672",
          "md5": "44dba59c276665dbe094b5ef045e4f0d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        },
        {
          "group": "com.google.mlkit",
          "module": "barcode-scanning",
          "version": {
            "requires": "17.3.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.3.4"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.3.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "mobile_scanner_release-0.66.aar",
          "url": "mobile_scanner_release-0.66.aar",
          "size": 68166,
          "sha512": "8795dadcf4dc4c382bb25a2c6be0ba8780ba6f2f385236eb41aa57e0a54f15445e642e2ea78b48781b21ad9f30e0949a3d5352af8be5da40abc1f8a7301f551f",
          "sha256": "358638c77c6721de28447f65cd3deb71c9a2f252f8fbcdb8e138c694280f111f",
          "sha1": "41cae8d9ab2fce2746028f2046fe329218630672",
          "md5": "44dba59c276665dbe094b5ef045e4f0d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "mobile_scanner_release-0.66-sources.jar",
          "url": "mobile_scanner_release-0.66-sources.jar",
          "size": 20090,
          "sha512": "d3362bed54acd1325cb709f17d94411437ca5b2f26cbf04bee894c45a1014964f855f9869cfa4d57be601465f6af445a644a3b756f1fe922cb86ea7dd856faed",
          "sha256": "d83d054e3d529b76cfe1b623f586029ca1492f55dd21a3d0a20a33654ac085cd",
          "sha1": "e46370da755c3f10ba18bb11111dfda70707b9d0",
          "md5": "020546aa5e6a0183f636d87d2e226082"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "mobile_scanner_release-0.66-javadoc.jar",
          "url": "mobile_scanner_release-0.66-javadoc.jar",
          "size": 380217,
          "sha512": "759f1f03ea0c91fb16786256ab72c1257203db415b0a9f722eb34687304f4a1267a46bdc74a6a73bab77a5ee629fd4f7e5b09268d1e9cd2e6a08b8be152799f0",
          "sha256": "e289611f809fa25e6703d57be8b3cba08b3d6f355f1f6b71fa56db69b3881060",
          "sha1": "74a8dab4bb44e1efba43e91e05bcac082fc54bb5",
          "md5": "e078b9785b94f471afb591a2859e1354"
        }
      ]
    }
  ]
}
