{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.yongxin_ring",
    "module": "yongxin_ring_release",
    "version": "0.56",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "yongxin_ring_release-0.56.aar",
          "url": "yongxin_ring_release-0.56.aar",
          "size": 127955,
          "sha512": "1aa546f416979c2cd901ce0d02454f8a7c182fd01c9a187013749d93ced9abc3622787a2a93730014661f8ebc7781aa76ad4b632bc7d6896b2bffe6401e2ad58",
          "sha256": "66645b72d97bf4bb493d905efe5d669b7dfef88d9da3f8fff6b8593b097d3a82",
          "sha1": "314892de42b7c014d619ed11775f4dc0cca3686a",
          "md5": "f27b216ddd4e457302b8a60e92bd2eb0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        },
        {
          "group": "com.lm",
          "module": "chipletRing",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.localbroadcastmanager",
          "module": "localbroadcastmanager",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.greenrobot",
          "module": "greendao",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "org.ligboy.retrofit2",
          "module": "converter-fastjson-android",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "24.0.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "com.zhy",
          "module": "okhttputils",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "com.tenmeter.smlibrary",
          "module": "tenmeter",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "yongxin_ring_release-0.56.aar",
          "url": "yongxin_ring_release-0.56.aar",
          "size": 127955,
          "sha512": "1aa546f416979c2cd901ce0d02454f8a7c182fd01c9a187013749d93ced9abc3622787a2a93730014661f8ebc7781aa76ad4b632bc7d6896b2bffe6401e2ad58",
          "sha256": "66645b72d97bf4bb493d905efe5d669b7dfef88d9da3f8fff6b8593b097d3a82",
          "sha1": "314892de42b7c014d619ed11775f4dc0cca3686a",
          "md5": "f27b216ddd4e457302b8a60e92bd2eb0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "yongxin_ring_release-0.56-sources.jar",
          "url": "yongxin_ring_release-0.56-sources.jar",
          "size": 37986,
          "sha512": "404ef913f186425cdaaf60f5279c6d177e4c2faa87fcb3ca4de1e32d2abf694d91c5e6ad852f654cb6cac87df058e311cfefe13151afbb43c9b181b135d5dc6a",
          "sha256": "8ac61fc29b479c2553c4aea2e68322246a4257990f9bf6cb0e439b0d37805964",
          "sha1": "da277b56e0b2ac9ca1e0ea857f00a13ad2dcd00e",
          "md5": "a81e32a43557547de636d10abd0976c3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "yongxin_ring_release-0.56-javadoc.jar",
          "url": "yongxin_ring_release-0.56-javadoc.jar",
          "size": 301906,
          "sha512": "79343269b6405b0baf24ab5db284c45e8797ec85935d0beced41759239ee39da72dafe0e1faf38f5d5692451f45754ab718fc6c42eadf5f5ea8015ea5e783e19",
          "sha256": "98a3e09df51fa75399730efaa6b69ce4a654bf80b632cfd975a9481795696db4",
          "sha1": "afd7f6ad3b784776a3d77c4e5f813c6cf775b2d8",
          "md5": "03aadc32d56cda03ff74e2935e70b594"
        }
      ]
    }
  ]
}
