{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.imagepicker",
    "module": "image_picker_android_release",
    "version": "0.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        }
      ],
      "files": [
        {
          "name": "image_picker_android_release-0.10.aar",
          "url": "image_picker_android_release-0.10.aar",
          "size": 69974,
          "sha512": "78f667f7c2184a5f8c280d7e5690ebf5dbc3c30efe7d1bb36696d5e3e2fe1f98df805c1e2f79ed23e31943895a546641141916656690086bfe7253a4aa8b8603",
          "sha256": "fe53ff3604a658f9e52318a27c50bf2fe888db92d83ee3a71a037636c2e4dd6b",
          "sha1": "cf3c774a20f9f2cfa2e06be8856f71a9631784aa",
          "md5": "6a1b08dfcf2a8798fdd7e05d66ffb354"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.7"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.9.3"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_release",
          "version": {
            "requires": "0.10"
          }
        }
      ],
      "files": [
        {
          "name": "image_picker_android_release-0.10.aar",
          "url": "image_picker_android_release-0.10.aar",
          "size": 69974,
          "sha512": "78f667f7c2184a5f8c280d7e5690ebf5dbc3c30efe7d1bb36696d5e3e2fe1f98df805c1e2f79ed23e31943895a546641141916656690086bfe7253a4aa8b8603",
          "sha256": "fe53ff3604a658f9e52318a27c50bf2fe888db92d83ee3a71a037636c2e4dd6b",
          "sha1": "cf3c774a20f9f2cfa2e06be8856f71a9631784aa",
          "md5": "6a1b08dfcf2a8798fdd7e05d66ffb354"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "image_picker_android_release-0.10-sources.jar",
          "url": "image_picker_android_release-0.10-sources.jar",
          "size": 26710,
          "sha512": "372c55c93aa9de3bc39caaa735c8e9f72983fb2a602de7ddd3be0527b8ab1f43bb8f5583d2ec4a8e3b61d6eb874e7e4cf34c0f725649e2d8806f4a45f0225e35",
          "sha256": "3cab7df6aafaac4936a8156024350f81aff0ce6ff88a827513403c895316ab3e",
          "sha1": "50f46bd80d3ea3246d7442d73c95694a4deafe04",
          "md5": "0651b7414a10b08945561bd62b096625"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "image_picker_android_release-0.10-javadoc.jar",
          "url": "image_picker_android_release-0.10-javadoc.jar",
          "size": 383512,
          "sha512": "cba6f55700f1182cb291f62b06487efc54762a1f0dba858bf15c410241c88a4c7adc8abd2a490d3ca9c2347618851e70b2249234f32de867fa269986bcae9a63",
          "sha256": "1e97cfe696ad50851adc22f065d03c70d7b90078253f28f34767ce954235d2be",
          "sha1": "7933aab6a3abf8d012e3818d8afa8ba3d6d5066b",
          "md5": "d3c187e3b48cb75781283505c2f2d43e"
        }
      ]
    }
  ]
}
