{
  "formatVersion": "1.1",
  "component": {
    "group": "com.fluttercandies.flutter_image_compress",
    "module": "flutter_image_compress_common_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_image_compress_common_debug-1.0.aar",
          "url": "flutter_image_compress_common_debug-1.0.aar",
          "size": 31525,
          "sha512": "85b76bb19dc698654de368d38e10dae0a20aa1911acef94cbfcdbc6f30e9bc22e0797523ab9d686fa17b96b872d0dd6fef97ea3cf573f08e96421e1708ea2d9e",
          "sha256": "7a22fbeaed32434524cf5e5097b88bd65ea9101a76b5883f83b03c65fd6c18d7",
          "sha1": "6cc327e48ba8b3cc1fc19206c07dfa9f705fd37d",
          "md5": "b8a8f772f68aa42ce31e44e8a185cd55"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "androidx.heifwriter",
          "module": "heifwriter",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_image_compress_common_debug-1.0.aar",
          "url": "flutter_image_compress_common_debug-1.0.aar",
          "size": 31525,
          "sha512": "85b76bb19dc698654de368d38e10dae0a20aa1911acef94cbfcdbc6f30e9bc22e0797523ab9d686fa17b96b872d0dd6fef97ea3cf573f08e96421e1708ea2d9e",
          "sha256": "7a22fbeaed32434524cf5e5097b88bd65ea9101a76b5883f83b03c65fd6c18d7",
          "sha1": "6cc327e48ba8b3cc1fc19206c07dfa9f705fd37d",
          "md5": "b8a8f772f68aa42ce31e44e8a185cd55"
        }
      ]
    },
    {
      "name": "debugVariantDebugSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_image_compress_common_debug-1.0-sources.jar",
          "url": "flutter_image_compress_common_debug-1.0-sources.jar",
          "size": 13283,
          "sha512": "9d463a80c9f9155d36af415dfbc87fadb7908f534f56929f46ded2280cbd3951f90518b08d83de17af9eab1bb66723f65b386d3d4df8b2a57dc67105fc8cad56",
          "sha256": "93a28e5f9b7fcb467c45057e584caa01f1eb412c0b4a92b23a49dc0100b4af37",
          "sha1": "8f0422fa7a12db6f03202df46f11b2c7ec84061a",
          "md5": "326cceeddeb7bc0e1af417bf6b15811f"
        }
      ]
    },
    {
      "name": "debugVariantDebugJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_image_compress_common_debug-1.0-javadoc.jar",
          "url": "flutter_image_compress_common_debug-1.0-javadoc.jar",
          "size": 351955,
          "sha512": "91725f23a2781321a4f9b4e3e3981c19532143c75940b1fba07fbf1d45e3ebee48f93640c7b4a813f2870fc65fdb7d105c52f439f48ea0fe3214541d3596159f",
          "sha256": "e515b6cc32255e60cda1a298591072f1ea8288dff6d8f37b8920829fdc42c16b",
          "sha1": "70a4e2fd5ac3b7756cec1d5711809498dd4348fa",
          "md5": "f7490eb1b9a17e4eec3ec5b64029da67"
        }
      ]
    }
  ]
}
