{
  "formatVersion": "1.1",
  "component": {
    "group": "com.benjaminabel.vibration",
    "module": "vibration_release",
    "version": "0.53",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        }
      ],
      "files": [
        {
          "name": "vibration_release-0.53.aar",
          "url": "vibration_release-0.53.aar",
          "size": 5670,
          "sha512": "438671eeae568fb44f97b35fb6dd53ec5b65d27dc136268cb1b760a941b41961f1010d3ae4a0900ee554bbfb71b2d3ad4cf79b59afb8f07adf2a54a1b9b8c45b",
          "sha256": "fd889b0c8e36d19c0cf7a71860721375d70ee929baea932d01d048a6f67d987c",
          "sha1": "8c8bc6200b71ac7b4e52ebd39e7880ce61b23285",
          "md5": "82318fee623adfeca93e43e66ab16ac4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        }
      ],
      "files": [
        {
          "name": "vibration_release-0.53.aar",
          "url": "vibration_release-0.53.aar",
          "size": 5670,
          "sha512": "438671eeae568fb44f97b35fb6dd53ec5b65d27dc136268cb1b760a941b41961f1010d3ae4a0900ee554bbfb71b2d3ad4cf79b59afb8f07adf2a54a1b9b8c45b",
          "sha256": "fd889b0c8e36d19c0cf7a71860721375d70ee929baea932d01d048a6f67d987c",
          "sha1": "8c8bc6200b71ac7b4e52ebd39e7880ce61b23285",
          "md5": "82318fee623adfeca93e43e66ab16ac4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vibration_release-0.53-sources.jar",
          "url": "vibration_release-0.53-sources.jar",
          "size": 3212,
          "sha512": "d5968737c6b71ee7b4cb2294798caa5ffcf06bad0dd878445306ce94d132e9f5ff482aa27ef53047940383b71edc6b41fb90e2571256fd4cb4ba2f80703a3df1",
          "sha256": "9ba7f8c690080fa9025eb06a74fdae61feaaefdbcda9f88e01f7344479c831c5",
          "sha1": "f366f2e24cf9806f2a34d2651525e7344789eaab",
          "md5": "28ab8d7e2ed74e9a55bdf7586ad556c0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vibration_release-0.53-javadoc.jar",
          "url": "vibration_release-0.53-javadoc.jar",
          "size": 265468,
          "sha512": "97aad965019d005e7f51d402e56d3d73a905c58dcd84997bb31d70cae81cbb5cca813bcd60f6597a200c2c36dda5c33f71e19ce31d6825c5e2cf9be552c30822",
          "sha256": "7fb5bba0d33e715c73463cb660924403830d918da77aa5c962d068a4a988d960",
          "sha1": "a0b47a04baa92f9bafb7e38a80e1c06262be4b65",
          "md5": "8c99f5c5df1a2547a156d61af3ea1129"
        }
      ]
    }
  ]
}
