{
  "formatVersion": "1.1",
  "component": {
    "group": "ch.simonbraillard.flutter_new_badger",
    "module": "flutter_new_badger_release",
    "version": "0.43",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_new_badger_release-0.43.aar",
          "url": "flutter_new_badger_release-0.43.aar",
          "size": 4058,
          "sha512": "1def178bef6b2726f0045d025b41f206ac023324861ebd4d12f28a293ba65b027d5b7d31a1d88038666b02d9469b2f4529036a8d0246f074b773095df1f5bada",
          "sha256": "e5d0d151b231d44d65a30c4e4682dbb5818dba8e9d94e3547e84dcdaeae35608",
          "sha1": "b0ef068a415986cb3bcf7fc4f1fe30d004440bb3",
          "md5": "1f3d0ded85dc4a56a5223c3035f2e663"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        },
        {
          "group": "me.leolin",
          "module": "ShortcutBadger",
          "version": {
            "requires": "1.1.22"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "ShortcutBadger",
              "type": "aar",
              "extension": "aar"
            }
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_new_badger_release-0.43.aar",
          "url": "flutter_new_badger_release-0.43.aar",
          "size": 4058,
          "sha512": "1def178bef6b2726f0045d025b41f206ac023324861ebd4d12f28a293ba65b027d5b7d31a1d88038666b02d9469b2f4529036a8d0246f074b773095df1f5bada",
          "sha256": "e5d0d151b231d44d65a30c4e4682dbb5818dba8e9d94e3547e84dcdaeae35608",
          "sha1": "b0ef068a415986cb3bcf7fc4f1fe30d004440bb3",
          "md5": "1f3d0ded85dc4a56a5223c3035f2e663"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_new_badger_release-0.43-sources.jar",
          "url": "flutter_new_badger_release-0.43-sources.jar",
          "size": 1776,
          "sha512": "c3d1ee04902cd70b0d5dad70cf8a33d467503a4187a2533a44f393362c35ed7346ace3326668222d4dffd17d1172b1df25dadad9ce27d30ace3e5c9c02c9c648",
          "sha256": "a29d615e4a0c05e28a1a76b0cd89cfc61b4f6648092aa31666d2c30e86c13a41",
          "sha1": "00948fe19d0d77a813d3083387c846f71a2237f1",
          "md5": "66078d106b1cb86ef6e66ffaa3a37a47"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_new_badger_release-0.43-javadoc.jar",
          "url": "flutter_new_badger_release-0.43-javadoc.jar",
          "size": 262488,
          "sha512": "875112395c4d68fe6cc2d0990e07645cbe6d3823ccd82400e50fae632d051acbec98f497e1bc2153ae2067ce69b1ecbac0c570570bbbc289f0ed4396b3279e71",
          "sha256": "0599e612f6cc89d5a3ac574324c239f8296d63b1d379453d5569dd9f95308b1a",
          "sha1": "5a5434bd65babc2e62aa3be3bf78f1d80548263e",
          "md5": "9d70ca50caf9c0328a742c5b7a8afc19"
        }
      ]
    }
  ]
}
